
*&---------------------------------------------------------------------*

*&  Include  ZEDR21_PRACTICE009_TOP

*&---------------------------------------------------------------------*




TABLES : ZEDT21_102, ZEDT21_103.

TABLES : ZEDT21_104.

TABLES : ZEDT21_106.







CONSTANTS : C_X TYPE CHAR1 VALUE 'X'.

CONSTANTS : C_A TYPE CHAR1 VALUE 'A'.



RANGES : R_FG FOR ZEDT21_102-ZQFLAG21.

"==========================EMPLOYEE INFO ===================================================

DATA : BEGIN OF GS_EMPLOYEE,

  ZPERNR LIKE ZEDT21_102-ZPERNR21,

  ZPNAME LIKE ZEDT21_103-ZPNAME21,

  ZDEPCODE LIKE ZEDT21_102-ZDEPCODE21,

  DATBI LIKE ZEDT21_102-DATBI,

  DATAB LIKE ZEDT21_102-DATAB,

  ZDEPRANK LIKE ZEDT21_104-ZRANK21,

  ZGENDER LIKE ZEDT21_103-ZGENDER21,

  ZEDATE LIKE ZEDT21_102-ZEDATE21,

  ZQDATE LIKE ZEDT21_102-ZQDATE21,

  ZQFLAG LIKE ZEDT21_102-ZQFLAG21,

  ZADDRESS LIKE ZEDT21_103-ZADDRESS21,

  END OF GS_EMPLOYEE.

  DATA : GT_EMPLOYEE LIKE TABLE OF GS_EMPLOYEE.



"============================EMPLOYEE INFORMATION ALV ====================================

DATA : BEGIN OF GS_EMPLOYEE_INFO,

  ICON TYPE C LENGTH 4,

  ZPERNR LIKE ZEDT21_102-ZPERNR21,

  ZPNAME LIKE ZEDT21_103-ZPNAME21,

  ZDEPCODE_NAME TYPE C LENGTH 10,

  DATBI LIKE ZEDT21_102-DATBI,

  DATAB LIKE ZEDT21_102-DATAB,

  ZRANK_NAME TYPE c LENGTH 8,

  ZGENDER_NAME TYPE C LENGTH 4,

  ZEDATE LIKE ZEDT21_102-ZEDATE21,

  ZQDATE LIKE ZEDT21_102-ZQDATE21,

  ZQFLAG LIKE ZEDT21_102-ZQFLAG21,

  ZADDRESS LIKE ZEDT21_103-ZADDRESS21,

  END OF GS_EMPLOYEE_INFO.

  DATA : GT_EMPLOYEE_INFO LIKE TABLE OF GS_EMPLOYEE_INFO.





  "=======================SALARY=============================================



  DATA : BEGIN OF GS_SALARY,

    ZPERNR LIKE ZEDT21_106-ZPERNR21,

    ZYEAR LIKE ZEDT21_106-ZYEAR21,

    DATBI LIKE ZEDT21_106-DATBI,

    DATAB LIKE ZEDT21_106-DATAB,

    ZSALARY LIKE ZEDT21_106-ZSALARY21,

    ZBANKCODE LIKE ZEDT21_106-ZBANKCODE21,

    ZACCOUNT LIKE ZEDT21_106-ZACCOUNT21,

    END OF GS_SALARY.

  DATA : GT_SALARY LIKE TABLE OF GS_SALARY.





 "=======================================SALARY INFO =============================

  DATA : BEGIN OF GS_SALARY_INFO,

    ZPERNR LIKE ZEDT21_106-ZPERNR21,

    ZYEAR LIKE ZEDT21_106-ZYEAR21,

    DATBI LIKE ZEDT21_106-DATBI,

    DATAB LIKE ZEDT21_106-DATAB,

    ZSALARY LIKE ZEDT21_106-ZSALARY21,

    ZWAERS TYPE WAERS,

    ZBANK_NAME TYPE C LENGTH 10,

    ZACCOUNT LIKE ZEDT21_106-ZACCOUNT21,

    END OF GS_SALARY_INFO.

    DATA : GT_SALARY_INFO LIKE TABLE OF GS_SALARY_INFO.





"============================ASSESS================================================



DATA : BEGIN OF GS_ASSESS,

  ZPERNR LIKE ZEDT21_104-ZPERNR21,

  ZDEPCODE LIKE ZEDT21_104-ZDEPCODE21,

  ZYEAR LIKE ZEDT21_104-ZYEAR21,

  DATBI LIKE ZEDT21_104-DATBI,

  DATAB LIKE ZEDT21_104-DATAB,

  ZRANK LIKE ZEDT21_104-ZRANK21,

  END OF GS_ASSESS.

  DATA : GT_ASSESS LIKE TABLE OF GS_ASSESS.





  "====================================ASSESS INFO ====================================



  DATA : BEGIN OF GS_ASSESS_INFO,

    ZPERNR LIKE ZEDT21_104-ZPERNR21,

    ZDEPCODE_NAME TYPE C LENGTH 10,

    ZYEAR LIKE ZEDT21_104-ZYEAR21,

    DATBI LIKE ZEDT21_104-DATBI,

    DATAB LIKE ZEDT21_104-DATAB,

    ZRANK LIKE ZEDT21_104-ZRANK21,

    END OF GS_ASSESS_INFO.

  DATA GT_ASSESS_INFO LIKE TABLE OF GS_ASSESS_INFO.



 "=====================================ALV, FIELD CAT RELATED DATA=======================

  DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA : GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA : GC_SPLITTER2 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA : GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER3 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER4 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT,

       GT_FIELDCAT1 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT2 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT3 TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GS_SORT TYPE LVC_S_SORT .

DATA : GT_SORT1 TYPE LVC_T_SORT.

DATA : GT_SORT2 TYPE LVC_T_SORT.

DATA : GT_SORT3 TYPE LVC_T_SORT.



DATA : GS_VARIANT TYPE DISVARIANT.