
*&---------------------------------------------------------------------*

*&  Include           ZEDR06_PRACTICE008_TOP

*&---------------------------------------------------------------------*






TABLES : ZEDT06_100, ZEDT06_101.



CONSTANTS C_X TYPE C VALUE 'X'.

CONSTANTS C_DOT TYPE C VALUE '.'.



RANGES R_IDCODE FOR ZEDT06_100-ZIDCODE.



DATA : OK_CODE TYPE SY-UCOMM.



" ## ## ### ## INTERNAL TABLE ##

DATA : BEGIN OF GS_ORDER,

  ZORDNO LIKE ZEDT06_100-ZORDNO,      " ####

  ZIDCODE LIKE ZEDT06_100-ZIDCODE,    " ##ID

  ZMATNR LIKE ZEDT06_100-ZMATNR,      " ####

  ZMATNAME LIKE ZEDT06_100-ZMATNAME,  " ###

  ZMTART LIKE ZEDT06_100-ZMTART,      " ####

  ZMTART_NAME TYPE C LENGTH 10,       " ####(#)

  ZVOLUM TYPE C LENGTH 3,             " ##

  VRKME LIKE ZEDT06_100-VRKME,        " ##

  ZNSAMT LIKE ZEDT06_100-ZNSAMT,      " ####

  ZSLAMT LIKE ZEDT06_100-ZSLAMT,      " ####

  ZDCAMT LIKE ZEDT06_100-ZDCAMT,      " ####

  ZWAERS LIKE ZEDT06_100-ZWAERS,      " ##

  ZSALE_FG TYPE ZEDT06_100-ZSALE_FG,  " ####

  ZSALE_NAME TYPE C LENGTH  4,        " ####(#)

  ZJDATE LIKE ZEDT06_100-ZJDATE,      " ####

  ZRET_FG LIKE ZEDT06_100-ZRET_FG,    " ####

  ZRDATE LIKE ZEDT06_100-ZRDATE,      " ####.

  END OF GS_ORDER.

DATA : GT_ORDER LIKE TABLE OF GS_ORDER.



" ## ## ## # ### AVL ### ##

DATA : BEGIN OF GS_ORDER_0100,      "ALV###

  ICON TYPE C LENGTH 4,             " ###

  ZORDNO LIKE ZEDT06_100-ZORDNO,    " ####

  ZIDCODE LIKE ZEDT06_100-ZIDCODE,  " ##ID

  ZMATNR LIKE ZEDT06_100-ZMATNR,    " ####

  ZMATNAME LIKE ZEDT06_100-ZMATNAME," #####

  ZMTART_NAME TYPE C LENGTH 10,     " #####

  ZVOLUM LIKE ZEDT06_100-ZVOLUM,    " ##

  VRKME LIKE ZEDT06_100-VRKME,      " ##

  ZNSAMT LIKE ZEDT06_100-ZNSAMT,    " ####

  ZSLAMT LIKE ZEDT06_100-ZSLAMT,    " ####

  ZDCAMT LIKE ZEDT06_100-ZDCAMT,    " ####

  ZWAERS LIKE ZEDT06_100-ZWAERS,    " ##

  ZSALE_NAME TYPE C LENGTH 4,       " ####

  ZJDATE LIKE ZEDT06_100-ZJDATE,    " ####

  ZRET_NAME TYPE C LENGTH 10,       " #####

  ZRDATE LIKE ZEDT06_100-ZRDATE,    " ####

  END OF GS_ORDER_0100.

DATA : GT_ORDER_0100 LIKE TABLE OF GS_ORDER_0100.



" ## ## ### ## INTERNAL TABLE.

DATA : BEGIN OF GS_DELIVERY,

  ZORDNO LIKE ZEDT06_101-ZORDNO,  " ####

  ZIDCODE LIKE ZEDT06_101-ZIDCODE, " ##ID

  ZMATNR LIKE ZEDT06_101-ZMATNR, " ####

  ZMTART LIKE ZEDT06_101-ZMTART,  " ####

  ZMTART_NAME TYPE C LENGTH 10,  " ####(#)

  ZMATNAME LIKE ZEDT06_101-ZMATNAME," ###

  ZVOLUM LIKE ZEDT06_101-ZVOLUM, " ##

  VOLUM LIKE ZEDT06_101-VOLUM, " VOLUME

  VRKME LIKE ZEDT06_101-VRKME, " SALES UNIT ##

  ZSLAMT LIKE ZEDT06_101-ZSLAMT, "####

  ZWAERS LIKE ZEDT06_101-ZWAERS, " ##

  ZDFLAG LIKE ZEDT06_101-ZDFLAG, " ####

  ZDFLAG_NAME LIKE ZEDT06_101-ZDFLAG, " ####(#)

  ZDGUBUN LIKE ZEDT06_101-ZDGUBUN, " ####

  ZDGB_NAME LIKE ZEDT06_101-ZDGUBUN, " ####(#)

  ZDDATE LIKE ZEDT06_101-ZDDATE, " ####

  ZRDATE LIKE ZEDT06_101-ZRDATE, " ####

  ZFLAG LIKE ZEDT06_101-ZFLAG, " ####

  END OF GS_DELIVERY.

DATA : GT_DELIVERY LIKE TABLE OF GS_DELIVERY.



" ## ## ### ## ALV ### ##

DATA : BEGIN OF GS_DELIVERY_0200,

  ICON TYPE C LENGTH 4,             " ###

  ZORDNO LIKE ZEDT06_101-ZORDNO,  " ####

  ZIDCODE LIKE ZEDT06_101-ZIDCODE, " ##ID

  ZMATNR LIKE ZEDT06_101-ZMATNR, " ####

  ZMTART LIKE ZEDT06_101-ZMTART,  " ####

  ZMTART_NAME TYPE C LENGTH 10,  " ####(#)

  ZMATNAME LIKE ZEDT06_101-ZMATNAME," ###

  ZVOLUM LIKE ZEDT06_101-ZVOLUM, " ##

  VOLUM LIKE ZEDT06_101-VOLUM, " VOLUME

  VRKME LIKE ZEDT06_101-VRKME, " SALES UNIT ##

  ZSLAMT LIKE ZEDT06_101-ZSLAMT, "####

  ZWAERS LIKE ZEDT06_101-ZWAERS, " ##

  ZDFLAG LIKE ZEDT06_101-ZDFLAG, " ####

  ZDFLAG_NAME TYPE C LENGTH 10, " ####(#)

  ZDGUBUN LIKE ZEDT06_101-ZDGUBUN, " ####

  ZDGB_NAME TYPE C LENGTH 10, " ####(#)

  ZDDATE LIKE ZEDT06_101-ZDDATE, " ####

  ZRDATE LIKE ZEDT06_101-ZRDATE, " ####

  ZFLAG LIKE ZEDT06_101-ZFLAG, " ####

  END OF GS_DELIVERY_0200.

DATA : GT_DELIVERY_0200 LIKE TABLE OF GS_DELIVERY_0200.





" ## ## ## ###

DATA : GC_DOCKING_100 TYPE REF TO CL_GUI_DOCKING_CONTAINER.

" GRID ## ## ###

DATA : GC_GRID_100 TYPE REF TO CL_GUI_ALV_GRID.



" ## ## ## ###

DATA : GC_DOCKING_0200 TYPE REF TO CL_GUI_DOCKING_CONTAINER.

" GRID ## ## ###

DATA : GC_GRID_0200 TYPE REF TO CL_GUI_ALV_GRID.



" ### ## FIELD CATALOG

DATA : GS_FIELDCAT TYPE LVC_S_FCAT.

DATA : GT_FIELDCAT TYPE LVC_T_FCAT.

" ### ## LAYOUT

DATA : GS_LAYOUT TYPE LVC_S_LAYO.

" ### ## SORT.

DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT TYPE LVC_T_SORT.

" ### ## VARIANT

DATA : GS_VARIANT TYPE DISVARIANT.