
*&---------------------------------------------------------------------*

*&  Include           ZEDR06_PRACTICE008_SCR

*&---------------------------------------------------------------------*








SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS S_ZORDNO FOR ZEDT06_100-ZORDNO.  " ####

  SELECT-OPTIONS S_IDCODE FOR ZEDT06_100-ZIDCODE NO INTERVALS NO-EXTENSION .   " ##ID

  SELECT-OPTIONS S_ZMATNT FOR ZEDT06_100-ZMATNR.  " ####

  SELECT-OPTIONS S_ZJDATE FOR ZEDT06_100-ZJDATE MODIF ID M1.  " ####

  SELECT-OPTIONS S_ZDDATE FOR ZEDT06_101-ZDDATE MODIF ID M2.  " ####

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.  " ####

  PARAMETERS P_R2 RADIOBUTTON GROUP R1.                   " ####

SELECTION-SCREEN END OF BLOCK B2.



SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME.

  PARAMETERS P_CHECK1 AS CHECKBOX DEFAULT 'X' MODIF ID M3.   " ######

SELECTION-SCREEN END OF BLOCK B3.