
*&---------------------------------------------------------------------*

*&  Include           ZMM23_002_TOP

*&---------------------------------------------------------------------*






TABLES : Z23EKKO, Z23EKPO, Z23MARA, Z23LFA1.



DATA : OK_CODE TYPE SY-UCOMM,

      GV_DYNNR TYPE SY-DYNNR VALUE '0101'.  "SUBSCREEN ## ## ##



DATA : GV_EBELPNUM TYPE I VALUE 10.

DATA : GV_FLAG TYPE C LENGTH 1 VALUE '1'.



CONTROLS CTR_200 TYPE TABLEVIEW USING SCREEN '0200'.

CONTROLS CTR_300 TYPE TABLEVIEW USING SCREEN '0300'.



"#### ## - SUBSCREEN 101

"#### ## - SUBSCREEN 102

DATA : GV_BUKRS LIKE Z23EKKO-BUKRS, "####

      GV_LIFNR LIKE Z23EKKO-LIFNR,  "#####

      GV_BEDAT LIKE Z23EKKO-BEDAT,  "###

      GV_EBELN LIKE Z23EKKO-EBELN.  "PO ##



"PO## - SCREEN 200

DATA : BEGIN OF GS_PO,

  GV_CHECK TYPE C LENGTH 1,    "#####(## #)

  GV_EBELP LIKE Z23EKPO-EBELP, "##

  GV_MATNR LIKE Z23EKPO-MATNR, "####

  GV_MAKTX LIKE Z23EKPO-MAKTX, "###

  GV_MENGE LIKE Z23EKPO-MENGE,  "PO##

  GV_STPRS LIKE Z23EKPO-STPRS,  "##

  GV_MEINS LIKE Z23EKPO-MEINS,  "##

  GV_WAERS LIKE Z23EKKO-WAERS,  "##

  "####

  GV_PRDAT LIKE Z23EKPO-PRDAT,  "###

  GV_WERKS LIKE Z23EKPO-WERKS,  "###

  GV_LGORT LIKE Z23EKPO-LGORT,"####

  END OF GS_PO.

DATA : GT_PO LIKE TABLE OF GS_PO.



DATA : GS_EKKO TYPE Z23EKKO.

"DATA : GT_EKKO LIKE TABLE OF GS_EKKO.

DATA : GS_EKPO TYPE Z23EKPO.

DATA : GT_EKPO LIKE TABLE OF GS_EKPO.