
*&---------------------------------------------------------------------*

*&  Include           ZMM05_002_SCR

*&---------------------------------------------------------------------*








SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.

  PARAMETERS : P_BUKRS TYPE BUKRS MODIF ID M1 DEFAULT '1000'.

  PARAMETERS : P_LIFNR1 TYPE LIFNR MODIF ID M1 DEFAULT '1000000000'.

  PARAMETERS : P_BEDAT TYPE ZEKKO_05-BEDAT MODIF ID M1 DEFAULT SY-DATUM.



  PARAMETERS : P_LIFNR2 TYPE LIFNR MODIF ID M2 DEFAULT '1000000005'.

  PARAMETERS : P_BUKRS2 TYPE BUKRS MODIF ID M2 DEFAULT '1000'.

  PARAMETERS : P_EBLEN TYPE EBELN MODIF ID M2 DEFAULT '4500000001'.

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS : R_CRE RADIOBUTTON GROUP G1 DEFAULT 'X' USER-COMMAND UCOM.

  PARAMETERS : R_VIEW RADIOBUTTON GROUP G1.

SELECTION-SCREEN END OF BLOCK B2.