
*&---------------------------------------------------------------------*

*& Report ZEDR03_010_PARAMETERS

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR03_010_PARAMETERS.



DATA : BEGIN OF GS_STUDENT,

  ZCODE LIKE ZEDT03_001-ZCODE,

  ZGENDER LIKE ZEDT03_001-ZGENDER,

END OF GS_STUDENT.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.





SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

PARAMETERS : P_ZCODE LIKE ZEDT03_001-ZCODE.

PARAMETERS : P_ZNUM TYPE P DECIMALS 2 NO-DISPLAY.

PARAMETERS : P_ZGEN LIKE ZEDT03_001-ZGENDER DEFAULT 'M'.

SELECTION-SCREEN END OF BLOCK B1.





SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.



SELECTION-SCREEN BEGIN OF LINE.

PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'.

SELECTION-SCREEN POSITION 3.

SELECTION-SCREEN COMMENT (10) FOR FIELD P_R1.

PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

SELECTION-SCREEN POSITION 79.

SELECTION-SCREEN COMMENT (10) FOR FIELD P_R2.

SELECTION-SCREEN END OF LINE.



PARAMETERS : Z_CHECK AS CHECKBOX DEFAULT 'X'.



SELECTION-SCREEN END OF BLOCK B2.



SELECT * FROM ZEDT03_001

  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

  WHERE ZCODE = P_ZCODE

  AND ZGENDER = P_ZGEN.



IF GT_STUDENT[] IS NOT INITIAL.

  WRITE :/ '### ##'.

ELSE.

  WRITE :/ '### ##'.

ENDIF.