
*&---------------------------------------------------------------------*

*&  Include           ZEDR13_PRACTICE009_TOP

*&---------------------------------------------------------------------*






TABLES : ZEDT13_102.



CONSTANTS : C_X TYPE CHAR1 VALUE 'X'.

CONSTANTS : C_A TYPE CHAR1 VALUE 'A'.

CONSTANTS : C_B TYPE CHAR1 VALUE 'B'.

CONSTANTS : C_C TYPE CHAR1 VALUE 'C'.

CONSTANTS : C_D TYPE CHAR1 VALUE 'D'.

CONSTANTS : C_E TYPE CHAR1 VALUE 'E'.

CONSTANTS : C_F TYPE CHAR1 VALUE 'F'.

CONSTANTS : C_G TYPE CHAR1 VALUE 'G'.

CONSTANTS : C_SS1 TYPE CHAR6 VALUE 'SS0001'.

CONSTANTS : C_SS2 TYPE CHAR3 VALUE 'SS0002'.

CONSTANTS : C_SS3 TYPE CHAR3 VALUE 'SS0003'.

CONSTANTS : C_SS4 TYPE CHAR3 VALUE 'SS0004'.

CONSTANTS : C_SS5 TYPE CHAR3 VALUE 'SS0005'.

CONSTANTS : C_SS6 TYPE CHAR3 VALUE 'SS0006'.



DATA : BEGIN OF GS_PERINFO,             "#######"

  ZPERNR TYPE ZEDT13_102-ZPERNR,        "####"

  ZPNAME TYPE ZEDT13_103-ZPNAME,        "####"

  ZDEPCODE TYPE ZEDT13_102-ZDEPCODE,    "####"

  DATBI LIKE ZEDT13_102-DATBI,          "####"

  DATAB LIKE ZEDT13_102-DATAB,          "####"

  ZDEPRANK TYPE ZEDT13_102-ZDEPRANK,    "####"

  ZGENDER TYPE ZEDT13_103-ZGENDER,      "##"

  ZEDATE TYPE ZEDT13_102-ZEDATE,        "####"

  ZADDRESS TYPE ZEDT13_103-ZADDRESS,    "##"

  ZQDATE TYPE ZEDT13_102-ZQDATE,        "####"

  ZQFLAG TYPE ZEDT13_102-ZQFLAG,        "####"

  END OF GS_PERINFO.

 DATA : GT_PERINFO LIKE TABLE OF GS_PERINFO.



DATA : BEGIN OF GS_WPERINFO,            "#######"

  ZICON TYPE C LENGTH 4,                "### ICON"

  ZPERNR TYPE ZEDT13_102-ZPERNR,        "####"

  ZPNAME TYPE ZEDT13_103-ZPNAME,        "####"

  ZDEPNAME TYPE C LENGTH 6,             "## <- ####"

  DATBI LIKE ZEDT13_102-DATBI,          "####"

  DATAB LIKE ZEDT13_102-DATAB,          "####"

  ZDEPRANK TYPE C LENGTH 3,             "## <- ####"

  ZGENDER TYPE C LENGTH 3,              "#/# <- ##"

  ZEDATE TYPE ZEDT13_102-ZEDATE,        "####"

  ZADDRESS TYPE ZEDT13_103-ZADDRESS,    "##"

  ZQDATE TYPE ZEDT13_102-ZQDATE,        "####"

  ZQFLAG TYPE ZEDT13_102-ZQFLAG,        "####"

  END OF GS_WPERINFO.

 DATA : GT_WPERINFO LIKE TABLE OF GS_WPERINFO.



 DATA : BEGIN OF GS_EVALCHECK,          "#######"

  ZPERNR LIKE ZEDT13_104-ZPERNR,        "####"

  ZDEPCODE LIKE ZEDT13_104-ZDEPCODE,    "####"

  ZYEAR LIKE ZEDT13_104-ZYEAR,          "####"

  DATBI LIKE ZEDT13_104-DATBI,          "####"

  DATAB LIKE ZEDT13_104-DATAB,          "####"

  ZRANK LIKE ZEDT13_104-ZRANK,          "##"

  END OF GS_EVALCHECK.

 DATA : GT_EVALCHECK LIKE TABLE OF GS_EVALCHECK.



 DATA : BEGIN OF GS_WEVALCHECK,         "#######"

  ZPERNR LIKE ZEDT13_104-ZPERNR,        "####"

  ZDEPNAME TYPE C LENGTH 6,             "## <- ####"

  ZYEAR LIKE ZEDT13_104-ZYEAR,          "####"

  DATBI LIKE ZEDT13_104-DATBI,          "####"

  DATAB LIKE ZEDT13_104-DATAB,          "####"

  ZRANK LIKE ZEDT13_104-ZRANK,          "##"

  END OF GS_WEVALCHECK.

 DATA : GT_WEVALCHECK LIKE TABLE OF GS_WEVALCHECK.



 DATA : BEGIN OF GS_SALARY,             "#######"

  ZPERNR LIKE ZEDT13_106-ZPERNR,        "####"

  ZYEAR LIKE ZEDT13_106-ZYEAR,          "####"

  DATBI LIKE ZEDT13_106-DATBI,          "####"

  DATAB LIKE ZEDT13_106-DATAB,          "####"

  ZSALARY LIKE ZEDT13_106-ZSALARY,      "####"

  ZBANKCODE LIKE ZEDT13_106-ZBANKCODE,  "####"

  ZACCOUNT LIKE ZEDT13_106-ZACCOUNT,    "####"

  END OF GS_SALARY.

DATA : GT_SALARY LIKE TABLE OF GS_SALARY.



DATA : BEGIN OF GS_WSALARY,             "#######"

  ZPERNR LIKE ZEDT13_106-ZPERNR,        "####"

  ZYEAR LIKE ZEDT13_106-ZYEAR,          "####"

  DATBI LIKE ZEDT13_106-DATBI,          "####"

  DATAB LIKE ZEDT13_106-DATAB,          "####"

  ZSALARY LIKE ZEDT13_106-ZSALARY,      "####"

  ZBANKNAME TYPE C LENGTH 6,            "### <- ####"

  ZWAERS TYPE WAERS,                    "## <-####"

  ZACCOUNT LIKE ZEDT13_106-ZACCOUNT,    "####"

  END OF GS_WSALARY.

DATA : GT_WSALARY LIKE TABLE OF GS_WSALARY.



RANGES : R_QFG FOR ZEDT13_102-ZQFLAG. "## ### ## ## ### ##### ### ##"



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT,  "CLASS ALV FIELDCAT"

       GT_FIELDCAT1 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT2 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT3 TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.    "CLASS ALV LAYOUT"



DATA : GS_SORT TYPE LVC_S_SORT .     "CLASS ALV SORT"

DATA : GT_SORT1 TYPE LVC_T_SORT.

DATA : GT_SORT2 TYPE LVC_T_SORT.

DATA : GT_SORT3 TYPE LVC_T_SORT.



DATA : GS_VARIANT TYPE DISVARIANT.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.



DATA : GC_SPLITTER1 TYPE REF TO CL_GUI_SPLITTER_CONTAINER. "### ####"

DATA : GC_SPLITTER2 TYPE REF TO CL_GUI_SPLITTER_CONTAINER. "### ####"



DATA : GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.  "## ##"

DATA : GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.  "### ##"

DATA : GC_CONTAINER3 TYPE REF TO CL_GUI_CONTAINER.  "## ## ##"

DATA : GC_CONTAINER4 TYPE REF TO CL_GUI_CONTAINER.  "## ## ##"



DATA : GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID.