
*&---------------------------------------------------------------------*

*&  Include           ZEDR03_017_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS : S_ZORDO FOR ZEDT03_100-ZORDNO. "####

  SELECT-OPTIONS : S_ZID FOR ZEDT03_100-ZIDCODE NO INTERVALS NO-EXTENSION. "##ID

  SELECT-OPTIONS : S_ZMATNR FOR ZEDT03_100-ZMATNR. "####

  SELECT-OPTIONS : S_ZJDATE FOR ZEDT03_100-ZJDATE MODIF ID M1. "####*

  SELECT-OPTIONS : S_ZDDATE FOR ZEDT03_101-ZDDATE MODIF ID M2. "####*

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS : P_ORDER RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

  PARAMETERS : P_DEV RADIOBUTTON GROUP R1.

SELECTION-SCREEN END OF BLOCK B2.



SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME.

  PARAMETERS : P_ZINCL AS CHECKBOX DEFAULT 'X'.

SELECTION-SCREEN END OF BLOCK B3.