
*&---------------------------------------------------------------------*

*&  Include           ZEDR03_017_TOP

*&---------------------------------------------------------------------*




TABLES : ZEDT03_001.



DATA : BEGIN OF GS_STUDENT,

  ZCOLOR TYPE C LENGTH 4,

  ZCODE LIKE ZEDT03_001-ZCODE, "####

  ZPERNR LIKE ZEDT03_001-ZPERNR, "####

  ZKNAME LIKE ZEDT03_001-ZKNAME, "##

  ZENAME LIKE ZEDT03_001-ZENAME, "###

  ZGENDER LIKE ZEDT03_001-ZGENDER, "##

  ZSUM LIKE ZEDT03_002-ZSUM, "##

  ZMAJOR LIKE ZEDT03_002-ZMAJOR, "##

  ZMNAME LIKE ZEDT03_002-ZMNAME, "###

  END OF GS_STUDENT.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.



DATA : OK_CODE TYPE SY-UCOMM. "###### ### ## ##



DATA : GC_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER. "### #### ##

DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID. " ### ## ## ##



DATA : GS_FIELDCAT TYPE LVC_S_FCAT. "## #### (## ALV# ###!)

DATA : GT_FIELDCAT TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO. "#### (## ALV# ###!)



DATA : GS_SORT TYPE LVC_S_SORT. "SORT (## ALV# ###!)

DATA : GT_SORT TYPE LVC_T_SORT.