
*&---------------------------------------------------------------------*

*&  Include           ZEDR23_PRACTICE009_SCR

*&---------------------------------------------------------------------*






SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS : S_ZPERNR FOR ZEDT23_102-ZPERNR."####

  SELECT-OPTIONS : S_DATE FOR ZEDT23_102-DATBI NO INTERVALS NO-EXTENSION. "####

  SELECT-OPTIONS : S_DEP FOR ZEDT23_102-ZDEPCODE NO INTERVALS NO-EXTENSION. "####

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS : P_CHECK AS CHECKBOX.

SELECTION-SCREEN END OF BLOCK B2.