
*&---------------------------------------------------------------------*

*&  Include           ZCLASS_EVENT22_TOP

*&---------------------------------------------------------------------*






TABLES : ZEDT022_001.



DATA : BEGIN OF GS_STUDENT,

         ICON    TYPE ICON_D,                       "### ### ##

         ZCOLOR  TYPE C LENGTH 4,

         ZCODE   LIKE ZEDT022_001-ZCODE,

         ZPERNR  LIKE ZEDT022_001-ZPERNR,

         ZKNAME  LIKE ZEDT022_001-ZKNAME,

         ZENAME  LIKE ZEDT022_001-ZENAME,

         ZGENDER LIKE ZEDT022_001-ZGENDER,

         ZTEL    LIKE ZEDT022_001-ZTEL,

         ZSUM    LIKE ZEDT022_002-ZSUM,

         ZMAJOR  LIKE ZEDT022_002-ZMAJOR,

         ZMNAME  LIKE ZEDT022_002-ZMNAME,

       END OF GS_STUDENT.



DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA : GC_GRID    TYPE REF TO CL_GUI_ALV_GRID.



DATA : GO_EVENT   TYPE REF TO EVENT.



DATA : GS_VARIANT TYPE DISVARIANT.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT.

DATA : GT_FIELDCAT TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT TYPE LVC_T_SORT.



DATA : GV_CHECK(1).



DATA : GS_SAVE TYPE ZEDT022_001, "### ## ###

       GT_SAVE LIKE TABLE OF GS_SAVE. "### ## ###