
*&---------------------------------------------------------------------*

*& Report ZEDR19_034

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR19_034.






*PARAMETERS : P_ZCODE LIKE ZEDT19_0001-ZCODE. "#### ##



*PARAMETERS : P_ZCODE LIKE ZEDT19_0001-ZCODE LOWER CASE. "### ### ##



*PARAMETERS : P_ZPERNR TYPE C LENGTH 10. "### ### ##



*PARAMETERS : P_ZCODE LIKE ZEDT19_0001-ZCODE OBLIGATORY. "##### ## ## ##, #### ### ##



*PARAMETERS : P_ZCODE LIKE ZEDT19_0001-ZCODE VISIBLE LENGTH 5. "### ### ### ### ##

*PARAMETERS : P_ZPERNR TYPE C LENGTH 10 NO-DISPLAY. "#### ##  ##

* "##### #### ### #### ### ## ### #### # ## ##

*PARAMETERS : P_ZNUM TYPE P DECIMALS 2. "### ### ## # ##

*PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER DEFAULT 'M'. "## # ## # ##

* "DATA## VALUE## #### ### ### ##

*PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'. "###### ## ### ##

*PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

*

*IF P_R1 = 'X'.

*  WRITE :/ '#### ##'.

*ELSEIF P_R2 = 'X'.

*  WRITE :/ '## ##'.

*ENDIF.

*

*PARAMETERS : Z_CHECK AS CHECKBOX DEFAULT 'X'. "Checkbox ### ### # ##

*

*IF Z_CHECK = 'X'.

*  WRITE :/ '#### ##'.

*ELSE.

*  WRITE :/ '## ##'.

*ENDIF.



*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'.

*PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

*PARAMETERS : Z_CHECK AS CHECKBOX DEFAULT 'X'.

*SELECTION-SCREEN END OF BLOCK B2.



*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*SELECTION-SCREEN BEGIN OF LINE.

*  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'.

*SELECTION-SCREEN POSITION 3.

*SELECTION-SCREEN COMMENT (10) FOR FIELD P_R1.

*  PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

*SELECTION-SCREEN POSITION 20.

*SELECTION-SCREEN COMMENT (10) FOR FIELD P_R2.

*SELECTION-SCREEN END OF LINE.

*SELECTION-SCREEN END OF BL2CK B2.



*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*SELECTION-SCREEN BEGIN OF LINE.

*  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'.

*SELECTION-SCREEN POSITION 3.

*SELECTION-SCREEN COMMENT (10) FOR FIELD P_R1.

*  PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

*SELECTION-SCREEN POSITION 20.

*SELECTION-SCREEN COMMENT (10) FOR FIELD P_R2.

*SELECTION-SCREEN END OF LINE.

*SELECTION-SCREEN END OF BLOCK B2.



*DATA : GT_STUDENT LIKE TABLE OF ZEDT19_0001,

*       GS_STUDENT LIKE ZEDT19_0001.

*

* "RADIO BUTTON# ### ### ## ##

*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*PARAMETERS : P_ZCODE LIKE ZEDT19_0001-ZCODE.

*PARAMETERS : P_ZPERNR TYPE C LENGTH 10 NO-DISPLAY.

*PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER DEFAULT 'M'.

*SELECTION-SCREEN END OF BLOCK B1.

*

* "DB ### ZEDT19_0001## ### #### ### ### GT_STUDENT# ##

*SELECT * FROM ZEDT19_0001

*  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

*  WHERE ZCODE = P_ZCODE

*  AND ZGENDER = P_ZGEN.

*

*IF GT_STUDENT[] IS NOT INITIAL.

*  WRITE :/ '### ##'.

*ELSE.

*  WRITE :/ '### ##'.

*ENDIF.



*SELECT-OPTIONS : S_ZCODE FOR ZEDT19_0001-ZCODE. "## ### ###

* "Ranges ##(sign, option, low, high)# ## #### ## ###

*PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER.



*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT19_0001-ZCODE.

*SELECTION-SCREEN END OF BLOCK B1.

*

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER.

*SELECTION-SCREEN END OF BLOCK B2.



*SELECT * FROM ZEDT19_0001

* "### #### #### ## ### ## ### GT_STUDENT# ##

*  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

*  WHERE ZCODE IN S_ZCODE

*  AND ZGENDER = P_ZGEN.

*

*IF GT_STUDENT[] IS NOT INITIAL. "GT_STUDENT# ## ## ###

*  CLEAR : GS_STUDENT.

*  LOOP AT GT_STUDENT INTO GS_STUDENT. "# ## GS_STUDENT# ##

*    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME.

*  ENDLOOP.

*ELSE.

*  WRITE :/ '### ##'.

*ENDIF.



*SELECT-OPTIONS : S_ZCODE FOR ZEDT19_0001-ZCODE DEFAULT 'SSU-01'.

* "S_ZCODE ## ## ## ## ##

*PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER.



*SELECT-OPTIONS : S_ZCODE FOR ZEDT19_0001-ZCODE DEFAULT 'SSU-01' SIGN I OPTION EQ.

* "## ### # # ##### ### #.

*PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER.



*SELECT-OPTIONS : S_ZCODE FOR ZEDT19_0001-ZCODE DEFAULT 'SSU-01' TO 'SSU-99' SIGN I OPTION BT.

*PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER. "DEFAULT# DATA# 1#### ## ##

*

* "DEFAULT# DATA# 1## ## BT ## -> BT# between###

*SELECT-OPTIONS : S_ZCODE FOR ZEDT19_0001-ZCODE DEFAULT 'SSU-01' TO 'SSU-99'.

*PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER.



* "SSU-01 ~ SSU-99 ### ####

*SELECT-OPTIONS : S_ZCODE FOR ZEDT19_0001-ZCODE DEFAULT 'SSU-01' TO 'SSU-99' SIGN E OPTION BT.

*PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER.



*"## ## #### ##

*SELECT-OPTIONS : S_ZCODE FOR ZEDT19_0001-ZCODE DEFAULT 'SSU-01' NO INTERVALS.

*PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER.



* "Multiple Selections ### ##

*SELECT-OPTIONS : S_ZCODE FOR ZEDT19_0001-ZCODE DEFAULT 'SSU-01' NO INTERVALS NO-EXTENSION.

*PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER.



* "Visible length : ## ##

*SELECT-OPTIONS : S_ZCODE FOR ZEDT19_0001-ZCODE DEFAULT 'SSU-01' VISIBLE LENGTH 3.

*PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER.



*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT19_0001-ZCODE.

*  PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER.

*SELECTION-SCREEN END OF BLOCK B1.

* "MODIF ID : #### ## ## ##

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : P_CH1 AS CHECKBOX DEFAULT 'X' MODIF ID M1. "## 3### ###

*  "### ### #### ###. (#### ### ### 3## ### ##)

*  PARAMETERS : P_CH2 AS CHECKBOX MODIF ID M2.

*SELECTION-SCREEN END OF BLOCK B2.



*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT19_0001-ZCODE.

*  PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER.

*SELECTION-SCREEN END OF BLOCK B1.

*

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : P_CH1 AS CHECKBOX DEFAULT 'X' MODIF ID M1.

*  PARAMETERS : P_CH2 AS CHECKBOX MODIF ID M2.

*SELECTION-SCREEN END OF BLOCK B2.

*

*AT SELECTION-SCREEN OUTPUT. "SELECTION-SCREEN# #### ## ##

* "SCREEN#, GROUP# #### ## ##

*  LOOP AT SCREEN.

*    IF SCREEN-GROUP1 = 'M2'. "modif id# ## ### ##

*      SCREEN-INPUT = '0'.

*      MODIFY SCREEN.

*    ENDIF.

*  ENDLOOP.



*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : P_CH1 AS CHECKBOX DEFAULT 'X' MODIF ID M1. "Selection Screen ### #### ## 1 ##

*  PARAMETERS : P_CH2 AS CHECKBOX MODIF ID M2.

*SELECTION-SCREEN END OF BLOCK B2.



*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT19_0001-ZCODE.

*  PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER.

*SELECTION-SCREEN END OF BLOCK B1.

*

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : P_CH1 AS CHECKBOX DEFAULT 'X' MODIF ID M1.

*  PARAMETERS : P_CH2 AS CHECKBOX MODIF ID M2.

*SELECTION-SCREEN END OF BLOCK B2.

*

* "Selection Screen# #### ### ### (## ##, #### #)

*AT SELECTION-SCREEN OUTPUT.

*  LOOP AT SCREEN.

*    IF SCREEN-GROUP1 = 'M2'.

*      SCREEN-INPUT = '0'. "MODIF ID# ## ### ##

*      MODIFY SCREEN.

*    ENDIF.

*  ENDLOOP.



*AT SELECTION-SCREEN OUTPUT.

*  LOOP AT SCREEN.

*    IF SCREEN-GROUP1 = 'P_CH2'. "MODIF ID ## ## ## 'P_CH2'# ### ### ##

*      SCREEN-INPUT = '0'. " ## ### ######

*      MODIFY SCREEN. " ## ### ## Selection Screen# ##

*    ENDIF.

*  ENDLOOP.



*AT SELECTION-SCREEN OUTPUT.

*  LOOP AT SCREEN.

*    IF SCREEN-GROUP1 = 'M2'.

*      SCREEN-ACTIVE = '0'. "## ### ####(## ##)

*      MODIFY SCREEN. " ## ### ## Selection Screen# ##

*    ENDIF.

*  ENDLOOP.



*AT SELECTION-SCREEN OUTPUT.

*  LOOP AT SCREEN.

*    IF SCREEN-GROUP1 = 'M2'.

*      SCREEN-REQUIRED = '1'. "P_CH2 ##### ### # ## ### ##

*      MODIFY SCREEN. " ## ### ## Selection Screen# ##

*    ENDIF.

*  ENDLOOP.



*AT SELECTION-SCREEN OUTPUT.

*  LOOP AT SCREEN.

*    IF SCREEN-GROUP1 = 'M2'.

*      SCREEN-OUTPUT = '0'. "## ## #### (P_CH2 ###)

*      MODIFY SCREEN. " ## ### ## Selection Screen# ##

*    ENDIF.

*  ENDLOOP.



*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT19_0001-ZCODE.

*  PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER.

*SELECTION-SCREEN END OF BLOCK B1.

*

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : P_CH1 AS CHECKBOX DEFAULT 'X' MODIF ID M1.

*  PARAMETERS : P_CH2 AS CHECKBOX MODIF ID M2.

*SELECTION-SCREEN END OF BLOCK B2.



*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT19_0001-ZCODE.

*  PARAMETERS : P_ZPERNR LIKE ZEDT19_0001-ZPERNR MODIF ID M1.

*  PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER MODIF ID M2.

*SELECTION-SCREEN END OF BLOCK B1.





*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  SELECT-OPTIONS : S_CODE FOR ZEDT19_0001-ZCODE.

*  PARAMETERS : P_ZPERNR LIKE ZEDT19_0001-ZPERNR MODIF ID M1.

*  PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER MODIF ID M2.

*SELECTION-SCREEN END OF BLOCK B1.

*

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

*  "user-command# #### ## UI ### ##### # ### ## SY-UCOMM# #### ###

*  "user-command : ###### #### ### ##### ### ### # #### #####.

*  PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

*SELECTION-SCREEN END OF BLOCK B2.

*

*AT SELECTION-SCREEN OUTPUT.

*  LOOP AT SCREEN.

*    IF SCREEN-GROUP1 = 'M2'. "M2 ### ## ### ##

*      IF P_R1 = 'X'.

*        SCREEN-ACTIVE = '1'. "#####1# ## -> ####

*      ELSEIF P_R2 = 'X'.

*        SCREEN-ACTIVE = '0'. "#####2# ## -> ####

*      ENDIF.

*    ENDIF.

*    MODIFY SCREEN. "#### ##

*  ENDLOOP.



*AT SELECTION-SCREEN OUTPUT.

*  LOOP AT SCREEN.

*    IF SCREEN-GROUP1 = 'M2'.

*      SCREEN-INTENSIFIED = '1'. "### ##### ##

*    ENDIF.

*    MODIFY SCREEN.

*  ENDLOOP.



*AT SELECTION-SCREEN OUTPUT.

*  LOOP AT SCREEN.

*    IF SCREEN-GROUP1 = 'M2'.

*      SCREEN-DISPLAY_3D = '1'. "### ### ##

*    ENDIF.

*    MODIFY SCREEN.

*  ENDLOOP.



*AT SELECTION-SCREEN OUTPUT.

*  LOOP AT SCREEN.

*    IF SCREEN-GROUP1 = 'M2'.

*      SCREEN-INVISIBLE = '1'. "#### ##

*    ENDIF.

*    MODIFY SCREEN.

*  ENDLOOP.



*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT19_0001-ZCODE.

*  PARAMETERS : P_ZPERNR LIKE ZEDT19_0001-ZPERNR MODIF ID M1.

*  PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER MODIF ID M2.

*SELECTION-SCREEN END OF BLOCK B1.

*

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'.

*  "usercommand# ###? -> enter# ##

*  PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

*SELECTION-SCREEN END OF BLOCK B2.



*TABLES : ZEDT19_0001.

*

*DATA : BEGIN OF GS_STUDENT.

*  INCLUDE TYPE ZEDT19_0001.

*  DATA : END OF GS_STUDENT.

*DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

*

*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT19_0001-ZCODE.

*  PARAMETERS : P_ZPERNR LIKE ZEDT19_0001-ZPERNR MODIF ID M1.

*  PARAMETERS : P_ZGEN LIKE ZEDT19_0001-ZGENDER MATCHCODE OBJECT ZSH19_001 MODIF ID M2.

*SELECTION-SCREEN END OF BLOCK B1.

*"SEARCH HELP# #### ## ### ##### MATCHCODE OBJECT ### ## ##



*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'.

*  "usercommand# ###? -> enter# ##

*  PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

*SELECTION-SCREEN END OF BLOCK B2.