
*&---------------------------------------------------------------------*

*& Report ZEDR15_016

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR15_016.






*"PARAMETERS : P_ZCODE LIKE ZEDT15_001-ZCODE LOWER CASE. "4) ### ##

*"PARAMETERS : P_ZCODE LIKE ZEDT15_001-ZCODE OBLIGATORY. "5) ### ##

*PARAMETERS : P_ZCODE LIKE ZEDT15_001-ZCODE VISIBLE LENGTH 5. "7)#### ##

*PARAMETERS : P_ZPERNR TYPE C LENGTH 10. "1) ## ##

*PARAMETERS : P_ZNUM TYPE P DECIMALS 2 NO-DISPLAY. "2) ### ## 6) #### ##

*PARAMETERS : P_ZGEN LIKE ZEDT15_001-ZGENDER DEFAULT 'M'. "3) DEFALUT# ##/ 8) SEARCH HELP

*

*"9) CHECKBOX

*PARAMETERS : Z_CHECK AS CHECKBOX DEFAULT 'X'.

*

*IF Z_CHECK = 'X'.

*  WRITE : / '#### ##'.

*ELSE.

*  WRITE : / '####'.

*ENDIF.

*

*"10) RADIO BUTTON

*PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'.

*PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

*

*IF P_R1 = 'X'.

*  WRITE : / '#### ##'.

*ELSEIF P_R2 = 'X'.

*  WRITE : / '## ##'.

*ENDIF.

*

*"10-2) RADIO BUTTON ( BLOCK## #### ### )

*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  PARAMETERS : P_ZCODE LIKE ZEDT15_001-ZCODE.

*  PARAMETERS : P_ZPERNR TYPE C LENGTH 10 NO-DISPLAY.

*  PARAMETERS : P_ZGEN LIKE ZEDT15_001-ZGENDER DEFAULT 'M'.

*SELECTION-SCREEN END OF BLOCK B1.

*

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'.

*  PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

*  PARAMETERS : Z_CHECK AS CHECKBOX DEFAULT 'X'.

*SELECTION-SCREEN END OF BLOCK B2.






"10-3) RADIO BUTTON (# ### #### ## ###)




*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  PARAMETERS : P_ZCODE LIKE ZEDT15_001-ZCODE.

*  PARAMETERS : P_ZPERNR TYPE C LENGTH 10 NO-DISPLAY.

*  PARAMETERS : P_ZGEN LIKE ZEDT15_001-ZGENDER DEFAULT 'M'.

*SELECTION-SCREEN END OF BLOCK B1.

*

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  SELECTION-SCREEN BEGIN OF LINE.

*    PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'.

*  SELECTION-SCREEN POSITION 3.

*  SELECTION-SCREEN COMMENT (10) FOR FIELD P_R1.

*    PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

*  SELECTION-SCREEN POSITION 20.

*  SELECTION-SCREEN COMMENT (10) FOR FIELD P_R2.

*  SELECTION-SCREEN END OF LINE.

*SELECTION-SCREEN END OF BLOCK B2.






"PARAMETERS# DB ## #

DATA : BEGIN OF GS_STUDENT,

  ZCODE TYPE ZEDT15_001-ZCODE,

  ZGENDER TYPE ZEDT15_001-ZGENDER,

  END OF GS_STUDENT.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.



SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  PARAMETERS : P_ZCODE LIKE ZEDT15_001-ZCODE.

  PARAMETERS : P_ZPERNR TYPE C LENGTH 10 NO-DISPLAY.

  PARAMETERS : P_ZGEN LIKE ZEDT15_001-ZGENDER DEFAULT 'M'.

SELECTION-SCREEN END OF BLOCK B1.



SELECT * FROM ZEDT00_001

  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

  WHERE ZCODE = P_ZCODE

  AND ZGENDER = P_ZGEN.



IF GT_STUDENT[] IS NOT INITIAL.

  WRITE : / '### ##'.

ELSE.

  WRITE : / '### ##'.

ENDIF.