
*&---------------------------------------------------------------------*

*&  Include           ZWORK23_001_TOP

*&---------------------------------------------------------------------*






TABLES : SSCRFIELDS.

SELECTION-SCREEN FUNCTION KEY 1.  "SCREEN# Toolbar# ## ## / ## 5# ##



DATA : BEGIN OF GS_TCURR2,

  ZKURST TYPE KURST_CURR, "####

  ZFCURR TYPE FCURR_CURR, "####

  ZTCURR TYPE TCURR_CURR, "####

  ZGDATU TYPE GDATU_INV, "## ## ###

  ZUKURS TYPE UKURS_CURR, "##

  "ZUKURS TYPE P DECIMALS 5, "##

  ZFFACT TYPE FFACT_CURR, "#### ### ##

  ZTFACT TYPE TFACT_CURR, "#### ### ##

  ZUNAME TYPE SY-UNAME,   "###

  ZDATUM TYPE SY-DATUM,   "###

  END OF GS_TCURR2.

DATA : GT_TCURR2 LIKE TABLE OF GS_TCURR2.



DATA : BEGIN OF GS_TCURR,

  ZKURST LIKE ZTCURR23-KURST, "####

  ZFCURR LIKE ZTCURR23-FCURR, "####

  ZTCURR LIKE ZTCURR23-TCURR, "####

  ZGDATU LIKE ZTCURR23-GDATU, "## ## ###

  ZUKURS LIKE ZTCURR23-UKURS, "##

  ZFFACT LIKE ZTCURR23-FFACT, "#### ### ##

  ZTFACT LIKE ZTCURR23-TFACT, "#### ### ##

  ZCRNAME LIKE ZTCURR23-CRNAME,   "###

  ZCRDATE LIKE ZTCURR23-CRDATE,    "###

  END OF GS_TCURR.

DATA : GT_TCURR LIKE TABLE OF GS_TCURR.



DATA : OK_CODE TYPE SY-UCOMM.

DATA : GO_EVENT TYPE REF TO EVENT.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT.

DATA : GT_FIELDCAT TYPE LVC_T_FCAT.

DATA : GS_LAYOUT TYPE LVC_S_LAYO.

DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT TYPE LVC_T_SORT.