
*&---------------------------------------------------------------------*

*& Report ZEDR20_017

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR20_017.



TABLES: ZEDT20_001.



DATA: BEGIN OF GS_STUDENT.

  include structure
ZEDT20_001
.

  DATA: END OF GS_STUDENT.

DATA: GT_STUDENT LIKE TABLE OF GS_STUDENT.



SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS : S_ZCODE FOR ZEDT20_001-ZCODE DEFAULT 'SSU-01'

    SIGN I

    NO INTERVALS

    NO-EXTENSION

    VISIBLE LENGTH 6

    MODIF ID M1."TO 'SSU-10' SIGN E OPTION BT.

  PARAMETERS: P_ZGEN TYPE C MATCHCODE OBJECT ZSH20_001 MODIF ID M2."LIKE ZEDT20_001-ZGENDER MODIF ID M2.

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS: P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

  PARAMETERS: P_R2 RADIOBUTTON GROUP R1.

SELECTION-SCREEN END OF BLOCK B2.






*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  SELECTION-SCREEN BEGIN OF LINE.

*    PARAMETERS: P_C1 AS CHECKBOX DEFAULT 'X' USER-COMMAND UC1.

*    SELECTION-SCREEN POSITION 3.

*    SELECTION-SCREEN COMMENT (10) FOR FIELD P_C1.

*    PARAMETERS: P_C2 AS CHECKBOX.

*    SELECTION-SCREEN POSITION 20.

*    SELECTION-SCREEN COMMENT (10) FOR FIELD P_C2.

*  SELECTION-SCREEN END OF LINE.

*SELECTION-SCREEN END OF BLOCK B2.






AT SELECTION-SCREEN OUTPUT.

  LOOP AT SCREEN.

    IF SCREEN-GROUP1 = 'M2'.

      IF P_R1 = 'X'.

        SCREEN-ACTIVE = '1'.

      ELSEIF P_R2 = 'X'.

        SCREEN-ACTIVE = '0'.

      ENDIF.

    ENDIF.

    MODIFY SCREEN.

  ENDLOOP.

"ENDAT.



SELECT ZCODE

      ZKNAME

  FROM ZEDT20_001

  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

  WHERE ZCODE IN S_ZCODE

  AND ZGENDER = P_ZGEN.



LOOP AT GT_STUDENT INTO GS_STUDENT.

  WRITE: / GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME.

ENDLOOP.