
*&---------------------------------------------------------------------*

*&  Include           ZEDR24_PRACTICE008_TOP

*&---------------------------------------------------------------------*






TABLES : ZEDT24_100, ZEDT24_101.

TYPE-POOLS: ICON.



DATA : BEGIN OF GS_100.

  include structure
ZEDT24_100
.

DATA : END OF GS_100.

DATA : GT_100 LIKE TABLE OF GS_100.



DATA : BEGIN OF GS_T100_RESULT, "###### ## ###

    ZORDNO LIKE ZEDT24_100-ZORDNO, "####

    ZIDCODE LIKE ZEDT24_100-ZIDCODE, "##ID

    ZMATNR LIKE ZEDT24_100-ZMATNR, "####

    ZMATNAME LIKE ZEDT24_100-ZMATNAME, "###

    ZMTART TYPE C LENGTH 8, "####

    ZVOLUM TYPE I, "##

    VRKME LIKE ZEDT24_100-VRKME, "Sales Unit

    ZNSAMT LIKE ZEDT24_100-ZNSAMT, "####

    ZSLAMT LIKE ZEDT24_100-ZSLAMT, "####

    ZDCAMT LIKE ZEDT24_100-ZDCAMT, "####

    ZWAERS LIKE ZEDT24_100-ZWAERS, "##

    ZSALE TYPE C LENGTH 4, "## ##

    ZJDATE LIKE ZEDT24_100-ZJDATE, "####

    ZRET TYPE C LENGTH 10, "## ##

    ZRDATE LIKE ZEDT24_100-ZRDATE, "####

    ZICON TYPE ICON_D,

  END OF GS_T100_RESULT.

DATA : GT_T100_RESULT LIKE TABLE OF GS_T100_RESULT.



DATA : BEGIN OF GS_101.

  include structure
ZEDT24_101
.

DATA : END OF GS_101.

DATA : GT_101 LIKE TABLE OF GS_101.



  DATA : BEGIN OF GS_T101_RESULT, "###### ## ###

    ZORDNO LIKE ZEDT24_101-ZORDNO, "####

    ZIDCODE LIKE ZEDT24_101-ZIDCODE, "##ID

    ZMATNR LIKE ZEDT24_101-ZMATNR, "####

    ZMATNAME LIKE ZEDT24_101-ZMATNAME, "###

    ZMTART TYPE C LENGTH 8, "####

    ZVOLUM TYPE I, "##

    VRKME LIKE ZEDT24_101-VRKME, "##

    ZSLAMT LIKE ZEDT24_100-ZSLAMT, "####

    ZDFLAG TYPE C LENGTH 8, "####

    ZDGUBUN TYPE C LENGTH 8, "####

    ZDDATE LIKE ZEDT24_101-ZDDATE, "####

    ZRDATE LIKE ZEDT24_101-ZRDATE, "####

    ZFLAG LIKE ZEDT24_101-ZFLAG, "####

    ZWAERS LIKE ZEDT24_100-ZWAERS, "##

    ZICON TYPE ICON_D,

  END OF GS_T101_RESULT.

DATA : GT_T101_RESULT LIKE TABLE OF GS_T101_RESULT.



"2. ALV ## #### ##

DATA : GS_FC_100 TYPE LVC_S_FCAT.

DATA : GT_FC_100 TYPE LVC_T_FCAT.



DATA : GS_FC_101 TYPE LVC_S_FCAT.

DATA : GT_FC_101 TYPE LVC_T_FCAT.



"3. ALV ####

DATA : GS_LAYOUT TYPE LVC_S_LAYO.



"4. ALV : SORT

DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT TYPE LVC_T_SORT.



"5. OK_CODE

DATA : OK_CODE TYPE SY-UCOMM.



"6. ## ## ##

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.



"7. ### ##

DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_VARIANT TYPE DISVARIANT.



RANGES GR_ZSALE FOR ZEDT24_100-ZSALE_FG.