
REPORT ZEDR13_048.






*PARAMETERS : P_ZCODE LIKE ZEDT13_001-ZCODE LOWER CASE. "#### ### ### #### #### ##"

*PARAMETERS : P_ZCODE LIKE ZEDT13_001-ZCODE OBLIGATORY.

*PARAMETERS : P_ZCODE LIKE ZEDT13_001-ZCODE VISIBLE LENGTH 5.

*PARAMETERS : P_ZCODE LIKE ZEDT13_001-ZCODE.

*PARAMETERS : P_ZPERNR TYPE C LENGTH 10 NO-DISPLAY.

*PARAMETERS : P_ZSUM TYPE P DECIMALS 2.

*PARAMETERS : P_ZGEN LIKE ZEDT13_001-ZGENDER DEFAULT 'M'.

*PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'.

*PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

*PARAMETERS : Z_CHECK AS CHECKBOX DEFAULT 'X'.



*IF Z_CHECK = 'X'.

*  WRITE :/ '#### ##'.

*ELSE.

*  WRITE :/ '## ##'.

*ENDIF.



*IF P_R1 = 'X'.

*  WRITE :/ '#### ##'.

*ELSEIF P_R2 = 'X'.

*  WRITE :/ '## ##'.

*ENDIF.



*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*PARAMETERS : P_ZCODE LIKE ZEDT13_001-ZCODE.

*PARAMETERS : P_ZPERNR TYPE C LENGTH 10 NO-DISPLAY.

*PARAMETERS : P_ZGEN LIKE ZEDT13_001-ZGENDER DEFAULT 'M'.

*SELECTION-SCREEN END OF BLOCK B1.

*

*DATA : GT_STUDENT TYPE ZEDT00_001 OCCURS 0 WITH HEADER LINE.

*

*SELECT * FROM ZEDT13_001

*  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

*  WHERE ZCODE = P_ZCODE

*  AND   ZGENDER = P_ZGEN.

*

*IF GT_STUDENT[] IS NOT INITIAL.

*  WRITE :/ '### ##'.

*ELSE.

*  WRITE :/ '### ##'.

*ENDIF.



*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*SELECTION-SCREEN BEGIN OF LINE.

* PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'.

*SELECTION-SCREEN POSITION 3.

*SELECTION-SCREEN COMMENT (10) FOR FIELD P_R1.

* PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

*SELECTION-SCREEN POSITION 20.

*SELECTION-SCREEN COMMENT (10) FOR FIELD P_R2.

*SELECTION-SCREEN END OF LINE.

*SELECTION-SCREEN END OF BLOCK B2.






TABLES : ZEDT13_001.

DATA : BEGIN OF GS_STUDENT.

  include structure
ZEDT13_001
.

  DATA : END OF GS_STUDENT.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.






*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT13_001-ZCODE.

*SELECTION-SCREEN END OF BLOCK B1.

*

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : P_ZGEN LIKE ZEDT13_001-ZGENDER.

*SELECTION-SCREEN END OF BLOCK B2.



*SELECT-OPTIONS : S_ZCODE FOR ZEDT13_001-ZCODE DEFAULT 'SSU-01'.

*PARAMETERS : P_ZGEN LIKE ZEDT13_001-ZGENDER.



*SELECT-OPTIONS : S_ZCODE FOR ZEDT13_001-ZCODE DEFAULT 'SSU-01' SIGN I OPTION EQ.

*SELECT-OPTIONS : S_ZCODE FOR ZEDT13_001-ZCODE DEFAULT 'SSU-01' SIGN E OPTION EQ.

*SELECT-OPTIONS : S_ZCODE FOR ZEDT13_001-ZCODE DEFAULT 'SSU-01' TO 'SSU-99' SIGN I OPTION BT.

*SELECT-OPTIONS : S_ZCODE FOR ZEDT13_001-ZCODE DEFAULT 'SSU-01' NO INTERVALS NO-EXTENSION.

*SELECT-OPTIONS : S_ZCODE FOR ZEDT13_001-ZCODE DEFAULT 'SSU-01' VISIBLE LENGTH 3.

*PARAMETERS : P_ZGEN LIKE ZEDT13_001-ZGENDER.



*SELECT * FROM ZEDT13_001

*  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

*  WHERE ZCODE IN S_ZCODE

*  AND   ZGENDER = P_ZGEN.

*

*IF GT_STUDENT[] IS NOT INITIAL.

*  CLEAR : GS_STUDENT.

*  LOOP AT GT_STUDENT INTO GS_STUDENT.

*    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME.

*  ENDLOOP.

*ELSE.

*  WRITE :/ '### ##'.

*ENDIF.



*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT13_001-ZCODE.

*  PARAMETERS : P_ZGEN LIKE ZEDT13_001-ZGENDER.

*SELECTION-SCREEN END OF BLOCK B1.

*

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : P_CH1 AS CHECKBOX DEFAULT 'X' MODIF ID M1.

*  PARAMETERS : P_CH2 AS CHECKBOX MODIF ID M2.

*SELECTION-SCREEN END OF BLOCK B2.



*AT SELECTION-SCREEN OUTPUT.

*  LOOP AT SCREEN.

*    IF SCREEN-GROUP1 = 'M2'.

*      SCREEN-INPUT = '0'.

*      MODIFY SCREEN.

*    ENDIF.

*    IF SCREEN-NAME = 'P_CH2'.

*      SCREEN-INPUT = '0'.

*      MODIFY SCREEN.

*    ENDIF.

*    IF SCREEN-GROUP1 = 'M2'.

*      SCREEN-ACTIVE = '0'.

*      MODIFY SCREEN.

*    ENDIF.

*    IF SCREEN-GROUP1 = 'M2'.

*      SCREEN-REQUIRED = '1'.

*      MODIFY SCREEN.

*    ENDIF.

*    IF SCREEN-GROUP1 = 'M2'.

*      SCREEN-OUTPUT = '0'.

*      MODIFY SCREEN.

*    ENDIF.

*  ENDLOOP.






SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS : S_ZCODE FOR ZEDT13_001-ZCODE.

  PARAMETERS : P_ZPERNR LIKE ZEDT13_001-ZPERNR MODIF ID M1.

  PARAMETERS : P_ZGEN LIKE ZEDT13_001-ZGENDER MATCHCODE OBJECT ZSH13_001 MODIF ID M2.

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UCL. "USER-COMMNAND#### ###?"

  PARAMETERS : P_R2 RADIOBUTTON GROUP R1.                              "-> ENTER ### ## ## ## ##"

SELECTION-SCREEN END OF BLOCK B2.



AT SELECTION-SCREEN OUTPUT.

  LOOP AT SCREEN.

    IF SCREEN-GROUP1 = 'M2'.




*      IF P_R1 = 'X'.

*        SCREEN-ACTIVE = '1'.

*      ELSEIF P_R2 = 'X'.

*        SCREEN-ACTIVE = '0'.

*      ENDIF.




      SCREEN-INTENSIFIED = '1'.




*      SCREEN-DISPLAY_3D = '1'.

*      SCREEN-INVISIBLE = '1'.




    ENDIF.

    MODIFY SCREEN.

  ENDLOOP.