
*&---------------------------------------------------------------------*

*& Report ZEDR12_PRACTICE002

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR12_PRACTICE002.

DATA: GS_ZEDT001 TYPE ZEDT12_001,

      GT_ZEDT001 LIKE TABLE OF ZEDT12_001.

DATA: GS_ZEDT002 TYPE ZEDT12_002,

      GT_ZEDT002 LIKE TABLE OF ZEDT12_002.

DATA: GS_ZEDT004 TYPE ZEDT12_004,

      GT_ZEDT004 LIKE TABLE OF ZEDT12_004.

DATA: BEGIN OF GS_STUDENT,

  ZCODE TYPE ZEDT12_001-ZCODE,

  ZKNAME TYPE ZEDT12_001-ZKNAME,

  ZGENDER TYPE ZEDT12_001-ZGENDER,

  ZTEL TYPE ZEDT12_001-ZTEL,

  ZMAJOR1 TYPE ZEDT12_002-ZMAJOR,

  ZMAJOR2 TYPE ZEDT12_004-ZMAJOR,

  ZGRADE TYPE ZEDT12_004-ZGRADE,

  END OF GS_STUDENT.



DATA: BEGIN OF GS_OUT,

  ZCODE TYPE ZEDT12_001-ZCODE,

  ZKNAME TYPE ZEDT12_001-ZKNAME,

  M_MOVE(10) TYPE C,

  ZGENDER TYPE ZEDT12_001-ZGENDER,

  ZTEL TYPE ZEDT12_001-ZTEL,

  WARNING(1) TYPE C,

  END OF GS_OUT.

  DATA: GT_OUT LIKE TABLE OF GS_OUT.



DATA: LV_MZSUM TYPE I,

      LV_FZSUM TYPE I.

SELECT * FROM ZEDT12_001

INTO CORRESPONDING FIELDS OF TABLE GT_ZEDT001.

SELECT * FROM ZEDT12_002

INTO CORRESPONDING FIELDS OF TABLE GT_ZEDT002.

SELECT * FROM ZEDT12_004

INTO CORRESPONDING FIELDS OF TABLE GT_ZEDT004.



SORT GT_ZEDT004 BY ZCODE ZGRADE DESCENDING. "ZCODE# ### ZGRADE# ####.

DELETE ADJACENT DUPLICATES FROM GT_ZEDT004 COMPARING ZCODE. "ZGRADE ##### ## ### #### ###.



MOVE-CORRESPONDING GT_ZEDT001[] TO GT_OUT[]. "GT_OUT# ZCODE, ZKNAME, ZTEL###.



LOOP AT GT_ZEDT004 INTO GS_ZEDT004.

  CLEAR: GS_OUT.

  MOVE-CORRESPONDING GS_ZEDT004 TO GS_OUT.



  READ TABLE GT_OUT WITH KEY ZCODE = GS_ZEDT004-ZCODE INTO GS_OUT

  COMPARING ZCODE.



  IF SY-SUBRC = 0.

    IF GS_ZEDT004-ZGRADE >= 'D'. "## ## D,F

      GS_OUT-WARNING = 'T'. "####

    ELSE.

      GS_OUT-WARNING = 'F'.

    ENDIF.

  ENDIF.

  MODIFY GT_OUT FROM GS_OUT INDEX SY-TABIX TRANSPORTING WARNING. "#### ##.



  CLEAR: GS_ZEDT002.

  READ TABLE GT_ZEDT002 WITH KEY ZCODE = GS_ZEDT004-ZCODE INTO GS_ZEDT002. "COMPARING ZCODE.

  IF SY-SUBRC = 0.

    IF GS_ZEDT004-ZMAJOR <> GS_ZEDT002-ZMAJOR.

      GS_OUT-M_MOVE = '####'.

    ELSE.

      GS_OUT-M_MOVE = ''.

    ENDIF.

  ENDIF.

  MODIFY GT_OUT FROM GS_OUT INDEX SY-TABIX TRANSPORTING M_MOVE. "#### ##.



  IF GS_OUT-ZGENDER = 'M'.

    ADD GS_ZEDT004-ZSUM TO LV_MZSUM.

  ELSE.

    ADD GS_ZEDT004-ZSUM TO LV_FZSUM.

  ENDIF.



ENDLOOP.






*"3.WORK AREA ##. 2)COMPARING

*LOOP AT GT_STUDENT INTO GS_STUDENT.

*    CLEAR:GS_MAJOR.

*    MOVE-CORRESPONDING GS_STUDENT TO GS_MAJOR.

*

*    READ TABLE GT_MAJOR WITH KEY ZCODE = GS_STUDENT-ZCODE

*    INTO GS_MAJOR COMPARING ZCODE.

*

*    IF SY-SUBRC = 0.

*      WRITE:/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_MAJOR-ZMNAME.

*    ELSE.

*      WRITE:/ '#### #### ##.'.

*    ENDIF.

*

*ENDLOOP.

*LOOP AT GT_ZEDT001 INTO GS_ZEDT001.

*  CLEAR: GS_STUDENT.

*  MOVE-CORRESPONDING GS_ZEDT001 TO GS_STUDENT.

*

*  READ TABLE GT_ZEDT002 WITH KEY ZCODE = GS_ZEDT001-ZCODE

*

*ENDLOOP