
*&---------------------------------------------------------------------*

*&  Include           ZEDR13_PRACTICE009_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS : S_PERNR FOR ZEDT13_102-ZPERNR.

  SELECT-OPTIONS : S_DATE FOR ZEDT13_102-ZEDATE NO INTERVALS NO-EXTENSION.

  SELECT-OPTIONS : S_DEP FOR ZEDT13_102-ZDEPCODE NO INTERVALS NO-EXTENSION.

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS P1 AS CHECKBOX DEFAULT 'X'.

SELECTION-SCREEN END OF BLOCK B2.