
*&---------------------------------------------------------------------*

*&  Include           ZMM18_003_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1.

  PARAMETERS : P_EBELN TYPE ZEKPO_18-EBELN.   " PO##

  PARAMETERS : P_WERKS TYPE ZEKPO_18-WERKS.   " ###

  PARAMETERS : P_BUDAT TYPE ZEKPO_18-PRDAT MODIF ID M1.   " #####

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2.

SELECTION-SCREEN BEGIN OF LINE.

  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

  SELECTION-SCREEN POSITION 3.

  SELECTION-SCREEN COMMENT (10) FOR FIELD P_R1.

  PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

  SELECTION-SCREEN POSITION 20.

  SELECTION-SCREEN COMMENT (10) FOR FIELD P_R2.

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B2.