
REPORT ZEDR13_026.



DATA : BEGIN OF GS_ZEDT13,

  ZCODE TYPE ZEDT13_001-ZCODE,

  ZKNAME TYPE ZEDT13_001-ZKNAME,

  ZENAME TYPE ZEDT13_001-ZENAME,

  ZGENDER TYPE ZEDT13_001-ZGENDER,

  ZTEL TYPE ZEDT13_001-ZTEL,

  END OF GS_ZEDT13.

 DATA : BEGIN OF GS_ZEDT13_2,

  ZGENDER TYPE ZEDT13_001-ZGENDER,

  ZCODE TYPE ZEDT13_001-ZCODE,

  ZKNAME TYPE ZEDT13_001-ZKNAME,

  ZENAME TYPE ZEDT13_001-ZENAME,

  ZTEL TYPE ZEDT13_001-ZTEL,

  END OF GS_ZEDT13_2.

 DATA : BEGIN OF GS_ZEDT13_3,

  ZGENDER TYPE ZEDT13_001-ZGENDER,

  ZCODE TYPE ZEDT13_001-ZCODE,

  ZKNAME TYPE ZEDT13_001-ZKNAME,

  ZENAME TYPE ZEDT13_001-ZENAME,

  ZTEL TYPE ZEDT13_001-ZTEL,

  END OF GS_ZEDT13_3.

  DATA : BEGIN OF GS_ZEDT13_4,

  ZZZZZCODE TYPE ZEDT13_001-ZCODE,

  ZZZZZZZKNAME TYPE ZEDT13_001-ZKNAME,

  ZZZZZZZZENAME TYPE ZEDT13_001-ZENAME,

  ZZZZZZZZZGENDER TYPE ZEDT13_001-ZGENDER,

  ZZZZZZZZTEL TYPE ZEDT13_001-ZTEL,

  END OF GS_ZEDT13_4.

  DATA : BEGIN OF GS_ZEDT13_5,

  ZZZZZCODE TYPE ZEDT13_001-ZCODE,

  ZZZZZZZKNAME TYPE ZEDT13_001-ZKNAME,

  ZZZZZZZZENAME TYPE ZEDT13_001-ZENAME,

  ZZZZZZZZZGENDER TYPE ZEDT13_001-ZGENDER,

  ZZZZZZZZTEL TYPE ZEDT13_001-ZTEL,

  END OF GS_ZEDT13_5.



GS_ZEDT13-ZCODE = 'SSU-01'.

GS_ZEDT13-ZKNAME = '###'.

GS_ZEDT13-ZENAME = 'DONG'.

GS_ZEDT13-ZGENDER = 'M'.

GS_ZEDT13-ZTEL = '01011112222'.




*&## #### ###




MOVE-CORRESPONDING GS_ZEDT13 TO GS_ZEDT13_2.



WRITE :/ GS_ZEDT13_2-ZCODE.

WRITE :/ GS_ZEDT13_2-ZKNAME.

WRITE :/ GS_ZEDT13_2-ZENAME.

WRITE :/ GS_ZEDT13_2-ZGENDER.

WRITE :/ GS_ZEDT13_2-ZTEL.




*&## #### ## ### ## ##<br />
   </div>
   <div class="code">
MOVE GS_ZEDT13 TO GS_ZEDT13_3.<br />
<br />
WRITE :/ GS_ZEDT13_3-ZCODE.<br />
WRITE :/ GS_ZEDT13_3-ZKNAME.<br />
WRITE :/ GS_ZEDT13_3-ZENAME.<br />
WRITE :/ GS_ZEDT13_3-ZGENDER.<br />
WRITE :/ GS_ZEDT13_3-ZTEL.<br />
<br />
MOVE GS_ZEDT13 TO GS_ZEDT13_4.<br />
   </div>
   <div class="codeComment">
*& ## # ### MOVE TO ##<br />
   </div>
   <div class="code">
WRITE :/ GS_ZEDT13_4-ZZZZZCODE.<br />
WRITE :/ GS_ZEDT13_4-ZZZZZZZKNAME.<br />
WRITE :/ GS_ZEDT13_4-ZZZZZZZZENAME.<br />
WRITE :/ GS_ZEDT13_4-ZZZZZZZZZGENDER.<br />
WRITE :/ GS_ZEDT13_4-ZZZZZZZZTEL.<br />
<br />
MOVE-CORRESPONDING GS_ZEDT13 TO GS_ZEDT13_5.<br />
   </div>
   <div class="codeComment">
*&## ##<br />
   </div>
   <div class="code">
WRITE :/ GS_ZEDT13_5-ZZZZZCODE.<br />
WRITE :/ GS_ZEDT13_5-ZZZZZZZKNAME.<br />
WRITE :/ GS_ZEDT13_5-ZZZZZZZZENAME.<br />
WRITE :/ GS_ZEDT13_5-ZZZZZZZZZGENDER.<br />
WRITE :/ GS_ZEDT13_5-ZZZZZZZZTEL.<br />
            </div>
          </td>
        </tr>
      </table>
      </td>
      </tr>
   <tr>
<td class="footer">Extracted by Mass Download version 1.5.5 - E.G.Mellodew. 1998-2025. Sap Release 750</td>
   </tr>
</table>
</body>
</html>