
*&---------------------------------------------------------------------*

*& Report ZEDR08_010

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR08_010.



DATA : GS_STUDENT TYPE ZEDT08_001.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.



DATA : BEGIN OF GS_MAJOR,

  ZCODE LIKE ZEDT08_001-ZCODE,

  ZPERNR LIKE ZEDT08_001-ZPERNR,

  ZKNAME LIKE ZEDT08_001-ZKNAME,

  ZMNAME LIKE ZEDT08_004-ZMNAME,

  END OF GS_MAJOR.



DATA : GT_MAJOR LIKE TABLE OF GS_MAJOR WITH NON-UNIQUE KEY ZCODE.



CLEAR : GS_STUDENT, GT_STUDENT, GS_MAJOR, GT_MAJOR.

GS_STUDENT-ZPERNR = '0000000001'.

GS_STUDENT-ZCODE = 'SSU-08'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'KIM'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01011112222'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_MAJOR-ZPERNR = '0000000001'.

GS_MAJOR-ZCODE = 'SSU-08'.

GS_MAJOR-ZMNAME = '#####'.

APPEND GS_MAJOR TO GT_MAJOR.



LOOP AT GT_STUDENT INTO GS_STUDENT.

  CLEAR : GS_MAJOR.

  MOVE-CORRESPONDING GS_STUDENT TO GS_MAJOR.

  READ TABLE GT_MAJOR FROM GS_MAJOR INTO GS_MAJOR.



  IF SY-SUBRC = 0.

    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_MAJOR-ZMNAME.

  ELSE.

    WRITE :/ '#### #### #####.'.

  ENDIF.

ENDLOOP.



" -----------------------------------------------------------------------------



CLEAR : GS_STUDENT, GT_STUDENT, GS_MAJOR, GT_MAJOR.

GS_STUDENT-ZPERNR = '0000000001'.

GS_STUDENT-ZCODE = 'SSU-08'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'KIM'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01011112222'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_MAJOR-ZPERNR = '0000000001'.

GS_MAJOR-ZCODE = 'SSU-08'.

GS_MAJOR-ZMNAME = '#####'.

APPEND GS_MAJOR TO GT_MAJOR.



LOOP AT GT_STUDENT INTO GS_STUDENT.

  CLEAR : GS_MAJOR.

  READ TABLE GT_MAJOR WITH TABLE KEY ZCODE = GS_STUDENT-ZCODE INTO GS_MAJOR.



  IF SY-SUBRC = 0.

    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_MAJOR-ZMNAME.

  ELSE.

    WRITE :/ '#### #### #####.'.

  ENDIF.

ENDLOOP.



" -----------------------------------------------------------------------------



CLEAR : GS_STUDENT, GT_STUDENT, GS_MAJOR, GT_MAJOR.

GS_STUDENT-ZPERNR = '0000000001'.

GS_STUDENT-ZCODE = 'SSU-08'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'KIM'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01011112222'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_MAJOR-ZPERNR = '0000000001'.

GS_MAJOR-ZCODE = 'SSU-08'.

GS_MAJOR-ZMNAME = '#####'.

APPEND GS_MAJOR TO GT_MAJOR.



LOOP AT GT_STUDENT INTO GS_STUDENT.

  CLEAR : GS_MAJOR.



  READ TABLE GT_MAJOR WITH KEY ZCODE = GS_STUDENT-ZCODE INTO GS_MAJOR.



  IF SY-SUBRC = 0.

    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_MAJOR-ZMNAME.

  ELSE.

    WRITE :/ '#### #### #####.'.

  ENDIF.

ENDLOOP.



" -----------------------------------------------------------------------------



CLEAR : GS_STUDENT, GT_STUDENT, GS_MAJOR, GT_MAJOR.

GS_STUDENT-ZPERNR = '0000000001'.

GS_STUDENT-ZCODE = 'SSU-08'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'KIM'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01011112222'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_MAJOR-ZPERNR = '0000000001'.

GS_MAJOR-ZCODE = 'SSU-08'.

GS_MAJOR-ZMNAME = '#####'.

APPEND GS_MAJOR TO GT_MAJOR.



LOOP AT GT_STUDENT INTO GS_STUDENT.

  CLEAR : GS_MAJOR.



  READ TABLE GT_MAJOR WITH KEY ZCODE = GS_STUDENT-ZCODE

                               ZPERNR = GS_STUDENT-ZPERNR

  INTO GS_MAJOR.



  IF SY-SUBRC = 0.

    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_MAJOR-ZMNAME.

  ELSE.

    WRITE :/ '#### #### #####.'.

  ENDIF.

ENDLOOP.



" -----------------------------------------------------------------------------



CLEAR : GS_STUDENT, GT_STUDENT, GS_MAJOR, GT_MAJOR.

GS_STUDENT-ZPERNR = '0000000001'.

GS_STUDENT-ZCODE = 'SSU-08'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'KIM'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01011112222'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_MAJOR-ZPERNR = '0000000001'.

GS_MAJOR-ZCODE = 'SSU-08'.

GS_MAJOR-ZMNAME = '#####'.

APPEND GS_MAJOR TO GT_MAJOR.



LOOP AT GT_STUDENT INTO GS_STUDENT.

  CLEAR : GS_MAJOR.

  MOVE-CORRESPONDING GS_STUDENT TO GS_MAJOR.



  READ TABLE GT_MAJOR WITH KEY ZCODE = GS_STUDENT-ZCODE INTO GS_MAJOR COMPARING ZCODE.



  IF SY-SUBRC = 0.

    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_MAJOR-ZMNAME.

  ELSE.

    WRITE :/ '#### #### #####.'.

  ENDIF.

ENDLOOP.



" -----------------------------------------------------------------------------



CLEAR : GS_STUDENT, GT_STUDENT, GS_MAJOR, GT_MAJOR.

GS_STUDENT-ZPERNR = '0000000001'.

GS_STUDENT-ZCODE = 'SSU-08'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'KIM'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01011112222'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_MAJOR-ZPERNR = '0000000001'.

GS_MAJOR-ZCODE = 'SSU-08'.

GS_MAJOR-ZMNAME = '#####'.

APPEND GS_MAJOR TO GT_MAJOR.



LOOP AT GT_STUDENT INTO GS_STUDENT.

  CLEAR : GS_MAJOR.

  MOVE-CORRESPONDING GS_STUDENT TO GS_MAJOR.



  READ TABLE GT_MAJOR WITH KEY ZCODE = GS_STUDENT-ZCODE INTO GS_MAJOR.



  IF SY-SUBRC = 0.

    GS_STUDENT-ZKNAME = GS_MAJOR-ZKNAME.

    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_MAJOR-ZMNAME.

  ELSE.

    WRITE :/ '#### #### #####.'.

  ENDIF.

ENDLOOP.



" -----------------------------------------------------------------------------



CLEAR : GS_STUDENT, GT_STUDENT, GS_MAJOR, GT_MAJOR.

GS_STUDENT-ZPERNR = '0000000001'.

GS_STUDENT-ZCODE = 'SSU-08'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'KIM'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01011112222'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_MAJOR-ZPERNR = '0000000001'.

GS_MAJOR-ZCODE = 'SSU-08'.

GS_MAJOR-ZMNAME = '#####'.

APPEND GS_MAJOR TO GT_MAJOR.



LOOP AT GT_STUDENT INTO GS_STUDENT.

  CLEAR : GS_MAJOR.

  MOVE-CORRESPONDING GS_STUDENT TO GS_MAJOR.



  READ TABLE GT_MAJOR INTO GS_MAJOR INDEX SY-TABIX.



  IF SY-SUBRC = 0.

    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_MAJOR-ZMNAME.

  ELSE.

    WRITE :/ '#### #### #####.'.

  ENDIF.

ENDLOOP.



" -----------------------------------------------------------------------------



CLEAR : GS_STUDENT, GT_STUDENT, GS_MAJOR, GT_MAJOR.

GS_STUDENT-ZPERNR = '0000000001'.

GS_STUDENT-ZCODE = 'SSU-08'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'KIM'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01011112222'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_MAJOR-ZPERNR = '0000000001'.

GS_MAJOR-ZCODE = 'SSU-08'.

GS_MAJOR-ZMNAME = '#####'.

APPEND GS_MAJOR TO GT_MAJOR.



SORT GT_STUDENT BY ZCODE.

SORT GT_MAJOR BY ZCODE.



LOOP AT GT_STUDENT INTO GS_STUDENT.

  CLEAR : GS_MAJOR.

  MOVE-CORRESPONDING GS_STUDENT TO GS_MAJOR.



  READ TABLE GT_MAJOR WITH KEY ZCODE = GS_STUDENT-ZCODE INTO GS_MAJOR BINARY SEARCH.



  IF SY-SUBRC = 0.

    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_MAJOR-ZMNAME.

  ELSE.

    WRITE :/ '#### #### #####.'.

  ENDIF.

ENDLOOP.



" -----------------------------------------------------------------------------