
*&---------------------------------------------------------------------*

*&  Include           ZEDR20_PROJECT004_TOP

*&---------------------------------------------------------------------*




TABLES: ZEDT20_MSEG, ZEDT20_MKPF.

CONTROLS: PACKAGE1 TYPE TABSTRIP.

DATA: GV_EXIT_FROM_POPUP(1) VALUE ''.

DATA: GV_CREDIT TYPE ZEDT20_BSEG-DMBTR,

      GV_DEBIT TYPE ZEDT20_BSEG-DMBTR,

      GV_TEMP_MWSKZ TYPE ZEDT20_LFM1-MWSKZ.

DATA: GV_SUBSCREEN TYPE SY-DYNNR VALUE '0101'.

CONSTANTS: C_YELLO TYPE ICON_D VALUE '@5D@',

           C_GREEN TYPE ICON_D VALUE '@5B@',

           C_RED TYPE ICON_d VALUE '@5C@'.

DATA: GV_TAX_RATE TYPE P LENGTH 2 DECIMALS 2.



DATA: GO_EVENT TYPE REF TO EVENT.

" ALV ## ##

DATA: GC_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER,    " ALV### CUSTOM CONTAINER #### ##

    GC_GRID TYPE REF TO CL_GUI_ALV_GRID,    " ALV ### ALV GRID #### ##

    OK_CODE TYPE SY-UCOMM,    " TOOLBAR ## ##

    GS_FIELDCAT TYPE LVC_S_FCAT,    " ###### ###

    GT_FIELDCAT TYPE LVC_T_FCAT,    " ###### ###

    GT_SORT TYPE LVC_T_SORT,    " SORT ###

    GS_SORT TYPE LVC_S_SORT,    " SORT ###

    GS_LAYOUT TYPE LVC_S_LAYO,    " LAYOUT ###

    GS_VARIANT TYPE DISVARIANT.   " LAYOUT #### ###



DATA: GC_POPUP TYPE REF TO CL_GUI_CUSTOM_CONTAINER,    " ## ALV### CUSTOM CONTAINER #### ##

      GC_POPUP_GRID TYPE REF TO CL_GUI_ALV_GRID,    " ## ALV ### ALV GRID #### ##

      GT_POPUP_FIELDCAT TYPE LVC_T_FCAT.    " ###### ###



DATA: BEGIN OF GS_COMMON_HEADER,

  " #### ### ###### ######

  EKGRP TYPE ZEDT20_EKKO-EKGRP,   " #####

  BEDAT TYPE ZEDT20_EKKO-BEDAT,    " #### ###

  LIFNR TYPE ZEDT20_EKKO-LIFNR,    " #####

  NAME1 TYPE ZEDT20_LFA1-NAME1,    " #####

  BUKRS TYPE ZEDT20_EKKO-BUKRS,    " ####

  END OF GS_COMMON_HEADER.

DATA: GT_COMMON_HEADER LIKE TABLE OF GS_COMMON_HEADER.



DATA: BEGIN OF GS_AMOUNT_HEADER,

  " ##### ##### #####?

  ZAMOUNT TYPE ZEDT20_BSEG-DMBTR,   " ##

  WAERS TYPE ZEDT20_LFM1-WAERS,   " ##

  MWSKZ TYPE ZEDT20_LFM1-MWSKZ,   " ####

  ZMEMO(10),    " ## ####

  ZBALANCE TYPE ZEDT20_BSEG-DMBTR,    " ##

  ZCOLOR TYPE ICON_D,    " ###

  END OF GS_AMOUNT_HEADER.

DATA: GT_AMOUNT_HEADER LIKE TABLE OF GS_AMOUNT_HEADER.



DATA: BEGIN OF GS_INVOICING,

  ZCHECK TYPE C,    " ##

  EBELP TYPE ZEDT20_EKPO-EBELP,    " ##

  MATNR TYPE ZEDT20_EKPO-MATNR,    " ####

  MAKTX TYPE ZEDT20_MARA-MAKTX,    " ###

  MENGE TYPE ZEDT20_EKPO-MENGE,    " ## ##

  POMENGE TYPE ZEDT20_EKPO-MENGE,   " # ##

  REMENGE TYPE ZEDT20_EKPO-MENGE,   " ## ##

  MEINS TYPE ZEDT20_EKPO-MEINS,    " ##

  BPRME TYPE ZEDT20_EKPO-BPRME,    " ##

  WAERS TYPE ZEDT20_EKKO-WAERS,    " ##

  DMBTR TYPE ZEDT20_BSEG-DMBTR,    " ####

  MWSTS TYPE ZEDT20_BSEG-DMBTR,   " ##

  ZAMNT TYPE ZEDT20_BSEG-DMBTR,   " ##

  LGORT TYPE ZEDT20_MSEG-LGORT,   " ####

  END OF GS_INVOICING.

DATA: GT_INVOICING LIKE TABLE OF GS_INVOICING.



DATA: BEGIN OF GS_INVOICED,

  ZCHECK TYPE C,    " ##

  EBELP TYPE ZEDT20_RSEG-EBELP,    " ##

  MATNR TYPE ZEDT20_RSEG-MATNR,    " ####

  MAKTX TYPE ZEDT20_MARA-MAKTX,    " ###

  BELNR TYPE ZEDT20_RSEG-BELNR,   " ######

  BUZEI TYPE ZEDT20_RSEG-BUZEI,   " ## ### ##

  BLART TYPE ZEDT20_RBKP-BLART,   " ####

  BLDAT TYPE ZEDT20_RBKP-BLDAT,   " ###

  POMENGE TYPE ZEDT20_RSEG-MENGE,   " PO##

  MENGE TYPE ZEDT20_RSEG-MENGE,    " ##

  MEINS TYPE ZEDT20_RSEG-MEINS,    " ##

  BPRME TYPE ZEDT20_RSEG-BPRME,    " ##

  WAERS TYPE ZEDT20_EKKO-WAERS,    " ##

  MWSKZ TYPE ZEDT20_RSEG-MWSKZ,   " ####

  DMBTR TYPE ZEDT20_BSEG-DMBTR,    " ####

  MWSTS TYPE ZEDT20_BSEG-DMBTR,   " ##

  WRBTR TYPE ZEDT20_BSEG-DMBTR,   " ##

  LOEVM TYPE ZEDT20_RSEG-LOEVM,   " ####

  ZSTATUS(2),   " ##

  LGORT TYPE ZEDT20_MSEG-LGORT,   " ####

  END OF GS_INVOICED.

DATA: GT_INVOICED LIKE TABLE OF GS_INVOICED.



DATA: BEGIN OF GS_EBELN,

  EBELN TYPE ZEDT20_RSEG-EBELN,

  END OF GS_EBELN.

  DATA: GT_EBELN LIKE TABLE OF GS_EBELN.



DATA: BEGIN OF GS_PAYMENT,

  BUKRS TYPE ZEDT20_BSIK-BUKRS,    " ####

  EBELN TYPE ZEDT20_BSIK-EBELN,   " ######

  DMBTR TYPE ZEDT20_BSIK-DMBTR,   " ####

  MWSTS TYPE ZEDT20_BSIK-MWSTS,   " ##

  ZAMNT TYPE ZEDT20_BSIK-DMBTR,   " ##

  WAERS TYPE ZEDT20_BSIK-WAERS,   " ##

  MWSKZ TYPE ZEDT20_BSIK-MWSKZ,   " ####

  SGTXT TYPE ZEDT20_BSIK-SGTXT,   " ###

  LIFNR TYPE ZEDT20_BSIK-LIFNR,   " ###

  END OF GS_PAYMENT.

  DATA: GT_PAYMENT LIKE TABLE OF GS_PAYMENT.



DATA: BEGIN OF GS_SIMULATION,

  LINENUM TYPE I,

  SHZKG TYPE ZEDT20_BSEG-SHZKG,   " ###

  AKONT TYPE ZEDT20_LFB1-AKONT,   " ##

  ZMEMO(20),    " ## ##

  DMBTR TYPE ZEDT20_BSIK-DMBTR,   " ##

  WAERS TYPE ZEDT20_BSIK-WAERS,   " ##

  EBELN TYPE ZEDT20_BSIK-EBELN,   " ####

  EBELP TYPE ZEDT20_EKPO-EBELP,   " ##

  SGTXT TYPE ZEDT20_BSIK-SGTXT,   " ##

  END OF GS_SIMULATION.

DATA: GT_SIMULATION LIKE TABLE OF GS_SIMULATION.



DATA: BEGIN OF GS_RBKP.

  include structure
ZEDT20_RBKP
.

  DATA: END OF GS_RBKP.

DATA: GT_RBKP LIKE TABLE OF GS_RBKP.



DATA: BEGIN OF GS_RSEG.

  include structure
ZEDT20_RSEG
.

  DATA: END OF GS_RSEG.

DATA: GT_RSEG LIKE TABLE OF GS_RSEG.



DATA: BEGIN OF GS_BKPF.

  include structure
ZEDT20_BKPF
.

  DATA: END OF GS_BKPF.

DATA: GT_BKPF LIKE TABLE OF GS_BKPF.



DATA: BEGIN OF GS_BSEG.

  include structure
ZEDT20_BSEG
.

  DATA: END OF GS_BSEG.

DATA: GT_BSEG LIKE TABLE OF GS_BSEG.



DATA: BEGIN OF GS_BSIK.

  include structure
ZEDT20_BSIK
.

  DATA: END OF GS_BSIK.