
*&---------------------------------------------------------------------*

*&  Include           ZMM23_003_TOP

*&---------------------------------------------------------------------*






DATA : OK_CODE TYPE SY-UCOMM,

      GV_DYNNR TYPE SY-DYNNR VALUE '0101'.



DATA : GV_FLAG TYPE C LENGTH 1 VALUE '0'.



SELECTION-SCREEN FUNCTION KEY 1.  " SCREEN 200# '##'

SELECTION-SCREEN FUNCTION KEY 2.  " SCREEN 300# '####'

CONTROLS CTR_200 TYPE TABLEVIEW USING SCREEN '0200'.  "####

CONTROLS CTR_300 TYPE TABLEVIEW USING SCREEN '0300'.  "####



" #### - SUBSCREEN 101

" #### - SUBSCREN 102

DATA : GV_EBELN TYPE Z23MSEG-EBELN,   "####

      GV_WERKS TYPE Z23MSEG-WERKS,    "###

      GV_BUDAT TYPE Z23MKPF-BUDAT.    "##### / DEFAULT: #####





" #####-##

DATA : GS_EKKO TYPE Z23EKKO.

DATA : GT_EKKO LIKE TABLE OF GS_EKKO.



" #####-###

DATA : BEGIN OF GS_EKPO,

  ZCHECK TYPE C LENGTH 1,   "######

  EBELN TYPE Z23EKPO-EBELN, "######

  EBELP TYPE Z23EKPO-EBELP, "##

  MATNR TYPE Z23EKPO-MATNR, "####

  MAKTX TYPE Z23EKPO-MAKTX,  "###

  MENGE TYPE Z23EKPO-MENGE,  "PO##

  MENGE_R TYPE Z23EKPO-MENGE, " ######

  MENGE_I TYPE Z23EKPO-MENGE, " ###### (INPUT)

  MEINS TYPE Z23EKPO-MEINS, "##

  STPRS TYPE Z23EKPO-STPRS, "##

  PRDAT TYPE Z23EKPO-PRDAT, "###

  WERKS TYPE Z23EKPO-WERKS, "###

  LGORT TYPE Z23EKPO-LGORT,"####

  END OF GS_EKPO.

DATA : GT_EKPO LIKE TABLE OF GS_EKPO.



" #####-##

DATA : GS_MKPF TYPE Z23MKPF.  " ######, ####, ####, ###, ###



" #####-###

DATA : BEGIN OF GS_MSEG,

  ZCHECK TYPE C LENGTH 1,   "######

  MBLNR TYPE Z23MSEG-MBLNR,  "######

  MJAHR TYPE Z23MSEG-MJAHR,   "####?

  MATNR TYPE Z23MSEG-MATNR, "####

  MAKTX TYPE Z23MSEG-MAKTX, "###

  WERKS TYPE Z23MSEG-WERKS, "###

  LGORT TYPE Z23MSEG-LGORT, "####

  WAERS TYPE Z23MSEG-WAERS,  "###

  MENGE TYPE Z23MSEG-MENGE, "##

  MEINS TYPE Z23MSEG-MEINS, "##

  EBELN TYPE Z23MSEG-EBELN, "######

  EBELP TYPE Z23MSEG-EBELP, "####

  BUKRS TYPE Z23MSEG-BUKRS, "####

  GJAHR TYPE Z23MSEG-GJAHR, "####

  BELNR TYPE Z23MSEG-BELNR, "####

  SHKZG TYPE Z23MSEG-SHKZG, "###

  DMBTR TYPE Z23MSEG-DMBTR, "##

  END OF GS_MSEG.

DATA : GT_MSEG LIKE TABLE OF GS_MSEG.