
*&---------------------------------------------------------------------*

*&  Include           ZEDR10_PRACTICE008_SCR

*&---------------------------------------------------------------------*






SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS:

  S_ZORDNO FOR GS_ORDER-ZORDNO,

  S_ZID FOR GS_ORDER-ZIDCODE NO-EXTENSION NO INTERVALS,

  S_ZMATNR FOR GS_ORDER-ZMATNR,

  S_ZJDATE FOR GS_ORDER-ZJDATE MODIF ID MJ,

  S_ZDDATE FOR GS_DELIVERY-ZDDATE MODIF ID MD.

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS:

  P_R_OR_F RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND SY-UCOMM,

  P_R_DE_F RADIOBUTTON GROUP R1.

SELECTION-SCREEN END OF BLOCK B2.



SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME.

  PARAMETERS:

  P_RET_F AS CHECKBOX DEFAULT 'X'.

SELECTION-SCREEN END OF BLOCK B3.