
*&---------------------------------------------------------------------*

*& Report ZEDR03_009_SELECT

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR03_009_SELECT.



DATA : BEGIN OF GS_SPFLI,

  CARRID TYPE SPFLI-CARRID,

  CONNID TYPE SPFLI-CONNID,

  END OF GS_SPFLI.

DATA : GT_SPFLI LIKE TABLE OF GS_SPFLI.



DATA : BEGIN OF GS_SFLIGHT,

  CARRID TYPE SFLIGHT-CARRID,

  CONNID TYPE SFLIGHT-CONNID,

  FLDATE TYPE SFLIGHT-FLDATE,

  PRICE TYPE SFLIGHT-PRICE,

  END OF GS_SFLIGHT.

DATA : GT_SFLIGHT LIKE TABLE OF GS_SFLIGHT.





SELECT CARRID

       CONNID

  FROM SPFLI

  INTO CORRESPONDING FIELDS OF TABLE GT_SPFLI "## ### #### ## ##

  WHERE CARRID LIKE 'A%'.



IF GT_SPFLI IS NOT INITIAL.

  SELECT CARRID

         CONNID

         FLDATE

         PRICE

       FROM SFLIGHT

       INTO CORRESPONDING FIELDS OF TABLE GT_SFLIGHT

       FOR ALL ENTRIES IN GT_SPFLI " FOR ALL ENTRIES IN# ##

       WHERE CARRID = GT_SPFLI-CARRID

       AND   CONNID = GT_SPFLI-CONNID.

ENDIF.



LOOP AT GT_SFLIGHT INTO GS_SFLIGHT.

  WRITE :/ GS_SFLIGHT-CARRID, GS_SFLIGHT-CONNID, GS_SFLIGHT-FLDATE, GS_SFLIGHT-PRICE.

ENDLOOP.