
*&---------------------------------------------------------------------*

*& Report ZEDR06_011

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR06_011.



"---------------------------------------------------------------------

" 1. ## READ ##

DATA : GS_STUDENT TYPE ZEDT06_001.

DATA : GT_STUDENT TYPE TABLE OF ZEDT06_001.



DATA : BEGIN OF GS_MAJOR,

  ZCODE LIKE ZEDT06_001-ZCODE,

  ZPERNR LIKE ZEDT06_001-ZPERNR,

  ZMNAME LIKE ZEDT06_004-ZMNAME,

  END OF GS_MAJOR.



DATA : GT_MAJOR LIKE TABLE OF GS_MAJOR WITH NON-UNIQUE KEY ZCODE.



CLEAR : GS_STUDENT, GT_STUDENT, GS_MAJOR, GT_MAJOR.

GS_STUDENT-ZPERNR = '000000001'.

GS_STUDENT-ZCODE = 'SSU-06'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENNAME = 'KWON'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01099268961'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_MAJOR-ZPERNR = '00000001'.

GS_MAJOR-ZCODE = 'SSU-06'.

GS_MAJOR-ZMNAME = '#####'.

APPEND GS_MAJOR TO GT_MAJOR.



CLEAR: GS_STUDENT.

LOOP AT GT_STUDENT INTO GS_STUDENT.

  CLEAR : GS_MAJOR.

  MOVE-CORRESPONDING GS_STUDENT TO GS_MAJOR.

  READ TABLE GT_MAJOR FROM GS_MAJOR INTO GS_MAJOR.



  IF SY-SUBRC = 0.

    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_MAJOR-ZMNAME.

  ELSE.

    WRITE :/ '#### #### #####.'.

  ENDIF.

ENDLOOP.

"---------------------------------------------------------------------

" 2. TABLE KEY ##

DATA : GS_STUDENT_01 TYPE ZEDT06_001.

DATA : GT_STUDENT_01 LIKE TABLE OF GS_STUDENT.



DATA : BEGIN OF GS_MAJOR_01,

  ZCODE LIKE ZEDT06_001-ZCODE,

  ZPERNR LIKE ZEDT06_001-ZPERNR,

  ZMNAME LIKE ZEDT06_004-ZMNAME,

  END OF GS_MAJOR_01.

DATA : GT_MAJOR_01 LIKE TABLE OF GS_MAJOR_01 WITH NON-UNIQUE KEY ZCODE.



CLEAR : GS_STUDENT_01, GT_STUDENT_01, GS_MAJOR_01, GT_MAJOR_01.

GS_STUDENT_01-ZPERNR = '000000001'.

GS_STUDENT_01-ZCODE = 'SSU-06'.

GS_STUDENT_01-ZKNAME = '###'.

GS_STUDENT_01-ZENNAME = 'KWON'.

GS_STUDENT_01-ZGENDER = 'M'.

GS_STUDENT_01-ZTEL = '01099268961'.

APPEND GS_STUDENT_01 TO GT_STUDENT_01.



GS_MAJOR_01-ZPERNR = '00000001'.

GS_MAJOR_01-ZCODE = 'SSU-06'.

GS_MAJOR_01-ZMNAME = '#####'.

APPEND GS_MAJOR_01 TO GT_MAJOR_01.



LOOP AT GT_STUDENT_01 INTO GS_STUDENT_01.

  CLEAR : GS_MAJOR_01.

  READ TABLE GT_MAJOR_01 WITH TABLE KEY ZCODE = GS_STUDENT_01-ZCODE INTO GS_MAJOR_01.



  IF SY-SUBRC = 0.

    WRITE :/ GS_STUDENT_01-ZCODE, GS_STUDENT_01-ZKNAME, GS_MAJOR_01-ZMNAME.

  ELSE.

    WRITE :/ '#### #### #####.'.

  ENDIF.

ENDLOOP.

"---------------------------------------------------------------------

" 3. WORK AREA ##

DATA : GS_STUDENT_02 TYPE ZEDT06_001.

DATA : GT_STUDENT_02 LIKE TABLE OF GS_STUDENT_02.



DATA : BEGIN OF GS_MAJOR_02,

  ZCODE LIKE ZEDT06_001-ZCODE,

  ZPERNR LIKE ZEDT06_001-ZPERNR,

  ZKNAME LIKE ZEDT06_001-ZKNAME,

  ZMNAME LIKE ZEDT06_004-ZMNAME,

  END OF GS_MAJOR_02.

DATA : GT_MAJOR_02 LIKE TABLE OF GS_MAJOR_02.



CLEAR : GS_STUDENT_02.

LOOP AT GT_STUDENT_02 INTO GS_STUDENT_02.

  CLEAR : GS_MAJOR_02.



  MOVE-CORRESPONDING GS_STUDENT TO GS_MAJOR.



  READ TABLE GT_MAJOR_02 WITH KEY ZCODE = GS_STUDENT_02-ZCODE

                               ZPERNR = GS_STUDENT_02-ZPERNR

  INTO GS_MAJOR_02

  COMPARING ZCODE. " ### GS_MAJOR## #### ### #### ##.



  IF SY-SUBRC = 0.

    GS_STUDENT_02-ZKNAME = GS_MAJOR_02-ZKNAME.

    WRITE :/ GS_STUDENT_02-ZCODE, GS_STUDENT_02-ZKNAME, GS_MAJOR_02-ZMNAME.

  ELSE.

    WRITE :/ '#### #### #####.'.

  ENDIF.

ENDLOOP.

"---------------------------------------------------------------------

" 4. WORK AREA ##

DATA : GS_STUDENT_03 TYPE ZEDT06_001.

DATA : GT_STUDENT_03 LIKE TABLE OF GS_STUDENT_02.



DATA : BEGIN OF GS_MAJOR_03,

  ZCODE LIKE ZEDT06_001-ZCODE,

  ZPERNR LIKE ZEDT06_001-ZPERNR,

  ZMNAME LIKE ZEDT06_004-ZMNAME,

  END OF GS_MAJOR_03.

DATA : GT_MAJOR_03 LIKE TABLE OF GS_MAJOR_03.



CLEAR : GS_STUDENT_03, GT_STUDENT_03, GS_MAJOR_03, GT_MAJOR_03.

GS_STUDENT_03-ZPERNR = '000000001'.

GS_STUDENT_03-ZCODE = 'SSU-06'.

GS_STUDENT_03-ZKNAME = '###'.

GS_STUDENT_03-ZENNAME = 'KWON'.

GS_STUDENT_03-ZGENDER = 'M'.

GS_STUDENT_03-ZTEL = '01099268961'.

APPEND GS_STUDENT_02 TO GT_STUDENT_02.



GS_MAJOR_03-ZPERNR = '00000001'.

GS_MAJOR_03-ZCODE = 'SSU-06'.

GS_MAJOR_03-ZMNAME = '#####'.

APPEND GS_MAJOR_03 TO GT_MAJOR_03.



CLEAR : GS_STUDENT_03.



LOOP AT GT_STUDENT_03 INTO GS_STUDENT_03.

  CLEAR : GS_MAJOR_03.

  MOVE-CORRESPONDING GS_STUDENT_03 TO GS_MAJOR_03.



  READ TABLE GT_MAJOR INTO GS_MAJOR INDEX SY-TABIX.



  IF SY-SUBRC = 0.

    WRITE :/ GS_STUDENT_03-ZCODE, GS_STUDENT_03-ZKNAME, GS_MAJOR_03-ZMNAME.

  ELSE.

    WRITE :/ '#### #### #####.'.

  ENDIF.

ENDLOOP.



"---------------------------------------------------------------------

" 5. READ BINARY SEARCH

SORT GT_STUDENT BY ZCODE.

SORT GT_MAJOR BY ZCODE.



LOOP AT GT_STUDENT_03 INTO GS_STUDENT_03.

  CLEAR : GS_MAJOR_03.

  MOVE-CORRESPONDING GS_STUDENT_03 TO GS_MAJOR_03.



  READ TABLE GT_MAJOR_03 WITH KEY ZCODE = GS_STUDENT_03-ZCODE INTO GS_MAJOR_03 BINARY SEARCH.



  IF SY-SUBRC = 0.

    WRITE :/ GS_STUDENT_03-ZCODE, GS_STUDENT_03-ZKNAME, GS_MAJOR_03-ZMNAME.

  ELSE.

    WRITE :/ '#### #### #####.'.

  ENDIF.

ENDLOOP.