
*&---------------------------------------------------------------------*

*&  Include           ZSPLITTER_CONTAINER10_TOP

*&---------------------------------------------------------------------*




TABLES: ZEDT10_001.



DATA: BEGIN OF GS_STUDENT,

        ZCOLOR TYPE C LENGTH 4.

    include structure
ZEDT10_001
.

DATA: ZSUM   LIKE ZEDT10_002-ZSUM,

      ZMAJOR LIKE ZEDT10_002-ZMAJOR,

      ZMNAME LIKE ZEDT10_002-ZMNAME,

      END OF GS_STUDENT.

DATA: GT_STUDENT LIKE TABLE OF GS_STUDENT.



DATA: OK_CODE TYPE SY-UCOMM.



DATA: GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA: GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



DATA: GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER,

      GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.



DATA: GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID,

      GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.



DATA: GS_FCAT TYPE REF TO LVC_S_FCAT,

      GT_FCAT TYPE REF TO LVC_T_FCAT.



DATA: GS_SORT TYPE REF TO LVC_S_SORT,

      GT_SORT TYPE REF TO LVC_T_SORT.



DATA: GS_LAYO TYPE REF TO LVC_S_LAYO.