
*&---------------------------------------------------------------------*

*&  Include           ZEDR13_060_TOP

*&---------------------------------------------------------------------*






TABLES : ZEDT13_001.



DATA : BEGIN OF GS_STUDENT,

  ZCODE LIKE ZEDT13_001-ZCODE,

  ZPERNR LIKE ZEDT13_001-ZPERNR,

  ZKNAME LIKE ZEDT13_001-ZKNAME,

  ZENAME LIKE ZEDT13_001-ZENAME,

  ZGENDER LIKE ZEDT13_001-ZGENDER,

  ZSUM LIKE ZEDT13_002-ZSUM,

  ZMAJOR LIKE ZEDT13_002-ZMAJOR,

  ZMNAME LIKE ZEDT13_002-ZMNAME,

  END OF GS_STUDENT.



DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA : GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



DATA : GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.



DATA : GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT,

       GT_FIELDCAT1 TYPE LVC_T_FCAT,

       GT_FIELDCAT2 TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GS_SORT TYPE LVC_S_SORT,

       GT_SORT1 TYPE LVC_T_SORT,

       GT_SORT2 TYPE LVC_T_SORT.



DATA : GS_VARIANT TYPE DISVARIANT.