
*&---------------------------------------------------------------------*

*&  Include           ZEDR02_PRACTICE009_TOP

*&---------------------------------------------------------------------*




"### ####

TABLES : ZEDT02_102, ZEDT02_103, ZEDT02_104, ZEDT02_106.



"####+#### ###

DATA: BEGIN OF GS_EMP,

  ZPERNR LIKE ZEDT02_102-ZPERNR, "####

  ZPNAME LIKE ZEDT02_103-ZPNAME, "####

  ZDEPCODE LIKE ZEDT02_102-ZDEPCODE, "####

  DATBI LIKE ZEDT02_102-DATAB, "####_FR

  DATAB LIKE ZEDT02_102-DATBI, "####_TO

  ZDEPRANK LIKE ZEDT02_102-ZDEPRANK, "####

  ZGENDER LIKE ZEDT02_103-ZGENDER, "##

  ZEDATE LIKE ZEDT02_102-ZEDATE, "###

  ZADDRESS LIKE ZEDT02_103-ZADDRESS, "##

  ZQDATE LIKE ZEDT02_102-ZQDATE, "####

  ZQFLAG LIKE ZEDT02_102-ZQFLAG, "####

END OF GS_EMP.

DATA : GT_EMP LIKE TABLE OF GS_EMP.



"####+#### ### ###

DATA: BEGIN OF GS_EMP_OUTPUT,

  ZCOLOR TYPE C LENGTH 4, "##(###)

  ZPERNR LIKE ZEDT02_102-ZPERNR, "####

  ZPNAME LIKE ZEDT02_103-ZPNAME, "####

  ZDEPNAME TYPE C LENGTH 10, "###

  DATBI LIKE ZEDT02_102-DATAB, "####_FR

  DATAB LIKE ZEDT02_102-DATBI, "####_TO

  ZDEPRANKNAME TYPE C LENGTH 10, "###

  ZGENDER TYPE C LENGTH 10, "##

  ZEDATE LIKE ZEDT02_102-ZEDATE, "###

  ZADDRESS LIKE ZEDT02_103-ZADDRESS, "##

  ZQDATE LIKE ZEDT02_102-ZQDATE, "####

  ZQFLAG LIKE ZEDT02_102-ZQFLAG, "####

END OF GS_EMP_OUTPUT.

DATA : GT_EMP_OUTPUT LIKE TABLE OF GS_EMP_OUTPUT.



"#### ###

DATA: GS_EVAL TYPE ZEDT02_104.

DATA: GT_EVAL TYPE TABLE OF ZEDT02_104.



"#### ### ###

DATA: BEGIN OF GS_EVAL_OUTPUT,

  ZPERNR LIKE ZEDT02_104-ZPERNR, "####

  ZDEPNAME TYPE C LENGTH 10, "###

  ZYEAR LIKE ZEDT02_104-ZYEAR, "##

  DATBI LIKE ZEDT02_104-DATBI, "####_FR

  DATAB LIKE ZEDT02_104-DATAB, "####_TO

  ZRANK LIKE ZEDT02_104-ZRANK, "####

END OF GS_EVAL_OUTPUT.

DATA: GT_EVAL_OUTPUT LIKE TABLE OF GS_EVAL_OUTPUT.



"#### ###

DATA: GS_CONT TYPE ZEDT02_106.

DATA: GT_CONT TYPE TABLE OF ZEDT02_106.



"#### ### ###

DATA: BEGIN OF GS_CONT_OUTPUT,

  ZPERNR LIKE ZEDT02_106-ZPERNR, "####

  ZYEAR LIKE ZEDT02_106-ZYEAR, "##

  DATBI LIKE ZEDT02_106-DATBI, "####

  DATAB LIKE ZEDT02_106-DATAB, "####

  ZSALARY LIKE ZEDT02_106-ZSALARY, "####

  ZBANKNAME TYPE C LENGTH 10, "###

  ZACCOUNT LIKE ZEDT02_106-ZACCOUNT, "####

  ZWAERS TYPE WAERS, "##

END OF GS_CONT_OUTPUT.

DATA: GT_CONT_OUTPUT LIKE TABLE OF GS_CONT_OUTPUT.



"##

CONSTANTS: GC_STAT_ACTIVE TYPE C LENGTH 4 VALUE '@08@', "###

           GC_STAT_RETIREE TYPE C LENGTH 4 VALUE '@0A@', "###

           GC_STAT_INTERN TYPE C LENGTH 4 VALUE '@09@'. "###



RANGES : GR_DEP FOR ZEDT02_102-ZDEPCODE. "####



DATA : OK_CODE TYPE SY-UCOMM.



DATA: GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER. "## ## ##

DATA: GC_SPLITTER_TOP TYPE REF TO CL_GUI_SPLITTER_CONTAINER,

      GC_SPLITTER_BOTTOM TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



DATA: GC_CONTAINER_TOP TYPE REF TO CL_GUI_CONTAINER,

      GC_CONTAINER_EMP TYPE REF TO CL_GUI_CONTAINER,

      GC_CONTAINER_EVAL TYPE REF TO CL_GUI_CONTAINER,

      GC_CONTAINER_CONT TYPE REF TO CL_GUI_CONTAINER.



"### ##

DATA: GC_GRID_EMP TYPE REF TO CL_GUI_ALV_GRID,

      GC_GRID_EVAL TYPE REF TO CL_GUI_ALV_GRID,

      GC_GRID_CONT TYPE REF TO CL_GUI_ALV_GRID.



"## ####

DATA: GT_FIELDCAT_EMP TYPE LVC_T_FCAT,

      GT_FIELDCAT_EVAL TYPE LVC_T_FCAT,

      GT_FIELDCAT_CONT TYPE LVC_T_FCAT,

      GS_FIELDCAT TYPE LVC_S_FCAT.



DATA: GS_LAYOUT TYPE LVC_S_LAYO. "####



"##

DATA: GT_SORT TYPE LVC_T_SORT,

      GS_SORT TYPE LVC_S_SORT.