
*&---------------------------------------------------------------------*

*& Report ZEDR12_IT_027

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR12_IT_027.

DATA: BEGIN OF GS_STUDENT, "### ##

  ZPERNR TYPE ZEDT12_001-ZPERNR, "####

  ZCODE TYPE ZEDT12_001-ZCODE, "####

  ZKNAME TYPE ZEDT12_001-ZKNAME, "##

  ZENAME TYPE ZEDT12_001-ZENAME, "####

  ZGENDER TYPE ZEDT12_001-ZGENDER, "##

  ZGNAME TYPE C LENGTH 8,

  ZTEL TYPE ZEDT12_001-ZTEL, "####



  END OF GS_STUDENT.



  DATA: GT_STUDENT LIKE TABLE OF GS_STUDENT.



  CLEAR: GS_STUDENT, GT_STUDENT.



GS_STUDENT-ZCODE = 'SSU-01'.

GS_STUDENT-ZPERNR = '0000000001'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'DONG'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01011111111'.  "HEADER(###)# ### ##.

 GS_STUDENT-ZGNAME = '####'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_STUDENT-ZCODE = 'SSU-01'.

GS_STUDENT-ZPERNR = '0000000001'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'DONG'.

GS_STUDENT-ZGENDER = 'F'.

GS_STUDENT-ZTEL = '01031111111'.  "HEADER(###)# ### ##.

 GS_STUDENT-ZGNAME = '####'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_STUDENT-ZCODE = 'SSU-01'.

GS_STUDENT-ZPERNR = '0000000001'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'DONG'.

GS_STUDENT-ZGENDER = 'A'.

GS_STUDENT-ZTEL = '01011111111'.  "HEADER(###)# ### ##.

 GS_STUDENT-ZGNAME = '####'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_STUDENT-ZCODE = 'SSU-02'.

GS_STUDENT-ZPERNR = '0000000002'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'LEE'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01011111222'.  "HEADER(###)# ### ##.

 GS_STUDENT-ZGNAME = '####'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_STUDENT-ZCODE = 'SSU-01'.

GS_STUDENT-ZPERNR = '0000000001'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'KANG'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01011111111'.  "HEADER(###)# ### ##.

 GS_STUDENT-ZGNAME = '####'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_STUDENT-ZCODE = 'SSU-01'.

GS_STUDENT-ZPERNR = '0000000001'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'DONG'.

GS_STUDENT-ZGENDER = 'F'.

GS_STUDENT-ZTEL = '01011111111'.  "HEADER(###)# ### ##.

 GS_STUDENT-ZGNAME = '####'.

APPEND GS_STUDENT TO GT_STUDENT.



CLEAR: GS_STUDENT.

SORT GT_STUDENT BY ZCODE ZKNAME ZENAME ZGENDER.



LOOP AT GT_STUDENT INTO GS_STUDENT.



  AT END OF ZENAME.

    GS_STUDENT-ZGNAME = '####'.

    MODIFY GT_STUDENT FROM GS_STUDENT INDEX SY-TABIX TRANSPORTING ZGNAME.

  ENDAT.



  CLEAR GS_STUDENT.

ENDLOOP.



" #### ##

LOOP AT GT_STUDENT INTO GS_STUDENT.

  WRITE : / GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_STUDENT-ZENAME, GS_STUDENT-ZGNAME.

ENDLOOP.