
*&---------------------------------------------------------------------*

*&  Include           ZEDR13_058_TOP

*&---------------------------------------------------------------------*




TABLES : ZEDT13_001.



DATA : BEGIN OF GS_STUDENT,

  ZCOLOR TYPE C LENGTH 4,

  ZCODE LIKE ZEDT13_001-ZCODE,

  ZPERNR LIKE ZEDT13_001-ZPERNR,

  ZKNAME LIKE ZEDT13_001-ZKNAME,

  ZENAME LIKE ZEDT13_001-ZENAME,

  ZGENDER LIKE ZEDT13_001-ZGENDER,

  ZSUM LIKE ZEDT13_002-ZSUM,

  ZMAJOR LIKE ZEDT13_002-ZMAJOR,

  ZMNAME LIKE ZEDT13_002-ZMNAME,

  END OF GS_STUDENT.



DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER.

DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT,

       GT_FIELDCAT TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT TYPE LVC_T_SORT.