
*&---------------------------------------------------------------------*

*&  Include           ZEDR16_PRACTICE009_SCR

*&---------------------------------------------------------------------*






SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

SELECT-OPTIONS : S_ZPERNR FOR ZEDT16_102-ZPERNR. " ####

SELECT-OPTIONS : S_ZDATE FOR ZEDT16_102-DATBI NO INTERVALS NO-EXTENSION. " ####




*PARAMETERS : P_ZDEP LIKE ZEDT16_102-ZDEPCODE MODIF ID M1. " ##### ###### # ## # # ### #### # #.




SELECT-OPTIONS : S_ZDEP FOR ZEDT16_102-ZDEPCODE NO INTERVALS NO-EXTENSION. " ####

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

PARAMETERS : P_QUIT AS CHECKBOX. " #####

SELECTION-SCREEN END OF BLOCK B2.