
*&---------------------------------------------------------------------*

*&  Include           ZEDR16_PRACTICE009_TOP

*&---------------------------------------------------------------------*






TABLES : ZEDT16_102, ZEDT16_103, ZEDT16_104, ZEDT16_106.






*1) ##### ## ####, ###### ### #### - 1#### ZEDT16_102, ZEDT16_103




DATA : BEGIN OF GS_EMP,

         ZPERNR   TYPE ZEDT16_102-ZPERNR, "####

         ZPNAME   TYPE ZEDT16_103-ZPNAME, "##

         ZDEPCODE TYPE ZEDT16_102-ZDEPCODE, "####

         DATBI    TYPE ZEDT16_102-DATBI, "####

         DATAB    TYPE ZEDT16_102-DATAB, "####

         ZDEPRANK TYPE ZEDT16_102-ZDEPRANK, "####

         ZGENDER  TYPE ZEDT16_103-ZGENDER, "####

         ZEDATE   TYPE ZEDT16_102-ZEDATE, "####

         ZADDRESS TYPE ZEDT16_103-ZADDRESS, "##

         ZQDATE   TYPE ZEDT16_102-ZQDATE, "####

         ZQFLAG   TYPE ZEDT16_102-ZQFLAG, "####

       END OF GS_EMP.

DATA : GT_EMP LIKE TABLE OF GS_EMP.



DATA : BEGIN OF GS_EMP_ALV,

         ICON         TYPE CHAR4, "###

         ZPERNR       TYPE ZEDT16_102-ZPERNR, "####

         ZPNAME       TYPE ZEDT16_103-ZPNAME, "##

         ZDEPCODE     TYPE ZEDT16_102-ZDEPCODE, "####

         ZDEPNAME     TYPE CHAR20, "###

         DATBI        TYPE ZEDT16_102-DATBI, "####

         DATAB        TYPE ZEDT16_102-DATAB, "####

         ZDEPRANK     TYPE ZEDT16_102-ZDEPRANK, "####

         ZDEPRANKNAME TYPE CHAR20, "#####

         ZGENDER      TYPE ZEDT16_103-ZGENDER, "####

         ZGENDERNAME  TYPE CHAR20, "###

         ZEDATE       TYPE ZEDT16_102-ZEDATE, "####

         ZADDRESS     TYPE ZEDT16_103-ZADDRESS, "##

         ZQDATE       TYPE ZEDT16_102-ZQDATE, "####

         ZQFLAG       TYPE ZEDT16_102-ZQFLAG, "####

       END OF GS_EMP_ALV.

DATA : GT_EMP_ALV LIKE TABLE OF GS_EMP_ALV.








*2) ##### ## #### #### - 2#### ZEDT16_104




DATA : BEGIN OF GS_EVAL.

    include structure
ZEDT16_104
.

DATA : END OF GS_EVAL.

DATA : GT_EVAL LIKE TABLE OF GS_EVAL.



DATA : BEGIN OF GS_EVAL_ALV,

         ZPERNR   TYPE ZEDT16_104-ZPERNR, "####

         ZDEPCODE TYPE ZEDT16_104-ZDEPCODE, "####

         ZDEPNAME TYPE CHAR20, "###

         ZYEAR    TYPE ZEDT16_104-ZYEAR, "##

         DATBI    TYPE ZEDT16_104-DATBI, "####

         DATAB    TYPE ZEDT16_104-DATAB, "####

         ZRANK    TYPE ZEDT16_104-ZRANK, "##

       END OF GS_EVAL_ALV.

DATA : GT_EVAL_ALV LIKE TABLE OF GS_EVAL_ALV.








*3) ##### ## #### #### - 3#### ZEDT16_106




DATA : BEGIN OF GS_CONTRACT.

    include structure
ZEDT16_106
.

DATA : END OF GS_CONTRACT.

DATA : GT_CONTRACT LIKE TABLE OF GS_CONTRACT.



DATA : BEGIN OF GS_CONTRACT_ALV,

         ZPERNR    TYPE ZEDT16_106-ZPERNR, "####

         ZYEAR     TYPE ZEDT16_106-ZYEAR, "##

         DATBI     TYPE ZEDT16_106-DATBI, "####

         DATAB     TYPE ZEDT16_106-DATAB, "####

         ZSALARY   TYPE ZEDT16_106-ZSALARY, "####

         ZBANKCODE TYPE ZEDT16_106-ZBANKCODE, "####

         ZBANKNAME TYPE CHAR20, "###

         ZACCOUNT  TYPE ZEDT16_106-ZACCOUNT, "####

         ZWAERS    TYPE WAERS, "##

       END OF GS_CONTRACT_ALV.

DATA : GT_CONTRACT_ALV LIKE TABLE OF GS_CONTRACT_ALV.



RANGES : GR_ZQFLAG FOR ZEDT16_102-ZQFLAG.



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.



" # ## SPLIT

DATA : GC_SPLITTER1 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



DATA : GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.



" ### ## ### SPLIT

DATA : GC_SPLITTER2 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



DATA : GC_CONTAINER3 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER4 TYPE REF TO CL_GUI_CONTAINER.



" GRID

DATA : GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID.



" VARINAT, LAYOUT, SORT ## ##

DATA : GS_VARIANT TYPE DISVARIANT.

DATA : GS_LAYOUT TYPE LVC_S_LAYO.

DATA : GS_SORT TYPE LVC_S_SORT .

DATA : GT_SORT TYPE LVC_T_SORT.



" ### 3# ### ### GT_FIELDCAT 3# ##

DATA : GS_FIELDCAT TYPE LVC_S_FCAT.

DATA : GT_FIELDCAT1 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT2 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT3 TYPE LVC_T_FCAT.