
*&---------------------------------------------------------------------*

*&  Include           ZEDR04_PRACTICE009_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS S_ZPERNR FOR ZEDT04_102-ZPERNR.  " ####

  SELECT-OPTIONS S_ZDATE  FOR ZEDT04_102-ZEDATE   NO INTERVALS NO-EXTENSION.  " ####

  SELECT-OPTIONS S_ZDCODE FOR ZEDT04_102-ZDEPCODE NO INTERVALS NO-EXTENSION.  " ####

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS C_ZFLAG  AS CHECKBOX DEFAULT 'X'.  " #####

SELECTION-SCREEN END OF BLOCK B2.