
*&---------------------------------------------------------------------*

*&  Include           ZEDR04_PRACTICE009_TOP

*&---------------------------------------------------------------------*




TABLES : ZEDT04_102.



CONSTANTS C_X TYPE C VALUE 'X'.

RANGES R_FLAG FOR ZEDT04_102-ZQFLAG.  " ### #### ##

DATA OK_CODE TYPE SY-UCOMM.           " ##### ### ### ##



" CLASS ALV ## ###

DATA GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA GC_SPLITTER1 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA GC_SPLITTER2 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.  "1####

DATA GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.  "2####

DATA GC_CONTAINER3 TYPE REF TO CL_GUI_CONTAINER.  "3####

DATA GC_CONTAINER2_3 TYPE REF TO CL_GUI_CONTAINER.  "2,3####

DATA GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.

DATA GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID.



" ## ####

DATA GS_FIELDCAT TYPE LVC_S_FCAT.

DATA GT_FIELDCAT1 TYPE LVC_T_FCAT.

DATA GT_FIELDCAT2 TYPE LVC_T_FCAT.

DATA GT_FIELDCAT3 TYPE LVC_T_FCAT.



" ALV SORT

DATA GS_SORT TYPE LVC_S_SORT.

DATA GT_SORT TYPE LVC_T_SORT.



" ALV LAYOUT

DATA GS_LAYOUT TYPE LVC_S_LAYO.



DATA GS_VARIANT TYPE DISVARIANT.



DATA : BEGIN OF GS_INFO,  " ####

  ZPERNR TYPE ZEDT04_102-ZPERNR,      " ####

  ZPNAME TYPE ZEDT04_103-ZPNAME,      " ##

  ZDEPCODE TYPE ZEDT04_102-ZDEPCODE,  " ####

  DATBI TYPE ZEDT04_102-DATBI,        " ####

  DATAB TYPE ZEDT04_102-DATAB,        " ####

  ZDEPRANK TYPE ZEDT04_102-ZDEPRANK,  " ####

  ZGENDER TYPE ZEDT04_103-ZGENDER,    " ##

  ZEDATE TYPE ZEDT04_102-ZEDATE,      " ####

  ZADDRESS TYPE ZEDT04_103-ZADDRESS,  " ##

  ZQDATE TYPE ZEDT04_102-ZQDATE,      " ####

  ZQFLAG TYPE ZEDT04_102-ZQFLAG,      " ####

  END OF GS_INFO.

DATA GT_INFO LIKE TABLE OF GS_INFO.



DATA : BEGIN OF GS_INFO_ALV,  " #### ###

  ZCOLOR TYPE C LENGTH 4,             " ##

  ZPERNR TYPE ZEDT04_102-ZPERNR,      " ####

  ZPNAME TYPE ZEDT04_103-ZPNAME,      " ##

  ZDEP_NAME TYPE C LENGTH 7,          " ##(##)

  DATBI TYPE ZEDT04_102-DATBI,        " ####

  DATAB TYPE ZEDT04_102-DATAB,        " ####

  ZRANK_NAME TYPE C LENGTH 5,         " ##(##)

  ZGEN_NAME TYPE C LENGTH 5,          " ##(##)

  ZEDATE TYPE ZEDT04_102-ZEDATE,      " ####

  ZADDRESS TYPE ZEDT04_103-ZADDRESS,  " ##

  ZQDATE TYPE ZEDT04_102-ZQDATE,      " ####

  ZQFLAG TYPE ZEDT04_102-ZQFLAG,      " ####

  END OF GS_INFO_ALV.

DATA GT_INFO_ALV LIKE TABLE OF GS_INFO_ALV.



DATA : BEGIN OF GS_RANK,  " ####

  ZPERNR TYPE ZEDT04_104-ZPERNR,      " ####

  ZDEPCODE TYPE ZEDT04_104-ZDEPCODE,  " ####

  ZYEAR TYPE ZEDT04_104-ZYEAR,        " ##

  DATBI TYPE ZEDT04_104-DATBI,        " ####

  DATAB TYPE ZEDT04_104-DATAB,        " ####

  ZRANK TYPE ZEDT04_104-ZRANK,        " ##

  END OF GS_RANK.

DATA GT_RANK LIKE TABLE OF GS_RANK.



DATA : BEGIN OF GS_RANK_ALV,  " #### ###

  ZPERNR TYPE ZEDT04_104-ZPERNR,      " ####

  ZDEP_NAME TYPE C LENGTH 7,          " ###(##)

  ZYEAR TYPE ZEDT04_104-ZYEAR,        " ##

  DATBI TYPE ZEDT04_104-DATBI,        " ####

  DATAB TYPE ZEDT04_104-DATAB,        " ####

  ZRANK TYPE ZEDT04_104-ZRANK,        " ##

  END OF GS_RANK_ALV.

DATA GT_RANK_ALV LIKE TABLE OF GS_RANK_ALV.



DATA : BEGIN OF GS_CONTRACT,  " ####

  ZPERNR TYPE ZEDT04_106-ZPERNR,      " ####

  ZYEAR TYPE ZEDT04_106-ZYEAR,        " ##

  DATBI TYPE ZEDT04_106-DATBI,        " ####

  DATAB TYPE ZEDT04_106-DATAB,        " ####

  ZSALARY TYPE ZEDT04_106-ZSALARY,    " ####

  ZBANKCODE TYPE ZEDT04_106-ZBANKCODE," ####

  ZACCOUNT TYPE ZEDT04_106-ZACCOUNT,  " ####

  END OF GS_CONTRACT.

DATA GT_CONTRACT LIKE TABLE OF GS_CONTRACT.



DATA : BEGIN OF GS_CONTRACT_ALV,  " #### ###

  ZPERNR TYPE ZEDT04_106-ZPERNR,      " ####

  ZYEAR TYPE ZEDT04_106-ZYEAR,        " ##

  DATBI TYPE ZEDT04_106-DATBI,        " ####

  DATAB TYPE ZEDT04_106-DATAB,        " ####

  ZSALARY TYPE ZEDT04_106-ZSALARY,    " ####

  ZWAERS TYPE WAERS,                  " ##(##)

  ZBANK_NAME TYPE C LENGTH 7,         " ###(##)

  ZACCOUNT TYPE ZEDT04_106-ZACCOUNT,  " ####

  END OF GS_CONTRACT_ALV.

DATA GT_CONTRACT_ALV LIKE TABLE OF GS_CONTRACT_ALV.