
TABLES : ZEDT05_102,ZEDT05_103, ZEDT05_104, ZEDT05_106.



RANGES : R_FG FOR ZEDT05_102-ZQFLAG.





DATA : BEGIN OF GS_EMP,

  ZPERNR LIKE ZEDT05_102-ZPERNR,

  ZPNAME LIKE ZEDT05_103-ZPNAME,

  ZDEPCODE LIKE ZEDT05_102-ZDEPCODE,

  DATBI LIKE ZEDT05_102-DATBI,

  DATAB LIKE ZEDT05_102-DATAB,

  ZDEPRANK LIKE ZEDT05_104-ZRANK,

  ZGENDER LIKE ZEDT05_103-ZGENDER,

  ZEDATE LIKE ZEDT05_102-ZEDATE,

  ZQDATE LIKE ZEDT05_102-ZQDATE,

  ZQFLAG LIKE ZEDT05_102-ZQFLAG,

  ZADDRESS LIKE ZEDT05_103-ZADDRESS,

END OF GS_EMP.

DATA : GT_EMP LIKE TABLE OF GS_EMP.



DATA : BEGIN OF GS_EMP_ALV,

  ICON TYPE C LENGTH 4,

  ZPERNR LIKE ZEDT05_102-ZPERNR,

  ZPNAME LIKE ZEDT05_103-ZPNAME,

  ZDEPCODE_NAME TYPE C LENGTH 10,

  DATBI LIKE ZEDT05_102-DATBI,

  DATAB LIKE ZEDT05_102-DATAB,

  ZRANK_NAME(8),

  ZGENDER_NAME(4),

  ZEDATE LIKE ZEDT05_102-ZEDATE,

  ZQDATE LIKE ZEDT05_102-ZQDATE,

  ZQFLAG LIKE ZEDT05_102-ZQFLAG,

  ZADDRESS LIKE ZEDT05_103-ZADDRESS,

  END OF GS_EMP_ALV.



DATA : GT_EMP_ALV LIKE TABLE OF GS_EMP_ALV.



DATA : BEGIN OF GS_PAY.

  include structure
ZEDT05_106
.

DATA : END OF GS_PAY.





DATA : GT_PAY LIKE TABLE OF GS_PAY.



DATA : BEGIN OF GS_PAY_ALV, "## #### ##

  ZPERNR LIKE ZEDT05_106-ZPERNR,

  ZYEAR LIKE ZEDT05_106-ZYEAR,

  DATBI LIKE ZEDT05_106-DATBI,

  DATAB LIKE ZEDT05_106-DATAB,

  ZSALARY LIKE ZEDT05_106-ZSALARY,

  ZWAERS TYPE WAERS, "##

  ZBANK_NAME TYPE C LENGTH 10,

  ZACCOUNT LIKE ZEDT05_106-ZACCOUNT,

END OF GS_PAY_ALV.



DATA : GT_PAY_ALV LIKE TABLE OF GS_PAY_ALV.



DATA : BEGIN OF GS_EVAL, "####

  ZPERNR LIKE ZEDT05_104-ZPERNR,

  ZDEPCODE LIKE ZEDT05_104-ZDEPCODE,

  ZYEAR LIKE ZEDT05_104-ZYEAR,

  DATBI LIKE ZEDT05_104-DATBI,

  DATAB LIKE ZEDT05_104-DATAB,

  ZRANK LIKE ZEDT05_104-ZRANK,

  END OF GS_EVAL.

DATA : GT_EVAL LIKE TABLE OF GS_EVAL.



DATA : BEGIN OF GS_EVAL_ALV, "#### ##

  ZPERNR LIKE ZEDT05_104-ZPERNR,

  ZDEPCODE_NAME TYPE C LENGTH 10,

  ZYEAR LIKE ZEDT05_104-ZYEAR,

  DATBI LIKE ZEDT05_104-DATBI,

  DATAB LIKE ZEDT05_104-DATAB,

  ZRANK LIKE ZEDT05_104-ZRANK,

  END OF GS_EVAL_ALV.



DATA : GT_EVAL_ALV LIKE TABLE OF GS_EVAL_ALV.



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.



DATA : GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER,

       GC_SPLITTER2 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



DATA : GC_CONTAINER_TOP TYPE REF TO CL_GUI_CONTAINER,

       GC_CONTAINER_BOTTOM TYPE REF TO CL_GUI_CONTAINER,

       GC_CONTAINER_TOPEVAL TYPE REF TO CL_GUI_CONTAINER,

       GC_CONTAINER_TOPPAY TYPE REF TO CL_GUI_CONTAINER,

       GC_GRID_TOPEVAL TYPE REF TO CL_GUI_ALV_GRID,

       GC_GRID_TOPPAY TYPE REF TO CL_GUI_ALV_GRID,

       GC_GRID_BOTTOM TYPE REF TO CL_GUI_ALV_GRID,

       GS_FIELDCAT TYPE LVC_S_FCAT,

       GT_FIELDCAT_BOTTOM TYPE LVC_T_FCAT,

       GT_FIELDCAT_TOPPAY TYPE LVC_T_FCAT,

       GT_FIELDCAT_TOPEVAL TYPE LVC_T_FCAT,

       GS_LAYOUT TYPE LVC_S_LAYO,

       GS_SORT TYPE LVC_S_SORT,

       GT_SORT1 TYPE LVC_T_SORT,

       GT_SORT2 TYPE LVC_T_SORT,

       GT_SORT3 TYPE LVC_T_SORT.



DATA : GS_VARIANT TYPE DISVARIANT.