
*&---------------------------------------------------------------------*

*&  Include           ZED23_PRACTICE008_TOP

*&---------------------------------------------------------------------*






TABLES : ZEDT23_100,

  ZEDT23_101.



CONSTANTS : TRUE TYPE C LENGTH 1 VALUE 'X'.



DATA : ZSTART_DAY TYPE SY-DATUM,

      ZEND_DAY TYPE SY-DATUM.





DATA : MAX_ID TYPE ZEDT23_100-ZIDCODE.

SELECT MAX( ZIDCODE ) INTO MAX_ID FROM ZEDT23_100.



RANGES : GR_ZIDCODE FOR ZEDT23_100-ZIDCODE.

  GR_ZIDCODE-SIGN = 'I'.

  GR_ZIDCODE-OPTION = 'BT'.

  GR_ZIDCODE-LOW = 'SSU-00'.

  GR_ZIDCODE-HIGH = MAX_ID.

  APPEND GR_ZIDCODE.



DATA : BEGIN OF GS_100,

  ZORDNO LIKE ZEDT23_100-ZORDNO,  "####

  ZIDCODE LIKE ZEDT23_100-ZIDCODE,  "##ID

  ZMATNR LIKE ZEDT23_100-ZMATNR, "####

  ZMATNAME LIKE ZEDT23_100-ZMATNAME,  "###

  ZMTART LIKE ZEDT23_100-ZMTART,  "####

  ZMTART_STR TYPE STRING,

  ZVOLUM LIKE ZEDT23_100-ZVOLUM, "##

  VRKME LIKE ZEDT23_100-VRKME, "##

  ZNSAMT LIKE ZEDT23_100-ZNSAMT,  "####

  ZSLAMT LIKE ZEDT23_100-ZSLAMT,  "####

  ZDCAMT LIKE ZEDT23_100-ZDCAMT,  "####

  ZWAERS LIKE ZEDT23_100-ZWAERS,  "##

  ZSALE_FG LIKE ZEDT23_100-ZSALE_FG,  "####

  ZLIGHT TYPE C LENGTH 1,          " ###

  ZSALE_FG_STR TYPE STRING,

  ZJDATE LIKE ZEDT23_100-ZJDATE,  "####

  ZRET_FG LIKE ZEDT23_100-ZRET_FG,  "####

  ZRET_FG_STR TYPE STRING,

  ZRDATE LIKE ZEDT23_100-ZRDATE,"####

  END OF GS_100.

DATA : GT_100 LIKE TABLE OF GS_100.



DATA : BEGIN OF GS_101,

  ZLIGHT TYPE C LENGTH 1, "##

  ZORDNO LIKE ZEDT23_101-ZORDNO,  "####

  ZIDCODE LIKE ZEDT23_101-ZIDCODE,  "##ID

  ZMATNR LIKE ZEDT23_101-ZMATNR,  "####

  ZMATNAME LIKE ZEDT23_101-ZMATNAME,  "###

  ZMTART LIKE ZEDT23_101-ZMTART,  "####

  ZMTART_STR TYPE STRING,

  ZVOLUM LIKE ZEDT23_101-ZVOLUM,  "##

  VRKME LIKE ZEDT23_101-VRKME, "##

  ZSLAMT LIKE ZEDT23_101-ZSLAMT,  "####

  ZWAERS LIKE ZEDT23_101-ZWAERS,  "##

  ZDFLAG LIKE ZEDT23_101-ZDFLAG,  "####

  ZDFLAG_STR TYPE STRING,

  ZDGUBUN LIKE ZEDT23_101-ZDGUBUN,  "####

  ZDGUBUN_STR TYPE STRING,

  ZDDATE LIKE ZEDT23_101-ZDDATE,  "####

  ZRDATE LIKE ZEDT23_101-ZRDATE,  "####

  ZFLAG LIKE ZEDT23_101-ZFLAG,     "####(####)

  END OF GS_101.

DATA : GT_101 LIKE TABLE OF GS_101.



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT.

DATA : GT_FIELDCAT TYPE LVC_T_FCAT.

DATA : GS_LAYOUT TYPE LVC_S_LAYO.

DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT TYPE LVC_T_SORT.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.

DATA : GS_VARIANT TYPE DISVARIANT.