
*&---------------------------------------------------------------------*

*&  Include           ZMMR04_003_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  PARAMETERS P_EBELN LIKE ZEKKO04-EBELN.        " PO##

  PARAMETERS P_ZWERKS LIKE ZEDT04_200-ZWERKS.   " ###

  PARAMETERS P_RGDAT TYPE DATUM MODIF ID M1.                " #####

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF LINE.

  " ####

  PARAMETERS P_RD1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

  SELECTION-SCREEN POSITION 3.

  SELECTION-SCREEN COMMENT (10) FOR FIELD P_RD1.



  " ####

  PARAMETERS P_RD2 RADIOBUTTON GROUP R1.

  SELECTION-SCREEN POSITION 20.

  SELECTION-SCREEN COMMENT (10) FOR FIELD P_RD2.

SELECTION-SCREEN END OF LINE.