
*&---------------------------------------------------------------------*

*& Report ZEDR20_010

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR20_010.






*DATA: GT_STUDENT TYPE TABLE OF ZEDT20_001. " WITH NON-UNIQUE KEY ZGENDER. " #### ## ## #### key##

*DATA: GS_STUDENT TYPE ZEDT20_001.

*

*CLEAR: GS_STUDENT, GT_STUDENT.

*

*GS_STUDENT-ZCODE = 'SSU-01'.

*GS_STUDENT-ZPERNR = '0000000001'.

*GS_STUDENT-ZKNAME = '###'.

*GS_STUDENT-ZENAME = 'DONG'.

*GS_STUDENT-ZGENDER = 'M'.

*GS_STUDENT-ZTEL = '01011112222'.

*APPEND GS_STUDENT TO GT_STUDENT.

*

*CLEAR: GS_STUDENT.

*GS_STUDENT-ZCODE = 'SSU-02'.

*GS_STUDENT-ZPERNR = '0000000002'.

*GS_STUDENT-ZKNAME = '###'.

*GS_STUDENT-ZENAME = 'HOON'.

*GS_STUDENT-ZGENDER = 'M'.

*GS_STUDENT-ZTEL = '01022223333'.

*APPEND GS_STUDENT TO GT_STUDENT.

*

*CLEAR: GS_STUDENT.

*GS_STUDENT-ZCODE = 'SSU-03'.

*GS_STUDENT-ZPERNR = '0000000003'.

*GS_STUDENT-ZKNAME = '###'.

*GS_STUDENT-ZENAME = 'SON'.

*GS_STUDENT-ZGENDER = 'F'.

*GS_STUDENT-ZTEL = '01033334444'.

*APPEND GS_STUDENT TO GT_STUDENT.

*

**" 1. LOOP# ### ##

**LOOP AT GT_STUDENT INTO GS_STUDENT.

**  IF GS_STUDENT-ZGENDER NE 'M'.

**    GS_STUDENT-ZGENDER = 'M'.

**    DELETE TABLE GT_STUDENT FROM GS_STUDENT.    " GT_STUDENT# #### GS_STUDENT# ### SY-SUBRC# 4# #

**

**    IF SY-SUBRC = 0.

**    ELSE.

**      WRITE:/ '####'.

**    ENDIF.

**  ELSE.

**    WRITE:/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_STUDENT-ZGENDER.

**  ENDIF.

**  BREAK-POINT.

**ENDLOOP.

*

**" 2. TABLE KEY# ### ##

**DELETE TABLE GT_STUDENT WITH TABLE KEY ZGENDER = 'F'.

*

**" 3. WHERE### ### ## ##

**DELETE GT_STUDENT WHERE ZGENDER = 'F'.

*

**" 4. INDEX# ### ## ##

**DELETE GT_STUDENT TO 2."FROM 2."FROM 2 TO 3."INDEX 2.

*

*" 5. ADJACENT DUPLICATE ### ### #### ##

*CLEAR: GS_STUDENT.

*GS_STUDENT-ZCODE = 'SSU-03'.

*GS_STUDENT-ZPERNR = '0000000003'.

*GS_STUDENT-ZKNAME = '###'.

*GS_STUDENT-ZENAME = 'SON'.

*GS_STUDENT-ZGENDER = 'F'.

*GS_STUDENT-ZTEL = '01033334445'.

*APPEND GS_STUDENT TO GT_STUDENT.

*

*LOOP AT GT_STUDENT INTO GS_STUDENT.

*  WRITE:/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_STUDENT-ZGENDER.

*  CLEAR: GS_STUDENT.

*ENDLOOP.

*

*DELETE ADJACENT DUPLICATES FROM GT_STUDENT COMPARING ZCODE.

*WRITE:/ '## ## #'.

*

*IF SY-SUBRC = 0.

*  LOOP AT GT_STUDENT INTO GS_STUDENT.

*    WRITE:/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_STUDENT-ZGENDER.

*    CLEAR: GS_STUDENT.

*  ENDLOOP.

*ELSE.

*  WRITE:/ '## ##'.

*ENDIF.