
*&---------------------------------------------------------------------*

*&  Include           ZMM06_002_SCR

*&---------------------------------------------------------------------*








SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  PARAMETERS P_LIFNR1   TYPE ZEDT06_EKKO-LIFNR  MODIF ID M1.      " ###

  PARAMETERS P_LIFNR2   TYPE ZEDT06_EKKO-LIFNR  MODIF ID M2.      " #####

  PARAMETERS P_BUKRS    TYPE ZEDT06_EKKO-BUKRS  MODIF ID COM.     " ####

  PARAMETERS P_BEDAT    TYPE ZEDT06_EKKO-BEDAT  MODIF ID M1 DEFAULT SY-DATUM.      " ###

  PARAMETERS P_EBELN    TYPE ZEDT06_EKKO-EBELN  MODIF ID M2.      " PO##

SELECTION-SCREEN END OF BLOCK B1.





SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.



  SELECTION-SCREEN BEGIN OF LINE.

    PARAMETERS P_CREATE RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

    SELECTION-SCREEN COMMENT 4(10) TEXT-B01 FOR FIELD P_CREATE.



    SELECTION-SCREEN POSITION 25.

    PARAMETERS P_FIND RADIOBUTTON GROUP R1.

    SELECTION-SCREEN COMMENT 32(10) TEXT-B02 FOR FIELD P_FIND.

  SELECTION-SCREEN END OF LINE.



SELECTION-SCREEN END OF BLOCK B2.