
*&---------------------------------------------------------------------*

*& Report ZEDR12_IT_019

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR12_IT_019.

DATA: BEGIN OF GS_STUDENT, "### ##

  ZPERNR TYPE ZEDT12_001-ZPERNR, "####

  ZCODE TYPE ZEDT12_001-ZCODE, "####

  ZKNAME TYPE ZEDT12_001-ZKNAME, "##

  ZENAME TYPE ZEDT12_001-ZENAME, "####

  ZGENDER TYPE ZEDT12_001-ZGENDER, "##

  ZGNAME TYPE C LENGTH 4,

  ZTEL TYPE ZEDT12_001-ZTEL, "####



  END OF GS_STUDENT.



  DATA: GT_STUDENT LIKE TABLE OF GS_STUDENT WITH NON-UNIQUE KEY ZCODE.



  CLEAR: GS_STUDENT, GT_STUDENT.



GS_STUDENT-ZCODE = 'SSU-01'.

GS_STUDENT-ZPERNR = '0000000001'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'KANG'.

GS_STUDENT-ZGENDER = 'F'.

GS_STUDENT-ZTEL = '01011111111'.  "HEADER(###)# ### ##.

APPEND GS_STUDENT TO GT_STUDENT.



"GS_STUDENT-ZGENDER = 'M'.

"MODIFY TABLE GT_STUDENT FROM GS_STUDENT.



GS_STUDENT-ZENAME = 'DONG'.

GS_STUDENT-ZGENDER = 'M'.

MODIFY TABLE GT_STUDENT FROM GS_STUDENT TRANSPORTING ZGENDER. "### ## ## ###, ### ### ### ###.