
*&---------------------------------------------------------------------*

*&  Include           ZEDR12_SPLITTER_CONTAINER_TOP

*&---------------------------------------------------------------------*




TABLES: ZEDT12_001.



DATA: BEGIN OF GS_STUDENT,

  ZCODE LIKE ZEDT12_001-ZCODE,    "####

  ZPERNR LIKE ZEDT12_001-ZPERNR,  " ####

  ZKNAME LIKE ZEDT12_001-ZKNAME,  " ##

  ZENAME LIKE ZEDT12_001-ZENAME,  " ###

  ZGENDER LIKE ZEDT12_001-ZGENDER," ##

  END OF GS_STUDENT.

DATA: GT_STUDENT LIKE TABLE OF GS_STUDENT.



DATA: OK_CODE TYPE SY-UCOMM. "#### ##### ## #####



"DOCKING ## ## ##.

DATA: GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

"SPLITTER ## ## ##.

DATA: GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

"CONTAINER ####

DATA: GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.

DATA: GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.

"GRID ####

DATA: GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA: GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.



"######, SORT,########



DATA: GS_VARIANT TYPE DISVARIANT.



DATA: GS_FIELDCAT TYPE LVC_S_FCAT.

DATA: GT_FIELDCAT1 TYPE LVC_T_FCAT.

DATA: GT_FIELDCAT2 TYPE LVC_T_FCAT.



" ALV ####

DATA: GS_LAYOUT TYPE LVC_S_LAYO.



" ALV SORT ### ##

DATA: GS_SORT TYPE LVC_S_SORT.

DATA: GT_SORT1 TYPE LVC_T_SORT.

DATA: GT_SORT2 TYPE LVC_T_SORT.