
*&---------------------------------------------------------------------*

*&  Include  ZEDR21_024_TOP

*&---------------------------------------------------------------------*




TABLES : ZEDT21_001, ZEDT21_002.



DATA : BEGIN OF GS_STUDENT,

  ZCOLOR TYPE C LENGTH 4,

  ZCODE LIKE ZEDT21_001-ZCODE21,

  ZPERNR LIKE ZEDT21_001-ZPERNR21,

  ZKNAME LIKE ZEDT21_001-ZKNAME21,

  ZENAME LIKE ZEDT21_001-ZENAME21,

  ZGENDER LIKE ZEDT21_001-ZGUBUN21,

  ZSUM LIKE ZEDT21_002-ZSUM21,

  ZMAJOR LIKE ZEDT21_002-ZMAJOR21,

  ZMNAME LIKE ZEDT21_002-ZMNAME21,

  END OF GS_STUDENT.



  DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.



  DATA : GS_FIELDCAT TYPE SLIS_FIELDCAT_ALV.

  DATA : GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV.



  DATA : GS_LAYOUT TYPE SLIS_LAYOUT_ALV.



  DATA : GS_SORT TYPE SLIS_SORTINFO_ALV.

  DATA: GT_SORT TYPE SLIS_T_SORTINFO_ALV.