
*&---------------------------------------------------------------------*

*&  Include           ZMMR01_002_SCR

*&---------------------------------------------------------------------*






SELECTION-SCREEN BEGIN OF BLOCK B1.

  PARAMETERS : P_LIFNR TYPE ZLFA1_01-LIFNR MODIF ID M1.  " ### ##

  PARAMETERS : P_BUKRS TYPE ZLFB1_01-BUKRS.              " ####

  PARAMETERS : P_KTOKK TYPE ZLFA1_01-KTOKK MODIF ID M2.  " ### ##

SELECTION-SCREEN END OF BLOCK B1.





SELECTION-SCREEN BEGIN OF LINE.

  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

SELECTION-SCREEN POSITION 3.

SELECTION-SCREEN COMMENT (10) FOR FIELD P_R1.

  PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

SELECTION-SCREEN POSITION 20.

SELECTION-SCREEN COMMENT (10) FOR FIELD P_R2.

SELECTION-SCREEN END OF LINE.