
*&---------------------------------------------------------------------*

*&  Include           ZEDR08_PRACTICE008_TOP

*&---------------------------------------------------------------------*






" ### #### ## ##

TABLES : ZEDT08_100,

         ZEDT08_101.



" ## ##

CONSTANTS: C_X TYPE CHAR1 VALUE 'X'.

CONSTANTS: C_A TYPE CHAR1 VALUE 'A'.



" ## ### ##

RANGES: R_FG FOR ZEDT08_100-ZSALE_FG.

RANGES: R_ZG FOR ZEDT08_101-ZFLAG.



" ALV ## ##

TYPE-POOLS: SLIS.



" ZEDT08_100 ##### ### ## ### GS_ORDER

DATA: BEGIN OF GS_ORDER,

  ZORDNO LIKE ZEDT08_100-ZORDNO,

  ZIDCODE LIKE ZEDT08_100-ZIDCODE,

  ZMATNR LIKE ZEDT08_100-ZMATNR,

  ZMTART LIKE ZEDT08_100-ZMTART,

  ZMATNAME LIKE ZEDT08_100-ZMATNAME,

  ZVOLUM LIKE ZEDT08_100-ZVOLUM,

  VRKME LIKE ZEDT08_100-VRKME,

  ZNSAMT LIKE ZEDT08_100-ZNSAMT,

  ZSLAMT LIKE ZEDT08_100-ZSLAMT,

  ZDCAMT LIKE ZEDT08_100-ZDCAMT,

  ZWAERS LIKE ZEDT08_100-ZWAERS,

  ZDC_FG LIKE ZEDT08_100-ZDC_FG,

  ZSALE_FG LIKE ZEDT08_100-ZSALE_FG,

  ZRET_FG LIKE ZEDT08_100-ZRET_FG,

  ZJDATE LIKE ZEDT08_100-ZJDATE,

  ZRDATE LIKE ZEDT08_100-ZRDATE,

  END OF GS_ORDER.

" GS_ORDER ### ### ###

DATA: GT_ORDER LIKE TABLE OF GS_ORDER.



" ALV# ## GT_ORDER ### ## GS_100

DATA: BEGIN OF GS_0100,

  ICON TYPE C LENGTH 4,

  ZORDNO LIKE ZEDT08_100-ZORDNO,

  ZIDCODE LIKE ZEDT08_100-ZIDCODE,

  ZMATNR LIKE ZEDT08_100-ZMATNR,

  ZMATNAME LIKE ZEDT08_100-ZMATNAME,

  ZMAT_NAME TYPE C LENGTH 8,

  ZVOLUM LIKE ZEDT08_100-ZVOLUM,

  VRKME LIKE ZEDT08_100-VRKME,

  ZNSAMT LIKE ZEDT08_100-ZNSAMT,

  ZSLAMT LIKE ZEDT08_100-ZSLAMT,

  ZDCAMT LIKE ZEDT08_100-ZDCAMT,

  ZWAERS LIKE ZEDT08_100-ZWAERS,

  ZSALE_NAME TYPE C LENGTH 4,

  ZJDATE LIKE ZEDT08_100-ZJDATE,

  ZRET_NAME TYPE C LENGTH 10,

  ZRDATE LIKE ZEDT08_100-ZRDATE,

  END OF GS_0100.

" ALV ### GT_0100 ### ##

DATA: GT_0100 LIKE TABLE OF GS_0100.



" ZEDT08_101 ##### ### ## GS_DELIVERY

DATA: BEGIN OF GS_DELIVERY,

  ZORDNO LIKE ZEDT08_101-ZORDNO,

  ZIDCODE LIKE ZEDT08_101-ZIDCODE,

  ZMATNR LIKE ZEDT08_101-ZMATNR,

  ZMTART LIKE ZEDT08_101-ZMTART,

  ZMATNAME LIKE ZEDT08_101-ZMATNAME,

  ZVOLUM LIKE ZEDT08_101-ZVOLUM,

  VRKME LIKE ZEDT08_101-VRKME,

  ZSLAMT LIKE ZEDT08_101-ZSLAMT,

  ZWAERS LIKE ZEDT08_101-ZWAERS,

  ZDFLAG LIKE ZEDT08_101-ZDFLAG,

  ZDGUBUN LIKE ZEDT08_101-ZDGUBUN,

  ZDDATE LIKE ZEDT08_101-ZDDATE,

  ZRDATE LIKE ZEDT08_101-ZRDATE,

  ZFLAG LIKE ZEDT08_101-ZFLAG,

  END OF GS_DELIVERY.

" GS_DELIVERY ### ###

DATA: GT_DELIVERY LIKE TABLE OF GS_DELIVERY.



" GT_DELIVERY ALV ###

DATA: BEGIN OF GS_0200,

  ICON TYPE C LENGTH 4,

  ZORDNO LIKE ZEDT08_101-ZORDNO,

  ZIDCODE LIKE ZEDT08_101-ZIDCODE,

  ZMATNR LIKE ZEDT08_101-ZMATNR,

  ZMATNAME LIKE ZEDT08_101-ZMATNAME,

  ZMAT_NAME TYPE C LENGTH 8,

  ZVOLUM LIKE ZEDT08_101-ZVOLUM,

  VRKME LIKE ZEDT08_101-VRKME,

  ZSLAMT LIKE ZEDT08_101-ZSLAMT,

  ZWAERS LIKE ZEDT08_100-ZWAERS,

  ZDFLAG_NAME TYPE C LENGTH 8,

  ZDGUBUN_NAME TYPE C LENGTH 6,

  ZDDATE LIKE ZEDT08_101-ZDDATE,

  ZRDATE LIKE ZEDT08_101-ZRDATE,

  ZFLAG LIKE ZEDT08_101-ZFLAG,

  END OF GS_0200.

" GS_0200 ### ###

DATA: GT_0200 LIKE TABLE OF GS_0200.



" #### ## ### ### ##

DATA: OK_CODE TYPE SY-UCOMM.



" ALV GRID CONTROL ## ## ##

DATA: GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA: GC_GRID TYPE REF TO CL_GUI_ALV_GRID.



" ALV ### ## ###, ###

DATA: GS_SORT TYPE LVC_S_SORT.

DATA: GT_SORT TYPE LVC_T_SORT.



" ALV ## #### ### ## ###, ###

DATA: GS_FIELDCAT TYPE LVC_S_FCAT,

      GT_FIELDCAT TYPE LVC_T_FCAT.



" ALV ### ## ###

DATA: GS_LAYOUT TYPE LVC_S_LAYO.

" ## ### ## ###

DATA: GS_VARIANT TYPE DISVARIANT.