
*&---------------------------------------------------------------------*

*&  Include           ZEDR08_PRACTICE008_SCR

*&---------------------------------------------------------------------*




" ## ## ##

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS: S_ZORDNO FOR ZEDT08_100-ZORDNO MODIF ID M1. " ## ##

  SELECT-OPTIONS: S_ZCODE FOR ZEDT08_100-ZIDCODE NO INTERVALS NO-EXTENSION MODIF ID M2. " ## ID

  SELECT-OPTIONS: S_ZMATNR FOR ZEDT08_100-ZMATNR MODIF ID M3. " ## ##

  SELECT-OPTIONS: S_ZJDATE FOR ZEDT08_100-ZJDATE MODIF ID M4. " ####

  SELECT-OPTIONS: S_ZDDATE FOR ZEDT08_101-ZDDATE MODIF ID M5. " ####

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS: P_RBUT1 RADIOBUTTON GROUP RBUT DEFAULT 'X' USER-COMMAND UC1, " ####

              P_RBUT2 RADIOBUTTON GROUP RBUT. " ## ##

SELECTION-SCREEN END OF BLOCK B2.



SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME.

  PARAMETERS: P_CHK1 AS CHECKBOX DEFAULT C_X USER-COMMAND UC2 MODIF ID UC2. " ######

SELECTION-SCREEN END OF BLOCK B3.