
*&---------------------------------------------------------------------*

*&  Include           ZEDR022_PRACTICE009_TOP

*&---------------------------------------------------------------------*






TABLES : ZEDT22_102, ZEDT22_103. "####

TABLES : ZEDT22_104. "####

TABLES : ZEDT22_106. "####



CONSTANTS : C_X TYPE CHAR1 VALUE 'X'.



RANGES : R_FG FOR ZEDT22_102-ZQFLAG."####





DATA : BEGIN OF GS_EMPL, "####

  ZPERNR LIKE ZEDT22_102-ZPERNR, "####

  ZPNAME LIKE ZEDT22_103-ZPNAME, "##

  ZDEPCODE LIKE ZEDT22_102-ZDEPCODE, "####

  DATBI LIKE ZEDT22_102-DATBI, "####

  DATAB LIKE ZEDT22_102-DATAB, "####

  ZDEPRANK LIKE ZEDT22_104-ZRANK, "##

  ZGENDER LIKE ZEDT22_103-ZGENDER, "##

  ZEDATE LIKE ZEDT22_102-ZEDATE, "####

  ZQDATE LIKE ZEDT22_102-ZQDATE, "####

  ZQFLAG LIKE ZEDT22_102-ZQFLAG, "####

  ZADDRESS LIKE ZEDT22_103-ZADDRESS, "##

  END OF GS_EMPL.

DATA : GT_EMPL LIKE TABLE OF GS_EMPL.



DATA : BEGIN OF GS_EMPL_ALV, "#### ##

  ICON TYPE C LENGTH 4, "###

  ZPERNR LIKE ZEDT22_102-ZPERNR, "####

  ZPNAME LIKE ZEDT22_103-ZPNAME, "##

  ZDEPCODE_NAME TYPE C LENGTH 10, "##

  DATBI LIKE ZEDT22_102-DATBI, "####

  DATAB LIKE ZEDT22_102-DATAB, "####

  ZRANK_NAME(8), "##

  ZGENDER_NAME(4), "##

  ZEDATE LIKE ZEDT22_102-ZEDATE, "####

  ZQDATE LIKE ZEDT22_102-ZQDATE, "####

  ZQFLAG LIKE ZEDT22_102-ZQFLAG, "####

  ZADDRESS LIKE ZEDT22_103-ZADDRESS, "##

  END OF GS_EMPL_ALV.

DATA : GT_EMPL_ALV LIKE TABLE OF GS_EMPL_ALV.



DATA : BEGIN OF GS_EVAL, "##

  ZPERNR LIKE ZEDT22_104-ZPERNR, "####

  ZDEPCODE LIKE ZEDT22_104-ZDEPCODE, "####

  ZYEAR LIKE ZEDT22_104-ZYEAR, "##

  DATBI LIKE ZEDT22_104-DATBI, "####

  DATAB LIKE ZEDT22_104-DATAB, "####

  ZRANK LIKE ZEDT22_104-ZRANK, "####

  END OF GS_EVAL.

DATA : GT_EVAL LIKE TABLE OF GS_EVAL.



DATA : BEGIN OF GS_EVAL_ALV, "##

  ZPERNR LIKE ZEDT22_104-ZPERNR, "####

  ZDEPCODE_NAME TYPE C LENGTH 10, "##

  ZYEAR LIKE ZEDT22_104-ZYEAR, "##

  DATBI LIKE ZEDT22_104-DATBI, "####

  DATAB LIKE ZEDT22_104-DATAB, "####

  ZRANK LIKE ZEDT22_104-ZRANK, "####

  END OF GS_EVAL_ALV.

DATA : GT_EVAL_ALV LIKE TABLE OF GS_EVAL_ALV.



DATA : BEGIN OF GS_CONTR, "##

  ZPERNR LIKE ZEDT22_106-ZPERNR, "####

  ZYEAR LIKE ZEDT22_106-ZYEAR, "####

  DATBI LIKE ZEDT22_106-DATBI, "####

  DATAB LIKE ZEDT22_106-DATAB, "####

  ZSALARY LIKE ZEDT22_106-ZSALARY, "####

  ZBANKCODE LIKE ZEDT22_106-ZBANKCODE, "####

  ZACCOUNT LIKE ZEDT22_106-ZACCOUNT, "####

  END OF GS_CONTR.

DATA : GT_CONTR LIKE TABLE OF GS_CONTR.



DATA : BEGIN OF GS_CONTR_ALV, "##

  ZPERNR LIKE ZEDT22_106-ZPERNR, "####

  ZYEAR LIKE ZEDT22_106-ZYEAR, "####

  DATBI LIKE ZEDT22_106-DATBI, "####

  DATAB LIKE ZEDT22_106-DATAB, "####

  ZSALARY LIKE ZEDT22_106-ZSALARY, "####

  ZWAERS TYPE WAERS, "##

  ZBANK_NAME TYPE C LENGTH 10, "##

  ZACCOUNT LIKE ZEDT22_106-ZACCOUNT, "ZBANKL

  END OF GS_CONTR_ALV.

DATA : GT_CONTR_ALV LIKE TABLE OF GS_CONTR_ALV.





DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.



DATA : GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA : GC_SPLITTER2 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



DATA : GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER3 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER4 TYPE REF TO CL_GUI_CONTAINER.



DATA : GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT,

       GT_FIELDCAT1 TYPE LVC_T_FCAT.



DATA : GT_FIELDCAT2 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT3 TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GS_SORT TYPE LVC_S_SORT .

DATA : GT_SORT1 TYPE LVC_T_SORT.

DATA : GT_SORT2 TYPE LVC_T_SORT.

DATA : GT_SORT3 TYPE LVC_T_SORT.



DATA : GS_VARIANT TYPE DISVARIANT.