
*&---------------------------------------------------------------------*

*&  Include           ZEDR022_PRACTICE009_SCR

*&---------------------------------------------------------------------*






SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

 SELECT-OPTIONS : S_ZPER FOR ZEDT22_102-ZPERNR. "####

 SELECT-OPTIONS : S_DATE FOR ZEDT22_102-DATBI NO INTERVALS NO-EXTENSION."####

 SELECT-OPTIONS : S_DEPT FOR ZEDT22_104-ZDEPCODE NO INTERVALS NO-EXTENSION."####

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME.

  PARAMETERS : P_CH1 AS CHECKBOX DEFAULT 'X'."#####

SELECTION-SCREEN END OF BLOCK B3.