
*&---------------------------------------------------------------------*

*&  Include           ZEDR13_PRACTICE008_SCR

*&---------------------------------------------------------------------*






SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS : S_ZORDNO FOR ZEDT13_100-ZORDNO.  "## #### ### ## #### ### #### ##"

  SELECT-OPTIONS : S_IDCODE FOR ZEDT13_100-ZIDCODE NO INTERVALS NO-EXTENSION.

  SELECT-OPTIONS : S_MATNR FOR ZEDT13_101-ZMATNR.

  SELECT-OPTIONS : S_ZJDATE FOR ZEDT13_100-ZJDATE MODIF ID M1.

  SELECT-OPTIONS : S_DDATE FOR ZEDT13_101-ZDDATE MODIF ID M2.

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS P1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1. "#### ## USER EVENT ####"

  PARAMETERS P2 RADIOBUTTON GROUP R1.

SELECTION-SCREEN END OF BLOCK B2.



SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME.

  PARAMETERS P3 AS CHECKBOX DEFAULT 'X'.

SELECTION-SCREEN END OF BLOCK B3.