
*&---------------------------------------------------------------------*

*&  Include           ZEDR13_PRACTICE008_TOP

*&---------------------------------------------------------------------*






TABLES : ZEDT13_100, ZEDT13_101. "SELECTION OPTION ##### ## ##"



DATA : GS_ORDER TYPE ZEDT13_100.

DATA : GT_ORDER LIKE TABLE OF GS_ORDER.



DATA : BEGIN OF GS_WORDER,

  ZICON TYPE C LENGTH 4,              "### ICON"

  ZORDNO LIKE ZEDT13_100-ZORDNO,      "####"

  ZIDCODE TYPE ZEDT13_100-ZIDCODE,    "##ID"

  ZMATNR LIKE ZEDT13_100-ZMATNR,      "####"

  ZMATNAME LIKE ZEDT13_100-ZMATNAME,  "###"

  ZMTART LIKE ZEDT13_100-ZMTART,      "####"

  ZVOLUM LIKE ZEDT13_100-ZVOLUM,      "##"

  VRKME LIKE ZEDT13_100-VRKME,        "##"

  ZNSAMT LIKE ZEDT13_100-ZNSAMT,      "####"

  ZSLAMT LIKE ZEDT13_100-ZSLAMT,      "####"

  ZDCAMT LIKE ZEDT13_100-ZDCAMT,      "####"

  ZWAERS LIKE ZEDT13_100-ZWAERS,      "##"

  ZSALE_FG TYPE C LENGTH 4,           "#### -> ##"

  ZJDATE TYPE C LENGTH 10,            "####"

  ZRET_FG TYPE C LENGTH 10,           "####"

  ZRDATE TYPE C LENGTH 10,            "####"

 END OF GS_WORDER.

 DATA : GT_WORDER LIKE TABLE OF GS_WORDER.



DATA : GS_DELIVERY TYPE ZEDT13_101.

DATA : GT_DELIVERY LIKE TABLE OF GS_DELIVERY.



DATA : BEGIN OF GS_WDELIVERY,

  ZICON TYPE C LENGTH 4,             "### ICON"

  ZORDNO LIKE ZEDT13_101-ZORDNO,     "####"

  ZIDCODE LIKE ZEDT13_101-ZIDCODE,   "##ID"

  ZMATNR LIKE ZEDT13_101-ZMATNR,     "####"

  ZMATNAME LIKE ZEDT13_101-ZMATNAME, "###"

  ZMTART LIKE ZEDT13_101-ZMTART,     "####"

  ZVOLUM LIKE ZEDT13_101-ZVOLUM,     "##"

  VRKME LIKE ZEDT13_101-VRKME,       "##"

  ZSLAMT LIKE ZEDT13_101-ZSLAMT,     "####"

  ZWAERS LIKE ZEDT13_101-ZWAERS,     "##"

  ZDFLAG TYPE C LENGTH 8,            "####"

  ZDGUBUN TYPE C LENGTH 6,           "#### -> ##"

  ZDDATE TYPE C LENGTH 10,           "####"

  ZRDATE TYPE C LENGTH 10,           "####"

  ZFLAG LIKE ZEDT13_101-ZFLAG,       "####"

  END OF GS_WDELIVERY.



DATA : GT_WDELIVERY LIKE TABLE OF GS_WDELIVERY.



RANGES : R_FG FOR ZEDT13_100-ZSALE_FG. "## ### ## ## ### ##### ### ##"

RANGES : R_CH FOR ZEDT13_101-ZFLAG.



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.



DATA : GC_GRID_0100 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID_0200 TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT,

       GT_FIELDCAT TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT TYPE LVC_T_SORT.



DATA : GS_VARIANT TYPE DISVARIANT.