
*&---------------------------------------------------------------------*

*&  Include           ZEDR20_PROJECT002_TOP

*&---------------------------------------------------------------------*






TABLES: ZEDT20_EKKO, ZEDT20_EKPO, ZEDT20_MARA.



" ALV ## ##

DATA: GC_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER,    " ALV### CUSTOM CONTAINER #### ##

    GC_GRID TYPE REF TO CL_GUI_ALV_GRID,    " ALV ### ALV GRID #### ##

    OK_CODE TYPE SY-UCOMM,    " TOOLBAR ## ##

    GS_FIELDCAT TYPE LVC_S_FCAT,    " ###### ###

    GT_FIELDCAT TYPE LVC_T_FCAT,    " ###### ###

    GT_SORT TYPE LVC_T_SORT,    " SORT ###

    GS_SORT TYPE LVC_S_SORT,    " SORT ###

    GS_LAYOUT TYPE LVC_S_LAYO,    " LAYOUT ###

    GS_VARIANT TYPE DISVARIANT.   " LAYOUT #### ###



DATA: GV_INDEX TYPE I VALUE 0.

DATA: GO_EVENT TYPE REF TO EVENT.

DATA: GV_LIFNAME TYPE ZEDT20_LFA1-NAME1.



DATA: BEGIN OF GS_PO,

  ZCHECK TYPE C,    " ##

  EBELP TYPE ZEDT20_EKPO-EBELP,    " ##

  MATNR TYPE ZEDT20_EKPO-MATNR,    " ####

  MAKTX TYPE ZEDT20_EKPO-MAKTX,    " ###

  MENGE TYPE ZEDT20_EKPO-MENGE,    " PO##

  BPRME TYPE ZEDT20_EKPO-BPRME,    " ##

  MEINS TYPE ZEDT20_EKPO-MEINS,    " ##

  WAERS TYPE ZEDT20_EKKO-WAERS,    " ##

  MWSKZ TYPE ZEDT20_LFM1-MWSKZ,    " ####

  PRDAT TYPE ZEDT20_EKPO-PRDAT,    " ###

  WERKS TYPE ZEDT20_EKPO-WERKS,    " ###

  LGORT TYPE ZEDT20_EKPO-LGORT,   " ####

  END OF GS_PO.

DATA: GT_PO LIKE TABLE OF GS_PO.



DATA: BEGIN OF GS_LIFNR,

  LIFNR TYPE ZEDT20_EKKO-LIFNR,

  END OF GS_LIFNR.

DATA: GT_LIFNR LIKE TABLE OF GS_LIFNR.



DATA: BEGIN OF GS_MARA.

  include structure
ZEDT20_MARA
.

  DATA: END OF GS_MARA.

DATA: GT_MARA LIKE TABLE OF GS_MARA.



DATA: BEGIN OF GS_MARD.

  include structure
ZEDT20_MARD
.

  DATA: END OF GS_MARD.

DATA: GT_MARD LIKE TABLE OF GS_MARD.



DATA: BEGIN OF GS_EKKO.

  include structure
ZEDT20_EKKO
.

  DATA: END OF GS_EKKO.

DATA: GT_EKKO LIKE TABLE OF GS_EKKO.



DATA: BEGIN OF GS_EKPO.

  include structure
ZEDT20_EKPO
.

  DATA: END OF GS_EKPO.

DATA: GT_EKPO LIKE TABLE OF GS_EKPO.



DATA: BEGIN OF GS_LFM1,

  EKORG TYPE ZEDT20_LFM1-EKORG,

  EKGRP TYPE ZEDT20_LFM1-EKGRP,

  MWSKZ TYPE ZEDT20_LFM1-MWSKZ,

  END OF GS_LFM1.

DATA: GT_LFM1 LIKE TABLE OF GS_LFM1.