
*&---------------------------------------------------------------------*

*& Report ZEDR04_046

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR04_046.



DATA : BEGIN OF GS_STUDENT,

  ZPERNR LIKE ZEDT04_001-ZPERNR,  "####

  ZCODE LIKE ZEDT04_001-ZCODE,    "####

  ZKNAME LIKE ZEDT04_001-ZKNAME,  "####

  ZENAME LIKE ZEDT04_001-ZENAME,  "####

  ZGENDER LIKE ZEDT04_001-ZGENDER,"##

  ZGNAME TYPE C LENGTH 4,  "## ## (##, ##)

  ZTEL LIKE ZEDT04_001-ZTEL,      "####

  END OF GS_STUDENT.

DATA GT_STUDENT LIKE TABLE OF GS_STUDENT.



CLEAR : GS_STUDENT, GT_STUDENT.

GS_STUDENT-ZPERNR = '0000000001'.

GS_STUDENT-ZCODE = 'SSU-01'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'DONG'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01012345678'.

APPEND GS_STUDENT TO GT_STUDENT.



CLEAR : GS_STUDENT.

GS_STUDENT-ZPERNR = '0000000002'.

GS_STUDENT-ZCODE = 'SSU-02'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'HOON'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01098765432'.

APPEND GS_STUDENT TO GT_STUDENT.



CLEAR : GS_STUDENT.

GS_STUDENT-ZPERNR = '0000000003'.

GS_STUDENT-ZCODE = 'SSU-03'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'SON'.

GS_STUDENT-ZGENDER = 'F'.

GS_STUDENT-ZTEL = '01033334444'.

APPEND GS_STUDENT TO GT_STUDENT.



CLEAR GS_STUDENT.

LOOP AT GT_STUDENT INTO GS_STUDENT.

  IF GS_STUDENT-ZGENDER = 'M'.

    GS_STUDENT-ZGNAME = '##'.

  ELSEIF GS_STUDENT-ZGENDER = 'F'.

    GS_STUDENT-ZGNAME = '##'.

  ELSE.

    GS_STUDENT-ZGNAME = '##'.

  ENDIF.



  "MODIFY GT_STUDENT FROM GS_STUDENT TRANSPORTING ZGNAME WHERE ZCODE = GS_STUDENT-ZCODE. " ####### ZGNAME ##

  MODIFY GT_STUDENT FROM GS_STUDENT INDEX SY-TABIX. " INDEX# ### # ## ## (SY-TABIX# LOOP## ###)



  CLEAR GS_STUDENT.

ENDLOOP.