
*&---------------------------------------------------------------------*

*&  Include           ZEDR20_PROJECT002_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS: S_LIFNR1 FOR ZEDT20_EKKO-LIFNR MODIF ID M2 NO INTERVALS NO-EXTENSION.   " #####

  PARAMETERS: P_BUKRS TYPE ZEDT20_EKKO-BUKRS.   " ####

  SELECT-OPTIONS: S_LIFNR2 FOR ZEDT20_EKKO-LIFNR MODIF ID M1 NO INTERVALS NO-EXTENSION.   " ###

  PARAMETERS: P_DATE TYPE ZEDT20_EKPO-PRDAT MODIF ID M1.   " ###

  PARAMETERS: P_EBELN TYPE ZEDT20_EKPO-EBELN MODIF ID M2.   " PO##

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  SELECTION-SCREEN BEGIN OF LINE.

    SELECTION-SCREEN COMMENT (5) TEXT-001 FOR FIELD P_R1.

    PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

    SELECTION-SCREEN COMMENT 20(5) TEXT-002 FOR FIELD P_R2.

    PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B2.