
*&---------------------------------------------------------------------*

*&  Include           ZEDR03_PRACTICE9_TOP

*&---------------------------------------------------------------------*




TABLES: ZEDT03_102,

        ZEDT03_103,

        ZEDT03_104,

        ZEDT03_105,

        ZEDT03_106.



" ### ##

CONSTANTS: C_X TYPE CHAR1 VALUE 'X'.



" 1# ### : ####, ###### ###

DATA : BEGIN OF GS_EMP1,

    ZCOLOR TYPE C LENGTH 4, "### ## ##

    ZPERNR LIKE ZEDT03_102-ZPERNR, "####

    ZPNAME LIKE ZEDT03_103-ZPNAME, "####

    ZDEPCODE LIKE ZEDT03_102-ZDEPCODE, "####

    ZDEPCODE_KR TYPE C LENGTH 20, "#####

    DATBI LIKE ZEDT03_106-DATBI, "####

    DATAB LIKE ZEDT03_106-DATAB, "####

    ZDEPRANK LIKE ZEDT03_102-ZDEPRANK, "####

    ZDEPRANK_KR TYPE C LENGTH 20, "#####

    ZGENDER LIKE ZEDT03_103-ZGENDER, "##

    ZGENDER_KR TYPE C LENGTH 20, "###

    ZEDATE LIKE ZEDT03_102-ZEDATE, "####

    ZADDRESS LIKE ZEDT03_103-ZADDRESS, "##

    ZQDATE LIKE ZEDT03_102-ZQDATE, "####

    ZQFLAG LIKE ZEDT03_102-ZQFLAG, "####

  END OF GS_EMP1.

DATA : GT_EMP1 LIKE TABLE OF GS_EMP1.



" 2# ### : ####

DATA : BEGIN OF GS_EMP2,

    ZPERNR LIKE ZEDT03_104-ZPERNR, "####

    ZDEPCODE LIKE ZEDT03_104-ZDEPCODE, "####

    ZDEPCODE_KR TYPE C LENGTH 20, "#####

    ZYEAR LIKE ZEDT03_104-ZYEAR, "##

    DATBI LIKE ZEDT03_104-DATBI, "####

    DATAB LIKE ZEDT03_104-DATAB, "####

    ZRANK LIKE ZEDT03_104-ZRANK, "####

  END OF GS_EMP2.

DATA : GT_EMP2 LIKE TABLE OF GS_EMP2.



" 3# ### : #### ###

DATA : BEGIN OF GS_EMP3,

    ZPERNR LIKE ZEDT03_106-ZPERNR, "####

    ZYEAR LIKE ZEDT03_106-ZYEAR, "##

    DATBI LIKE ZEDT03_106-DATBI, "####

    DATAB LIKE ZEDT03_106-DATAB, "####

    ZSALARY LIKE ZEDT03_106-ZSALARY, "####

    ZBANKCODE LIKE ZEDT03_106-ZBANKCODE, "####

    ZBANKCODE_KR TYPE C LENGTH 20, "#####

    ZACCOUNT LIKE ZEDT03_106-ZACCOUNT, "####

    ZWAERS TYPE WAERS, "##

  END OF GS_EMP3.

DATA : GT_EMP3 LIKE TABLE OF GS_EMP3.



"## ##

RANGES GR_ZDATE FOR ZEDT03_100-ZJDATE.



"### ## RANGE

RANGES : GR_ZQFLAG     FOR ZEDT03_102-ZQFLAG.



"###### ### ## ##

DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER. "## #### ##

DATA : GC_SPLITTER_MAIN TYPE REF TO CL_GUI_SPLITTER_CONTAINER. "## #### : 2# 1#

DATA : GC_SPLITTER_TOP TYPE REF TO CL_GUI_SPLITTER_CONTAINER. "## #### : 1# 2#



DATA : GC_CONTAINER_TOP TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER_BOTTOM TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER_TOP_LEFT TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER_TOP_RIGHT TYPE REF TO CL_GUI_CONTAINER.



DATA : GC_GRID_TOP_LEFT TYPE REF TO CL_GUI_ALV_GRID. " ### ## ## ##1 (# ###### ### ###!)

DATA : GC_GRID_TOP_RIGHT TYPE REF TO CL_GUI_ALV_GRID. " ### ## ## ##2

DATA : GC_GRID_BOTTOM TYPE REF TO CL_GUI_ALV_GRID. " ### ## ## ##3



DATA : GS_VARIANT TYPE DISVARIANT.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT. "## #### (## ALV# ###!)

DATA : GT_FIELDCAT1 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT2 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT3 TYPE LVC_T_FCAT.





DATA : GS_LAYOUT TYPE LVC_S_LAYO. "#### (## ALV# ###!)



DATA : GS_SORT TYPE LVC_S_SORT. "SORT (## ALV# ###!)

DATA : GT_SORT TYPE LVC_T_SORT.