
*&---------------------------------------------------------------------*

*&  Include           ZEDR03_PRACTICE9_SCR

*&---------------------------------------------------------------------*






SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

 SELECT-OPTIONS: S_ZPERNR FOR ZEDT03_102-ZPERNR.

 SELECT-OPTIONS: S_DATE   FOR ZEDT03_102-DATBI NO INTERVALS NO-EXTENSION.

 SELECT-OPTIONS: S_DEPT   FOR ZEDT03_102-ZDEPCODE NO INTERVALS NO-EXTENSION.

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS: P_CH1 AS CHECKBOX DEFAULT 'X'.

SELECTION-SCREEN END OF BLOCK B2.