
*&---------------------------------------------------------------------*

*&  Include           ZEDR20_PROJECT001_TOP

*&---------------------------------------------------------------------*




TABLES: ZEDT20_LFA1, ZEDT20_LFB1, ZEDT20_LFM1.



DATA: OK_CODE TYPE SY-UCOMM.



DATA: BEGIN OF GS_MASTER.

  include structure
ZEDT20_LFA1
.

  DATA: BUKRS TYPE ZEDT20_LFB1-BUKRS,

        AKONT TYPE ZEDT20_LFB1-AKONT,

        ZTERM TYPE ZEDT20_LFB1-ZTERM,

        EKORG TYPE ZEDT20_LFM1-EKORG,

        EKGRP TYPE ZEDT20_LFM1-EKGRP,

        WAERS TYPE ZEDT20_LFM1-WAERS,

        MWSKZ TYPE ZEDT20_LFM1-MWSKZ.

  DATA: END OF GS_MASTER.

DATA: GT_MASTER LIKE TABLE OF GS_MASTER.



DATA: BEGIN OF GS_LFA1.

  include structure
ZEDT20_LFA1
.

  DATA:END OF GS_LFA1.

DATA: GT_LFA1 LIKE TABLE OF GS_LFA1.



DATA: BEGIN OF GS_LFB1.

  include structure
ZEDT20_LFB1
.

  DATA:END OF GS_LFB1.

DATA: GT_LFB1 LIKE TABLE OF GS_LFB1.



DATA: BEGIN OF GS_LFM1.

include structure
ZEDT20_LFM1
.

  DATA:END OF GS_LFM1.

DATA: GT_LFM1 LIKE TABLE OF GS_LFM1.



DATA: GV_STCD1_TXT(8),

      GV_STCD2_TXT(8),

  GV_LIFNR TYPE ZEDT20_LFA1-LIFNR,

  GV_NAME1 TYPE ZEDT20_LFA1-NAME1,

  GV_LAND1 TYPE ZEDT20_LFA1-LAND1,

  GV_KTOKK TYPE ZEDT20_LFA1-KTOKK,

  GV_STCD1 TYPE ZEDT20_LFA1-STCD1,

  GV_STCD2 TYPE ZEDT20_LFA1-STCD2,

  GV_STRAS TYPE ZEDT20_LFA1-STRAS,

  GV_BUKRS TYPE ZEDT20_LFB1-BUKRS,

  GV_AKONT TYPE ZEDT20_LFB1-AKONT,

  GV_ZTERM TYPE ZEDT20_LFB1-ZTERM,

  GV_EKORG TYPE ZEDT20_LFM1-EKORG,

  GV_EKGRP TYPE ZEDT20_LFM1-EKGRP,

  GV_WAERS TYPE ZEDT20_LFM1-WAERS,

  GV_MWSKZ TYPE ZEDT20_LFM1-MWSKZ.