
*&---------------------------------------------------------------------*

*&  Include           ZEDR20_PROJECT001_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  PARAMETERS: P_LIFNR TYPE ZEDT20_LFA1-LIFNR VISIBLE LENGTH 10 MODIF ID M1.

  PARAMETERS: P_BUKRS TYPE ZEDT20_LFB1-BUKRS VISIBLE LENGTH 10 MODIF ID M2.

  PARAMETERS: P_KTOKK TYPE ZEDT20_LFA1-KTOKK VISIBLE LENGTH 10 MODIF ID M3.

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  SELECTION-SCREEN BEGIN OF LINE.

    SELECTION-SCREEN COMMENT (5) TEXT-001 FOR FIELD P_R1.

    PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

    SELECTION-SCREEN COMMENT 20(5) TEXT-002 FOR FIELD P_R2.

    PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B2.