
*&---------------------------------------------------------------------*

*& Report ZEDR15_017

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR15_017.



TABLES : ZEDT00_001.



DATA : BEGIN OF GS_STUDENT.

  include structure
ZEDT00_001
.

  DATA: END OF GS_STUDENT.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.






*SELECT-OPTIONS : S_ZCODE FOR ZEDT00_001-ZCODE.

*PARAMETERS : P_ZGEN LIKE ZEDT00_001-ZGENDER.



*"## ## ###

*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT00_001-ZCODE.

*SELECTION-SCREEN END OF BLOCK B1.

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : P_ZGEN LIKE ZEDT00_001-ZGENDER.

*SELECTION-SCREEN END OF BLOCK B2.

*

*SELECT * FROM ZEDT00_001

*  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

*  WHERE ZCODE IN S_ZCODE " S_ZCODE ## # ## ## # #### #### IN##

*  AND ZGENDER = P_ZGEN.

*

*IF GT_STUDENT[] IS NOT INITIAL.

*  CLEAR : GS_STUDENT.

*  LOOP AT GT_STUDENT INTO GS_STUDENT.

*    WRITE : / GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME.

*  ENDLOOP.

*ELSE.

*  WRITE : / '#####'.

*ENDIF.






"1) DEFAULT ### ##




*SELECT-OPTIONS : S_ZCODE FOR ZEDT00_001-ZCODE DEFAULT 'SSU-01' SIGN I OPTION EQ.

*"SELECT-OPTIONS : S_ZCODE FOR ZEDT00_001-ZCODE DEFAULT 'SSU-01' SIGN E OPTION EQ.

*"SELECT-OPTIONS : S_ZCODE FOR ZEDT00_001-ZCODE DEFAULT 'SSU-01' TO 'SSU-99' SIGN I OPTION BT.

*"SELECT-OPTIONS : S_ZCODE FOR ZEDT00_001-ZCODE DEFAULT 'SSU-01' TO 'SSU-99' SIGN E OPTION BT.

*PARAMETERS : P_ZGEN LIKE ZEDT00_001-ZGENDER.






"2) NO INTERVALS : #### #### ##




*SELECT-OPTIONS : S_ZCODE FOR ZEDT00_001-ZCODE DEFAULT 'SSU-01' NO INTERVALS.

*PARAMETERS : P_ZGEN LIKE ZEDT00_001-ZGENDER.



*"3) NO-EXTENSION :  MULTIPLE SELECTIONS### ##

*SELECT-OPTIONS : S_ZCODE FOR ZEDT00_001-ZCODE DEFAULT 'SSU-01' NO INTERVALS NO-EXTENSION.

*PARAMETERS : P_ZGEN LIKE ZEDT00_001-ZGENDER.



*"4) VISIBLE LENGTH : ## ##

*SELECT-OPTIONS : S_ZCODE FOR ZEDT00_001-ZCODE DEFAULT 'SSU-01' VISIBLE LENGTH 3.

*PARAMETERS : P_ZGEN LIKE ZEDT00_001-ZGENDER.



*"5) MODIF ID : #### ### ## ## ## ## ###

*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT00_001-ZCODE.

*  PARAMETERS : P_ZGEN LIKE ZEDT00_001-ZGENDER.

*SELECTION-SCREEN END OF BLOCK B1.

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : P_CH1 AS CHECKBOX DEFAULT 'X' MODIF ID M1. "### ## #### ##

*  PARAMETERS : P_CH2 AS CHECKBOX MODIF ID M2.

*SELECTION-SCREEN END OF BLOCK B2.

*

*AT SELECTION-SCREEN OUTPUT. "## ## ##

*  LOOP AT SCREEN.

*    IF SCREEN-GROUP1 = 'M2'. "## #### SCREEN## GROUP1# ##

*      "SCREEN-INPUT = '0'. "#### ## ####

*      "SCREEN-ACTIVE = '0'. "### ## ####

*      "SCREEN-REQUIRED = '1'. "### # ## ## ##

*      SCREEN-OUTPUT = '0'. "## ## ####

*      MODIFY SCREEN.

*    ENDIF.

*  ENDLOOP.






"6) USERCOMMAND : ### ## ### ## ## ####




*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT00_001-ZCODE.

*  PARAMETERS : P_ZPERNR LIKE ZEDT00_001-ZPERNR MODIF ID M1.

*  PARAMETERS : P_ZGEN LIKE ZEDT00_001-ZGENDER MODIF ID M2.

*SELECTION-SCREEN END OF BLOCK B1.

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : P_CH1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

*  PARAMETERS : P_CH2 RADIOBUTTON GROUP R1.

*SELECTION-SCREEN END OF BLOCK B2.

*

*AT SELECTION-SCREEN OUTPUT. "## ## ##

*  LOOP AT SCREEN.

*    IF SCREEN-GROUP1 = 'M2'. "## #### SCREEN## GROUP1# ##

**      IF P_R1 = 'X'.

**        SCREEN-ACTIVE = '1'.

**      ELSEIF P_R2 = 'X'.

**        SCREEN-ACTIVE = '0'.

**      ENDIF.

*      "SCREEN-INTENSIFIED = '1'.

*      "SCREEN-DISPLAY_3D = '1'.

*      SCREEN-INVISIBLE = '1'.

*    ENDIF.

*    MODIFY SCREEN.

*  ENDLOOP.






"7)SEARCH HELP

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS : S_ZCODE FOR ZEDT00_001-ZCODE.

  PARAMETERS : P_ZPERNR LIKE ZEDT00_001-ZPERNR MODIF ID M1.

  PARAMETERS : P_ZGEN LIKE ZEDT00_001-ZGENDER MATCHCODE OBJECT ZSH15_001 MODIF ID M2.

SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS : P_CH1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

  PARAMETERS : P_CH2 RADIOBUTTON GROUP R1.

SELECTION-SCREEN END OF BLOCK B2.