
*&---------------------------------------------------------------------*

*&  Include           ZMM10_FK01_TOP

*&---------------------------------------------------------------------*




TABLES: ZEDT10_LFA1, ZEDT10_LFB1, ZEDT10_LFM1.



" ACTION ### ##.

TABLES: SSCRFIELDS.



DATA: GS_LFA1 TYPE ZEDT10_LFA1,

      GS_LFB1 TYPE ZEDT10_LFB1,

      GS_LFM1 TYPE ZEDT10_LFM1.



DATA:GV_LIFNR TYPE ZEDT10_LFA1-LIFNR,

     GV_NAME1 TYPE ZEDT10_LFA1-NAME1,

     GV_LAND1 TYPE ZEDT10_LFA1-LAND1,

     GV_KTOKK TYPE ZEDT10_LFA1-KTOKK,

     GV_STCD1 TYPE ZEDT10_LFA1-STCD1,

     GV_STCD2 TYPE ZEDT10_LFA1-STCD2,

     GV_STRAS TYPE ZEDT10_LFA1-STRAS.



DATA: GV_BUKRS TYPE ZEDT10_LFB1-BUKRS,

      GV_AKONT TYPE ZEDT10_LFB1-AKONT,

      GV_ZTERM TYPE ZEDT10_LFB1-ZTERM.



DATA: GV_EKORG TYPE ZEDT10_LFM1-EKORG,

      GV_EKGRP TYPE ZEDT10_LFM1-EKGRP,

      GV_WAERS TYPE ZEDT10_LFM1-WAERS,

      GV_MWSKZ TYPE ZEDT10_LFM1-MWSKZ.





DATA:    BEGIN OF GS_VENDER.

    include structure
ZEDT10_LFA1
.

DATA: BUKRS TYPE ZEDT10_LFB1-BUKRS,

      AKONT TYPE ZEDT10_LFB1-AKONT,

      ZTERM TYPE ZEDT10_LFB1-ZTERM.

DATA: EKORG TYPE ZEDT10_LFM1-EKORG,

      EKGRP TYPE ZEDT10_LFM1-EKGRP,

      WAERS TYPE ZEDT10_LFM1-WAERS,

      MWSKZ TYPE ZEDT10_LFM1-MWSKZ.

DATA: LOEVM TYPE LOEVM.

DATA: END OF GS_VENDER.



DATA: OK_CODE TYPE SY-UCOMM.