
*&---------------------------------------------------------------------*

*& Report ZEDR21_011

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR21_011 MESSAGE-ID ZMED21.

"PARAMETERS #### ## ## ## ## ### ## #






*PARAMETERS : P_ZCODE LIKE ZEDT21_001-ZCODE21.

*PARAMETERS : P_ZPERNR TYPE C LENGTH 10. " ## ## ##

*PARAMETERS : P_ZNUM TYPE P DECIMALS 2.

*PARAMETERS : P_ZGEN LIKE ZEDT21_001-ZGUBUN21 DEFAULT 'M'. "# ##



*PARAMETERS : P_ZCODE LIKE ZEDT21_001-ZCODE21 LOWER CASE. " ####

*PARAMETERS : Z_PERNR TYPE C LENGTH 10.

*PARAMETERS : P_ZGEN LIKE ZEDT21_001-ZGUBUN21 DEFAULT 'M'.



*PARAMETERS : P_ZCODE LIKE ZEDT21_001-ZCODE21 OBLIGATORY. "#### ## ## # ##

*PARAMETERS : P_ZPERNR TYPE C LENGTH 10 NO-DISPLAY. " ### #### ##

*PARAMETERS : P_ZGEN LIKE ZEDT21_001-ZGUBUN21 DEFAULT 'M'.



*PARAMETERS : P_ZCODE LIKE ZEDT21_001-ZCODE21 VISIBLE LENGTH 5. "### ### #### ## ##

*PARAMETERS : P_ZPERNR TYPE C LENGTH 10 NO-DISPLAY. " ### #### ##

*PARAMETERS : P_ZGEN LIKE ZEDT21_001-ZGUBUN21 DEFAULT 'M'.



*PARAMETERS : P_ZCODE LIKE ZEDT21_001-ZCODE21.

*PARAMETERS : P_ZPERNR TYPE C LENGTH 10 NO-DISPLAY.

*PARAMETERS : P_ZGEN LIKE ZEDT21_001-ZGUBUN21 DEFAULT 'M'.

*PARAMETERS : Z_CHECK AS CHECKBOX DEFAULT 'X'.

*

*IF Z_CHECK = 'X'.

*  WRITE :/ '#### ##'.

*ELSE.

*  WRITE :/ '## ##'.

*  ENDIF.



*PARAMETERS : P_ZCODE LIKE ZEDT21_001-ZCODE21.

*PARAMETERS : P_ZPERNR TYPE C LENGTH 10 NO-DISPLAY.

*PARAMETERS : P_ZGEN LIKE ZEDT21_001-ZGUBUN21 DEFAULT 'M'.

*PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'.

*PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

*PARAMETERS : Z_CHECK AS CHECKBOX DEFAULT 'X'.

*

*IF P_R1 = 'X'.

*  WRITE :/ '#### ##'.

*ELSEIF P_R2 = 'X'.

*  WRITE :/ '## ##'.

*  ENDIF.






"----BLOCK## #### ###




*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  PARAMETERS : P_ZCODE LIKE ZEDT21_001-ZCODE21.

*  PARAMETERS : P_ZPERNR TYPE C LENGTH  10 NO-DISPLAY.

*  PARAMETERS : P_ZGEN LIKE ZEDT21_001-ZGUBUN21 DEFAULT 'M'.

*  SELECTION-SCREEN END OF BLOCK B1.

*

*  SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'.

*  PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

*  PARAMETERS : Z_CHECK AS CHECKBOX DEFAULT 'X'.

*  SELECTION-SCREEN END OF BLOCK B2.






"RADIO BUTTON ## ## ##




*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  PARAMETERS : P_ZCODE LIKE ZEDT21_001-ZCODE21.

*  PARAMETERS : P_ZPERNR TYPE C LENGTH  10 NO-DISPLAY.

*  PARAMETERS : P_ZGEN LIKE ZEDT21_001-ZGUBUN21 DEFAULT 'M'.

*  SELECTION-SCREEN END OF BLOCK B1.

*

*  SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*

*  SELECTION-SCREEN BEGIN OF LINE.

*  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'.

*  SELECTION-SCREEN POSITION 3. "POSITION  ## ##

*  SELECTION-SCREEN COMMENT (10) FOR FIELD P_R1.  "### ##

*  PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

*  SELECTION-SCREEN POSITION 20.

*  SELECTION-SCREEN COMMENT (10) FOR FIELD P_R2.

*  SELECTION-SCREEN END OF LINE.

*  SELECTION-SCREEN END OF BLOCK B2.






"PARAMETERS# DB ## #




*DATA : GT_STUDENT LIKE TABLE OF ZEDT21_001.

*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  PARAMETERS : P_ZCODE LIKE ZEDT21_001-ZCODE21.

*  PARAMETERS : P_ZPERNR TYPE C LENGTH  10 NO-DISPLAY.

*  PARAMETERS : P_ZGEN LIKE ZEDT21_001-ZGUBUN21 DEFAULT 'M'.

*  SELECTION-SCREEN END OF BLOCK B1.

*

*  SELECT * FROM ZEDT21_001

*    INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

*    WHERE ZCODE21 = P_ZCODE

*    AND ZGUBUN21 = P_ZGEN.

*

*    IF GT_STUDENT[] IS NOT INITIAL.

*      WRITE :/ '### ##'.

*    ELSE.

*      WRITE :/ '### ##'.

*    ENDIF.






"SELECT-OPTION #






*TABLES : ZEDT21_001.

*

*DATA : BEGIN OF GS_STUDENT.

*  INCLUDE TYPE ZEDT21_001.

*  DATA : END OF GS_STUDENT.

*

* DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

*

*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

* SELECT-OPTIONS : S_ZCODE FOR ZEDT21_001-ZCODE21 DEFAULT 'SSU-01'. "DEFAULT ### ## OR SIGN I OPTION EQ

*SELECTION-SCREEN END OF BLOCK B1.

*

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

* PARAMETERS : P_ZGEN LIKE ZEDT21_001-ZGUBUN21.

*SELECTION-SCREEN END OF BLOCK B2.

*

*SELECT * FROM ZEDT21_001

*  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

*  WHERE ZCODE21 IN S_ZCODE

*  AND ZGUBUN21 = P_ZGEN.

*

*IF GT_STUDENT[] IS NOT INITIAL.

*  CLEAR : GS_STUDENT.

*  LOOP AT GT_STUDENT INTO GS_STUDENT.

*    WRITE :/ GS_STUDENT-ZCODE21, GS_STUDENT-ZKNAME21.

*    ENDLOOP.

*    ELSE.

*      WRITE :/ 'NO DATA'.

*      ENDIF.









*TABLES : ZEDT21_001.

*

*DATA : BEGIN OF GS_STUDENT.

*  INCLUDE TYPE ZEDT21_001.

*  DATA : END OF GS_STUDENT.

*

* DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

*

*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

* SELECT-OPTIONS : S_ZCODE FOR ZEDT21_001-ZCODE21 DEFAULT 'SSU-01' TO 'SSU-99' SIGN I OPTION BT. "DEFAULT ### ## OR SIGN I OPTION EQ

*SELECTION-SCREEN END OF BLOCK B1.

*

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*

* PARAMETERS : P_ZGEN LIKE ZEDT21_001-ZGUBUN21.

*SELECTION-SCREEN END OF BLOCK B2.

*

*SELECT * FROM ZEDT21_001

*  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

*  WHERE ZCODE21 IN S_ZCODE

*  AND ZGUBUN21 = P_ZGEN.

*

*IF GT_STUDENT[] IS NOT INITIAL.

*  CLEAR : GS_STUDENT.

*  LOOP AT GT_STUDENT INTO GS_STUDENT.

*    WRITE :/ GS_STUDENT-ZCODE21, GS_STUDENT-ZKNAME21.

*    ENDLOOP.

*    ELSE.

*      WRITE :/ 'NO DATA'.

*      ENDIF.









*TABLES : ZEDT21_001.

*

*DATA : BEGIN OF GS_STUDENT.

*  INCLUDE TYPE ZEDT21_001.

*  DATA : END OF GS_STUDENT.

*

* DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

*

*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  "MULTIPLE SELECTION ### ##

* SELECT-OPTIONS : S_ZCODE FOR ZEDT21_001-ZCODE21 DEFAULT 'SSU-01' NO INTERVALS NO-EXTENSION.

*SELECTION-SCREEN END OF BLOCK B1.

*

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*

* PARAMETERS : P_ZGEN LIKE ZEDT21_001-ZGUBUN21.

*SELECTION-SCREEN END OF BLOCK B2.

*

*SELECT * FROM ZEDT21_001

*  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

*  WHERE ZCODE21 IN S_ZCODE

*  AND ZGUBUN21 = P_ZGEN.

*

*IF GT_STUDENT[] IS NOT INITIAL.

*  CLEAR : GS_STUDENT.

*  LOOP AT GT_STUDENT INTO GS_STUDENT.

*    WRITE :/ GS_STUDENT-ZCODE21, GS_STUDENT-ZKNAME21.

*    ENDLOOP.

*    ELSE.

*      WRITE :/ 'NO DATA'.

*      ENDIF.





*TABLES : ZEDT21_001.

*

*DATA : BEGIN OF GS_STUDENT.

*  INCLUDE TYPE ZEDT21_001.

*  DATA : END OF GS_STUDENT.

*

* DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

*

*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  "MULTIPLE SELECTION ### ##

* SELECT-OPTIONS : S_ZCODE FOR ZEDT21_001-ZCODE21.

*  PARAMETERS : P_ZGEN LIKE ZEDT21_001-ZGUBUN21.

*SELECTION-SCREEN END OF BLOCK B1.

*

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*PARAMETERS : P_CH1 AS CHECKBOX DEFAULT 'X' MODIF ID M1. "###

*PARAMETERS : P_CH2 AS CHECKBOX MODIF ID M2. " ## ### ###

*SELECTION-SCREEN END OF BLOCK B2.

*

*AT SELECTION-SCREEN OUTPUT.

*  LOOP AT SCREEN.

*    IF SCREEN-GROUP1 = 'M2'.

*      SCREEN-OUTPUT = '0'. "ACTIVE# #### , SCREEN-INPUT## #### , REQUIRED# ## ##,

*      "OUTPUT## ## ## ## ##

*      MODIFY SCREEN.

*      ENDIF.

*      ENDLOOP.

*

*SELECT * FROM ZEDT21_001

*  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

*  WHERE ZCODE21 IN S_ZCODE

*  AND ZGUBUN21 = P_ZGEN.

*

*IF GT_STUDENT[] IS NOT INITIAL.

*  CLEAR : GS_STUDENT.

*  LOOP AT GT_STUDENT INTO GS_STUDENT.

*    WRITE :/ GS_STUDENT-ZCODE21, GS_STUDENT-ZKNAME21.

*    ENDLOOP.

*    ELSE.

*      WRITE :/ 'NO DATA'.

*      ENDIF.








TABLES : ZEDT21_001.



DATA : BEGIN OF GS_STUDENT.

  include structure
ZEDT21_001
.

  DATA : END OF GS_STUDENT.



 DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.



SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  "MULTIPLE SELECTION ### ##

 SELECT-OPTIONS : S_ZCODE FOR ZEDT21_001-ZCODE21.

  PARAMETERS : Z_PERNR LIKE ZEDT21_001-ZPERNR21 MODIF ID M1.

  PARAMETERS : P_ZGEN LIKE ZEDT21_001-ZGUBUN21 MATCHCODE OBJECT ZSH21_001 MODIF ID M2. "MATCHCODE# ### #### SEARCH HELP## ### ##

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'. "### #### ### UC ## UC ### #####

PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

SELECTION-SCREEN END OF BLOCK B2.



IF S_ZCODE IS INITIAL.

  MESSAGE I000.

  ENDIF.










*AT SELECTION-SCREEN OUTPUT.

*  LOOP AT SCREEN.

*    IF SCREEN-GROUP1 = 'M2'.

*      SCREEN-INTENSIFIED ='1'. "## ## ### 1# ###

*      SCREEN-DISPLAY_3D = '1'. " ### ### ##

**      SCREEN-INVISIBLE = '1'. "#### ##

*      IF P_R1 = 'X'.

*        SCREEN-ACTIVE = '1'.

*      ELSEIF P_R2 = 'X'.

*        SCREEN-ACTIVE = '0'.

*        ENDIF.

*        ENDIF.

*         "ACTIVE# #### , SCREEN-INPUT## #### , REQUIRED# ## ##,

*      "OUTPUT## ## ## ## ##

*      MODIFY SCREEN.

*      ENDLOOP.



*

*SELECT * FROM ZEDT21_001

*  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

*  WHERE ZCODE21 IN S_ZCODE

*  AND ZGUBUN21 = P_ZGEN.

*

*IF GT_STUDENT[] IS NOT INITIAL.

*  CLEAR : GS_STUDENT.

*  LOOP AT GT_STUDENT INTO GS_STUDENT.

*    WRITE :/ GS_STUDENT-ZCODE21, GS_STUDENT-ZKNAME21.

*    ENDLOOP.

*    ELSE.

*      WRITE :/ 'NO DATA'.

*      ENDIF.