
*&---------------------------------------------------------------------*

*&  Include           ZMM24_004_TOP

*&---------------------------------------------------------------------*






TABLES : ZRBKP24. "##-##

TABLES : ZRSEG24. "##-###

TABLES : ZEKKO24. "####-##

TABLES : ZEKPO24. "####-###



TYPE-POOLS: ICON.



"## ##

CONSTANTS : C_TAX_V1 TYPE P DECIMALS 2 VALUE '0.10',

            C_TAX_V2 TYPE P DECIMALS 2 VALUE '0.00',

            C_TAX_V3 TYPE P DECIMALS 2 VALUE '0.00',

            C_TAX_V4 TYPE P DECIMALS 2 VALUE '0.10',

            C_TAX_V5 TYPE P DECIMALS 2 VALUE '0.10'.



"#####

DATA : GV_LEFT_MONEY TYPE WRBTR,

       GV_SIGNAL TYPE ICON_D VALUE ICON_LED_RED.



"### ##

DATA : GO_EVENT TYPE REF TO EVENT,

       GY_DYNNR TYPE SY-DYNNR VALUE '0110'. "SUB-SCREEN ##





"[100# ###]

DATA : GC_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,

       GC_GRID TYPE REF TO CL_GUI_ALV_GRID.



"[200# ## ## : TREE]

DATA : GC_CON_TREE TYPE REF TO CL_GUI_CUSTOM_CONTAINER, "### ####

       GO_TREE TYPE REF TO CL_GUI_SIMPLE_TREE.  "## ##



"[200# ## ## : ALV]

DATA : GC_CONTAINER_210 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,

       GC_GRID_210 TYPE REF TO CL_GUI_ALV_GRID.



"[##]

DATA : GS_FC TYPE LVC_S_FCAT,

       GT_FC TYPE LVC_T_FCAT.



"####

CONTROLS: TAB_INPUT TYPE TABSTRIP.



"## ## ##

DATA : BEGIN OF GS_RBKP,

  BELNR LIKE ZRBKP24-BELNR, "######

  GJAHR LIKE ZRBKP24-GJAHR, "####

  BLART LIKE ZRBKP24-BLART, "####

  BLDAT LIKE ZRBKP24-BLDAT, "###

  BUDAT LIKE ZRBKP24-BUDAT, "###

  BUKRS LIKE ZRBKP24-BUKRS, "####

  LIFNR LIKE ZRBKP24-LIFNR, "### (####)

  WAERS LIKE ZRBKP24-WAERS, "###

  ZTERM LIKE ZRBKP24-ZTERM, "####

  BKTXT LIKE ZRBKP24-BKTXT, "#####

  XMWST LIKE ZRBKP24-XMWST, "## ## ## (####)

  MWSKZ LIKE ZRBKP24-MWSKZ, "## ##

  WMWST LIKE ZRBKP24-WMWST, "##

  RMWWR LIKE ZRBKP24-RMWWR, "# ## ## (## ###)

  STBLG LIKE ZRBKP24-STBLG, "## (####)

  STJAH LIKE ZRBKP24-STJAH, "## (##)

  RBSTAT LIKE ZRBKP24-RBSTAT,"## ##

  XBLNR LIKE ZRBKP24-XBLNR, "## ## ##

  END OF GS_RBKP.

DATA : GT_RBKP LIKE TABLE OF GS_RBKP.



"## ## ###

DATA : BEGIN OF GS_RSEG,

  LOEKZ LIKE ZRSEG24-LOEKZ, "## ###

  STATUS_ICON TYPE C LENGTH 4, "###

  BELNR LIKE ZRSEG24-BELNR, "######

  GJAHR LIKE ZRSEG24-GJAHR, "####

  BUZEI LIKE ZRSEG24-BUZEI, "#### ##

  EBELN LIKE ZRSEG24-EBELN, "#### ##

  EBELP LIKE ZRSEG24-EBELP, "#### ##

  MATNR LIKE ZRSEG24-MATNR, "## ##

  TXZ01 LIKE ZRSEG24-TXZ01, "## ## (MAKTX# ##)

  WERKS LIKE ZRSEG24-WERKS, "###

  WRBTR LIKE ZRSEG24-WRBTR, "####

  MENGE LIKE ZRSEG24-MENGE, "##

  BSTME LIKE ZRSEG24-BSTME, "## (## ## / ## ##)

  MWSKZ LIKE ZRSEG24-MWSKZ, "## ##

  WMWST LIKE ZRSEG24-WMWST, "##

  SGTXT LIKE ZRSEG24-SGTXT, "###

  WAERS LIKE ZRSEG24-WAERS, "# ##

  MEINS LIKE ZRSEG24-MEINS, "## ##

  END OF GS_RSEG.

DATA : GT_RSEG LIKE TABLE OF GS_RSEG.



"#### ##

DATA : BEGIN OF GS_EKKO,

  EBELN LIKE ZEKKO24-EBELN, "#### ##

  BUKRS LIKE ZEKKO24-BUKRS, "####

  EKGRP LIKE ZEKKO24-EKGRP, "####

  EKORG LIKE ZEKKO24-EKORG, "####

  LIFNR LIKE ZEKKO24-LIFNR, "###

  BEDAT LIKE ZEKKO24-BEDAT, "###

  WAERS LIKE ZEKKO24-WAERS, "##

  END OF GS_EKKO.



"#### ###

DATA : BEGIN OF GS_EKPO,

  EBELN LIKE ZEKPO24-EBELN, "#### ##

  EBELP LIKE ZEKPO24-EBELP, "##

  MWSKZ LIKE ZEKPO24-MWSKZ, "####

  MATNR LIKE ZEKPO24-MATNR, "####

  MAKTX LIKE ZEKPO24-MAKTX, "###

  MENGE LIKE ZEKPO24-MENGE, "##

  MEINS LIKE ZEKPO24-MEINS, "##

  BPRME LIKE ZEKPO24-BPRME, "##2

  PRDAT LIKE ZEKPO24-PRDAT, "###

  WERKS LIKE ZEKPO24-WERKS, "###

  LGORT LIKE ZEKPO24-LGORT, "####

  STPRS LIKE ZEKPO24-STPRS, "##

  WEMNG LIKE ZEKPO24-WEMNG, "## (## ## ###)

  REMNG LIKE ZEKPO24-REMNG, "## ## ##

  END OF GS_EKPO.

DATA : GT_EKPO LIKE TABLE OF GS_EKPO.



"### ### (ALV ###)

DATA : BEGIN OF GS_ITEM,

  CHECK  TYPE C,              "## ### ####

  BELNR LIKE ZRBKP24-BELNR, "######

  GJAHR LIKE ZRBKP24-GJAHR, "####

  BUZEI  LIKE ZRSEG24-BUZEI,  "## ###

  EBELN  LIKE ZRSEG24-EBELN,  "PO##

  EBELP  LIKE ZRSEG24-EBELP,  "PO# ## ##

  MATNR  LIKE ZRSEG24-MATNR,  "####

  TXZ01  LIKE ZRSEG24-TXZ01,  "####

  WERKS  LIKE ZRSEG24-WERKS,  "###

  WRBTR  LIKE ZRSEG24-WRBTR,  "#### (## x ##)

  STPRS  LIKE ZEKPO24-STPRS,  "##

  WAERS  LIKE ZEKKO24-WAERS,  "##

  MENGE  LIKE ZRSEG24-MENGE,  "## ## ##

  WEMNG  LIKE ZEKPO24-WEMNG,  "## ##

  REMNG  LIKE ZEKPO24-REMNG,  "## ## ##

  OPEN_QTY LIKE ZEKPO24-MENGE,"## ## ##

  IR_QTY LIKE ZEKPO24-REMNG, "## ## ##

  MEINS  LIKE ZEKPO24-MEINS,  "##

  BSTME  LIKE ZRSEG24-BSTME,  "##

  MWSKZ  LIKE ZRSEG24-MWSKZ,  "####

  WMWST  LIKE ZRSEG24-WMWST,  "##

  DMBTR  LIKE BSIK-DMBTR,     "## ## (### + ##)

  SGTXT  LIKE ZRSEG24-SGTXT,  "###

  END OF GS_ITEM.

DATA : GT_ITEM LIKE TABLE OF GS_ITEM.