
*&---------------------------------------------------------------------*

*&  Include           ZMM21_002_SCR

*&---------------------------------------------------------------------*






SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  PARAMETERS : P_BUKRS TYPE ZEKKO21-BUKRS MODIF ID ALL. "####

  PARAMETERS : P_LIFNR TYPE ZEKKO21-LIFNR MODIF ID ALL. "###

  PARAMETERS : P_BEDAT TYPE ZEKKO21-BEDAT MODIF ID M1. "###

  PARAMETERS : P_EBELN TYPE ZEKPO21-EBELN MODIF ID M2. "######

  SELECTION-SCREEN END OF BLOCK B1.





SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  SELECTION-SCREEN BEGIN OF LINE.

    "## #####

    PARAMETERS : P_RAD1 RADIOBUTTON GROUP RB1 DEFAULT 'X' USER-COMMAND UC1.

    SELECTION-SCREEN COMMENT (10) FOR FIELD P_RAD1.

    "## #####

    PARAMETERS : P_RAD2 RADIOBUTTON GROUP RB1.

    SELECTION-SCREEN COMMENT (10) FOR FIELD P_RAD2.

    SELECTION-SCREEN END OF LINE.



SELECTION-SCREEN END OF BLOCK B2.