
*&---------------------------------------------------------------------*

*&  Include           ZEDR09_PRACTICE009_TOP

*&---------------------------------------------------------------------*






"#### (102,103), ####(106), ####(104) ### ##

TABLES : ZEDT09_102, ZEDT09_103, ZEDT09_106, ZEDT09_104.



"##

CONSTANTS : C_X TYPE C VALUE 'X'.



"range ##

RANGES : GR_QFLAG FOR ZEDT09_102-ZQFLAG. "####



"### OKCODE

DATA : OK_CODE TYPE SY-UCOMM.



"###### - 1# ### (####, ######) , alv###

DATA : BEGIN OF GS_EMP,

  ZPERNR LIKE ZEDT09_102-ZPERNR,    "####

  ZPNAME LIKE ZEDT09_103-ZPNAME,    "####

  ZDEPCODE LIKE ZEDT09_102-ZDEPCODE,  "####

  DATBI LIKE ZEDT09_102-DATBI,       "####

  DATAB LIKE ZEDT09_102-DATAB,       "####

  ZDEPRANK LIKE ZEDT09_102-ZDEPRANK,  "####

  ZGENDER LIKE ZEDT09_103-ZGENDER,    "##

  ZEDATE LIKE ZEDT09_102-ZEDATE,      "####

  ZADDRESS LIKE ZEDT09_103-ZADDRESS,   "##

  ZQDATE LIKE ZEDT09_102-ZQDATE,      "####

  ZQFLAG LIKE ZEDT09_102-ZQFLAG,      "####

END OF GS_EMP.

DATA : GT_EMP LIKE TABLE OF GS_EMP.



DATA : BEGIN OF GS_EMP_ALV,

  ZCOLOR TYPE C LENGTH 4,           "### ##

  ZPERNR LIKE ZEDT09_102-ZPERNR,    "####

  ZPNAME LIKE ZEDT09_103-ZPNAME,    "####

  ZDEPCODE_NAME TYPE C LENGTH 10,   "###

  DATBI LIKE ZEDT09_102-DATBI,       "####

  DATAB LIKE ZEDT09_102-DATAB,       "####

  ZDEPRANK_NAME TYPE C LENGTH 10,    "#####

  ZGENDER_NAME TYPE C LENGTH 10,     "####

  ZEDATE LIKE ZEDT09_102-ZEDATE,      "####

  ZADDRESS LIKE ZEDT09_103-ZADDRESS,   "##

  ZQDATE LIKE ZEDT09_102-ZQDATE,      "####

  ZQFLAG LIKE ZEDT09_102-ZQFLAG,      "####

END OF GS_EMP_ALV.

DATA : GT_EMP_ALV LIKE TABLE OF GS_EMP_ALV.





"###### - 2# ### (####), alv ###

DATA : BEGIN OF GS_ASSESS,

  ZPERNR LIKE ZEDT09_104-ZPERNR,    "####

  ZDEPCODE LIKE ZEDT09_104-ZDEPCODE,  "####

  ZYEAR LIKE ZEDT09_104-ZYEAR,       "##

  DATBI LIKE ZEDT09_104-DATBI,       "####

  DATAB LIKE ZEDT09_104-DATAB,       "####

  ZRANK LIKE ZEDT09_104-ZRANK,       "####

END OF GS_ASSESS.

DATA : GT_ASSESS LIKE TABLE OF GS_ASSESS.



DATA : BEGIN OF GS_ASSESS_ALV,

  ZPERNR LIKE ZEDT09_104-ZPERNR,    "####

  ZDEPCODE_NAME TYPE C LENGTH 10,   "###

  ZYEAR LIKE ZEDT09_104-ZYEAR,       "##

  DATBI LIKE ZEDT09_104-DATBI,       "####

  DATAB LIKE ZEDT09_104-DATAB,       "####

  ZRANK LIKE ZEDT09_104-ZRANK,       "####

END OF GS_ASSESS_ALV.

DATA : GT_ASSESS_ALV LIKE TABLE OF GS_ASSESS_ALV.





"###### - 3# ### (####), alv ###

DATA : BEGIN OF GS_SALARY,

  ZPERNR LIKE ZEDT09_106-ZPERNR,    "####

  ZYEAR LIKE ZEDT09_106-ZYEAR,      "##

  DATBI LIKE ZEDT09_106-DATBI,      "####

  DATAB LIKE ZEDT09_106-DATAB,      "####

  ZSALARY LIKE ZEDT09_106-ZSALARY,   "####

  ZBANKCODE LIKE ZEDT09_106-ZBANKCODE,  "####

  ZACCOUNT LIKE ZEDT09_106-ZACCOUNT,   "####

END OF GS_SALARY.

DATA : GT_SALARY LIKE TABLE OF GS_SALARY.



DATA : BEGIN OF GS_SALARY_ALV,

  ZPERNR LIKE ZEDT09_106-ZPERNR,    "####

  ZYEAR LIKE ZEDT09_106-ZYEAR,      "##

  DATBI LIKE ZEDT09_106-DATBI,      "####

  DATAB LIKE ZEDT09_106-DATAB,      "####

  ZSALARY LIKE ZEDT09_106-ZSALARY,   "####

  ZWAERS TYPE WAERS,                 "##

  ZBANKCODE_NAME TYPE C LENGTH 20,    "####

  ZACCOUNT LIKE ZEDT09_106-ZACCOUNt,   "####

END OF GS_SALARY_ALV.

DATA : GT_SALARY_ALV LIKE TABLE OF GS_SALARY_ALV.



"docking ####

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.



"splitter ####

DATA : GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA : GC_SPLITTER_TOP TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



"####

DATA : GC_CON_TOP TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CON_BOTTOM TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CON_LEFT TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CON_RIGHT TYPE REF TO CL_GUI_CONTAINER.



"grid ##

DATA : GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID.





"######, ####, ## ####, #### ##

DATA : GS_FIELDCAT TYPE LVC_S_FCAT,

       GT_FIELDCAT1 TYPE LVC_T_FCAT,

       GT_FIELDCAT2 TYPE LVC_T_FCAT,

       GT_FIELDCAT3 TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.

DATA : GS_VARIANT TYPE DISVARIANT.



DATA : GS_SORT TYPE LVC_S_SORT,

       GT_SORT TYPE LVC_T_SORT.