
*&---------------------------------------------------------------------*

*&  Include           ZMMR25_001_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.

  PARAMETERS : P_LIFNR LIKE ZEDT25_LFA1-LIFNR MODIF ID M2.

  PARAMETERS : P_BUKRS TYPE ZEDT25_LFB1-BUKRS.

  PARAMETERS : P_KTOKK LIKE ZEDT25_LFA1-KTOKK MODIF ID M1.

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-002.

  SELECTION-SCREEN BEGIN OF LINE.

  SELECTION-SCREEN COMMENT (5) TEXT-003 FOR FIELD P_CRE.

  PARAMETERS : P_CRE RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

  SELECTION-SCREEN COMMENT 20(5) TEXT-004 FOR FIELD P_VIEW.

  PARAMETERS : P_VIEW RADIOBUTTON GROUP R1.

  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B2.