
*&---------------------------------------------------------------------*

*&  Include           ZEDR06_PRACTICE009_TOP

*&---------------------------------------------------------------------*






TABLES : ZEDT06_102. "#######

TABLES : ZEDT06_103. "####-####

TABLES : ZEDT06_104. "####

TABLES : ZEDT06_106. "####



CONSTANTS C_X TYPE C VALUE 'X'.

CONSTANTS C_DOT TYPE C VALUE '.'.



RANGES R_ZQFLAG FOR ZEDT06_102-ZQFLAG.



DATA : BEGIN OF GS_EMP_INFO, " #### ###

  ZPERNR LIKE ZEDT06_102-ZPERNR,  " ####

  ZDEPCODE LIKE ZEDT06_102-ZDEPCODE, " ####

  DATBI LIKE ZEDT06_102-DATBI,  " ####_FR

  DATAB LIKE ZEDT06_102-DATAB, "####_TO

  ZDEPRANK LIKE ZEDT06_102-ZDEPRANK, " ####

  ZEDATE LIKE ZEDT06_102-ZEDATE,  " ####

  ZQDATE LIKE ZEDT06_102-ZQDATE,  " ####

  ZQFLAG LIKE ZEDT06_102-ZQFLAG,  " ####

  ZPNAME LIKE ZEDT06_103-ZPNAME,  " ####

  ZGENDER LIKE ZEDT06_103-ZGENDER,  " ##

  ZADDRESS LIKE ZEDT06_103-ZADDRESS,  " ##

  END OF GS_EMP_INFO.

DATA : GT_EMP_INFO LIKE TABLE OF GS_EMP_INFO.



DATA : BEGIN OF GS_EMP_INFO_ALV, " #### ### AVL ###

  ICON TYPE C LENGTH 4, " ###

  ZPERNR LIKE ZEDT06_102-ZDEPCODE, " ####

  ZPNAME LIKE ZEDT06_103-ZPNAME, " ##

  ZDEPCODE_NAME TYPE C LENGTH 10," ##(#)

  DATBI LIKE ZEDT06_102-DATBI, " ####

  DATAB LIKE ZEDT06_102-DATAB, " ####

  ZDEPRANK_NAME TYPE C LENGTH 10, " ##(#)

  ZGENDER_NAME TYPE C LENGTH 10, " ##(#)

  ZEDATE LIKE ZEDT06_102-ZEDATE, " ####

  ZADDRESS LIKE ZEDT06_103-ZADDRESS, " ##

  ZQDATE LIKE ZEDT06_102-ZQDATE, " ####

  ZQFLAG LIKE ZEDT06_102-ZQFLAG, " ####

  END OF GS_EMP_INFO_ALV.

DATA : GT_EMP_INFO_ALV LIKE TABLE OF GS_EMP_INFO_ALV.





DATA : BEGIN OF GS_EMP_EVALUATE, " ####

  ZPERNR LIKE ZEDT06_104-ZPERNR,      " ####

  ZDEPCODE LIKE ZEDT06_104-ZDEPCODE,  " ##

  ZYEAR LIKE ZEDT06_104-ZYEAR,        " ##

  DATBI LIKE ZEDT06_104-DATBI,        " ####

  DATAB LIKE ZEDT06_104-DATAB,        " ####

  ZRANK LIKE ZEDT06_104-ZRANK,        " ##

  END OF GS_EMP_EVALUATE.

DATA : GT_EMP_EVALUATE LIKE TABLE OF GS_EMP_EVALUATE.



DATA : BEGIN OF GS_EMP_EVALUATE_ALV, " #### AVL ###

  ZPERNR LIKE ZEDT06_104-ZPERNR,  " ####

  ZDEPCODE_NAME TYPE C LENGTH 10, " ##(#)

  ZYEAR LIKE ZEDT06_104-ZYEAR,    " ##

  DATBI LIKE ZEDT06_104-DATBI,    " ####

  DATAB LIKE ZEDT06_104-DATAB,    " ####

  ZRANK LIKE ZEDT06_104-ZRANK,    " ##

  END OF GS_EMP_EVALUATE_ALV.

DATA : GT_EMP_EVALUATE_ALV LIKE TABLE OF GS_EMP_EVALUATE_ALV.





DATA : BEGIN OF GS_EMP_SALARY,  " ####

  ZPERNR TYPE ZEDT06_106-ZPERNR,  " ####

  ZYEAR TYPE ZEDT06_106-ZYEAR,    " ####

  DATBI TYPE ZEDT06_106-DATBI,    " ####

  DATAB TYPE ZEDT06_106-DATAB,    " ####

  ZSALARY TYPE ZEDT06_106-ZSALARY," ####

  ZBANKCODE TYPE ZEDT06_106-ZBANKCODE,  " ####

  ZACCOUNT TYPE ZEDT06_106-ZACCOUNT,  " ####

  END OF GS_EMP_SALARY.

DATA : GT_EMP_SALARY LIKE TABLE OF GS_EMP_SALARY.



DATA : BEGIN OF GS_EMP_SALARY_ALV,  " #### ### ALV

  ZPERNR TYPE ZEDT06_106-ZPERNR,  " ####

  ZYEAR TYPE ZEDT06_106-ZYEAR,    " ####

  DATBI TYPE ZEDT06_106-DATBI,    " ####

  DATAB TYPE ZEDT06_106-DATAB,    " ####

  ZSALARY TYPE ZEDT06_106-ZSALARY," ####

  ZBANKCODE_NAME TYPE C LENGTH 10,  " ####(#)

  ZACCOUNT TYPE ZEDT06_106-ZACCOUNT,  " ####

  END OF GS_EMP_SALARY_ALV.

DATA : GT_EMP_SALARY_ALV LIKE TABLE OF GS_EMP_SALARY_ALV.



DATA : OK_CODE TYPE SY-UCOMM.



" ## #### ## ## ###

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.



" #### #### ## ## ###

DATA : GC_SPLITTER1 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA : GC_SPLITTER2 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



" #### ### ### #### ## ## ### 3#

DATA : GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER3 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER4 TYPE REF TO CL_GUI_CONTAINER.



" ##### ## GRID #### ## ## ### 3#.

DATA : GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID.



" ALV ### ## FIELDCAT##

DATA : GS_FIELDCAT TYPE LVC_S_FCAT.

DATA : GT_FIELDCAT1 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT2 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT3 TYPE LVC_T_FCAT.



" ALV ### ## LAYOUT ##

DATA : GS_LAYOUT TYPE LVC_S_LAYO.



" ALV ### ## SORT ##

DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT1 TYPE LVC_T_SORT.

DATA : GT_SORT2 TYPE LVC_T_SORT.

DATA : GT_SORT3 TYPE LVC_T_SORT.