
*&---------------------------------------------------------------------*

*&  Include           ZEDR23_PRACTICE009_TOP

*&---------------------------------------------------------------------*






TABLES : ZEDT23_102,

  ZEDT23_103,

  ZEDT23_104,

  ZEDT23_105,

  ZEDT23_106.



CONSTANTS : TRUE TYPE C LENGTH 1 VALUE 'X',

  GREEN TYPE C LENGTH 4 VALUE '@08@', "###

  RED TYPE C LENGTH 4 VALUE '@0A@', "###

  YELLOW TYPE C LENGTH 4 VALUE '@09@'. "###



DATA : Z_LASTDAY TYPE SY-DATUM.



DATA : MAX_ZDEP TYPE ZEDT23_102-ZDEPCODE.

SELECT MAX( ZDEPCODE ) INTO MAX_ZDEP FROM ZEDT23_102.



RANGES : GR_ZDEPCODE FOR ZEDT23_102-ZDEPCODE.

  GR_ZDEPCODE-SIGN = 'I'.

  GR_ZDEPCODE-OPTION = 'BT'.

  GR_ZDEPCODE-LOW = 'SS0001'.

  GR_ZDEPCODE-HIGH = MAX_ZDEP.

  APPEND GR_ZDEPCODE.



"2# ### - 104

DATA : BEGIN OF GS_01,

  ZPERNR LIKE ZEDT23_102-ZPERNR,  "####

  ZDEPCODE LIKE ZEDT23_102-ZDEPCODE,  "##

  ZDEPCODE_STR TYPE STRING,

  ZQFLAG LIKE ZEDT23_102-ZQFLAG,  "####

  ZYEAR LIKE ZEDT23_104-ZYEAR,  "##

  DATBI LIKE ZEDT23_104-DATBI,  "####

  DATAB LIKE ZEDT23_104-DATAB,  "####

  ZRANK LIKE ZEDT23_104-ZRANK,  "##

END OF GS_01.

DATA : GT_01 LIKE TABLE OF GS_01.



" 3#### - 106

DATA : BEGIN OF GS_02,

  ZPERNR LIKE ZEDT23_102-ZPERNR,  "####

  ZDEPCODE LIKE ZEDT23_102-ZDEPCODE,

  ZQDATE LIKE ZEDT23_102-ZQDATE,  "####

  ZQFLAG LIKE ZEDT23_102-ZQFLAG,  "####

  ZYEAR LIKE ZEDT23_106-ZYEAR,  "##

  DATBI LIKE ZEDT23_106-DATBI,  "####

  DATAB LIKE ZEDT23_106-DATAB,  "####

  ZWAERS TYPE WAERS,

  ZSALARY LIKE ZEDT23_106-ZSALARY,  "####

  ZBANKCODE LIKE ZEDT23_106-ZBANKCODE,  "###

  ZBANKCODE_STR TYPE STRING,

  ZACCOUNT LIKE ZEDT23_106-ZACCOUNT,  "####

END OF GS_02.

DATA : GT_02 LIKE TABLE OF GS_02.



" 1#### - 102, 103

DATA : BEGIN OF GS_03,

  ZLIGHT TYPE C LENGTH 4, "##

  ZPERNR LIKE ZEDT23_102-ZPERNR,  "####

  ZPNAME LIKE ZEDT23_103-ZPNAME,  "##

  ZDEPCODE LIKE ZEDT23_102-ZDEPCODE,  "##

  ZDEPCODE_STR TYPE STRING,

  DATBI LIKE ZEDT23_102-DATBI,  "####

  DATAB LIKE ZEDT23_102-DATAB,  "####

  ZDEPRANK LIKE ZEDT23_102-ZDEPRANK,  "##

  ZDEPRANK_STR TYPE STRING,

  ZGENDER LIKE ZEDT23_103-ZGENDER,  "##

  ZGENDER_STR TYPE STRING,

  ZEDATE LIKE ZEDT23_102-ZEDATE,  "####

  ZADDRESS LIKE ZEDT23_103-ZADDRESS,  "##

  ZQDATE LIKE ZEDT23_102-ZQDATE,  "####

  ZQFLAG LIKE ZEDT23_102-ZQFLAG,"####

END OF GS_03.

DATA : GT_03 LIKE TABLE OF GS_03.



DATA : GS_VARIANT TYPE DISVARIANT.



DATA : OK_CODE TYPE SY-UCOMM.

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA : GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA : GC_SPLITTER_ROW1 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA : GC_ROW1 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_ROW2 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.



DATA : GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT.

DATA : GT_FIELDCAT1 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT2 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT3 TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT1 TYPE LVC_T_SORT.

DATA : GT_SORT2 TYPE LVC_T_SORT.

DATA : GT_SORT3 TYPE LVC_T_SORT.