
*&---------------------------------------------------------------------*

*&  Include           ZEDR08_PRACTICE009_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS: S_ZEMP FOR ZEDT08_102-ZPERNR MODIF ID M1.

  SELECT-OPTIONS: S_DATE FOR ZEDT08_102-DATBI NO INTERVALS NO-EXTENSION MODIF ID M2.

  SELECT-OPTIONS: S_ZDEP FOR ZEDT08_104-ZDEPCODE NO INTERVALS NO-EXTENSION MODIF ID M3.

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS: P_CHK1 AS CHECKBOX DEFAULT C_X USER-COMMAND UC1 MODIF ID UC1.

SELECTION-SCREEN END OF BLOCK B2.