
*&---------------------------------------------------------------------*

*&  Include           ZEDR08_PRACTICE009_TOP

*&---------------------------------------------------------------------*






TABLES: ZEDT08_102,

        ZEDT08_103,

        ZEDT08_106,

        ZEDT08_104.



CONSTANTS: C_X TYPE CHAR1 VALUE 'X'.

CONSTANTS: C_A TYPE CHAR1 VALUE 'A'.



RANGES: R_FG FOR ZEDT08_102-ZQFLAG.



DATA: BEGIN OF GS_EMPLOYEE,

  ZPERNR LIKE ZEDT08_102-ZPERNR,

  ZPNAME LIKE ZEDT08_103-ZPNAME,

  ZDEPCODE LIKE ZEDT08_102-ZDEPCODE,

  DATBI LIKE ZEDT08_102-DATBI,

  DATAB LIKE ZEDT08_102-DATAB,

  ZDEPRANK LIKE ZEDT08_104-ZRANK,

  ZGENDER LIKE ZEDT08_103-ZGENDER,

  ZEDATE LIKE ZEDT08_102-ZEDATE,

  ZQDATE LIKE ZEDT08_102-ZQDATE,

  ZQFLAG LIKE ZEDT08_102-ZQFLAG,

  ZADDRESS LIKE ZEDT08_103-ZADDRESS,

  END OF GS_EMPLOYEE.

DATA: GT_EMPLOYEE LIKE TABLE OF GS_EMPLOYEE.



DATA: BEGIN OF GS_EMPLOYEE_ALV,

  ICON TYPE C LENGTH 4,

  ZPERNR LIKE ZEDT08_102-ZPERNR,

  ZPNAME LIKE ZEDT08_103-ZPNAME,

  ZDEPCODE_NAME TYPE C LENGTH 10,

  DATBI LIKE ZEDT08_102-DATBI,

  DATAB LIKE ZEDT08_102-DATAB,

  ZRANK_NAME(8),

  ZGENDER_NAME(4),

  ZEDATE LIKE ZEDT08_102-ZEDATE,

  ZQDATE LIKE ZEDT08_102-ZQDATE,

  ZQFLAG LIKE ZEDT08_102-ZQFLAG,

  ZADDRESS LIKE ZEDT08_103-ZADDRESS,

  END OF GS_EMPLOYEE_ALV.

DATA: GT_EMPLOYEE_ALV LIKE TABLE OF GS_EMPLOYEE_ALV.



DATA: BEGIN OF GS_CONTACT,

  ZPERNR LIKE ZEDT08_106-ZPERNR,

  ZYEAR LIKE ZEDT08_106-ZYEAR,

  DATBI LIKE ZEDT08_106-DATBI,

  DATAB LIKE ZEDT08_106-DATAB,

  ZSALARY LIKE ZEDT08_106-ZSALARY,

  ZBANKCODE LIKE ZEDT08_106-ZBANKCODE,

  ZACCOUNT LIKE ZEDT08_106-ZACCOUNT,

  END OF GS_CONTACT.

DATA: GT_CONTACT LIKE TABLE OF GS_CONTACT.



DATA: BEGIN OF GS_CONTACT_ALV,

  ZPERNR LIKE ZEDT08_106-ZPERNR,

  ZYEAR LIKE ZEDT08_106-ZYEAR,

  DATBI LIKE ZEDT08_106-DATBI,

  DATAB LIKE ZEDT08_106-DATAB,

  ZSALARY LIKE ZEDT08_106-ZSALARY,

  ZWAERS TYPE WAERS,

  ZBANK_NAME TYPE C LENGTH 10,

  ZACCOUNT LIKE ZEDT08_106-ZACCOUNT,

  END OF GS_CONTACT_ALV.

DATA: GT_CONTACT_ALV LIKE TABLE OF GS_CONTACT_ALV.



DATA: BEGIN OF GS_ASSESS,

  ZPERNR LIKE ZEDT08_104-ZPERNR,

  ZDEPCODE LIKE ZEDT08_104-ZDEPCODE,

  ZYEAR LIKE ZEDT08_104-ZYEAR,

  DATBI LIKE ZEDT08_104-DATBI,

  DATAB LIKE ZEDT08_104-DATAB,

  ZRANK LIKE ZEDT08_104-ZRANK,

  END OF GS_ASSESS.

DATA: GT_ASSESS LIKE TABLE OF GS_ASSESS.



DATA: BEGIN OF GS_ASSESS_ALV,

  ZPERNR LIKE ZEDT08_104-ZPERNR,

  ZDEPCODE_NAME TYPE C LENGTH 10,

  ZYEAR LIKE ZEDT08_104-ZYEAR,

  DATBI LIKE ZEDT08_104-DATBI,

  DATAB LIKE ZEDT08_104-DATAB,

  ZRANK LIKE ZEDT08_104-ZRANK,

  END OF GS_ASSESS_ALV.

DATA: GT_ASSESS_ALV LIKE TABLE OF GS_ASSESS_ALV.



DATA: OK_CODE TYPE SY-UCOMM.



DATA: GS_FIELDCAT TYPE LVC_S_FCAT,

      GT_FIELDCAT1 TYPE LVC_T_FCAT.

DATA: GT_FIELDCAT2 TYPE LVC_T_FCAT.

DATA: GT_FIELDCAT3 TYPE LVC_T_FCAT.



DATA: GS_LAYOUT TYPE LVC_S_LAYO.



DATA: GS_SORT1 TYPE LVC_S_SORT.

DATA: GT_SORT1 TYPE LVC_T_SORT.

DATA: GT_SORT2 TYPE LVC_T_SORT.

DATA: GT_SORT3 TYPE LVC_T_SORT.



DATA: GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.

DATA: GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.

DATA: GC_CONTAINER3 TYPE REF TO CL_GUI_CONTAINER.

DATA: GC_CONTAINER4 TYPE REF TO CL_GUI_CONTAINER.



DATA: GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.



DATA: GC_SPLITTER1 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA: GC_SPLITTER2 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



DATA: GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA: GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.

DATA: GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID.



DATA: GS_VARIANT TYPE DISVARIANT.