
*&---------------------------------------------------------------------*

*&  Include           ZEDR14_PRACTICE009_TOP

*&---------------------------------------------------------------------*






TABLES : ZEDT14_102, ZEDT14_103, ZEDT14_104, ZEDT14_105, ZEDT14_106.



"CONSTANTS ##

CONSTANTS FIRST_DATE(5) VALUE '01.01'.

CONSTANTS C_X VALUE 'X'.



"### ITAB

DATA : BEGIN OF GS_FINAL1,

  ZCOLOR TYPE C LENGTH 4,              "###

  ZPERNR LIKE ZEDT14_102-ZPERNR,       "####

  ZPNAME LIKE ZEDT14_103-ZPNAME,       "####

  ZDEPCODE LIKE ZEDT14_102-ZDEPCODE,   "####

  ZDEPNAME TYPE C LENGTH 3,            "## ##

  DATBI LIKE ZEDT14_102-DATBI,         "####

  DATAB LIKE ZEDT14_102-DATAB,         "####

  ZDEPRANK LIKE ZEDT14_102-ZDEPRANK,   "####

  ZDEPRANKNAME TYPE C LENGTH 2,        "## ##

  ZGENDER LIKE ZEDT14_103-ZGENDER,     "##

  ZGENDERNAME TYPE C LENGTH 2,         "## ##

  ZEDATE LIKE ZEDT14_102-ZEDATE,       "####

  ZADDRESS LIKE ZEDT14_103-ZADDRESS,   "##

  ZQDATE LIKE ZEDT14_102-ZQDATE,       "####

  ZQFLAG LIKE ZEDT14_102-ZQFLAG,       "####

  END OF GS_FINAL1.

DATA : GT_FINAL1 LIKE TABLE OF GS_FINAL1.



DATA : BEGIN OF GS_FINAL2,

  ZPERNR LIKE ZEDT14_102-ZPERNR,       "####

  ZDEPCODE LIKE ZEDT14_102-ZDEPCODE,   "####

  ZDEPNAME TYPE C LENGTH 3,            "## ##

  ZYEAR LIKE ZEDT14_104-ZYEAR,         "##

  DATBI LIKE ZEDT14_104-DATBI,         "####

  DATAB LIKE ZEDT14_104-DATAB,         "####

  ZRANK LIKE ZEDT14_104-ZRANK,         "##

  END OF GS_FINAL2.

DATA : GT_FINAL2 LIKE TABLE OF GS_FINAL2.



DATA : BEGIN OF GS_FINAL3,

  ZPERNR LIKE ZEDT14_102-ZPERNR,       "####

  ZYEAR LIKE ZEDT14_106-ZYEAR,         "##

  DATBI LIKE ZEDT14_106-DATBI,         "####

  DATAB LIKE ZEDT14_106-DATAB,         "####

  ZSALARY LIKE ZEDT14_106-ZSALARY,     "####

  ZWAERS TYPE WAERS,                   "##

  ZBANKCODE LIKE ZEDT14_106-ZBANKCODE, "####

  ZBANKNAME TYPE C LENGTH 3,           "### ##

  ZACCOUNT LIKE ZEDT14_106-ZACCOUNT,   "####

  END OF GS_FINAL3.

DATA : GT_FINAL3 LIKE TABLE OF GS_FINAL3.



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA : GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



DATA : GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER3 TYPE REF TO CL_GUI_CONTAINER.



DATA : GC_SPLITTER_TOP TYPE REF TO CL_GUI_SPLITTER_CONTAINER,

       GC_TOP_CONTAINER TYPE REF TO CL_GUI_CONTAINER.



DATA : GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_VARIANT TYPE DISVARIANT.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT.

DATA : GT_FIELDCAT1 TYPE LVC_T_FCAT,

       GT_FIELDCAT2 TYPE LVC_T_FCAT,

       GT_FIELDCAT3 TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT TYPE LVC_T_SORT.