
*&---------------------------------------------------------------------*

*&  Include           ZWORK22_001_TOP

*&---------------------------------------------------------------------*




TABLES: SSCRFIELDS.

"TABLES : ZTCURR22.



SELECTION-SCREEN FUNCTION KEY 1.



CONSTANTS: C_OBJID TYPE WWWDATATAB-OBJID VALUE 'ZCURRENCY_TEMPLATE'.



"###

DATA : GO_EVENT TYPE REF TO EVENT.



DATA : BEGIN OF GS_CURR,

         KURST TYPE ZTCURR22-KURST,

         FCURR TYPE ZTCURR22-FCURR,

         TCURR TYPE ZTCURR22-TCURR,

         GDATU(8) TYPE C,

         UKURS TYPE ZTCURR22-UKURS,

         FFACT TYPE ZTCURR22-FFACT,

         TFACT TYPE ZTCURR22-TFACT,

         CRNAME TYPE SY-UNAME, "###

         CRDATE TYPE SY-DATUM, "###

       END OF GS_CURR,

       GT_CURR LIKE TABLE OF GS_CURR.



DATA : BEGIN OF GS_CURR_ALV, "###

  KURST LIKE ZTCURR22-KURST, "####

  FCURR LIKE ZTCURR22-FCURR, "####

  TCURR LIKE ZTCURR22-TCURR, "####

  "GDATU LIKE ZTCURR22-GDATU, "## ## ###

  GDATU(8) TYPE C,

  UKURS LIKE ZTCURR22-UKURS, "##

  FFACT LIKE ZTCURR22-FFACT, "#### ### ##

  TFACT LIKE ZTCURR22-TFACT, "#### ### ##

  CRNAME TYPE SY-UNAME,      "###

  CRDATE TYPE SY-DATUM,      "###

END OF GS_CURR_ALV.

DATA : GT_CURR_ALV LIKE TABLE OF GS_CURR_ALV.








* ALV ## ### ##




DATA: GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA: GC_GRID TYPE REF TO CL_GUI_ALV_GRID.

DATA: OK_CODE TYPE SY-UCOMM.

DATA: GS_FIELDCAT TYPE LVC_S_FCAT.

DATA: GT_FIELDCAT TYPE LVC_T_FCAT.

DATA: GT_SORT TYPE LVC_T_SORT.

DATA: GS_SORT TYPE LVC_S_SORT.

DATA: GS_LAYOUT TYPE LVC_S_LAYO.

DATA: GS_VARIANT TYPE DISVARIANT.