
*&---------------------------------------------------------------------*

*& Report ZEDR24_013_SELECT_OPTIONS

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR24_013_SELECT_OPTIONS.



"--------------------------------------------------------

"1. SELECTION-OPTIONS ## ##




*TABLES : ZEDT24_001. "SELECT OPTIONS ## ## ### ##

*

*DATA : BEGIN OF GS_STUDENT.

*  INCLUDE TYPE ZEDT24_001.

*DATA : END OF GS_STUDENT.

*DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

*

*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT24_001-ZCODE.

*SELECTION-SCREEN END OF BLOCK B1.

*

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : P_ZGEN LIKE ZEDT24_001-ZGENDER.

*SELECTION-SCREEN END OF BLOCK B2.

*

*

*SELECT * FROM ZEDT00_001

*  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

*  WHERE ZCODE IN S_ZCODE "SELECTION-OPTIONS ### IN ##

*    AND ZGENDER = P_ZGEN.

*

*IF GT_STUDENT[] IS NOT INITIAL.

*  CLEAR : GS_STUDENT.

*  LOOP AT GT_STUDENT INTO GS_STUDENT.

*    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_STUDENT-ZENAME, GS_STUDENT-ZPERNR.

*  ENDLOOP.

*ELSE.

*  WRITE :/ '### ##'.

*ENDIF.






"--------------------------------------------------------

"2. SELECTION-OPTIONS ## ##




*TABLES : ZEDT24_001. "SELECT OPTIONS ## ## ### ##

*

*DATA : BEGIN OF GS_STUDENT.

*  INCLUDE TYPE ZEDT24_002.

*DATA : END OF GS_STUDENT.

*DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

*

*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT24_001-ZCODE DEFAULT 'SSU-01'.                   "## ### ##

**  SELECT-OPTIONS : S_ZCODE FOR ZEDT24_001-ZCODE DEFAULT 'SSU-01' SIGN I OPTION EQ.

*

**  SELECT-OPTIONS : S_ZCODE FOR ZEDT24_001-ZCODE DEFAULT 'SSU-01' SIGN E OPTION EQ. "### ## # ##

*

**  SELECT-OPTIONS : S_ZCODE FOR ZEDT24_001-ZCODE DEFAULT 'SSU-01' SIGN I OPTION BT. "DEFAULT# DATA# 1## ## BT ##

**  SELECT-OPTIONS : S_ZCODE FOR ZEDT24_001-ZCODE DEFAULT 'SSU-01' TO 'SSU-99' SIGN I OPTION BT. "BETWEEN ##

*

**  SELECT-OPTIONS : S_ZCODE FOR ZEDT24_001-ZCODE DEFAULT 'SSU-01' NO INTERVALS. "## ## #### ## 1## ## ##

**  SELECT-OPTIONS : S_ZCODE FOR ZEDT24_001-ZCODE DEFAULT 'SSU-01' NO INTERVALS NO-EXTENSION. "MULTI SELECTION ### ##

*

**  SELECT-OPTIONS : S_ZCODE FOR ZEDT24_001-ZCODE DEFAULT 'SSU-01' VISIBLE LENGTH 3. "### ## ##

*SELECTION-SCREEN END OF BLOCK B1.

*

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : P_ZGEN LIKE ZEDT24_001-ZGENDER.

*SELECTION-SCREEN END OF BLOCK B2.

*

*

*SELECT * FROM ZEDT00_001

*  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

*  WHERE ZCODE IN S_ZCODE "SELECTION-OPTIONS ### IN ##

*    AND ZGENDER = P_ZGEN.

*

*IF GT_STUDENT[] IS NOT INITIAL.

*  CLEAR : GS_STUDENT.

*  LOOP AT GT_STUDENT INTO GS_STUDENT.

*    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME.

*  ENDLOOP.

*ELSE.

*  WRITE :/ '### ##'.

*ENDIF.






"--------------------------------------------------------

"3. MODIF ID ## (##### ## ##, SELECTION SCREEN ##)




*TABLES : ZEDT24_001. "SELECT OPTIONS ## ## ### ##

*

*DATA : BEGIN OF GS_STUDENT.

*  INCLUDE TYPE ZEDT24_001.

*DATA : END OF GS_STUDENT.

*DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

*

*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT24_001-ZCODE.

*  PARAMETERS : P_ZGEN LIKE ZEDT24_001-ZGENDER.

*SELECTION-SCREEN END OF BLOCK B1.

*

*"3-1. #### ##

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : P_CH1 AS CHECKBOX DEFAULT 'X' MODIF ID M1. "SELECTION SCREEN# GROUP1## ### # ## #### ####.

*  PARAMETERS : P_CH2 AS CHECKBOX MODIF ID M2.

*SELECTION-SCREEN END OF BLOCK B2.

*

*"3-2. SELECTION-SCREEN# #### ####

*AT SELECTION-SCREEN OUTPUT.

*  LOOP AT SCREEN.

*    "3-3. MODIF ID# ## ### ##

*    IF SCREEN-GROUP1 = 'M2'. "GROUP1# M2 ## ## ## -> ### ####.

*      "3-4. ### # ## # ##

**      SCREEN-INPUT = '0'.    "0## ## ####, 1## ## ###

**      SCREEN-ACTIVE = '0'.   "0## ### ### #### ## -> ###

**      SCREEN-REQUIRED = '1'. "1## ## ##

**      SCREEN-OUTPUT = '0'.   "## ## ####, ##### ## ##

*      MODIFY SCREEN.

*    ENDIF.

*  ENDLOOP.






"--------------------------------------------------------

"4. USER-COMMAND




*TABLES : ZEDT24_001.

*

*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT24_001-ZCODE.

*  PARAMETERS : P_ZPERNR LIKE ZEDT24_001-ZPERNR MODIF ID M1.

*  PARAMETERS : P_ZGEN LIKE ZEDT24_001-ZGENDER MODIF ID M2.

*SELECTION-SCREEN END OF BLOCK B1.

*

*"4-1. ### ### #### ##

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  "4-2. USER-COMMAND FCODE# ## #### #### ## ###.

*  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1. "#### #### #####

*  PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

*SELECTION-SCREEN END OF BLOCK B2.

*

*"4-3. SELECTION-SCREEN# #### ## ##

*AT SELECTION-SCREEN OUTPUT.

*  LOOP AT SCREEN.

*    IF SCREEN-GROUP1 = 'M2'. "P_ZGEN ## ## ### ### ###

*      IF P_R1 = 'X'.

*        SCREEN-ACTIVE = '1'.

*      ELSEIF P_R2 = 'X'.

*        SCREEN-ACTIVE = '0'.

*      ENDIF.

*    ENDIF.

*    MODIFY SCREEN.

*  ENDLOOP.






TABLES : ZEDT24_001. "SELECT OPTIONS ## ## ### ##



DATA : BEGIN OF GS_STUDENT,

  ZMNAME LIKE ZEDT24_002-ZMNAME,

   ZKNAME LIKE ZEDT24_001-ZKNAME,

  ZCODE LIKE ZEDT24_001-ZCODE,

END OF GS_STUDENT.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.



SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS : S_ZCODE FOR ZEDT24_001-ZCODE DEFAULT 'SSU-01'.                   "## ### ##




*  SELECT-OPTIONS : S_ZCODE FOR ZEDT24_001-ZCODE DEFAULT 'SSU-01' SIGN I OPTION EQ.



*  SELECT-OPTIONS : S_ZCODE FOR ZEDT24_001-ZCODE DEFAULT 'SSU-01' SIGN E OPTION EQ. "### ## # ##



*  SELECT-OPTIONS : S_ZCODE FOR ZEDT24_001-ZCODE DEFAULT 'SSU-01' SIGN I OPTION BT. "DEFAULT# DATA# 1## ## BT ##

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT24_001-ZCODE DEFAULT 'SSU-01' TO 'SSU-99' SIGN I OPTION BT. "BETWEEN ##



*  SELECT-OPTIONS : S_ZCODE FOR ZEDT24_001-ZCODE DEFAULT 'SSU-01' NO INTERVALS. "## ## #### ## 1## ## ##

*  SELECT-OPTIONS : S_ZCODE FOR ZEDT24_001-ZCODE DEFAULT 'SSU-01' NO INTERVALS NO-EXTENSION. "MULTI SELECTION ### ##



*  SELECT-OPTIONS : S_ZCODE FOR ZEDT24_001-ZCODE DEFAULT 'SSU-01' VISIBLE LENGTH 3. "### ## ##




SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS : P_ZGEN LIKE ZEDT24_001-ZGENDER.

SELECTION-SCREEN END OF BLOCK B2.





SELECT * FROM ZEDT00_001

  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

  WHERE ZCODE IN S_ZCODE "SELECTION-OPTIONS ### IN ##

    AND ZGENDER = P_ZGEN.



IF GT_STUDENT[] IS NOT INITIAL.

  CLEAR : GS_STUDENT.

  LOOP AT GT_STUDENT INTO GS_STUDENT.

    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZMNAME.

  ENDLOOP.

ELSE.

  WRITE :/ '### ##'.

ENDIF.