
*&---------------------------------------------------------------------*

*&  Include           ZEDR01_022_TOP

*&---------------------------------------------------------------------*






TABLES : ZEDT01_002.



DATA : BEGIN OF GS_STUDENT,

  ZCOLOR TYPE C LENGTH 4,

  ZCODE LIKE ZEDT01_001-ZCODE,

  ZPERNR LIKE ZEDT01_001-ZPERNR,

  ZKNAME LIKE ZEDT01_001-ZKNAME,

  ZENAME LIKE ZEDT01_001-ZENAME,

  ZGENDER LIKE ZEDT01_001-ZGENDER,

  ZMAJOR LIKE ZEDT01_002-ZMAJOR,

  ZMNAME LIKE ZEDT01_002-ZMNAME,

  END OF GS_STUDENT.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER.

DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT.

DATA : GT_FIELDCAT TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT TYPE LVC_T_SORT.