
*&---------------------------------------------------------------------*

*&  Include           ZMM23_004_TOP

*&---------------------------------------------------------------------*






DATA : OK_CODE TYPE SY-UCOMM,

      GV_DYNNR TYPE SY-DYNNR VALUE '0101'.



DATA : GV_FLAG TYPE C LENGTH 1 VALUE '0'.



"SELECTION-SCREEN FUNCTION KEY 1.  " SCREEN 200# '####'

"SELECTION-SCREEN FUNCTION KEY 2.  " SCREEN 300# '####'

CONTROLS CTR_200 TYPE TABLEVIEW USING SCREEN '0200'.  "####

CONTROLS CTR_300 TYPE TABLEVIEW USING SCREEN '0300'.  "####

CONTROLS TAB_200 TYPE TABSTRIP.   "



" #### - SUBSCREEN 101

" #### - SUBSCREN 102

DATA : GV_EBELN TYPE Z23RSEG-EBELN,   "####

      GV_WERKS TYPE Z23RSEG-WERKS,    "###

      GV_BUDAT TYPE Z23RBKP-BUDAT.    "#####(###)



" PO ##

DATA : GS_EKKO TYPE Z23EKKO.



" PO ###

DATA : BEGIN OF GS_EKPO,

  ZCHECK TYPE C LENGTH 1,

  EBELN TYPE Z23EKPO-EBELN, "######

  EBELP TYPE Z23EKPO-EBELP, "##

  MATNR TYPE Z23EKPO-MATNR, "####

  MAKTX TYPE Z23EKPO-MAKTX,  "###

  MENGE TYPE Z23EKPO-MENGE,  "PO##

  MEINS TYPE Z23EKPO-MEINS, "##

  STPRS TYPE Z23EKPO-STPRS, "##

  WRBTR TYPE Z23RSEG-WRBTR, "#### (INPUT)

  PRDAT TYPE Z23EKPO-PRDAT, "###

  WERKS TYPE Z23EKPO-WERKS, "###

  LGORT TYPE Z23EKPO-LGORT,"####

  END OF GS_EKPO.

DATA : GT_EKPO LIKE TABLE OF GS_EKPO.



DATA : GS_RBKP TYPE Z23RBKP.





" ## ###

DATA : BEGIN OF GS_RSEG,

  ZCHECK TYPE C LENGTH 1, "##

  BELNR TYPE Z23RSEG-BELNR, "######

  GJAHR TYPE Z23RSEG-GJAHR, "####

  BUZEI TYPE Z23RSEG-BUZEI,

  EBELN TYPE Z23RSEG-EBELN, "######

  "EBELP TYPE Z23RSEG-EBELP,   "####

  "MATNR TYPE Z23RSEG-MATNR,  "####

  "TXZ01 TYPE Z23RSEG-TXZ01,  "####

  WERKS TYPE Z23RSEG-WERKS,  "###

  "WRBTR TYPE Z23RSEG-WRBTR,  "####

  "WMWST TYPE Z23RSEG-WMWST,  "##

  "MENGE TYPE Z23RSEG-MENGE,  "##

  "BSTME TYPE Z23RSEG-BSTME,  "##

 " MWSKZ TYPE Z23RSEG-MWSKZ, "####

  END OF GS_RSEG.

DATA : GT_RSEG LIKE TABLE OF GS_RSEG.



DATA : BEGIN OF GS_RBKP_ITAB,

  ZCHECK TYPE C LENGTH 1, "##

  BELNR TYPE Z23RBKP-BELNR,  "######

  GJAHR TYPE Z23RBKP-GJAHR,  "####

  BLDAT TYPE Z23RBKP-BLDAT,  "###

  BUDAT TYPE Z23RBKP-BUDAT,  "###

  BUKRS TYPE Z23RBKP-BUKRS,  "####

  LIFNR TYPE Z23RBKP-LIFNR,  "###

  BKTXT TYPE Z23RBKP-BKTXT,  "#####

  RMWWR TYPE Z23RBKP-RMWWR,  "#####

  WAERS TYPE Z23RBKP-WAERS,  "###

  END OF GS_RBKP_ITAB.

DATA : GT_RBKP_ITAB LIKE TABLE OF GS_RBKP_ITAB.