
*&---------------------------------------------------------------------*

*&  Include           ZWORK18_002_TOP

*&---------------------------------------------------------------------*




TABLES : ZTCURR18.



TYPE-POOLS: OLE2.



" OLE ### ##

DATA: GV_TEMP_DIR TYPE STRING,

      GV_XLS_PATH TYPE STRING,

      GV_PDF_PATH TYPE STRING.



DATA : GV_TEMPLATE_RL TYPE RLGRAP-FILENAME."## ## ##

DATA : GV_PDF_PATH_RL TYPE RLGRAP-FILENAME."PDF ## ##



" EXCEL OLE ##

DATA: GO_EXCEL     TYPE OLE2_OBJECT,

      GO_WORKBOOKS TYPE OLE2_OBJECT,

      GO_WORKBOOK  TYPE OLE2_OBJECT,

      GO_SHEETS    TYPE OLE2_OBJECT,

      GO_SHEET     TYPE OLE2_OBJECT,

      GO_RANGE     TYPE OLE2_OBJECT.



DATA : BEGIN OF GS_CURR,

         KURST LIKE ZTCURR18-KURST,

         FCURR LIKE ZTCURR18-FCURR,

         TCURR LIKE ZTCURR18-TCURR,

         GDATU LIKE ZTCURR18-GDATU,

         UKURS LIKE ZTCURR18-UKURS,

         FFACT LIKE ZTCURR18-FFACT,

         TFACT LIKE ZTCURR18-TFACT,

         ERNAM LIKE ZTCURR18-ERNAM,

         ERDAT LIKE ZTCURR18-ERDAT,

       END OF GS_CURR.

DATA : GT_CURR LIKE TABLE OF GS_CURR.



DATA : GC_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER.

DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT.

DATA : GT_FIELDCAT TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT TYPE LVC_T_SORT.