
*&---------------------------------------------------------------------*

*& Report ZEDR02_016

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR02_016.



DATA : BEGIN OF GS_STUDENT.

  include structure
ZEDT02_001
.

DATA : END OF GS_STUDENT.

DATA: GT_STUDENT LIKE TABLE OF GS_STUDENT.



SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  PARAMETERS : P_ZCODE LIKE ZEDT02_001-ZCODE LOWER CASE OBLIGATORY VISIBLE LENGTH 10.

  PARAMETERS : P_ZPERNR TYPE C LENGTH 10 NO-DISPLAY.

  "PARAMETERS : P_ZNUM TYPE P DECIMALS 2.

  PARAMETERS : P_ZGEN LIKE ZEDT02_001-ZGENDER DEFAULT 'M'.

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  SELECTION-SCREEN BEGIN OF LINE.

    PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'.

  SELECTION-SCREEN POSITION 3. "Position ## ## ##

  SELECTION-SCREEN COMMENT (10) FOR FIELD P_R1. "###(###)##

    PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

  SELECTION-SCREEN POSITION 20.

  SELECTION-SCREEN COMMENT (10) FOR FIELD P_R2.

  SELECTION-SCREEN END OF LINE.

  PARAMETERS : Z_CHECK AS CHECKBOX DEFAULT 'X'.

SELECTION-SCREEN END OF BLOCK B2.



SELECT * FROM ZEDT02_001

  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

  WHERE ZCODE = P_ZCODE

  AND   ZGENDER = P_ZGEN.



IF GT_STUDENT[] IS NOT INITIAL.

  WRITE : / '### ##'.

ELSE.

  WRITE : / '### ##'.

ENDIF.



IF Z_CHECK = 'X'.

  WRITE : / '#### ##'.

ELSE.

  WRITE : / '## ##'.

ENDIF.