
*&---------------------------------------------------------------------*

*&  Include  ZEDR21_PRACTICE009_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS : S_ZEMP FOR ZEDT21_102-ZPERNR21.

  SELECT-OPTIONS : S_DATE FOR ZEDT21_102-DATAB NO INTERVALS NO-EXTENSION.

  SELECT-OPTIONS : S_ZDEP FOR ZEDT21_102-ZDEPCODE21 NO INTERVALS NO-EXTENSION.

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS : P_CH1 AS CHECKBOX.

SELECTION-SCREEN END OF BLOCK B2.