
*&---------------------------------------------------------------------*

*&  Include           ZEDR05_PRACTICE009_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS : S_PERNR FOR ZEDT05_103-ZPERNR.

  SELECT-OPTIONS : S_DATBI FOR ZEDT05_102-DATAB NO INTERVALS NO-EXTENSION.

  SELECT-OPTIONS : S_DEP FOR ZEDT05_102-ZDEPCODE NO INTERVALS NO-EXTENSION..

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS : P_ZFLAG AS CHECKBOX.

SELECTION-SCREEN END OF BLOCK B2.