
*&---------------------------------------------------------------------*

*&  Include           ZMM09_003_TOP

*&---------------------------------------------------------------------*






CONTROLS : TC_ITEMS TYPE TABLEVIEW USING SCREEN '0100'.

DATA : OK_CODE TYPE SY-UCOMM.







"###100 ####

DATA : GF_MBLNR LIKE ZMKPF09-MBLNR,

       GF_MJAHR LIKE ZMKPF09-MJAHR,

       GF_BLART LIKE ZMKPF09-BLART,

       GF_BLDAT LIKE ZMKPF09-BLDAT,

       GF_BUDAT LIKE ZMKPF09-BUDAT.



DATA : GV_BELNR LIKE ZBKPF09-BELNR. "#### (##)



"###100 #####

DATA : BEGIN OF GS_ITEM,

  L_CHECK TYPE C LENGTH 1, "## (####)

  EBELN LIKE ZEKKO_09-EBELN, "######

  EBELP LIKE ZEKPO_09-EBELP, "##

  LIFNR LIKE ZEKKO_09-LIFNR, "###

  BEDAT LIKE ZEKKO_09-BEDAT, "###

  MATNR LIKE ZEKPO_09-MATNR, "####

  ZMATNAME LIKE ZMARA09-ZMATNAME, "###

  MENGE LIKE ZEKPO_09-MENGE, "## (PO##)

  MEINS LIKE ZEKPO_09-MEINS, "##

  STPRS LIKE ZEKPO_09-STPRS, "##

  WAERS LIKE ZEKKO_09-WAERS, "##

  PRDAT LIKE ZEKPO_09-PRDAT, "###

  WERKS LIKE ZEKPO_09-WERKS, "###

  LGORT LIKE ZEKPO_09-LGORT, "####

  GR_DONE TYPE MENGE_D, "## ### ##

  GR_REM TYPE MENGE_D,  "## ##

  GR_NOW TYPE MENGE_D,  "## ## ##

END OF GS_ITEM.

DATA : GT_ITEM LIKE TABLE OF GS_ITEM.



DATA : G_ONCE TYPE C LENGTH 1.



"#### ##, ###

DATA : GS_MKPF TYPE ZMKPF09,

       GS_MSEG TYPE ZMSEG09.

DATA : GT_MKPF LIKE TABLE OF GS_MKPF,

       GT_MSEG LIKE TABLE OF GS_MSEG.



"#### ##, ###

DATA : GS_BKPF TYPE ZBKPF09,

       GS_BSEG TYPE ZBSEG09.

DATA : GT_BKPF LIKE TABLE OF GS_BKPF,

       GT_BSEG LIKE TABLE OF GS_BSEG.





"#######

DATA : BEGIN OF GS_GOODS_LIST,

  MBLNR LIKE ZMKPF09-MBLNR, "######

  BUDAT LIKE ZMKPF09-BUDAT, "###

END OF GS_GOODS_LIST.

DATA : GT_GOODS_LIST LIKE TABLE OF GS_GOODS_LIST.



DATA : BEGIN OF GS_GOODS_ALV,

  DISP_TEXT TYPE CHAR200,

END OF GS_GOODS_ALV.

DATA : GT_GOODS_ALV LIKE TABLE OF GS_GOODS_ALV.



"### ###

DATA : BEGIN OF GS_HEADER_ALV,

  MBLNR LIKE ZMKPF09-MBLNR, "######

  BLART LIKE ZMKPF09-BLART, "####

  BLDAT LIKE ZMKPF09-BLDAT, "###

  BUDAT LIKE ZMKPF09-BUDAT, "###

END OF GS_HEADER_ALV.

DATA : GT_HEADER_ALV LIKE TABLE OF GS_HEADER_ALV.



"## #####

DATA : MBLNR_200 LIKE ZMKPF09-MBLNR,

       BLART_200 LIKE ZMKPF09-BLART,

       BLDAT_200 LIKE ZMKPF09-BLDAT,

       BUDAT_200 LIKE ZMKPF09-BUDAT.



DATA : BEGIN OF GS_ITEM_ALV,

  LV_CHECK TYPE C LENGTH 1, "#### (##### ##)

  CANCEL_TEXT TYPE STRING, "#### ###

  ZEILE LIKE ZMSEG09-ZEILE, "## (PO####)

  MATNR LIKE ZMSEG09-MATNR, "####

  ZMATNAME LIKE ZMARA09-ZMATNAME, "###

  MENGE LIKE ZMSEG09-MENGE, "##

  MEINS LIKE ZMSEG09-MEINS, "##

  WERKS LIKE ZMSEG09-WERKS, "###

  LGORT LIKE ZMSEG09-LGORT, "####

  BWART LIKE ZMSEG09-BWART, "#### (### ##### ##)

  LIFNR LIKE ZMSEG09-LIFNR, "##### (PO## ##)

  BUKRS LIKE ZMSEG09-BUKRS, "#### (FI### ##)

  STYLE TYPE LVC_T_STYL,

END OF GS_ITEM_ALV.

DATA : GT_ITEM_ALV LIKE TABLE OF GS_ITEM_ALV.



"alv ##

DATA : GC_CUSTOM_GOODS_LIST TYPE REF TO CL_GUI_CUSTOM_CONTAINER.

DATA : GC_GRID_GOODS_LIST TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT,

       GT_FIELDCAT TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



"item alv

DATA : GC_CUSTOM_GOODS_ITEM TYPE REF TO CL_GUI_CUSTOM_CONTAINER.

DATA : GC_GRID_GOODS_ITEM TYPE REF TO CL_GUI_ALV_GRID.



"####

DATA : GT_TOOLBAR TYPE UI_FUNCTIONS.



DATA : GO_EVENT TYPE REF TO EVENT.



"### ### ### ##

TYPES : BEGIN OF TY_FI_LIST,

    BELNR TYPE BELNR_D,

    OBJTYPETXT TYPE STRING,

END OF TY_FI_LIST.



DATA : GT_FI_LIST TYPE STANDARD TABLE OF TY_FI_LIST.



"### 300#

DATA : GO_CONT_300 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,

       GO_ALV_300  TYPE REF TO CL_GUI_ALV_GRID.



"### ## 300

DATA : GO_EVENT_300 TYPE REF TO EVENT.



"### #### ID

DATA : GV_SEL_BELNR TYPE ZBKPF09-BELNR.



"400# ###, ### #### ####

DATA : GT_SEL_MSEG TYPE STANDARD TABLE OF ZMSEG09.



"400# ### ## ##

DATA : BEGIN OF GS_BKPF_400,

  BELNR LIKE ZBKPF09-BELNR, "####

  BUKRS LIKE ZBKPF09-BUKRS, "####

  GJAHR LIKE ZBKPF09-GJAHR, "####

  BLDAT LIKE ZBKPF09-BLDAT, "###

  BUDAT LIKE ZBKPF09-BUDAT, "###

  WAERS LIKE ZBKPF09-WAERS, "####

END OF GS_BKPF_400.



"400# ### ### (get_besg##)

DATA : GS_BSEG_400 TYPE ZBSEG09,

       GT_BSEG_400 LIKE TABLE OF GS_BSEG_400.



"400# ### ALV ## (modify_bseg##)

DATA : BEGIN OF GS_BSEG_400_ALV,

  BUKRS LIKE ZBSEG09-BUKRS,       "CoCd

  BUZEI LIKE ZBSEG09-BUZEI,       "##

  BSCHL LIKE ZBSEG09-BSCHL,       "# (###)

  KOART LIKE ZBSEG09-KOART,       "SG

  SHKZG LIKE ZBSEG09-SHKZG,       "##/## ###

  HKONT LIKE ZBSEG09-HKONT,       "##

  TXT1 LIKE ZSKA109-TEXT,         "##

  HKONT2 LIKE ZBSEG09-HKONT,       "G/L ## (####)

  TXT2 LIKE ZSKA109-TEXT,        "G/L ### (####)

  DMBTR LIKE ZBSEG09-DMBTR,       "##

  PSWSL LIKE ZBSEG09-PSWSL,       "##

  WRBTR LIKE ZBSEG09-WRBTR,       "# ## ## ## (####)

  PSWSL2 LIKE ZBSEG09-PSWSL,      "## ##

END OF GS_BSEG_400_ALV.

DATA : GT_BSEG_400_ALV LIKE TABLE OF GS_BSEG_400_ALV.



"400# ### ####, ALV, ######

DATA : GO_CONT_400 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,

       GO_ALV_400  TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_FIELDCAT_400 TYPE LVC_S_FCAT,

       GT_FIELDCAT_400 TYPE LVC_T_FCAT.



DATA : GS_SORT_400 TYPE LVC_S_SORT,

       GT_SORT_400 TYPE LVC_T_SORT.



DATA : GS_LATOUT_400 TYPE LVC_S_LAYO.



"N : ##, R :###

DATA: GV_FI_VIEW_MODE TYPE C.



"410 ### ####

TYPES: BEGIN OF TY_REV_BELNR,

         BELNR TYPE ZBKPF09-BELNR,

       END OF TY_REV_BELNR.



DATA: GT_REV_BELNR TYPE STANDARD TABLE OF TY_REV_BELNR.








*GT_REV_BELNR TYPE SORTED TABLE OF ZBKPF09-BELNR

*                   WITH UNIQUE KEY TABLE_LINE,




DATA: GO_CONT_410  TYPE REF TO CL_GUI_CUSTOM_CONTAINER,

      GO_ALV_410   TYPE REF TO CL_GUI_ALV_GRID.



DATA : GO_EVENT_410 TYPE REF TO EVENT.



DATA : GS_FCAT_410 TYPE LVC_S_FCAT,

       GT_FCAT_410 TYPE LVC_T_FCAT.