
*&---------------------------------------------------------------------*

*&  Include           ZSPLITTER_CONTAINER18_TOP

*&---------------------------------------------------------------------*




TABLES : ZEDT018_001.



DATA : GS_STUDENT TYPE ZEDT018_001.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.



DATA : OK_CODE LIKE SY-UCOMM.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA : GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



DATA : GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.



DATA : GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_VARIANT TYPE DISVARIANT. "#### ## ## ##



DATA : GS_FIELDCAT TYPE LVC_S_FCAT.

DATA : GT_FIELDCAT1 TYPE LVC_T_FCAT.

DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GT_FIELDCAT2 TYPE LVC_T_FCAT.

DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT1 TYPE LVC_T_SORT.

DATA : GT_SORT2 TYPE LVC_T_SORT.