
*&---------------------------------------------------------------------*

*&  Include           ZMM15_004_TOP

*&---------------------------------------------------------------------*






DATA : OK_CODE TYPE SY-UCOMM.



CONSTANTS : C_V1 TYPE P DECIMALS 2 VALUE '0.10',

           C_V2 TYPE P DECIMALS 2 VALUE '0.00',

           C_V3 TYPE P DECIMALS 2 VALUE '0.00',

           C_V4 TYPE P DECIMALS 2 VALUE '0.10',

           C_V5 TYPE P DECIMALS 2 VALUE '0.10'.



"### 100

DATA : G_BLDAT LIKE ZRBKP_15-BLDAT, "### (#####)

       G_BUDAT LIKE ZRBKP_15-BUDAT, "###

       G_RMWWR LIKE ZRBKP_15-RMWWR, "##

       G_WAERS LIKE ZRBKP_15-WAERS, "###

       G_MWSKZ LIKE ZRBKP_15-MWSKZ, "####

       G_WMWST1 LIKE ZRBKP_15-WMWST1, "##

       G_BKTXT LIKE ZRBKP_15-BKTXT, "###

       G_ZTERM LIKE ZRBKP_15-ZTERM, "####

       G_ZFBDT LIKE ZRBKP_15-ZFBDT, "###

       G_BALANCE TYPE WRBTR, "##

       G_WAERS2 TYPE WAERS.



"###

DATA : ICON TYPE ICONS-TEXT.





"SCREEN 100 ### (###)

DATA : BEGIN OF GS_ALV_100,

  CHECK TYPE C LENGTH 1, "####

  BUZEI LIKE ZRSEG_15-BUZEI,  "## ##

  NETPR LIKE ZEKPO_15-STPRS, "##

  WAERS LIKE ZEKKO_15-WAERS, "##

  MENGE TYPE ZRSEG_15-MENGE, "## (####)

  MEINS LIKE ZRSEG_15-MEINS, "##

  WRBTR LIKE ZRSEG_15-WRBTR, "#### (##*##)

  EBELN LIKE ZRSEG_15-EBELN, "PO##

  EBELP LIKE ZRSEG_15-EBELP, "PO# ## ##

  MWSKZ_S TYPE STRING,       "####

  WMWST  TYPE WMWST,         "##

  MATNR LIKE ZRSEG_15-MATNR, "####

  ZMATNAME LIKE ZMAT_15-ZMATNAME, "#### (###)

  WERKS LIKE ZRSEG_15-WERKS, "###

  DMBTR LIKE ZRSEG_15-DMBTR, "## (###+##)

  SGTXT LIKE ZRSEG_15-SGTXT, "###

END OF GS_ALV_100.

DATA : GT_ALV_100 LIKE TABLE OF GS_ALV_100.



"ALV ##

DATA : GC_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER,

       GC_GRID   TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT,

       GT_FIELDCAT TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.





"###

DATA : GO_EVENT TYPE REF TO EVENT.



"##### ## ##

DATA : GV_FLAG_EVENT TYPE ABAP_BOOL VALUE ABAP_FALSE.



"##

DATA : GV_BELNR LIKE ZRBKP_15-BELNR, "######

       GV_LIFNR LIKE ZEKKO_15-LIFNR, "#####

       GV_BUKRS LIKE ZEKKO_15-BUKRS. "####



DATA : GS_RBKP LIKE ZRBKP_15. "####



DATA : GS_RSEG LIKE ZRSEG_15, "## ###

      GT_RSEG LIKE TABLE OF GS_RSEG.









"#### ### ###### (### 200)

DATA : BEGIN OF GS_LIST,

       BELNR TYPE ZRBKP_15-BELNR,

  END OF GS_LIST.

DATA : GT_LIST LIKE TABLE OF GS_LIST.





"###### #### ## (### 200)

DATA : GC_CUSTOM_LIST TYPE REF TO CL_GUI_CUSTOM_CONTAINER.

DATA : GC_GRID_LIST TYPE REF TO CL_GUI_ALV_GRID.



"#### #### ## (### 200)

DATA : GC_CUSTOM_200 TYPE REF TO CL_GUI_CUSTOM_CONTAINER.

DATA : GC_GRID_200 TYPE REF TO CL_GUI_ALV_GRID.



"### ### ###(### 200)

DATA : GS_FIELDCAT_LIST TYPE LVC_S_FCAT.

DATA : GT_FIELDCAT_LIST TYPE LVC_T_FCAT.



"### 200

DATA : G_BELNR2 LIKE ZRBKP_15-BELNR, "######

       G_GJAHR2 LIKE ZRBKP_15-GJAHR, "##

       G_BLDAT2 LIKE ZRBKP_15-BLDAT, "### (#####)

       G_BUDAT2 LIKE ZRBKP_15-BUDAT, "###

       G_BLART2 LIKE ZRBKP_15-BLART. "###



"SCREEN 200 ### (###)

DATA : BEGIN OF GS_ALV_200,

  CHECK TYPE C LENGTH 1, "####

  BELNR TYPE ZRSEG_15-BELNR, "######

  GJAHR TYPE ZRSEG_15-GJAHR, "####

  BUZEI TYPE ZRSEG_15-BUZEI, "## ##

  EBELN TYPE ZRSEG_15-EBELN, "######

  EBELP LIKE ZRSEG_15-EBELN, "##

  MATNR TYPE ZRSEG_15-MATNR, "####

  WERKS TYPE ZRSEG_15-WERKS, "###

  MAKTX TYPE ZEKPO_15-MAKTX, "###

  WRBTR TYPE ZRSEG_15-WRBTR, "####

  MENGE TYPE ZRSEG_15-MENGE, "####

  MEINS TYPE ZRSEG_15-MEINS, "##

  NETPR TYPE ZRSEG_15-NETPR, "##

  SGTXT TYPE ZRSEG_15-SGTXT, "###

  DMBTR TYPE ZRSEG_15-DMBTR, "##

  SHKZG TYPE ZRSEG_15-SHKZG,

  WAERS TYPE WAERS,

END OF GS_ALV_200.

DATA : GT_ALV_200 LIKE TABLE OF GS_ALV_200.