
*&---------------------------------------------------------------------*

*&  Include           ZEDR04_PRACTICE008_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS S_ZORDNO FOR ZEDT04_100-ZORDNO.  " ####

  PARAMETERS P_ZID TYPE ZEDT04_100-ZIDCODE.       " ##ID

  SELECT-OPTIONS S_ZMATNR FOR ZEDT04_100-ZMATNR.  " ####

  SELECT-OPTIONS S_ZJDATE FOR ZEDT04_100-ZJDATE MODIF ID M1.  " ####

  SELECT-OPTIONS S_ZDDATE FOR ZEDT04_101-ZDDATE MODIF ID M2.  " ####

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS P_RD1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1. " ####

  PARAMETERS P_RD2 RADIOBUTTON GROUP R1.                              " ####

SELECTION-SCREEN END OF BLOCK B2.



SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME.

  PARAMETERS P_ZFLAG AS CHECKBOX DEFAULT 'X'. " ######

SELECTION-SCREEN END OF BLOCK B3.