
*&---------------------------------------------------------------------*

*&  Include           ZMM18_001_TOP

*&---------------------------------------------------------------------*




TABLES : ZLFA1_18, ZLFB1_18, ZLFM1_18.



DATA: OK_CODE TYPE SY-UCOMM.



"###### ### ###

"## ###

DATA: GS_LFA1 TYPE ZLFA1_18.

DATA: GT_LFA1 TYPE TABLE OF ZLFA1_18.



" #######

DATA: GS_LFB1 TYPE ZLFB1_18.

DATA: GT_LFB1 TYPE TABLE OF ZLFB1_18.



" #######

DATA: GS_LFM1 TYPE ZLFM1_18.

DATA: GT_LFM1 TYPE TABLE OF ZLFM1_18.



"ALV #

DATA: GS_LFA1_ALV TYPE ZLFA1_18,

      GT_LFA1_ALV TYPE STANDARD TABLE OF ZLFA1_18.



DATA: GS_LFB1_ALV TYPE ZLFB1_18,

      GT_LFB1_ALV TYPE STANDARD TABLE OF ZLFB1_18.



DATA: GS_LFM1_ALV TYPE ZLFM1_18,

      GT_LFM1_ALV TYPE STANDARD TABLE OF ZLFM1_18.



"### ALV

TYPES: BEGIN OF TY_VIEW_ALL,

         " ZLFA1_18

         LIFNR    TYPE ZLFA1_18-LIFNR,

         NAME1    TYPE ZLFA1_18-NAME1,

         LAND1    TYPE ZLFA1_18-LAND1,

         KTOKK    TYPE ZLFA1_18-KTOKK,

         STCD1    TYPE ZLFA1_18-STCD1,

         STCD2    TYPE ZLFA1_18-STCD2, "#####

         STRAS    TYPE ZLFA1_18-STRAS, "##



         " ZLFB1_18

         BUKRS    TYPE ZLFB1_18-BUKRS,

         AKONT    TYPE ZLFB1_18-AKONT,

         ZTERM    TYPE ZLFB1_18-ZTERM,

         LOEVM_B1 TYPE ZLFB1_18-LOEVM,



         " ZLFM1_18

         EKORG    TYPE ZLFM1_18-EKORG,

         EKGRP    TYPE ZLFM1_18-EKGRP,

         WAERS    TYPE ZLFM1_18-WAERS,

         MWSKZ    TYPE ZLFM1_18-MWSKZ,

         LOEVM_M1 TYPE ZLFM1_18-LOEVM,

       END OF TY_VIEW_ALL.



DATA: GT_VIEW_ALV TYPE STANDARD TABLE OF TY_VIEW_ALL,

      GS_VIEW_ALV TYPE TY_VIEW_ALL.



DATA: GC_GRID TYPE REF TO CL_GUI_ALV_GRID.



DATA: GC_DOCKING_0100   TYPE REF TO CL_GUI_DOCKING_CONTAINER,

      GC_SPLITTER_1     TYPE REF TO CL_GUI_SPLITTER_CONTAINER,

      GC_SPLITTER_2     TYPE REF TO CL_GUI_SPLITTER_CONTAINER,

      GC_CONTAINER1     TYPE REF TO CL_GUI_CONTAINER,

      GC_CONTAINER2     TYPE REF TO CL_GUI_CONTAINER,

      GC_CONTAINER3     TYPE REF TO CL_GUI_CONTAINER,

      GC_CONTAINER4     TYPE REF TO CL_GUI_CONTAINER,

      GC_GRID1          TYPE REF TO CL_GUI_ALV_GRID,

      GC_GRID2          TYPE REF TO CL_GUI_ALV_GRID,

      GC_GRID3          TYPE REF TO CL_GUI_ALV_GRID.



DATA: GC_DOCKING_0200   TYPE REF TO CL_GUI_DOCKING_CONTAINER,

      GC_GRID_0200      TYPE REF TO CL_GUI_ALV_GRID.





DATA : GS_FIELDCAT  TYPE LVC_S_FCAT,

       GT_FIELDCAT1 TYPE LVC_T_FCAT,

       GT_FIELDCAT2 TYPE LVC_T_FCAT,

       GT_FIELDCAT3 TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.

DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT1 TYPE LVC_T_SORT.

DATA : GT_SORT2 TYPE LVC_T_SORT.

DATA : GT_SORT3 TYPE LVC_T_SORT.



DATA : GS_VARIANT TYPE DISVARIANT.