
*&---------------------------------------------------------------------*

*&  Include           ZMM18_001_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  PARAMETERS:

    P_LIFNR TYPE LIFNR       MODIF ID M2,   "#####(## #)

    P_BUKRS TYPE BUKRS       MODIF ID M0,   "####(##)

    P_KTOKK LIKE ZLFA1_18-KTOKK MODIF ID M1."#####(## #)



SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  SELECTION-SCREEN BEGIN OF LINE.



    PARAMETERS: P_CR RADIOBUTTON GROUP R1 USER-COMMAND UC1 DEFAULT 'X'."##

    SELECTION-SCREEN COMMENT 10(6) FOR FIELD P_CR.



    PARAMETERS: P_DIS RADIOBUTTON GROUP R1."##

    SELECTION-SCREEN COMMENT 25(6) FOR FIELD P_DIS.



  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B2.