
*&---------------------------------------------------------------------*

*&  Include  ZEDR018_020_TOP

*&---------------------------------------------------------------------*






DATA : BEGIN OF GS_STUDENT,

         ZCOLOR  TYPE C LENGTH 4,

         ZCODE   TYPE ZEDT018_001-ZCODE,

         ZPERNR  TYPE ZEDT018_001-ZPERNR,

         ZKNAME  TYPE ZEDT018_001-ZKNAME,

         ZENAME  TYPE ZEDT018_001-ZENAME,

         ZGENDER TYPE ZEDT018_001-ZGENDER,

         ZSUM    TYPE ZEDT018_002-ZSUM,

         ZMAJOR  LIKE ZEDT018_002-ZMAJOR,

         ZMNAME  LIKE ZEDT018_002-ZMNAME,

       END OF GS_STUDENT.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.



" SCREEN OK CODE

DATA : OK_CODE TYPE SY-UCOMM. " ### ## ### ### ###### ### ## ####### ### ## ##.



DATA : GS_FIELDCAT TYPE SLIS_FIELDCAT_ALV.

DATA : GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV.



DATA : GS_LAYOUT TYPE SLIS_LAYOUT_ALV.



DATA : GS_SORT TYPE SLIS_SORTINFO_ALV.

DATA : GT_SORT TYPE SLIS_T_SORTINFO_ALV.