
*&---------------------------------------------------------------------*

*& Report ZEDR12_SELECTOPTIONS001

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR12_SELECTOPTIONS001.

TABLES: ZEDT12_001.



DATA: BEGIN OF GS_STUDENT.

  include structure
ZEDT12_001
.

DATA: END OF GS_STUDENT.

DATA: GT_STUDENT LIKE TABLE OF GS_STUDENT.



SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

 SELECT-OPTIONS : S_ZCODE FOR ZEDT12_001-ZCODE DEFAULT 'SSU-01' NO INTERVALS. "TO 'SSU-99' SIGN I OPTION BT

"SELECT-OPTIONS ### ##. #### ##.

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

 PARAMETERS: P_ZGEN LIKE ZEDT12_001-ZGENDER.

SELECTION-SCREEN END OF BLOCK B2.



SELECT * FROM ZEDT12_001

  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

  WHERE ZCODE IN S_ZCODE

  AND ZGENDER = P_ZGEN.



IF GT_STUDENT[] IS NOT INITIAL.

  CLEAR: GS_STUDENT.

  LOOP AT GT_STUDENT INTO GS_STUDENT.

    WRITE:/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME.

  ENDLOOP.

ELSE.

  WRITE:/ '### ##'.

ENDIF.