
*&---------------------------------------------------------------------*

*&  Include           ZMMR13_003_TOP

*&---------------------------------------------------------------------*




DATA : GS_EKKO TYPE ZEKKO_13,         "######"

       GT_EKKO LIKE TABLE OF GS_EKKO,

       GS_EKPO TYPE ZEKPO_13,         "#######"

       GT_EKPO LIKE TABLE OF GS_EKPO,

       GS_MKPF TYPE ZMKPF_13,         "######"

       GT_MKPF LIKE TABLE OF GS_MKPF,

       GS_MSEG TYPE ZMSEG_13,         "#######"

       GT_MSEG LIKE TABLE OF GS_MSEG.



DATA : BEGIN OF GS_MSEG_DISPLAY,

       MARK TYPE C LENGTH 1.

       include structure
ZMSEG_13
.

DATA : END OF GS_MSEG_DISPLAY,

GT_MSEG_DISPLAY LIKE TABLE OF GS_MSEG_DISPLAY.



DATA : BEGIN OF GS_ITEM,

  MARK TYPE C LENGTH 1,      "######"

  EBELN TYPE ZEKKO_13-EBELN, "######"

  EBELP TYPE ZEKPO_13-EBELP, "####"

  LIFNR TYPE ZEKKO_13-LIFNR, "###"

  BEDAT TYPE ZEKKO_13-BEDAT, "###"

  WAERS TYPE ZEKKO_13-WAERS, "##"

  MATNR TYPE ZEKPO_13-MATNR, "####"

  MATNAME TYPE ZEKPO_13-MATNAME,"###"

  MENGE TYPE ZEKPO_13-MENGE, "##"

  MEINS TYPE ZEKPO_13-MEINS, "##"

  STPRS TYPE ZEKPO_13-STPRS, "##"

  PRDAT TYPE ZEKPO_13-PRDAT, "###"

  WERKS TYPE ZEKPO_13-WERKS, "###"

  LGORT TYPE ZEKPO_13-LGORT, "####"

  WEMNG TYPE ZEKPO_13-MENGE, "#####"

  REMNG TYPE ZEKPO_13-MENGE, "## ##"

  ERFMG TYPE ZEKPO_13-MENGE, "## ## ##"

  BUKRS TYPE BUKRS,          "## ##, ### ### # ###"

  END OF GS_ITEM,

  GT_ITEM LIKE TABLE OF GS_ITEM.



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER.

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID,

       GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID. "200"



DATA : GO_EVENT TYPE REF TO EVENT.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT,

       GT_FIELDCAT TYPE LVC_T_FCAT,

       GT_FIELDCAT2 TYPE LVC_T_FCAT. "200"



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT TYPE LVC_T_SORT.



DATA : GS_VARIANT TYPE DISVARIANT.



DATA: GT_EXCLUDE TYPE UI_FUNCTIONS,

      GS_EXCLUDE TYPE UI_FUNC.



DATA : GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



DATA : GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.