
*&---------------------------------------------------------------------*

*&  Include           ZMM03_002_SCR

*&---------------------------------------------------------------------*






"## ## ## ## (MODIF ID : CRE)

"####, ###, ###

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  PARAMETERS : P_BUKRS TYPE ZEDT03_EKKO-BUKRS MODIF ID CRE, "####

               P_LIFNR TYPE ZEDT03_EKKO-LIFNR MODIF ID CRE, " ###

               P_BEDAT TYPE ZEDT03_EKKO-BEDAT MODIF ID CRE DEFAULT SY-DATUM. " ###

SELECTION-SCREEN END OF BLOCK B1.



"## ## ## ## (MODIF ID : DIS)

"###, ####, PO##

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  SELECT-OPTIONS: S_LIFNR FOR ZEDT03_EKKO-LIFNR MODIF ID DIS, " ###

                  S_BUKRS FOR ZEDT03_EKKO-BUKRS MODIF ID DIS, " ####

                  S_EBELN FOR ZEDT03_EKKO-EBELN MODIF ID DIS. " PO##

SELECTION-SCREEN END OF BLOCK B2.



"## OR ## ##

SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME.

  SELECTION-SCREEN BEGIN OF LINE.

    PARAMETERS: P_CRE  RADIOBUTTON GROUP RG1 DEFAULT 'X' USER-COMMAND U1.

    SELECTION-SCREEN COMMENT 3(10) TEXT-C01 FOR FIELD P_CRE.



    PARAMETERS: P_DIS RADIOBUTTON GROUP RG1.

    SELECTION-SCREEN COMMENT 18(10) TEXT-C02 FOR FIELD P_DIS.

  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B3.