
*&---------------------------------------------------------------------*

*&  Include           ZPRACTICE008_CONTAINER18_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

SELECT-OPTIONS : S_ZORDNO FOR ZEDT018_100-ZORDNO.

PARAMETERS : P_ZID LIKE ZEDT018_100-ZIDCODE.

SELECT-OPTIONS : S_ZMATNR FOR ZEDT018_100-ZMATNR.

SELECT-OPTIONS : S_ZJDATE FOR ZEDT018_100-ZJDATE MODIF ID M1.

SELECT-OPTIONS : S_ZDDATE FOR ZEDT018_101-ZDDATE MODIF ID M2.

SELECTION-SCREEN END OF BLOCK B1.





SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

SELECTION-SCREEN BEGIN OF LINE.

PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

SELECTION-SCREEN COMMENT (10) FOR FIELD P_R1. " ### ## ## #(###) ##

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.

PARAMETERS : P_R2 RADIOBUTTON GROUP R1. "## ## ### ### ## ##### #.

SELECTION-SCREEN COMMENT (10) FOR FIELD P_R2. " ## #(###) ##

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B2.



SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME.

PARAMETERS : P_CH AS CHECKBOX DEFAULT 'X'.

SELECTION-SCREEN END OF BLOCK B3.