
*&---------------------------------------------------------------------*

*&  Include           ZEDR08_026_TOP

*&---------------------------------------------------------------------*






TABLES: ZEDT08_001.



DATA: BEGIN OF GS_STUDENT,

  ZCOLOR TYPE C LENGTH 4,

  ZCODE LIKE ZEDT08_001-ZCODE,

  ZPERNR LIKE ZEDT08_001-ZPERNR,

  ZKNAME LIKE ZEDT08_001-ZKNAME,

  ZENAME LIKE ZEDT08_001-ZENAME,

  ZGENDER LIKE ZEDT08_001-ZGENDER,

  ZSUM LIKE ZEDT08_002-ZSUMM,

  ZMAJOR LIKE ZEDT08_002-ZMAJOR,

  ZMNAME LIKE ZEDT08_002-ZMNAME,

  END OF GS_STUDENT.



DATA: GT_STUDENT LIKE TABLE OF GS_STUDENT.



DATA: OK_CODE TYPE SY-UCOMM.



DATA: GS_FIELDCAT TYPE SLIS_FIELDCAT_ALV.

DATA: GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV.

DATA: GS_LAYOUT TYPE SLIS_LAYOUT_ALV.

DATA: GS_SORT TYPE SLIS_SORTINFO_ALV.

DATA: GT_SORT TYPE SLIS_T_SORTINFO_ALV.



DATA: GC_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER.



DATA: GC_GRID TYPE REF TO CL_GUI_ALV_GRID.