
*&---------------------------------------------------------------------*

*&  Include           ZEDR19_PRACTICE009_SCR

*&---------------------------------------------------------------------*






SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.



  " ## #### - ####

  SELECT-OPTIONS: S_PERNR FOR ZEDT19_102-ZPERNR MODIF ID ALL.



  " ##### ####

  PARAMETERS: P_DATE TYPE D NO-DISPLAY MODIF ID M1.

  PARAMETERS : P_DATE_D TYPE CHAR10 MODIF ID M1.

  SELECT-OPTIONS: S_DEPT FOR ZEDT19_102-ZDEPCODE NO INTERVALS NO-EXTENSION MODIF ID M1.



SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME.



  PARAMETERS: P_CHK1 AS CHECKBOX DEFAULT 'X' MODIF ID M1. "### ##



SELECTION-SCREEN END OF BLOCK B3.