
*&---------------------------------------------------------------------*

*&  Include           ZEDR05_PRACTICE008_TOP

*&---------------------------------------------------------------------*






TABLES : ZEDT05_100, ZEDT05_101.





RANGES : R_FG FOR ZEDT05_100-ZSALE_FG.

RANGES : R_ZG FOR ZEDT05_101-ZFLAG.





DATA : BEGIN OF GS_ORDER.

  include structure
ZEDT05_100
. "#### ###

DATA : END OF GS_ORDER.

DATA : GT_ORDER LIKE TABLE OF GS_ORDER.



DATA : BEGIN OF GS_100, "ALV###

  ICON TYPE C LENGTH 4,

  ZORDNO LIKE ZEDT05_100-ZORDNO,

  ZIDCODE LIKE ZEDT05_100-ZIDCODE,

  ZMATNR LIKE ZEDT05_100-ZMATNR,

  ZMATNAME LIKE ZEDT05_100-ZMATNAME,

  ZMAT_NAME TYPE C LENGTH 8,

  ZVOLUM LIKE ZEDT05_100-ZVOLUM,

  VRKME LIKE ZEDT05_100-VRKME,

  ZNSAMT LIKE ZEDT05_100-ZNSAMT,

  ZSLAMT LIKE ZEDT05_100-ZSLAMT,

  ZDCAMT LIKE ZEDT05_100-ZDCAMT,

  ZWAERS LIKE ZEDT05_100-ZWAERS,

  ZSALE_NAME TYPE C LENGTH 4,

  ZJDATE LIKE ZEDT05_100-ZJDATE,

  ZRET_NAME TYPE C LENGTH 10,

  ZRDATE LIKE ZEDT05_100-ZRDATE,

  END OF GS_100.

DATA : GT_100 LIKE TABLE OF GS_100.



DATA : BEGIN OF GS_DELIVERY. "#### ###

  include structure
ZEDT05_101
.

DATA : END OF GS_DELIVERY.

DATA : GT_DELIVERY LIKE TABLE OF GS_DELIVERY.



DATA : BEGIN OF GS_200, "ALV###

  ICON TYPE C LENGTH 4,

  ZORDNO LIKE ZEDT05_101-ZORDNO,

  ZIDCODE LIKE ZEDT05_101-ZIDCODE,

  ZMATNR LIKE ZEDT05_101-ZMATNR,

  ZMATNAME LIKE ZEDT05_101-ZMATNAME,

  ZMAT_NAME TYPE C LENGTH 8,

  ZVOLUM LIKE ZEDT05_101-ZVOLUM,

  VRKME LIKE ZEDT05_101-VRKME,

  ZSLAMT LIKE ZEDT05_101-ZSLAMT,

  ZWAERS LIKE ZEDT05_100-ZWAERS,

  ZDFLAG_NAME TYPE C LENGTH 8,

  ZDGUBUN_NAME TYPE C LENGTH 6,

  ZDDATE LIKE ZEDT05_101-ZDDATE,

  ZRDATE LIKE ZEDT05_101-ZRDATE,

  ZFLAG LIKE ZEDT05_101-ZFLAG,

  END OF GS_200.

DATA : GT_200 LIKE TABLE OF GS_200.





DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER,

      GC_GRID_100 TYPE REF TO CL_GUI_ALV_GRID,

      GC_GRID_200 TYPE REF TO CL_GUI_ALV_GRID,

      GS_FIELDCAT TYPE LVC_S_FCAT,

      GT_FIELDCAT TYPE LVC_T_FCAT,

      GS_SORT TYPE LVC_S_SORT,

      GT_SORT TYPE LVC_T_SORT,

      GS_VARIANT TYPE DISVARIANT,

      GS_LAYOUT TYPE LVC_S_LAYO.