
*&---------------------------------------------------------------------*

*&  Include           ZMM12_002_TOP

*&---------------------------------------------------------------------*






TABLES: ZEKKO_12, ZEKPO_12. " #### ## / #### ##

TABLES: ZLFA1_12, ZLFB1_12. "##### / #######

TABLES: SSCRFIELDS.

data: gv_mwskz like zlfm1_12-mwskz.



DATA : GS_LFA1 TYPE ZLFA1_12, "#####"

       GT_LFA1 LIKE TABLE OF GS_LFA1,

       GS_LFB1 TYPE ZLFB1_12, "#######"

       GT_LFB1 LIKE TABLE OF GS_LFB1,

       GS_LFM1 TYPE ZLFM1_12, "#######"

       GT_LFM1 LIKE TABLE OF GS_LFM1.



DATA: GS_EKKO TYPE ZEKKO_12.

DATA: GT_EKKO LIKE TABLE OF GS_EKKO.



DATA: BEGIN OF GS_EKPO,

  WAERS TYPE WAERS.




*  MWSKZ TYPE MWSKZ. " ####




  include structure
ZEKPO_12
.

DATA: END OF GS_EKPO.

DATA: GT_EKPO LIKE TABLE OF GS_EKPO.



DATA : BEGIN OF GS_DISPLAY,

  EBELN TYPE ZEKKO_12-EBELN, "######"

  BUKRS TYPE ZEKKO_12-BUKRS, "####"

  EKGRP TYPE ZEKKO_12-EKGRP, "####"

  EKORG TYPE ZEKKO_12-EKORG, "####"

  LIFNR TYPE ZEKKO_12-LIFNR, "###"

  BEDAT TYPE ZEKKO_12-BEDAT, "###"

  WAERS TYPE ZEKKO_12-WAERS, "##"

  EBELP TYPE ZEKPO_12-EBELP, "####"

  MATNR TYPE ZEKPO_12-MATNR, "####"

  MATNAME TYPE ZEKPO_12-MATNAME,"###"

  MENGE TYPE ZEKPO_12-MENGE, "##"

  MEINS TYPE ZEKPO_12-MEINS, "##"

  STPRS TYPE ZEKPO_12-STPRS, "##"

  PRDAT TYPE ZEKPO_12-PRDAT, "###"

  WERKS TYPE ZEKPO_12-WERKS, "###"

  LGORT TYPE ZEKPO_12-LGORT, "####"

  END OF GS_DISPLAY,

  GT_DISPLAY LIKE TABLE OF GS_DISPLAY.



" ## OK_CODE / ALV-EVENT##

DATA: OK_CODE TYPE SY-UCOMM.



DATA : GO_EVENT TYPE REF TO EVENT.

DATA : GS_VARIANT TYPE DISVARIANT.

"######

DATA: GC_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER.

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

"### ##

DATA: GC_GRID_HEADER TYPE REF TO CL_GUI_ALV_GRID.

DATA: GC_GRID_ITEM TYPE REF TO CL_GUI_ALV_GRID.

DATA: GC_GRID TYPE REF TO CL_GUI_ALV_GRID.

"######

DATA: GT_FIELDCAT_HEADER TYPE LVC_T_FCAT.

DATA: GS_FIELDCAT_HEADER TYPE LVC_S_FCAT.

DATA: GT_FIELDCAT_ITEM TYPE LVC_T_FCAT.

DATA: GS_FIELDCAT_ITEM TYPE LVC_S_FCAT.

DATA: GT_FIELDCAT_DISP TYPE LVC_T_FCAT,

      GS_FIELDCAT_DISP TYPE LVC_S_FCAT.

" ALV ####

DATA GS_LAYOUT TYPE LVC_S_LAYO.

DATA: GT_EXCLUDE TYPE UI_FUNCTIONS,

      GS_EXCLUDE TYPE UI_FUNC.



DATA GS_SORT TYPE LVC_S_SORT.

DATA GT_SORT TYPE LVC_T_SORT.