
*&---------------------------------------------------------------------*

*&  Include           ZEDR09_PRACTICE008_TOP

*&---------------------------------------------------------------------*






" select-options# ## ### ##

TABLES : ZEDT09_100, ZEDT09_101.



"## ('X' ##)

CONSTANTS : C_X TYPE C VALUE 'X'.



" #### ### #### # range ## ##

RANGES : R_ZFLAG FOR ZEDT09_101-ZFLAG.



" ### OKCODE

DATA : OK_CODE TYPE SY-UCOMM.



" ###### ## - ###, ## ###

DATA : BEGIN OF GS_ORDER,

  ZORDNO LIKE ZEDT09_100-ZORDNO,    "####

  ZIDCODE LIKE ZEDT09_100-ZIDCODE,  "##ID

  ZMATNR LIKE ZEDT09_100-ZMATNR,    "####

  ZMATNAME LIKE ZEDT09_100-ZMATNAME, "###

  ZMTART LIKE ZEDT09_100-ZMTART,    "####

  ZVOLUM LIKE ZEDT09_100-ZVOLUM,    "##

  VRKME LIKE ZEDT09_100-VRKME,      "##

  ZNSAMT LIKE ZEDT09_100-ZNSAMT,    "####

  ZSLAMT LIKE ZEDT09_100-ZSLAMT,    "####

  ZDCAMT LIKE ZEDT09_100-ZDCAMT,    "####

  ZWAERS LIKE ZEDT09_100-ZWAERS,    "##

  ZSALE_FG LIKE ZEDT09_100-ZSALE_FG, "####

  ZJDATE LIKE ZEDT09_100-ZJDATE,     "####

  ZRET_FG LIKE ZEDT09_100-ZRET_FG,   "####

  ZRDATE LIKE ZEDT09_100-ZRDATE,     "####

END OF GS_ORDER.

DATA : GT_ORDER LIKE TABLE OF GS_ORDER.



DATA : BEGIN OF GS_ORDER_ALV,

  ZCOLOR TYPE C LENGTH 4,           "### ####

  ZORDNO LIKE ZEDT09_100-ZORDNO,    "####

  ZIDCODE LIKE ZEDT09_100-ZIDCODE,  "##ID

  ZMATNR LIKE ZEDT09_100-ZMATNR,    "####

  ZMATNAME LIKE ZEDT09_100-ZMATNAME, "###

  ZMTART_NAME TYPE C LENGTH 10,       "####_##

  ZVOLUM LIKE ZEDT09_100-ZVOLUM,    "##

  VRKME LIKE ZEDT09_100-VRKME,      "##

  ZNSAMT LIKE ZEDT09_100-ZNSAMT,    "####

  ZSLAMT LIKE ZEDT09_100-ZSLAMT,    "####

  ZDCAMT LIKE ZEDT09_100-ZDCAMT,    "####

  ZWAERS LIKE ZEDT09_100-ZWAERS,    "##

  ZSALE_NAME TYPE C LENGTH 10,        "####_##

  ZJDATE LIKE ZEDT09_100-ZJDATE,     "####

  ZRET_NAME TYPE C LENGTH 20,         "####_##

  ZRDATE LIKE ZEDT09_100-ZRDATE,     "####

END OF GS_ORDER_ALV.

DATA : GT_ORDER_ALV LIKE TABLE OF GS_ORDER_ALV.



" ###### ## - ###, #####

DATA : BEGIN OF GS_DELIVERY,

  ZORDNO LIKE ZEDT09_101-ZORDNO,     "####

  ZIDCODE LIKE ZEDT09_101-ZIDCODE,   "##ID

  ZMATNR LIKE ZEDT09_101-ZMATNR,     "####

  ZMATNAME LIKE ZEDT09_101-ZMATNAME, "###

  ZMTART LIKE ZEDT09_101-ZMTART,     "####

  ZVOLUM LIKE ZEDT09_101-ZVOLUM,    "##

  VRKME LIKE ZEDT09_101-VRKME,       "##

  ZSLAMT LIKE ZEDT09_101-ZSLAMT,     "####

  ZWAERS LIKE ZEDT09_101-ZWAERS,     "##

  ZDFLAG LIKE ZEDT09_101-ZDFLAG,     "####

  ZDGUBUN LIKE ZEDT09_101-ZDGUBUN,   "####

  ZDDATE LIKE ZEDT09_101-ZDDATE,     "####

  ZRDATE LIKE ZEDT09_101-ZRDATE,     "####

  ZFLAG LIKE ZEDT09_101-ZFLAG,       "####

END OF GS_DELIVERY.

DATA : GT_DELIVERY LIKE TABLE OF GS_DELIVERY.



DATA : BEGIN OF GS_DELIVERY_ALV,

  ZCOLOR TYPE C LENGTH 4,           "### ####

  ZORDNO LIKE ZEDT09_101-ZORDNO,     "####

  ZIDCODE LIKE ZEDT09_101-ZIDCODE,   "##ID

  ZMATNR LIKE ZEDT09_101-ZMATNR,     "####

  ZMATNAME LIKE ZEDT09_101-ZMATNAME, "###

  ZMTART_NAME TYPE C LENGTH 10,       "####_##

  ZVOLUM LIKE ZEDT09_101-ZVOLUM,    "##

  VRKME LIKE ZEDT09_101-VRKME,       "##

  ZSLAMT LIKE ZEDT09_101-ZSLAMT,     "####

  ZWAERS LIKE ZEDT09_101-ZWAERS,     "##

  ZDFLAG_NAME TYPE C LENGTH 20,        "####_##

  ZDGUBUN_NAME TYPE C LENGTH 20,       "####_##

  ZDDATE LIKE ZEDT09_101-ZDDATE,     "####

  ZRDATE LIKE ZEDT09_101-ZRDATE,     "####

  ZFLAG LIKE ZEDT09_101-ZFLAG,       "####

END OF GS_DELIVERY_ALV.

DATA : GT_DELIVERY_ALV LIKE TABLE OF GS_DELIVERY_ALV.



"docking #### ## ## ##

DATA : GC_DOCKING_100 TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA : GC_DOCKING_200 TYPE REF TO CL_GUI_DOCKING_CONTAINER.



"grid ## ## ##

DATA : GC_GRID_100 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID_200 TYPE REF TO CL_GUI_ALV_GRID.



"######, ####, #### ####, ## ## ##

DATA : GS_FIELDCAT TYPE LVC_S_FCAT,

       GT_FIELDCAT TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.

DATA : GS_VARIANT TYPE DISVARIANT.



DATA : GS_SORT TYPE LVC_S_SORT,

       GT_SORT TYPE LVC_T_SORT.