
*&---------------------------------------------------------------------*

*&  Include           ZEDR25_PRACTICE008_TOP

*&---------------------------------------------------------------------*

*&---------------------------------------------------------------------*

*&  Include           ZEDR25_PRACTICE008_TOP

*&---------------------------------------------------------------------*




TABLES : ZEDT25_100, ZEDT25_101.



CONSTANTS : C_X TYPE CHAR1 VALUE 'X'.

CONSTANTS : C_A TYPE CHAR1 VALUE 'A'.

RANGES : R_FG FOR ZEDT25_100-ZSALE_FG.

RANGES : R_ZG FOR ZEDT25_101-ZFLAG.



DATA : BEGIN OF GS_ORDER, "#### ###

  ZORDNO   LIKE ZEDT25_100-ZORDNO,   "####

  ZIDCODE  LIKE ZEDT25_100-ZIDCODE,  "##ID

  ZMATNR   LIKE ZEDT25_100-ZMATNR,   "####

  ZMTART   LIKE ZEDT25_100-ZMTART,   "####

  ZMATNAME LIKE ZEDT25_100-ZMATNAME, "###

  ZVOLUM   LIKE ZEDT25_100-ZVOLUM,   "##

  VRKME    LIKE ZEDT25_100-VRKME,    "####

  ZNSAMT   LIKE ZEDT25_100-ZNSAMT,   "####

  ZSLAMT   LIKE ZEDT25_100-ZSLAMT,   "####

  ZDCAMT   LIKE ZEDT25_100-ZDCAMT,   "####

  ZWAERS   LIKE ZEDT25_100-ZWAERS,   "##

  ZDC_FG   LIKE ZEDT25_100-ZDC_FG,   "####

  ZSALE_FG LIKE ZEDT25_100-ZSALE_FG, "####

  ZRET_FG  LIKE ZEDT25_100-ZRET_FG,  "####

  ZJDATE   LIKE ZEDT25_100-ZJDATE,   "####

  ZRDATE   LIKE ZEDT25_100-ZRDATE,   "####

END OF GS_ORDER.

DATA : GT_ORDER LIKE TABLE OF GS_ORDER.



DATA : BEGIN OF GS_0100, "ALV###

  ICON TYPE C LENGTH 4,

  ZORDNO    LIKE ZEDT25_100-ZORDNO,   "####

  ZIDCODE   LIKE ZEDT25_100-ZIDCODE,  "##ID

  ZMATNR    LIKE ZEDT25_100-ZMATNR,   "####

  ZMATNAME  LIKE ZEDT25_100-ZMATNAME, "#####

  ZMAT_NAME TYPE C LENGTH 8,          "#####

  ZVOLUM    LIKE ZEDT25_100-ZVOLUM,   "##

  VRKME     LIKE ZEDT25_100-VRKME,    "##

  ZNSAMT    LIKE ZEDT25_100-ZNSAMT,   "####

  ZSLAMT    LIKE ZEDT25_100-ZSLAMT,   "####

  ZDCAMT    LIKE ZEDT25_100-ZDCAMT,   "####

  ZWAERS    LIKE ZEDT25_100-ZWAERS,   "##

  ZSALE_NAME TYPE C LENGTH 4,         "####

  ZJDATE    LIKE ZEDT25_100-ZJDATE,   "####

  ZRET_NAME TYPE C LENGTH 10,         "####

  ZRDATE    LIKE ZEDT25_100-ZRDATE,   "####

END OF GS_0100.

DATA : GT_0100 LIKE TABLE OF GS_0100.



DATA : BEGIN OF GS_DELIVERY, "#### ###

  ZORDNO   LIKE ZEDT25_101-ZORDNO,   "####

  ZIDCODE  LIKE ZEDT25_101-ZIDCODE,  "##ID

  ZMATNR   LIKE ZEDT25_101-ZMATNR,   "####

  ZMTART   LIKE ZEDT25_101-ZMTART,   "####

  ZMATNAME LIKE ZEDT25_101-ZMATNAME, "###

  ZVOLUM   LIKE ZEDT25_101-ZVOLUM,   "##

  VRKME    LIKE ZEDT25_101-VRKME,    "####

  ZSLAMT   LIKE ZEDT25_101-ZSLAMT,   "####

  ZWAERS   LIKE ZEDT25_100-ZWAERS,   "##

  ZDFLAG   LIKE ZEDT25_101-ZDFLAG,   "####

  ZDGUBUN  LIKE ZEDT25_101-ZDGUBUN,  "####

  ZDDATE   LIKE ZEDT25_101-ZDDATE,   "####

  ZRDATE   LIKE ZEDT25_101-ZRDATE,   "####

  ZFLAG    LIKE ZEDT25_101-ZFLAG,    "FLAG

END OF GS_DELIVERY.

DATA : GT_DELIVERY LIKE TABLE OF GS_DELIVERY.



DATA : BEGIN OF GS_0200, "ALV###

  ICON TYPE C LENGTH 4,

  ZORDNO       LIKE ZEDT25_101-ZORDNO,   "####

  ZIDCODE      LIKE ZEDT25_101-ZIDCODE,  "##ID

  ZMATNR       LIKE ZEDT25_101-ZMATNR,   "####

  ZMATNAME     LIKE ZEDT25_101-ZMATNAME, "###

  ZMAT_NAME    TYPE C LENGTH 8,          "#####

  ZVOLUM       LIKE ZEDT25_101-ZVOLUM,   "##

  VRKME        LIKE ZEDT25_101-VRKME,    "####

  ZSLAMT       LIKE ZEDT25_101-ZSLAMT,   "####

  ZWAERS       LIKE ZEDT25_100-ZWAERS,   "##

  ZDFLAG_NAME  TYPE C LENGTH 8,          "####

  ZDGUBUN_NAME TYPE C LENGTH 6,          "####

  ZDDATE       LIKE ZEDT25_101-ZDDATE,   "####

  ZRDATE       LIKE ZEDT25_101-ZRDATE,   "####

  ZFLAG        LIKE ZEDT25_101-ZFLAG,    "FLAG

END OF GS_0200.

DATA : GT_0200 LIKE TABLE OF GS_0200.



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.



DATA : GC_GRID_100 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID_200 TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT,

       GT_FIELDCAT TYPE LVC_T_FCAT.

DATA : GS_LAYOUT TYPE LVC_S_LAYO.

DATA : GS_SORT TYPE LVC_S_SORT .

DATA : GT_SORT TYPE LVC_T_SORT.



DATA : GS_VARIANT TYPE DISVARIANT.