
*&---------------------------------------------------------------------*

*&  Include           ZEDR12_MODULEPOOL_TOP

*&---------------------------------------------------------------------*




TABLES: ZEDT12_001.



DATA: BEGIN OF GS_STUDENT,

  ZCOLOR TYPE C LENGTH 4,

  ZCODE LIKE ZEDT12_001-ZCODE, "####

  ZPERNR LIKE ZEDT12_001-ZPERNR, "####

  ZKNAME LIKE ZEDT12_001-ZKNAME, "##

  ZENAME LIKE ZEDT12_001-ZENAME, "####

  ZGENDER LIKE ZEDT12_001-ZGENDER, "##

  ZSUM LIKE ZEDT12_002-ZSUM, "##

  ZMAJOR LIKE ZEDT12_002-ZMAJOR, "##

  ZMNAME LIKE ZEDT12_002-ZMNAME, "###

  END OF GS_STUDENT.

DATA: GT_STUDENT LIKE TABLE OF GS_STUDENT.





DATA: OK_CODE TYPE SY-UCOMM. "#### ##### ## #####



DATA: GS_FIELDCAT TYPE SLIS_FIELDCAT_ALV.

DATA: GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV.



DATA: GS_LAYOUT TYPE SLIS_LAYOUT_ALV.



DATA: GS_SORT TYPE SLIS_SORTINFO_ALV.

DATA: GT_SORT TYPE SLIS_T_SORTINFO_ALV.