
SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME.

  PARAMETERS : p_ebeln TYPE ZMSEG21-ebeln MODIF ID all. "####

  PARAMETERS : p_werks TYPE ZMSEG21-werks MODIF ID all. "###

  PARAMETERS : p_stdat TYPE sy-datum MODIF ID m1. "#####

SELECTION-SCREEN END OF BLOCK b1.



SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME.

    PARAMETERS : p_rad1 RADIOBUTTON GROUP rb1 DEFAULT 'X' USER-COMMAND uc1. "####

    PARAMETERS : p_rad2 RADIOBUTTON GROUP rb1. "##

SELECTION-SCREEN END OF BLOCK b2.