
*&---------------------------------------------------------------------*

*& Report ZEDR04_052

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR04_052.



DATA : BEGIN OF GS_STUDENT,

  ZPERNR LIKE ZEDT04_001-ZPERNR,  "####

  ZCODE LIKE ZEDT04_001-ZCODE,    "####

  ZKNAME LIKE ZEDT04_001-ZKNAME,  "####

  ZENAME LIKE ZEDT04_001-ZENAME,  "####

  ZGENDER LIKE ZEDT04_001-ZGENDER,"##

  ZGNAME TYPE C LENGTH 8,  "## ## (##, ##)

  ZTEL LIKE ZEDT04_001-ZTEL,      "####

  END OF GS_STUDENT.

DATA GT_STUDENT LIKE TABLE OF GS_STUDENT.



CLEAR : GS_STUDENT, GT_STUDENT.

GS_STUDENT-ZPERNR = '0000000001'.

GS_STUDENT-ZCODE = 'SSU-01'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'DONG'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01012345678'.

GS_STUDENT-ZGNAME = '####'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_STUDENT-ZGENDER = 'F'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_STUDENT-ZGENDER = 'A'.

APPEND GS_STUDENT TO GT_STUDENT.



CLEAR : GS_STUDENT.

GS_STUDENT-ZPERNR = '0000000002'.

GS_STUDENT-ZCODE = 'SSU-02'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'HOON'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01098765432'.

GS_STUDENT-ZGNAME = '####'.

APPEND GS_STUDENT TO GT_STUDENT.



CLEAR : GS_STUDENT.

GS_STUDENT-ZPERNR = '0000000001'.

GS_STUDENT-ZCODE = 'SSU-01'.

GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'KANG'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01012345678'.

GS_STUDENT-ZGNAME = '####'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_STUDENT-ZKNAME = '###'.

GS_STUDENT-ZENAME = 'DONG'.

GS_STUDENT-ZGENDER = 'F'.

GS_STUDENT-ZGNAME = '####'.

APPEND GS_STUDENT TO GT_STUDENT.



" AT NEW <FIELD> / AT END OF <FIELD> ## # ## ##

SORT GT_STUDENT BY ZCODE ZKNAME ZENAME ZGENDER.



LOOP AT GT_STUDENT INTO GS_STUDENT.

  AT END OF ZENAME.

    GS_STUDENT-ZGNAME = '####'.

    MODIFY GT_STUDENT FROM GS_STUDENT INDEX SY-TABIX TRANSPORTING ZGNAME.

  ENDAT.



  CLEAR GS_STUDENT.

ENDLOOP.



" #### ##

LOOP AT GT_STUDENT INTO GS_STUDENT.

  WRITE : / GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_STUDENT-ZENAME, GS_STUDENT-ZGNAME.

ENDLOOP.