
*&---------------------------------------------------------------------*

*&  Include           ZEDR24_PRACTICE009_TOP

*&---------------------------------------------------------------------*




TABLES : ZEDT24_102. "#### ###

TABLES : ZEDT24_103. "####-####

TABLES : ZEDT24_104. "####

TABLES : ZEDT24_105. "####

TABLES : ZEDT24_106. "####



TYPE-POOLS: ICON.



RANGES : GR_ISQUIT FOR ZEDT24_102-ZQFLAG. "####



"1# ### : #### ### + ####

DATA : BEGIN OF GS_EMPLOYEE,

  ZPERNR LIKE ZEDT24_102-ZPERNR, "####

  ZDEPCODE LIKE ZEDT24_102-ZDEPCODE, "####

  DATBI LIKE ZEDT24_102-DATBI, "VALID TO DATE

  DATAB LIKE ZEDT24_102-DATAB,  "VALID FROM DATE

  ZDEPRANK LIKE ZEDT24_102-ZDEPRANK, "####

  ZEDATE LIKE ZEDT24_102-ZEDATE, "####

  ZQDATE LIKE ZEDT24_102-ZQDATE, "####

  ZQFLAG LIKE ZEDT24_102-ZQFLAG, "####

  ZPNAME LIKE ZEDT24_103-ZPNAME, "####

  ZGENDER LIKE ZEDT24_103-ZGENDER, "##

  ZADDRESS LIKE ZEDT24_103-ZADDRESS, "##

  END OF GS_EMPLOYEE.

DATA : GT_EMPLOYEE LIKE TABLE OF GS_EMPLOYEE.



"2# ### : ####

DATA : BEGIN OF GS_EVAL.

  include structure
ZEDT24_104
.

  DATA : END OF GS_EVAL.

DATA : GT_EVAL LIKE TABLE OF GS_EVAL.



"3# ### : ####

DATA : BEGIN OF GS_CONTRACT.

  include structure
ZEDT24_106
.

  DATA : END OF GS_CONTRACT.

DATA : GT_CONTRACT LIKE TABLE OF GS_CONTRACT.



"## 1# ### : #### ### + ####

DATA : BEGIN OF GS_EMP_RESULT,

  ZICON TYPE ICON_D,  "## (##, ##, ##)

  ZPERNR LIKE ZEDT24_102-ZPERNR,  "####

  ZPNAME LIKE ZEDT24_103-ZPNAME,  "##

  ZDEPNAME TYPE C LENGTH 10,  "(#### ->) ####

  DATBI LIKE ZEDT24_102-DATBI,  "####

  DATAB LIKE ZEDT24_102-DATAB,  "####

  ZDEPRANKNAME TYPE C LENGTH 10,  "##

  ZGENDERNAME TYPE C LENGTH 5,  "##

  ZEDATE LIKE ZEDT24_102-ZEDATE,  "####

  ZADDRESS LIKE ZEDT24_103-ZADDRESS,  "##

  ZQDATE LIKE ZEDT24_102-ZQDATE,  "####

  ZQFLAG LIKE ZEDT24_102-ZQFLAG,  "####

  END OF GS_EMP_RESULT.

DATA : GT_EMP_RESULT LIKE TABLE OF GS_EMP_RESULT.



"## 2# ### : ####

DATA : BEGIN OF GS_EVAL_RESULT,

  ZPERNR LIKE ZEDT24_104-ZPERNR,  "####

  ZDEPNAME TYPE C LENGTH 10,  "(#### ->) ####

  ZYEAR LIKE ZEDT24_104-ZYEAR,  "##

  DATBI LIKE ZEDT24_104-DATBI,  "####

  DATAB LIKE ZEDT24_104-DATAB,  "####

  ZRANK LIKE ZEDT24_104-ZRANK,  "##

  END OF GS_EVAL_RESULT.

DATA : GT_EVAL_RESULT LIKE TABLE OF GS_EVAL_RESULT.



"## 3# ### : ####

DATA : BEGIN OF GS_CON_RESULT,

  ZPERNR LIKE ZEDT24_106-ZPERNR, "####

  ZYEAR LIKE ZEDT24_106-ZYEAR,  "##

  DATBI LIKE ZEDT24_106-DATBI,  "####

  DATAB LIKE ZEDT24_106-DATAB,  "####

  ZSALARY LIKE ZEDT24_106-ZSALARY,  "####

  ZWAERS TYPE WAERS,

  ZBANKNAME TYPE C LENGTH 10, "(ZBANKCODE->ZBANKNAME)###

  ZACCOUNT LIKE ZEDT24_106-ZACCOUNT,  "####

  END OF GS_CON_RESULT.

DATA : GT_CON_RESULT LIKE TABLE OF GS_CON_RESULT.



DATA : OK_CODE TYPE SY-UCOMM.



"## ##

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.



"## ### ## ### ##

DATA : GC_SPLITTER_MAIN TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA : GC_SPLITTER_DOWN TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



DATA : GC_CONTAINER_TOP TYPE REF TO CL_GUI_CONTAINER. "## - #

DATA : GC_CONTAINER_TOP1 TYPE REF TO CL_GUI_CONTAINER. "## - #

DATA : GC_CONTAINER_TOP2 TYPE REF TO CL_GUI_CONTAINER. "##

DATA : GC_CONTAINER_BOTTOM TYPE REF TO CL_GUI_CONTAINER. "## - #



DATA : GC_GRID_TOP1 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID_TOP2 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID_BOTTOM TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_VARIANT TYPE DISVARIANT.



DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT TYPE LVC_T_SORT.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT.

DATA : GT_FC_TOP1 TYPE LVC_T_FCAT.

DATA : GT_FC_TOP2 TYPE LVC_T_FCAT.

DATA : GT_FC_BOTTOM TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.