
*&---------------------------------------------------------------------*

*&  Include           ZMMR04_002_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  PARAMETERS P_LIFNR LIKE ZLFA1_04-LIFNR.            " #####

  PARAMETERS P_BUKRS LIKE ZLFB1_04-BUKRS.            " ####

  PARAMETERS P_BEDAT LIKE ZEKKO04-BEDAT MODIF ID M1. " ###

  PARAMETERS P_EBELN LIKE ZEKKO04-EBELN MODIF ID M2. " PO##

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF LINE.

  " ##

  PARAMETERS P_RD1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

  SELECTION-SCREEN POSITION 3.

  SELECTION-SCREEN COMMENT (10) FOR FIELD P_RD1.



  " ##

  PARAMETERS P_RD2 RADIOBUTTON GROUP R1.

  SELECTION-SCREEN POSITION 20.

  SELECTION-SCREEN COMMENT (10) FOR FIELD P_RD2.

SELECTION-SCREEN END OF LINE.