
*&---------------------------------------------------------------------*

*&  Include           ZMM08_003_TOP

*&---------------------------------------------------------------------*




TABLES: ZEDT08_EKPO,

        ZEDT08_EKKO,

        ZEDT08_MKRF,

        ZEDT08_MSEG.



" CLASS LCL_EVENT_HANDLER DEFINITION DEFERRED.

" DATA: GO_EVENT TYPE REF TO LCL_EVENT_HANDLER.



DATA: GV_TITLE_1(20) TYPE C.

DATA: GV_TITLE_2(20) TYPE C.

DATA: GV_TITLE_3(20) TYPE C.



DATA: OK_CODE TYPE SY-UCOMM.



DATA: BEGIN OF GS_MKRF,

       MBLNR TYPE ZEDT08_MKRF,

       MJAHR TYPE ZEDT08_MKRF,

       BLART TYPE ZEDT08_MKRF,

       BLDAT TYPE ZEDT08_MKRF,

       BUDAT TYPE ZEDT08_MKRF,

       END OF GS_MKRF.



DATA: BEGIN OF GS_ITEM,

       MARK  TYPE C LENGTH 1,         " ####

       EBELN TYPE ZEDT08_EKPO-EBELN,  " ####

       EBELP TYPE ZEDT08_EKPO-EBELP,  " ##

       MATNR TYPE ZEDT08_EKPO-MATNR,  " ####

       MAKTX TYPE ZEDT08_EKPO-MAKTX,  " ###

       WERKS TYPE ZEDT08_EKPO-WERKS,  " ###

       LGORT TYPE ZEDT08_EKPO-LGORT,  " ####

       MENGE TYPE ZEDT08_EKPO-MENGE,  " PO ##

       MEINS TYPE ZEDT08_EKPO-MEINS,  " ##

       WEMNG TYPE ZEDT08_EKPO-MENGE,  " ### ## (## ### #)

       REMNG TYPE ZEDT08_EKPO-MENGE,  " ## ## (PO## - ###)

       ERFMG TYPE ZEDT08_EKPO-MENGE,  " [##] ## ## ##

       LIFNR TYPE ZEDT08_EKKO-LIFNR,  " ###

       DMBTR TYPE ZEDT08_MSEG-DMBTR,  " ## (MSEG ##)

       WAERS TYPE ZEDT08_MSEG-WAERS,  " ##

       END OF GS_ITEM.

DATA: GT_ITEM LIKE TABLE OF GS_ITEM.



TYPES: BEGIN OF TY_WEMNG,

         EBELN TYPE ZEDT08_MSEG-EBELN,

         EBELP TYPE ZEDT08_MSEG-ZEILE,

         MENGE TYPE ZEDT08_MSEG-MENGE,

       END OF TY_WEMNG.

DATA: LT_WEMNG TYPE TABLE OF TY_WEMNG.



DATA: BEGIN OF GS_DOC_LIST,

        MBLNR     TYPE ZEDT08_MKRF-MBLNR, " ####

        MJAHR     TYPE ZEDT08_MKRF-MJAHR, " ##

        BUDAT     TYPE ZEDT08_MKRF-BUDAT, " ###

        COUNT_ITM TYPE I,                 " ## # (##)

      END OF GS_DOC_LIST.

DATA: GT_DOC_LIST LIKE TABLE OF GS_DOC_LIST.



DATA: BEGIN OF GS_DOC_DETAIL,

        MBLNR TYPE ZEDT08_MSEG-MBLNR,

        ZEILE TYPE ZEDT08_MSEG-ZEILE, " ##

        MATNR TYPE ZEDT08_MSEG-MATNR, " ##

        MAKTX TYPE ZEDT08_EKPO-MAKTX, " ### (Join ##)

        MENGE TYPE ZEDT08_MSEG-MENGE, " ##

        MEINS TYPE ZEDT08_MSEG-MEINS, " ##

        DMBTR TYPE ZEDT08_MSEG-DMBTR, " ##

        WAERS TYPE ZEDT08_MSEG-WAERS, " ##

        WERKS TYPE ZEDT08_MSEG-WERKS, " ###

        LGORT TYPE ZEDT08_MSEG-LGORT, " ####

        EBELN TYPE ZEDT08_MSEG-EBELN, " PO ##

        BUKRS TYPE ZEDT08_MSEG-BUKRS, " ####

      END OF GS_DOC_DETAIL.

DATA: GT_DOC_DETAIL LIKE TABLE OF GS_DOC_DETAIL.



DATA: GC_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER,

      GC_GRID   TYPE REF TO CL_GUI_ALV_GRID.



DATA: GC_DOCK_LEFT TYPE REF TO CL_GUI_DOCKING_CONTAINER,

      GC_GRID_LEFT TYPE REF TO CL_GUI_ALV_GRID.



DATA: GC_DOCK_BOTTOM TYPE REF TO CL_GUI_DOCKING_CONTAINER,

      GC_GRID_BOTTOM TYPE REF TO CL_GUI_ALV_GRID.



DATA: GS_FIELDCAT TYPE LVC_S_FCAT,

      GT_FIELDCAT TYPE LVC_T_FCAT,

      GS_LAYOUT   TYPE LVC_S_LAYO,

      GS_VARIANT  TYPE DISVARIANT,

      GS_STABLE   TYPE LVC_S_STBL.