
*&---------------------------------------------------------------------*

*&  Include           ZMM08_003_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT_01.



  " 1. ####

  PARAMETERS: P_EBELN TYPE ZEDT08_EKKO-EBELN MODIF ID M1,

              P_WERKS TYPE ZEDT08_EKPO-WERKS MODIF ID M1,

              P_BUDAT TYPE DATS DEFAULT SY-DATUM MODIF ID M1.



  " 2. ####

  PARAMETERS: P_EBELN2 TYPE ZEDT08_EKKO-EBELN MODIF ID M2,

              P_WERKS2 TYPE ZEDT08_EKPO-WERKS MODIF ID M2.



  SELECTION-SCREEN SKIP.



  " ### ##

  SELECTION-SCREEN BEGIN OF LINE.

    PARAMETERS: P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

    SELECTION-SCREEN COMMENT 3(10) TEXT_02 FOR FIELD P_R1.



    SELECTION-SCREEN POSITION 30.

    PARAMETERS: P_R2 RADIOBUTTON GROUP R1.

    SELECTION-SCREEN COMMENT 32(10) TEXT_03 FOR FIELD P_R2.

  SELECTION-SCREEN END OF LINE.



SELECTION-SCREEN END OF BLOCK B1.