
*&---------------------------------------------------------------------*

*&  Include           ZEDR12_PRACTICE129_TOP

*&---------------------------------------------------------------------*




TABLES : ZEDT12_102, ZEDT12_103. "####

TABLES : ZEDT12_104. "####

TABLES : ZEDT12_106. "####



RANGES : R_ZQFLAG FOR ZEDT12_102-ZQFLAG.



"1) ##### ## ####, ###### ### #### - 1####

DATA : BEGIN OF GS_WORKER,            "####

  ZPERNR LIKE ZEDT12_102-ZPERNR,      "####

  ZPNAME LIKE ZEDT12_103-ZPNAME,      "##

  ZDEPCODE LIKE ZEDT12_102-ZDEPCODE,  "####

  DATBI LIKE ZEDT12_102-DATBI,        "####

  DATAB LIKE ZEDT12_102-DATAB,        "####

  ZDEPRANK LIKE ZEDT12_102-ZDEPRANK,     "####

  ZGENDER LIKE ZEDT12_103-ZGENDER,    "####

  ZEDATE LIKE ZEDT12_102-ZEDATE,      "####

  ZQDATE LIKE ZEDT12_102-ZQDATE,      "####

  ZQFLAG LIKE ZEDT12_102-ZQFLAG,      "####

  ZADDRESS LIKE ZEDT12_103-ZADDRESS,  "##

  END OF GS_WORKER.

DATA : GT_WORKER LIKE TABLE OF GS_WORKER.



DATA : BEGIN OF GS_WORKER_ALV,        "#### ##

  ZCOLOR TYPE C LENGTH 4,             "###

  ZPERNR LIKE ZEDT12_102-ZPERNR,      "####

  ZPNAME LIKE ZEDT12_103-ZPNAME,      "##

  ZDEPCODE_NAME TYPE C LENGTH 10,     "##

  DATBI LIKE ZEDT12_102-DATBI,        "####

  DATAB LIKE ZEDT12_102-DATAB,        "####

  ZDEPRANK_NAME(8),                      "##

  ZGENDER_NAME(4),                    "##

  ZEDATE LIKE ZEDT12_102-ZEDATE,      "####

  ZQDATE LIKE ZEDT12_102-ZQDATE,      "####

  ZQFLAG LIKE ZEDT12_102-ZQFLAG,      "####

  ZADDRESS LIKE ZEDT12_103-ZADDRESS,  "##

  END OF GS_WORKER_ALV.

DATA : GT_WORKER_ALV LIKE TABLE OF GS_WORKER_ALV.



"2) ##### ## #### #### - 2####

DATA : BEGIN OF GS_ASSESS, "####

  ZPERNR LIKE ZEDT12_104-ZPERNR, "####

  ZDEPCODE LIKE ZEDT12_104-ZDEPCODE, "####

  ZYEAR LIKE ZEDT12_104-ZYEAR, "####

  DATBI LIKE ZEDT12_104-DATBI, "####

  DATAB LIKE ZEDT12_104-DATAB, "####

  ZRANK LIKE ZEDT12_104-ZRANK, "##

  END OF GS_ASSESS.

DATA : GT_ASSESS LIKE TABLE OF GS_ASSESS.



DATA : BEGIN OF GS_ASSESS_ALV, "#### ##

  ZPERNR LIKE ZEDT12_104-ZPERNR, "####

  ZDEPCODE_NAME TYPE C LENGTH 10, "##

  ZYEAR LIKE ZEDT12_104-ZYEAR, "####

  DATBI LIKE ZEDT12_104-DATBI, "####

  DATAB LIKE ZEDT12_104-DATAB, "####

  ZRANK LIKE ZEDT12_104-ZRANK, "##

  END OF GS_ASSESS_ALV.

DATA : GT_ASSESS_ALV LIKE TABLE OF GS_ASSESS_ALV.





"3) ##### ## #### #### - 3####

DATA : BEGIN OF GS_CONTRACT, "## ####

  ZPERNR LIKE ZEDT12_106-ZPERNR, "####

  ZYEAR LIKE ZEDT12_106-ZYEAR, "####

  DATBI LIKE ZEDT12_106-DATBI, "####

  DATAB LIKE ZEDT12_106-DATAB, "####

  ZSALARY LIKE ZEDT12_106-ZSALARY, "####

  ZBANKCODE LIKE ZEDT12_106-ZBANKCODE, "####

  ZACCOUNT LIKE ZEDT12_106-ZACCOUNT, "####

  END OF GS_CONTRACT.

DATA : GT_CONTRACT LIKE TABLE OF GS_CONTRACT.



DATA : BEGIN OF GS_CONTRACT_ALV, "## #### ##

  ZPERNR LIKE ZEDT12_106-ZPERNR, "####

  ZYEAR LIKE ZEDT12_106-ZYEAR, "####

  DATBI LIKE ZEDT12_106-DATBI, "####

  DATAB LIKE ZEDT12_106-DATAB, "####

  ZSALARY LIKE ZEDT12_106-ZSALARY, "####

  ZWAERS TYPE WAERS, "##

  ZBANK_NAME TYPE C LENGTH 10, "##

  ZACCOUNT LIKE ZEDT12_106-ZACCOUNT, "ZBANKL

  END OF GS_CONTRACT_ALV.

DATA : GT_CONTRACT_ALV LIKE TABLE OF GS_CONTRACT_ALV.





DATA: OK_CODE TYPE SY-UCOMM.



DATA: GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.



DATA: GC_SPLITTER1 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA: GC_SPLITTER2 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



DATA: GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.

DATA: GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.

DATA: GC_CONTAINER3 TYPE REF TO CL_GUI_CONTAINER.

DATA: GC_CONTAINER4 TYPE REF TO CL_GUI_CONTAINER.



DATA: GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA: GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.

DATA: GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID.



"######, SORT,########



DATA: GS_VARIANT TYPE DISVARIANT.



DATA: GS_FIELDCAT TYPE LVC_S_FCAT.

DATA: GT_FIELDCAT3 TYPE LVC_T_FCAT.

DATA: GT_FIELDCAT4 TYPE LVC_T_FCAT.

DATA: GT_FIELDCAT2 TYPE LVC_T_FCAT.



" ALV ####

DATA: GS_LAYOUT TYPE LVC_S_LAYO.



" ALV SORT ### ##

DATA: GS_SORT TYPE LVC_S_SORT.

DATA: GT_SORT3 TYPE LVC_T_SORT.

DATA: GT_SORT4 TYPE LVC_T_SORT.

DATA: GT_SORT2 TYPE LVC_T_SORT.