
*&---------------------------------------------------------------------*

*&  Include           ZWORK23_002_TOP

*&---------------------------------------------------------------------*






TABLES : SSCRFIELDS,

  ZTCURR23.

SELECTION-SCREEN FUNCTION KEY 1.



DATA : BEGIN OF GS_TCURR,

  KURST LIKE ZTCURR23-KURST, "####

  FCURR LIKE ZTCURR23-FCURR, "####

  TCURR LIKE ZTCURR23-TCURR, "####

  GDATU LIKE ZTCURR23-GDATU, "## ## ###

  UKURS LIKE ZTCURR23-UKURS, "##

  "ZUKURS TYPE P DECIMALS 5, "##

  FFACT LIKE ZTCURR23-FFACT, "#### ### ##

  TFACT LIKE ZTCURR23-TFACT, "#### ### ##

  CRNAME LIKE ZTCURR23-CRNAME,   "###

  CRDATE LIKE ZTCURR23-CRDATE,   "###

  END OF GS_TCURR.

DATA : GT_TCURR LIKE TABLE OF GS_TCURR.



DATA : OK_CODE TYPE SY-UCOMM.

"DATA : GO_EVENT TYPE REF TO EVENT.



DATA : BORDERS TYPE OLE2_OBJECT,

     RANGE TYPE OLE2_OBJECT.



DATA : GC_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER.

DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.





"DATA : GS_FIELDCAT TYPE SLIS_FIELDCAT_ALV.

"DATA : GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV.

"DATA : GS_LAYOUT TYPE SLIS_LAYOUT_ALV.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT.

DATA : GT_FIELDCAT TYPE LVC_T_FCAT.

DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT TYPE LVC_T_SORT.

DATA : GS_LAYOUT TYPE LVC_S_LAYO.