
*&---------------------------------------------------------------------*

*&  Include  ZEDR19_052_TOP

*&---------------------------------------------------------------------*






TABLES : ZEDT19_0001.



DATA : BEGIN OF GS_STUDENT,

  ZCOLOR TYPE C LENGTH 4,

  ZCODE LIKE ZEDT19_0001-ZCODE, "####

  ZPERNR LIKE ZEDT19_0001-ZPERNR, "####

  ZKNAME LIKE ZEDT19_0001-ZKNAME, "##

  ZENAME LIKE ZEDT19_0001-ZENAME, "###

  ZGENDER LIKE ZEDT19_0001-ZGENDER, "##

  ZSUM LIKE ZEDT19_0001-ZSUM, "##

  ZMAJOR LIKE ZEDT19_0001-ZMAJOR, "##

  ZMNAME LIKE ZEDT19_0001-ZMNAME, "###

  END OF GS_STUDENT.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GS_FIELDCAT TYPE SLIS_FIELDCAT_ALV.

DATA : GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV.



DATA : GS_LAYOUT TYPE SLIS_LAYOUT_ALV.



DATA : GS_SORT TYPE SLIS_FIELDCAT_ALV.

DATA : GT_SORT TYPE SLIS_T_FIELDCAT_ALV.