
*&---------------------------------------------------------------------*

*&  Include           ZMM22_001_TOP

*&---------------------------------------------------------------------*






TABLES : ZLFA1_22, ZLFB1_22, ZLFM1_22.



DATA: G_BUKRS TYPE BUKRS,      "### ####

      G_KTOKK TYPE KTOKK,      "### ####

      G_LIFNR TYPE LIFNR.      "### #####

DATA: gv_mode TYPE char1.    " 'C' = ##, 'R' = ##

DATA: OK_CODE TYPE SY-UCOMM.



"###### ### ###

"## ###

DATA: GS_LFA1 TYPE ZLFA1_22.

DATA: GT_LFA1 TYPE TABLE OF ZLFA1_22.



" #######

DATA: GS_LFB1 TYPE ZLFB1_22.

DATA: GT_LFB1 TYPE TABLE OF ZLFB1_22.



" #######

DATA: GS_LFM1 TYPE ZLFM1_22.

DATA: GT_LFM1 TYPE TABLE OF ZLFM1_22.



"ALV #

DATA: GS_LFA1_ALV TYPE ZLFA1_22,

      GT_LFA1_ALV TYPE STANDARD TABLE OF ZLFA1_22.



DATA: GS_LFB1_ALV TYPE ZLFB1_22,

      GT_LFB1_ALV TYPE STANDARD TABLE OF ZLFB1_22.



DATA: GS_LFM1_ALV TYPE ZLFM1_22,

      GT_LFM1_ALV TYPE STANDARD TABLE OF ZLFM1_22.



"### ALV

TYPES: BEGIN OF TY_VENDOR_ALL,

         " ZLFA1_22

         LIFNR TYPE LIFNR,

         NAME1 TYPE ZLFA1_22-NAME1,

         LAND1 TYPE ZLFA1_22-LAND1,

         KTOKK TYPE ZLFA1_22-KTOKK,

         STCD1 TYPE ZLFA1_22-STCD1,

         STCD2 TYPE ZLFA1_22-STCD2, " # #### ## ##

         STRAS TYPE ZLFA1_22-STRAS,



         " ZLFB1_22

         BUKRS TYPE ZLFB1_22-BUKRS,

         AKONT TYPE ZLFB1_22-AKONT,

         ZTERM TYPE ZLFB1_22-ZTERM,

         LOEVM1 TYPE ZLFB1_22-LOEVM,



         " ZLFM1_22

         EKORG TYPE ZLFM1_22-EKORG,

         EKGRP TYPE ZLFM1_22-EKGRP,

         WAERS TYPE ZLFM1_22-WAERS,

         MWSKZ TYPE ZLFM1_22-MWSKZ,

         LOEVM2 TYPE ZLFM1_22-LOEVM,

       END OF TY_VENDOR_ALL.



DATA: GT_VENDOR_ALL TYPE STANDARD TABLE OF TY_VENDOR_ALL,

      GS_VENDOR_ALL TYPE TY_VENDOR_ALL.







DATA : GC_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER.

DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.



DATA : GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA : GC_SPLITTER2 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



DATA : GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER3 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER4 TYPE REF TO CL_GUI_CONTAINER.



DATA : GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT,

       GT_FIELDCAT1 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT2 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT3 TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.

DATA : GS_SORT TYPE LVC_S_SORT .

DATA : GT_SORT1 TYPE LVC_T_SORT.

DATA : GT_SORT2 TYPE LVC_T_SORT.

DATA : GT_SORT3 TYPE LVC_T_SORT.



DATA : GS_VARIANT TYPE DISVARIANT.