
*&---------------------------------------------------------------------*

*&  Include           ZMM06_001_SCR

*&---------------------------------------------------------------------*






" ###

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  PARAMETERS P_LIFNR TYPE ZEDT06_LFA1-LIFNR MODIF ID FI.    " #####

  PARAMETERS P_BUKRS TYPE ZEDT06_LFB1-BUKRS MODIF ID COM.     " ####

  PARAMETERS P_KTOKK TYPE ZEDT06_LFA1-KTOKK MODIF ID CR.  " #####

SELECTION-SCREEN END OF BLOCK B1.



" ##

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.



  SELECTION-SCREEN BEGIN OF LINE.

    PARAMETERS P_CREATE RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

    SELECTION-SCREEN COMMENT 4(10) TEXT-B01 FOR FIELD P_CREATE.



    SELECTION-SCREEN POSITION 25.

    PARAMETERS P_FIND RADIOBUTTON GROUP R1.

    SELECTION-SCREEN COMMENT 32(10) TEXT-B02 FOR FIELD P_FIND.

  SELECTION-SCREEN END OF LINE.



SELECTION-SCREEN END OF BLOCK B2.