
*&---------------------------------------------------------------------*

*& Report ZEDR01_011

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR01_011.






* ### STRUCETURE , TABLE ##




DATA : BEGIN OF GS_WRITE_STUDENT_INFO,

  ZPERNR LIKE ZEDT00_001-ZPERNR,                        " #### "

  ZCODE LIKE ZEDT00_001-ZCODE,                          " #### "

  ZKNAME LIKE ZEDT00_001-ZKNAME,                        " #### "

  ZENAME LIKE ZEDT00_001-ZENAME,                        " #### "

  ZGENDER LIKE ZEDT00_001-ZGENDER,                      " #### "

  ZTEL LIKE ZEDT00_001-ZTEL,                            " ### "

  ZMGUBUN LIKE ZEDT00_002-ZMGUBUN,                      " #### "

  ZMNAME LIKE ZEDT00_002-ZMNAME,                   " ## #### "

  ZMAJOR LIKE ZEDT00_002-ZMAJOR,

  ZSUM LIKE ZEDT00_002-ZSUM,                            " ## "

  ZWAERS LIKE ZEDT00_002-ZWAERS,                        " ### "

  ZMNAME_OUT LIKE ZEDT00_004-ZMNAME,                    " ## #### "

  ZSCHOOL LIKE ZEDT00_004-ZSCHOOL,                      " ## "

  ZEXAM LIKE ZEDT00_004-ZEXAM,                          " #### "

  ZGRADE LIKE ZEDT00_004-ZGRADE,                        " #### "

  ZMAJOR_TRANS_FLAG TYPE C LENGTH 10,                   " ## ## "

  ZWARN_FLAG TYPE C LENGTH 10,                          " ## ## "

  END OF GS_WRITE_STUDENT_INFO.

DATA : GT_WRITE_STUDENT_INFO LIKE TABLE OF GS_WRITE_STUDENT_INFO.






*SELECT ZPERNR FROM ZEDT00_001 INTO TABLE GT_WRITE_STUDENT_INFO.



*SELECT  ZPERNR

*        ZCODE

*        ZKNAME

*        ZENAME

*        ZGENDER

*        ZTEL

*  FROM ZEDT00_001

*  INTO TABLE GT_WRITE_STUDENT_INFO.



*SELECT  ZPERNR

*        ZCODE

*        ZKNAME

*        ZENAME

*        ZGENDER

*        ZTEL

*  FROM ZEDT00_001

*  INTO TABLE GT_WRITE_STUDENT_INFO

*  WHERE ZGENDER = 'M'.

*

*SELECT  ZPERNR

*        ZCODE

*        ZKNAME

*        ZENAME

*        ZGENDER

*        ZTEL

*  FROM ZEDT00_001

*  APPENDING TABLE GT_WRITE_STUDENT_INFO

*  WHERE ZGENDER = 'F'.



*SELECT  ZPERNR

*        ZCODE

*        ZMAJOR

*        ZMNAME

*  FROM ZEDT00_002

*  INTO TABLE GT_WRITE_STUDENT_INFO

*  WHERE ZMNAME LIKE '#%'.

*

*  SELECT  ZPERNR

*        ZCODE

*        ZMAJOR

*        ZMNAME

*  FROM ZEDT00_002

*  APPENDING TABLE GT_WRITE_STUDENT_INFO

*  WHERE ZMNAME BETWEEN '#%' AND '#%'.



*SELECT  ZPERNR

*        ZCODE

*        ZMAJOR

*        ZMNAME

*  FROM ZEDT00_002

*  INTO TABLE GT_WRITE_STUDENT_INFO

*  WHERE ZMNAME IN ( '######' , '####' ).



*RANGES : GR_STUDENT_MAJOR FOR ZEDT00_002-ZMAJOR. " A ~ E "

*

*CLEAR : GR_STUDENT_MAJOR.

*

*GR_STUDENT_MAJOR-SIGN = 'E'.

*GR_STUDENT_MAJOR-OPTION = 'EQ'.

*GR_STUDENT_MAJOR-LOW = 'A'.

*GR_STUDENT_MAJOR-HIGH = 'D'.

*

*APPEND GR_STUDENT_MAJOR.

*

*SELECT *

*  FROM ZEDT00_002

*  INTO CORRESPONDING FIELDS OF TABLE GT_WRITE_STUDENT_INFO

*  WHERE ZMAJOR IN GR_STUDENT_MAJOR.



*DATA : BEGIN OF GS_STUDENT_SUM,

*  ZMAJOR LIKE ZEDT00_002-ZMAJOR,

*  GV_SUM TYPE i,

*  END OF GS_STUDENT_SUM.

*DATA : GT_STUDENT_SUM LIKE TABLE OF GS_STUDENT_SUM.

*

*SELECT ZMAJOR

*       AVG( ZSUM ) AS GV_SUM

*  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT_SUM

*  FROM ZEDT00_002 GROUP BY ZMAJOR.

*

*LOOP AT GT_STUDENT_SUM INTO GS_STUDENT_SUM.

*  WRITE :/ GS_STUDENT_SUM-ZMAJOR , GS_STUDENT_SUM-GV_SUM.

*ENDLOOP.



*DATA : BEGIN OF GS_STUDENT_SUM,

*  ZPERNR LIKE ZEDT00_002-ZPERNR,

*  ZMAJOR LIKE ZEDT00_002-ZMAJOR,

*  GV_SUM TYPE i,

*  END OF GS_STUDENT_SUM.

*DATA : GT_STUDENT_SUM LIKE TABLE OF GS_STUDENT_SUM.

*

*SELECT ZPERNR

*       ZMAJOR

*  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT_SUM

*  FROM ZEDT00_002

*  WHERE ZPERNR IN ( SELECT ZPERNR

*                     FROM ZEDT00_004

*                     WHERE ZPERNR = ZEDT00_002~ZPERNR ).

*SELECT ZPERNR

*       ZMAJOR

*  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT_SUM

*  FROM ZEDT00_002 AS TABLE2

*  WHERE ZPERNR IN ( SELECT ZPERNR

*                     FROM ZEDT00_004

*                     WHERE ZPERNR = TABLE2~ZPERNR ).

*

*LOOP AT GT_STUDENT_SUM INTO GS_STUDENT_SUM.

*  WRITE :/ GS_STUDENT_SUM-ZPERNR , GS_STUDENT_SUM-ZMAJOR.

*ENDLOOP.



*SELECT A~ZPERNR

*       A~ZCODE

*       A~ZMAJOR

*       B~ZPERNR

*       B~ZGRADE

*  INTO CORRESPONDING FIELDS OF TABLE GT_WRITE_STUDENT_INFO

*  FROM ZEDT00_002 AS A

*  INNER JOIN ZEDT00_004 AS B

*  ON A~ZPERNR = B~ZPERNR.



*SELECT A~ZPERNR

*       A~ZCODE

*       A~ZMAJOR

*       B~ZPERNR

*       B~ZGRADE

*  INTO CORRESPONDING FIELDS OF TABLE GT_WRITE_STUDENT_INFO

*  FROM ZEDT00_002 AS A

*  LEFT OUTER JOIN ZEDT00_004 AS B

*  ON A~ZPERNR = B~ZPERNR.

*

*LOOP AT GT_WRITE_STUDENT_INFO INTO GS_WRITE_STUDENT_INFO.

*  WRITE :/ GS_WRITE_STUDENT_INFO-ZPERNR ,GS_WRITE_STUDENT_INFO-ZCODE,GS_WRITE_STUDENT_INFO-ZMAJOR,GS_WRITE_STUDENT_INFO-ZGRADE.

*ENDLOOP.






DATA : GS_ZEDT001 LIKE ZEDT00_001,

       GS_ZEDT002 LIKE ZEDT00_002,

       GS_ZEDT004 LIKE ZEDT00_004,

       GT_ZEDT001 LIKE TABLE OF ZEDT00_001,

       GT_ZEDT002 LIKE TABLE OF ZEDT00_002,

       GT_ZEDT004 LIKE TABLE OF ZEDT00_004.



SELECT * FROM ZEDT00_001

INTO CORRESPONDING FIELDS OF TABLE GT_ZEDT001.



SELECT * FROM ZEDT00_002

INTO CORRESPONDING FIELDS OF TABLE GT_ZEDT002.



SELECT * FROM ZEDT00_004

INTO CORRESPONDING FIELDS OF TABLE GT_ZEDT004.



IF GT_ZEDT002 IS NOT INITIAL.

  SELECT ZPERNR

         ZCODE

         ZMAJOR

         ZMNAME

         ZSUM

         ZGRADE

  FROM ZEDT00_004

  INTO CORRESPONDING FIELDS OF TABLE GT_WRITE_STUDENT_INFO

  FOR ALL ENTRIES IN GT_ZEDT002

  WHERE ZPERNR = GT_ZEDT002-ZPERNR.

 ENDIF.



 WRITE : /'## '.