
*&---------------------------------------------------------------------*

*&  Include           ZEDR25_024_TOP

*&---------------------------------------------------------------------*




TABLES: ZEDT25_001, ZEDT25_002.



TYPE-POOLS: ICON.

INCLUDE <ICON>.



DATA: GS_001 TYPE ZEDT25_001,

      GT_001 TYPE STANDARD TABLE OF ZEDT25_001 WITH DEFAULT KEY.



DATA : BEGIN OF GS_STUDENT,

         ICON    TYPE ICON_D,

         ZCODE   LIKE ZEDT25_001-ZCODE,

         ZPERNR  LIKE ZEDT25_001-ZPERNR,

         ZKNAME  LIKE ZEDT25_001-ZKNAME,

         ZENAME  LIKE ZEDT25_001-ZENAME,

         ZGENDER LIKE ZEDT25_001-ZGENDER,

         ZTEL    LIKE ZEDT25_001-ZTEL,



       END OF GS_STUDENT.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT.

DATA : GT_FIELDCAT TYPE LVC_T_FCAT.

DATA : GS_LAYOUT TYPE LVC_S_LAYO.

DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT TYPE LVC_T_SORT.



DATA : GS_VARIANT TYPE DISVARIANT.



DATA : GO_EVENT TYPE REF TO EVENT.