
*&---------------------------------------------------------------------*

*&  Include           ZMMR13_002_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK A1 WITH FRAME TITLE TEXT-T01.



  PARAMETERS : P4 TYPE ZLFA1_13-LIFNR MODIF ID M2.  "###(=#####)"

  PARAMETERS : P1 TYPE ZLFB1_13-BUKRS.     "####"

  PARAMETERS : P2 TYPE ZLFA1_13-LIFNR MODIF ID M1.  "###(=#####)"

  PARAMETERS : P3 TYPE BEDAT MODIF ID M1.  "###"

  PARAMETERS : P5 TYPE EBELN MODIF ID M2.  "PO ##"



  SELECTION-SCREEN BEGIN OF LINE.

  PARAMETERS : P_R1 RADIOBUTTON GROUP RA1 DEFAULT 'X' USER-COMMAND U1.

  SELECTION-SCREEN COMMENT 15(6) FOR FIELD P_R1.

  PARAMETERS : P_R2 RADIOBUTTON GROUP RA1.

  SELECTION-SCREEN COMMENT 35(6) FOR FIELD P_R2.



  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK A1.