
*&---------------------------------------------------------------------*

*&  Include           ZMMR13_002_TOP

*&---------------------------------------------------------------------*




DATA : GS_LFA1 TYPE ZLFA1_13, "#####"

       GT_LFA1 LIKE TABLE OF GS_LFA1,

       GS_LFB1 TYPE ZLFB1_13, "#######"

       GT_LFB1 LIKE TABLE OF GS_LFB1,

       GS_LFM1 TYPE ZLFM1_13, "#######"

       GT_LFM1 LIKE TABLE OF GS_LFM1,

       GS_EKKO TYPE ZEKKO_13, "######"

       GT_EKKO LIKE TABLE OF GS_EKKO.

DATA : BEGIN OF GS_EKPO,

  WAERS TYPE WAERS.

  include structure
ZEKPO_13
.

DATA : END OF GS_EKPO,

GT_EKPO LIKE TABLE OF GS_EKPO.  "#######"



DATA : BEGIN OF GS_DISPLAY,

  EBELN TYPE ZEKKO_13-EBELN, "######"

  BUKRS TYPE ZEKKO_13-BUKRS, "####"

  EKGRP TYPE ZEKKO_13-EKGRP, "####"

  EKORG TYPE ZEKKO_13-EKORG, "####"

  LIFNR TYPE ZEKKO_13-LIFNR, "###"

  BEDAT TYPE ZEKKO_13-BEDAT, "###"

  WAERS TYPE ZEKKO_13-WAERS, "##"

  EBELP TYPE ZEKPO_13-EBELP, "####"

  MATNR TYPE ZEKPO_13-MATNR, "####"

  MATNAME TYPE ZEKPO_13-MATNAME,"###"

  MENGE TYPE ZEKPO_13-MENGE, "##"

  MEINS TYPE ZEKPO_13-MEINS, "##"

  BPRME TYPE ZEKPO_13-STPRS, "##"

  PRDAT TYPE ZEKPO_13-PRDAT, "###"

  WERKS TYPE ZEKPO_13-WERKS, "###"

  LGORT TYPE ZEKPO_13-LGORT, "####"

  END OF GS_DISPLAY,

  GT_DISPLAY LIKE TABLE OF GS_DISPLAY.



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER.

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.



DATA : GO_EVENT TYPE REF TO EVENT.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT,

       GT_FIELDCAT TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT TYPE LVC_T_SORT.



DATA : GS_VARIANT TYPE DISVARIANT.



DATA: GT_EXCLUDE TYPE UI_FUNCTIONS,

      GS_EXCLUDE TYPE UI_FUNC.