
*&---------------------------------------------------------------------*

*&  Include           ZEDR20_PRACTICE009_TOP

*&---------------------------------------------------------------------*




TABLES: ZEDT20_102.



DATA: GV_DATE TYPE SY-DATUM.

RANGES: R_DATE FOR SY-DATUM.

RANGES: R_BANKCODE FOR ZEDT20_106-ZBANKCODE.



DATA: BEGIN OF GS_ZPINFO_DATA.

  DATA: ZPERNR TYPE ZEDT20_103-ZPERNR,   " ####

        ZPNAME TYPE ZEDT20_103-ZPNAME,   " ## ##

        ZDEPCODE TYPE ZEDT20_102-ZDEPCODE,   " ####

        DATBI TYPE ZEDT20_102-DATBI,    " ####

        DATAB TYPE ZEDT20_102-DATAB,    " ####

        ZDEPRANK TYPE ZEDT20_102-ZDEPRANK,    " ####

        ZGENDER TYPE ZEDT20_103-ZGENDER,   " ##

        ZEDATE TYPE ZEDT20_102-ZEDATE,   " ####

        ZADDRESS TYPE ZEDT20_103-ZADDRESS,   " ##

        ZQFLAG TYPE ZEDT20_102-ZQFLAG,   " ####

        ZQDATE TYPE ZEDT20_102-ZQDATE.    " ####

  DATA: END OF GS_ZPINFO_DATA.

  DATA: GT_ZPINFO_DATA LIKE TABLE OF GS_ZPINFO_DATA.



DATA: BEGIN OF GS_ZPINFO_ALV.

  DATA: ZCOLOR(4),    " ##

        ZPERNR TYPE ZEDT20_103-ZPERNR,   " ####

        ZPNAME TYPE ZEDT20_103-ZPNAME,   " ## ##

        ZDEPNAME(3),   " ###

        DATBI TYPE ZEDT20_102-DATBI,    " ####

        DATAB TYPE ZEDT20_102-DATAB,    " ####

        ZRNAME(2),   " ###

        ZGENDER_KR(2),   " ##

        ZEDATE TYPE ZEDT20_102-ZEDATE,   " ####

        ZADDRESS TYPE ZEDT20_103-ZADDRESS,   " ##

        ZQFLAG TYPE ZEDT20_102-ZQFLAG,   " ####

        ZQDATE TYPE ZEDT20_102-ZQDATE.    " ####

  DATA: END OF GS_ZPINFO_ALV.

  DATA: GT_ZPINFO_ALV LIKE TABLE OF GS_ZPINFO_ALV.



DATA: BEGIN OF GS_RANK_DATA.

  DATA: ZPERNR TYPE ZEDT20_103-ZPERNR,    " ## ##

        ZDEPCODE TYPE ZEDT20_102-ZDEPCODE,   " ####

        ZYEAR TYPE ZEDT20_104-ZYEAR,    " ##

        DATBI TYPE ZEDT20_102-DATBI,    " ####

        DATAB TYPE ZEDT20_102-DATAB,    " ####

        ZRANK TYPE ZEDT20_104-ZRANK.    " ##

  DATA: END OF GS_RANK_DATA.

  DATA: GT_RANK_DATA LIKE TABLE OF GS_RANK_DATA.



DATA: BEGIN OF GS_RANK_ALV.

  DATA: ZPERNR TYPE ZEDT20_103-ZPERNR,    " ## ##

        ZDEPNAME(3),   " ###

        ZYEAR TYPE ZEDT20_104-ZYEAR,    " ##

        DATBI TYPE ZEDT20_102-DATBI,    " ####

        DATAB TYPE ZEDT20_102-DATAB,    " ####

        ZRANK TYPE ZEDT20_104-ZRANK.    " ##

  DATA: END OF GS_RANK_ALV.

  DATA: GT_RANK_ALV LIKE TABLE OF GS_RANK_ALV.



DATA: BEGIN OF GS_SALARY_DATA.

  DATA: ZPERNR TYPE ZEDT20_103-ZPERNR,    " ## ##

        ZYEAR TYPE ZEDT20_104-ZYEAR,    " ##

        DATBI TYPE ZEDT20_102-DATBI,    " ####

        DATAB TYPE ZEDT20_102-DATAB,    " ####

        ZSALARY TYPE ZEDT20_106-ZSALARY,    " ###

        ZBANKCODE TYPE ZEDT20_106-ZBANKCODE,   " ####

        ZACCOUNT TYPE ZEDT20_106-ZACCOUNT.    " ####

  DATA: END OF GS_SALARY_DATA.

  DATA: GT_SALARY_DATA LIKE TABLE OF GS_SALARY_DATA.



DATA: BEGIN OF GS_SALARY_ALV.

  DATA: ZPERNR TYPE ZEDT20_103-ZPERNR,    " ## ##

        ZYEAR TYPE ZEDT20_104-ZYEAR,    " ##

        DATBI TYPE ZEDT20_102-DATBI,    " ####

        DATAB TYPE ZEDT20_102-DATAB,    " ####

        ZSALARY TYPE ZEDT20_106-ZSALARY,    " ###

        ZBANKNAME(8),   " ###

        ZACCOUNT TYPE ZEDT20_106-ZACCOUNT,    " ####

        ZWAERS LIKE T001-WAERS.    " ##

  DATA: END OF GS_SALARY_ALV.

  DATA: GT_SALARY_ALV LIKE TABLE OF GS_SALARY_ALV.



DATA: GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA: GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA: GC_SPLITTER2 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



DATA: GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.

DATA: GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.

DATA: GC_CONTAINER3 TYPE REF TO CL_GUI_CONTAINER.

DATA: GC_CONTAINER4 TYPE REF TO CL_GUI_CONTAINER.



DATA: GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA: GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.

DATA: GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID.



DATA: OK_CODE TYPE SY-UCOMM.



DATA: GT_FIELDCAT1 TYPE LVC_T_FCAT.

DATA: GT_FIELDCAT2 TYPE LVC_T_FCAT.

DATA: GT_FIELDCAT3 TYPE LVC_T_FCAT.

DATA: GS_FIELDCAT TYPE LVC_S_FCAT.

DATA: GS_LAYOUT TYPE LVC_S_LAYO.

DATA: GS_SORT TYPE LVC_S_SORT.

DATA: GT_SORT TYPE LVC_T_SORT.



DATA: GS_VARIANT TYPE DISVARIANT.