
*&---------------------------------------------------------------------*

*& Report ZEDR20_016

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR20_016.



SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  PARAMETERS: P_ZCODE LIKE ZEDT20_001-ZCODE OBLIGATORY VISIBLE LENGTH 6.

  PARAMETERS: P_ZPERNR TYPE C LENGTH 10.

  PARAMETERS: P_ZNUM TYPE P DECIMALS 2 NO-DISPLAY.

  PARAMETERS: P_ZGEN LIKE ZEDT20_001-ZGENDER DEFAULT 'M'.

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  SELECTION-SCREEN BEGIN OF LINE.

    PARAMETERS: P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'.

    SELECTION-SCREEN POSITION 3.

    SELECTION-SCREEN COMMENT (10) FOR FIELD P_R1.

    PARAMETERS: P_R2 RADIOBUTTON GROUP R1.

    SELECTION-SCREEN POSITION 20.

    SELECTION-SCREEN COMMENT (10) FOR FIELD P_R2.

  SELECTION-SCREEN END OF LINE.

  PARAMETERS: Z_CHECK AS CHECKBOX DEFAULT 'X'.

SELECTION-SCREEN END OF BLOCK B2.



DATA: BEGIN OF GS_STUDENT.

  include structure
ZEDT20_001
.

  DATA: END OF GS_STUDENT.

DATA: GT_STUDENT LIKE TABLE OF GS_STUDENT.



SELECT *

  FROM ZEDT20_001

  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

  WHERE ZCODE = P_ZCODE.



IF Z_CHECK = 'X'.

  WRITE: / '#### ##'.

ELSE.

  WRITE: / '#### ##'.

ENDIF.



LOOP AT GT_STUDENT INTO GS_STUDENT.

  WRITE: / GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME.

ENDLOOP.