
*&---------------------------------------------------------------------*

*& Report ZEDR02_017

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR02_017.



TABLES : ZEDT02_001, ZEDT02_002.



DATA: BEGIN OF GS_STUDENT.

  include structure
ZEDT02_001
.

DATA : END OF GS_STUDENT.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.



SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  "SELECT-OPTIONS : S_ZCODE FOR ZEDT02_001-ZCODE DEFAULT 'SSU-01'. "SIGN I OPTION EQ# ### ###

  "SELECT-OPTIONS : S_ZCODE FOR ZEDT02_001-ZCODE DEFAULT 'SSU-01' SIGN E OPTION EQ. "### ## # ##

  "SELECT-OPTIONS : S_ZCODE FOR ZEDT02_001-ZCODE DEFAULT 'SSU-01' SIGN E OPTION BT. "DEFAULT# DATA# 1## ## BT ##

  "SELECT-OPTIONS : S_ZCODE FOR ZEDT02_001-ZCODE DEFAULT 'SSU-01' TO 'SSU-99'. "SIGN I OPTION BT# ### ##

  "SELECT-OPTIONS : S_ZCODE FOR ZEDT02_001-ZCODE DEFAULT 'SSU-01' TO 'SSU-99' SIGN E OPTION BT.

  "SELECT-OPTIONS : S_ZCODE FOR ZEDT02_001-ZCODE DEFAULT 'SSU-01' NO INTERVALS. "## # # ###

  "SELECT-OPTIONS : S_ZCODE FOR ZEDT02_001-ZCODE DEFAULT 'SSU-01' NO INTERVALS NO-EXTENSION. "Multiple Selections ### ##

  SELECT-OPTIONS : S_ZCODE FOR ZEDT02_001-ZCODE DEFAULT 'SSU-01' VISIBLE LENGTH 5 MODIF ID M3. "## ##

SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS: P_ZGEN LIKE ZEDT02_001-ZGENDER MODIF ID M4.

  "SEARCH HELP# #### ## ### ##-> MATCHCODE OBJECT ### ## ##

  PARAMETERS: P_ZMGUB LIKE ZEDT02_002-ZMGUBUN MATCHCODE OBJECT ZSH02_001 MODIF ID M4.

SELECTION-SCREEN END OF BLOCK B2.




*SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME.

*  PARAMETERS : P_CH1 AS CHECKBOX DEFAULT 'X' MODIF ID M1. "## 3### ### ##

*  PARAMETERS : P_CH2 AS CHECKBOX MODIF ID M2.

*SELECTION-SCREEN END OF BLOCK B3.




SELECTION-SCREEN BEGIN OF BLOCK B4 WITH FRAME.

  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

  "PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'. "ENTER### #### ## ##

  PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

SELECTION-SCREEN END OF BLOCK B4.






*SELECT * FROM ZEDT02_001

*  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

*  WHERE ZCODE IN S_ZCODE

*  AND   ZGENDER = P_ZGEN.

*

*IF GT_STUDENT[] IS NOT INITIAL.

*  CLEAR : GS_STUDENT.

*  LOOP AT GT_STUDENT INTO GS_STUDENT.

*    WRITE: / GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME.

*  ENDLOOP.

*ELSE.

*  WRITE: / '### ##'.

*ENDIF.



*AT SELECTION-SCREEN OUTPUT. "SELECTION-SCREEN# #### ##

*  LOOP AT SCREEN.

*    IF SCREEN-GROUP1 = 'M2'. "MODIF ID# ## ### ##

*    "IF SCREEN-NAME = 'P_CH2'.

*      "SCREEN-INPUT = '0'. "#### ## ####->#### #

*      "SCREEN-ACTIVE = '0'. "### ### #### ##->## # ##

*      "SCREEN-REQUIRED = '1'. "### # ## ##

*      SCREEN-OUTPUT = '0'. "## ## ####

*      MODIFY SCREEN.

*    ENDIF.

*  ENDLOOP.






AT SELECTION-SCREEN OUTPUT.

  LOOP AT SCREEN.

    IF SCREEN-GROUP1 = 'M4'. "###### ## M4(##) ##

      "SCREEN-INTENSIFIED = '1'. "## ##(1# ###)

      "SCREEN-DISPLAY_3D = '1'. "### ### ##

      "SCREEN-INVISIBLE = '1'. "###### ##

      IF P_R1 = 'X'.

        SCREEN-ACTIVE = '1'.

      ELSEIF P_R2 = 'X'.

        SCREEN-ACTIVE = '0'.

      ENDIF.

    ENDIF.

    MODIFY SCREEN.

  ENDLOOP.