
*&---------------------------------------------------------------------*

*& Report ZEDR04_056

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR04_056.



DATA GS_STUDENT TYPE ZEDT04_001.

DATA GT_STUDENT LIKE TABLE OF GS_STUDENT.



DATA : BEGIN OF GS_MAJOR,

  ZCODE LIKE ZEDT04_001-ZCODE,    " ####

  ZPERNR LIKE ZEDT04_001-ZPERNR,  " ####

  ZMNAME LIKE ZEDT04_004-ZMNAME,  " ###

  ZKNAME LIKE ZEDT04_001-ZKNAME,  " ## (##)

  END OF GS_MAJOR.

DATA GT_MAJOR LIKE TABLE OF GS_MAJOR.   " WITH NON-UNIQUE KEY ZCODE ## ##



CLEAR : GS_STUDENT, GT_STUDENT, GS_MAJOR, GT_MAJOR.

GS_STUDENT-ZPERNR = '0000000001'.

GS_STUDENT-ZCODE = 'SSU-01'.

GS_STUDENT-ZENAME = 'DONG'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01011112222'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_MAJOR-ZPERNR = '0000000001'.

GS_MAJOR-ZCODE = 'SSU-01'.

GS_MAJOR-ZMNAME = '####'.

GS_MAJOR-ZKNAME = '###'.

APPEND GS_MAJOR TO GT_MAJOR.



CLEAR : GS_STUDENT, GS_MAJOR.

GS_STUDENT-ZPERNR = '0000000002'.

GS_STUDENT-ZCODE = 'SSU-02'.

GS_STUDENT-ZENAME = 'HOON'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01022223333'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_MAJOR-ZPERNR = '0000000002'.

GS_MAJOR-ZCODE = 'SSU-02'.

GS_MAJOR-ZMNAME = '#####'.

GS_MAJOR-ZKNAME = '###'.

APPEND GS_MAJOR TO GT_MAJOR.



CLEAR : GS_STUDENT, GS_MAJOR.

GS_STUDENT-ZPERNR = '0000000003'.

GS_STUDENT-ZCODE = 'SSU-03'.

GS_STUDENT-ZENAME = 'BIN'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01033334444'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_MAJOR-ZPERNR = '0000000003'.

GS_MAJOR-ZCODE = 'SSU-03'.

GS_MAJOR-ZMNAME = '######'.

GS_MAJOR-ZKNAME = '##'.

APPEND GS_MAJOR TO GT_MAJOR.



CLEAR : GS_STUDENT, GS_MAJOR.

GS_STUDENT-ZPERNR = '0000000004'.

GS_STUDENT-ZCODE = 'SSU-04'.

GS_STUDENT-ZENAME = 'JENNY'.

GS_STUDENT-ZGENDER = 'F'.

GS_STUDENT-ZTEL = '01044445555'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_MAJOR-ZPERNR = '0000000004'.

GS_MAJOR-ZCODE = 'SSU-04'.

GS_MAJOR-ZMNAME = '####'.

GS_MAJOR-ZKNAME = '##'.

APPEND GS_MAJOR TO GT_MAJOR.



CLEAR : GS_STUDENT, GS_MAJOR.

GS_STUDENT-ZPERNR = '0000000005'.

GS_STUDENT-ZCODE = 'SSU-05'.

GS_STUDENT-ZENAME = 'KOOK'.

GS_STUDENT-ZGENDER = 'M'.

GS_STUDENT-ZTEL = '01055556666'.

APPEND GS_STUDENT TO GT_STUDENT.



GS_MAJOR-ZPERNR = '0000000005'.

GS_MAJOR-ZCODE = 'SSU-05'.

GS_MAJOR-ZMNAME = '#####'.

GS_MAJOR-ZKNAME = '##'.

APPEND GS_MAJOR TO GT_MAJOR.



SORT GT_STUDENT BY ZCODE.

SORT GT_MAJOR BY ZCODE.



CLEAR GS_STUDENT.

LOOP AT GT_STUDENT INTO GS_STUDENT.

  CLEAR GS_MAJOR.






*  " 3-3. TRANSPORTING## ### ### ##

*  MOVE-CORRESPONDING GS_STUDENT TO GS_MAJOR.  " READ ## GS_MAJOR-ZCODE ## ### ## ## ##

*  READ TABLE GT_MAJOR WITH KEY ZCODE = GS_STUDENT-ZCODE INTO GS_MAJOR

*  TRANSPORTING ZMNAME.  " GS_MAJOR-ZMNAME# ## ##. ZKNAME# READ # #



*  " 4. INDEX #### ### ##

*  READ TABLE GT_MAJOR INTO GS_MAJOR INDEX SY-TABIX. " GT_MAJOR# GT_STUDENT ## ## #### #






  " 5. BINARY SEARCH# ### ##

  READ TABLE GT_MAJOR WITH KEY ZCODE = GS_STUDENT-ZCODE INTO GS_MAJOR BINARY SEARCH.



  IF SY-SUBRC = 0.

    WRITE : / GS_STUDENT-ZCODE, GS_MAJOR-ZKNAME, GS_MAJOR-ZMNAME.

  ELSE.

    WRITE / '#### #### #####.'.

  ENDIF.

ENDLOOP.