
*&---------------------------------------------------------------------*

*&  Include           ZMM10_FK01_SCR

*&---------------------------------------------------------------------*






SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

PARAMETERS: P_BUKRS1 TYPE ZEDT10_LFB1-BUKRS MODIF ID CRE MATCHCODE OBJECT ZSH10_BUKRS,

            P_KTOKK  TYPE ZEDT10_LFA1-KTOKK MODIF ID CRE MATCHCODE OBJECT ZSH10_KTOKK.



PARAMETERS: P_LIFNR  TYPE ZEDT10_LFA1-LIFNR MATCHCODE OBJECT ZSH10_LIFNR MODIF ID SEA,

            P_BUKRS2 TYPE ZEDT10_LFB1-BUKRS MODIF ID SEA MATCHCODE OBJECT ZSH10_BUKRS.



SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

SELECTION-SCREEN BEGIN OF LINE.

SELECTION-SCREEN COMMENT 1(5) FOR FIELD PR_CREA.

PARAMETERS: PR_CREA RADIOBUTTON GROUP R1 USER-COMMAND SY-UCOMM DEFAULT 'X'.

SELECTION-SCREEN COMMENT 10(5) FOR FIELD PR_SEAR.

PARAMETERS: PR_SEAR RADIOBUTTON GROUP R1.

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B2.