
*&---------------------------------------------------------------------*

*&  Include           ZEDR12_PRACTICE008_TOP

*&---------------------------------------------------------------------*




TABLES: ZEDT12_100.

TABLES: ZEDT12_101.



DATA: LV_FIRST TYPE D. "### 1#

DATA: LV_LAST TYPE D. "### ##



RANGES: R_FG FOR ZEDT12_100-ZSALE_FG.

RANGES: R_ZG FOR ZEDT12_101-ZFLAG.





"ITAB##

DATA : BEGIN OF GS_ORDER, "#### ###

  ZCOLOR TYPE C LENGTH 4, "##=### ##

  ZORDNO LIKE ZEDT12_100-ZORDNO, "####

  ZIDCODE LIKE ZEDT12_100-ZIDCODE, "##ID

  ZMATNR LIKE ZEDT12_100-ZMATNR, "####

  ZMTART LIKE ZEDT12_100-ZMTART, "####

  ZMATNAME LIKE ZEDT12_100-ZMATNAME, "###

  ZVOLUM LIKE ZEDT12_100-ZVOLUM, "##

  VRKME LIKE ZEDT12_100-VRKME, "####

  ZNSAMT LIKE ZEDT12_100-ZNSAMT, "####

  ZSLAMT LIKE ZEDT12_100-ZSLAMT, "####

  ZDCAMT LIKE ZEDT12_100-ZDCAMT, "####

  ZWAERS LIKE ZEDT12_100-ZWAERS, " ##

  ZDC_FG LIKE ZEDT12_100-ZDC_FG, "####

  ZSALE_FG LIKE ZEDT12_100-ZSALE_FG, "####

  ZRET_FG LIKE ZEDT12_100-ZRET_FG, "####

  ZJDATE LIKE ZEDT12_100-ZJDATE, "####

  ZRDATE LIKE ZEDT12_100-ZRDATE, "####

  END OF GS_ORDER.

DATA : GT_ORDER LIKE TABLE OF GS_ORDER.



DATA : BEGIN OF GS_DELIVERY, "#### ###

  ZCOLOR TYPE C LENGTH 4, "##=### ##

  ZORDNO LIKE ZEDT12_101-ZORDNO, "####

  ZIDCODE LIKE ZEDT12_101-ZIDCODE, "##ID

  ZMATNR LIKE ZEDT12_101-ZMATNR, "####

  ZMTART LIKE ZEDT12_101-ZMTART, "####

  ZMATNAME LIKE ZEDT12_101-ZMATNAME, "###

  ZVOLUM LIKE ZEDT12_101-ZVOLUM, "##

  VRKME LIKE ZEDT12_101-VRKME, "####

  ZSLAMT LIKE ZEDT12_101-ZSLAMT, "####

  ZWAERS LIKE ZEDT12_101-ZWAERS, " ##

  ZDFLAG LIKE ZEDT12_101-ZDFLAG, "####

  ZDGUBUN LIKE ZEDT12_101-ZDGUBUN, "####

  ZDDATE LIKE ZEDT12_101-ZDDATE, "####

  ZRDATE LIKE ZEDT12_101-ZRDATE, "####

  ZFLAG LIKE ZEDT12_101-ZFLAG, "FLAG

  END OF GS_DELIVERY.

DATA : GT_DELIVERY LIKE TABLE OF GS_DELIVERY.



"4. ### ### ###

DATA: BEGIN OF GS_OUT_ORDER,

  ZCOLOR TYPE C LENGTH 4, "##=### ##

  ZORDNO LIKE ZEDT12_100-ZORDNO, "####

  ZIDCODE LIKE ZEDT12_100-ZIDCODE, "##ID

  ZMATNR LIKE ZEDT12_100-ZMATNR, "####

  ZMTART LIKE ZEDT12_100-ZMTART, "####

  ZMATNAME LIKE ZEDT12_100-ZMATNAME, "###

  ZVOLUM LIKE ZEDT12_100-ZVOLUM, "##

  VRKME LIKE ZEDT12_100-VRKME, "####

  ZNSAMT LIKE ZEDT00_100-ZNSAMT, "####

  ZSLAMT LIKE ZEDT00_100-ZSLAMT, "####

  ZDCAMT LIKE ZEDT00_100-ZDCAMT, "####

  ZWAERS LIKE ZEDT12_100-ZWAERS, " ##

  ZDC_FG LIKE ZEDT12_100-ZDC_FG, "####

  ZSALE_FG LIKE ZEDT12_100-ZSALE_FG, "####

  ZRET_FG LIKE ZEDT12_100-ZRET_FG, "####

  ZJDATE LIKE ZEDT12_100-ZJDATE, "####

  ZRDATE LIKE ZEDT12_100-ZRDATE, "####

  ZMTART_NAME(10) TYPE C, "####, #### ### ##

  ZSALE_FG_NAME(4) TYPE C, "####

  ZRET_FG_NAME(10) TYPE C, "####

END OF GS_OUT_ORDER.

DATA: GT_OUT_ORDER LIKE TABLE OF GS_OUT_ORDER.



DATA: BEGIN OF GS_OUT_DELIVERY,

  ZCOLOR TYPE C LENGTH 4, "##=### ##

  ZORDNO LIKE ZEDT12_101-ZORDNO, "####

  ZIDCODE LIKE ZEDT12_101-ZIDCODE, "##ID

  ZMATNR LIKE ZEDT12_101-ZMATNR, "####

  ZMTART LIKE ZEDT12_101-ZMTART, "####

  ZMATNAME LIKE ZEDT12_101-ZMATNAME, "###

  ZVOLUM LIKE ZEDT12_101-ZVOLUM, "##

  VRKME LIKE ZEDT12_101-VRKME, "####

  ZSLAMT LIKE ZEDT00_100-ZSLAMT, "####

  ZWAERS LIKE ZEDT12_101-ZWAERS, " ##

  ZDFLAG LIKE ZEDT12_101-ZDFLAG, "####

  ZDGUBUN LIKE ZEDT12_101-ZDGUBUN, "####

  ZDDATE LIKE ZEDT12_101-ZDDATE, "####

  ZRDATE LIKE ZEDT12_101-ZRDATE, "####

  ZFLAG LIKE ZEDT12_101-ZFLAG, "FLAG

  ZMTART_NAME(10) TYPE C,

  ZDFLAG_NAME(10) TYPE C,

  ZDGUBUN_NAME(10) TYPE C,

  END OF GS_OUT_DELIVERY.

  DATA: GT_OUT_DELIVERY LIKE TABLE OF GS_OUT_DELIVERY.



  DATA: OK_CODE TYPE SY-UCOMM. "SCREEN 100#### ##### ## #####



  DATA: GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.  "#### ->F01## FORM CREATE_OBJECT

  DATA: GC_GRID_100 TYPE REF TO CL_GUI_ALV_GRID.  "#### ->F01## FORM CREATE_OBJECT

  DATA: GC_GRID_200 TYPE REF TO CL_GUI_ALV_GRID.  "#### ->F01## FORM CREATE_OBJECT





DATA: GS_FIELDCAT TYPE LVC_S_FCAT.

DATA: GT_FIELDCAT TYPE LVC_T_FCAT.



"##########,  PERFORM ALV_LAYOUT## #### #####

DATA: GS_VARIANT TYPE DISVARIANT.

" ALV ####

DATA GS_LAYOUT TYPE LVC_S_LAYO.



" ALV SORT ### ##

DATA GS_SORT TYPE LVC_S_SORT.

DATA GT_SORT TYPE LVC_T_SORT.