
*&---------------------------------------------------------------------*

*&  Include           ZMM10_ME21N_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

PARAMETERS:

  P_BUKRS1 TYPE BUKRS MATCHCODE OBJECT ZSH10_BUKRS MODIF ID MC,

  P_LIFNR1 TYPE LIFNR MATCHCODE OBJECT ZSH10_LIFNR MODIF ID MC,

  P_BEDAT1 TYPE BEDAT MODIF ID MC DEFAULT SY-DATUM.

PARAMETERS:

  P_LIFNR2 TYPE LIFNR MATCHCODE OBJECT ZSH10_LIFNR MODIF ID MS,

  P_BUKRS2 TYPE BUKRS MATCHCODE OBJECT ZSH10_BUKRS MODIF ID MS,

  P_EBELN2 TYPE EBELN MATCHCODE OBJECT ZSH10_EBELN MODIF ID MS.

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

SELECTION-SCREEN BEGIN OF LINE.

PARAMETERS: PR_CREA RADIOBUTTON GROUP R1 USER-COMMAND RR DEFAULT 'X'.

SELECTION-SCREEN COMMENT 3(10) FOR FIELD PR_CREA.

PARAMETERS: PR_SEAR RADIOBUTTON GROUP R1.

SELECTION-SCREEN COMMENT 16(10) FOR FIELD PR_SEAR.

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B2.