
*&---------------------------------------------------------------------*

*&  Include           ZPRACTICE009_CONTAINER18_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

SELECT-OPTIONS : S_ZPERNR FOR ZEDT18_102-ZPERNR.

SELECT-OPTIONS : S_ZEDATE FOR ZEDT18_102-DATBI NO INTERVALS NO-EXTENSION.

SELECT-OPTIONS : S_ZDEPCD FOR ZEDT18_102-ZDEPCODE NO INTERVALS NO-EXTENSION.

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

PARAMETERS : P_CH AS CHECKBOX DEFAULT 'X'.

SELECTION-SCREEN END OF BLOCK B2.