
*&---------------------------------------------------------------------*

*& Report ZEDR08_015

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR08_015.



TABLES : ZEDT08_001.



DATA : BEGIN OF GS_STUDENT.

  include structure
ZEDT08_001
.

  DATA : END OF GS_STUDENT.



DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.



SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  " SELECT-OPTIONS : S_ZCODE FOR ZEDT08_001-ZCODE DEFAULT 'SSU-01' VISIBLE LENGTH 3.

  SELECT-OPTIONS : S_ZCODE FOR ZEDT08_001-ZCODE DEFAULT 'SSU-01' TO 'SSU-10'.

  " SELECT-OPTIONS : S_ZCODE FOR ZEDT08_001-ZCODE DEFAULT 'SSU-01' NO INTERVALS NO-EXTENSION.

  " SELECT-OPTIONS : S_ZCODE FOR ZEDT08_001-ZCODE DEFAULT 'SSU-01' NO INTERVALS.

  " SELECT-OPTIONS : S_ZCODE FOR ZEDT08_001-ZCODE DEFAULT 'SSU-01' TO 'SSU-10' SIGN E OPTION BT.

  " SELECT-OPTIONS : S_ZCODE FOR ZEDT08_001-ZCODE DEFAULT 'SSU-01' TO 'SSU-10' SIGN I OPTION BT.

  " SELECT-OPTIONS : S_ZCODE FOR ZEDT08_001-ZCODE DEFAULT 'SSU-01' SIGN I OPTION EQ.

  " SELECT-OPTIONS : S_ZCODE FOR ZEDT08_001-ZCODE DEFAULT 'SSU-01' SIGN E OPTION EQ.

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS : P_ZGEN LIKE ZEDT08_001-ZGENDER MATCHCODE OBJECT ZSH08_001 MODIF ID M3.

SELECTION-SCREEN END OF BLOCK B2.



SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME.

  PARAMETERS : P_CH1 AS CHECKBOX DEFAULT 'X' MODIF ID M1.

  PARAMETERS : P_CH2 AS CHECKBOX MODIF ID M2.

SELECTION-SCREEN END OF BLOCK B3.



SELECTION-SCREEN BEGIN OF BLOCK B4 WITH FRAME.

  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

  PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

SELECTION-SCREEN END OF BLOCK B4.



SELECT * FROM ZEDT08_001

  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

  WHERE ZCODE IN S_ZCODE

  AND ZGENDER = P_ZGEN.



AT SELECTION-SCREEN OUTPUT.

  LOOP AT SCREEN.

    IF SCREEN-GROUP1 = 'M2'.

      IF P_R1 = 'X'.

      " SCREEN-INPUT = '0'.

      SCREEN-OUTPUT = '0'.

      SCREEN-ACTIVE = '1'.

      SCREEN-INVISIBLE = '1'.

      ELSEIF P_R2 = 'X'.

        SCREEN-ACTIVE = '0'.

      ENDIF.

      MODIFY SCREEN.

    ENDIF.



    IF SCREEN-NAME = 'P_CH1'.

      " SCREEN-INPUT = '0'.

      SCREEN-REQUIRED = '1'.

      SCREEN-INTENSIFIED = '1'.

      SCREEN-DISPLAY_3D = '1'.

      MODIFY SCREEN.

    ENDIF.

  ENDLOOP.



IF GT_STUDENT[] IS NOT INITIAL.

  CLEAR : GS_STUDENT.

  LOOP AT GT_STUDENT INTO GS_STUDENT.

    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME.

  ENDLOOP.

ELSE.

  WRITE :/ '### ##'.

ENDIF.



"------------------------------------------------------------------------