
*&---------------------------------------------------------------------*

*&  Include           ZEDR03_017_TOP

*&---------------------------------------------------------------------*




TABLES : ZEDT03_100.

TABLES : ZEDT03_101.



CONSTANTS : C_X TYPE CHAR1 VALUE 'X'.



"#### ###

DATA : BEGIN OF GS_ORDER,

  ZCOLOR TYPE C LENGTH 4, "### ## ##

  ZORDNO LIKE ZEDT03_100-ZORDNO, "####

  ZIDCODE LIKE ZEDT03_100-ZIDCODE, "##ID

  ZMATNR LIKE ZEDT03_100-ZMATNR , "####

  ZMTART LIKE ZEDT03_100-ZMTART, "####

  ZMTART_KR TYPE C LENGTH 20, "#####

  ZMATNAME LIKE ZEDT03_100-ZMATNAME, "###

  ZVOLUM LIKE ZEDT03_100-ZVOLUM, "##

  VOLUM LIKE ZEDT03_100-VOLUM, "VOLUM

  VRKME LIKE ZEDT03_100-VRKME, "Sales Unit

  ZNSAMT LIKE ZEDT03_100-ZNSAMT, "####

  ZSLAMT LIKE ZEDT03_100-ZSLAMT, "####

  ZDCAMT LIKE ZEDT03_100-ZDCAMT, "####

  ZWARS LIKE ZEDT03_100-ZWARS, "##

  ZDC_FG LIKE ZEDT03_100-ZDC_FG, "####

  ZSALE_FG LIKE ZEDT03_100-ZSALE_FG, "####

  ZSALE_FG_KR TYPE C LENGTH 20, "#####

  ZRET_FG LIKE ZEDT03_100-ZRET_FG, "####

  ZRET_FG_KR TYPE C LENGTH 20, "#####

  ZJDATE LIKE ZEDT03_100-ZJDATE, "####

  ZRDATE LIKE ZEDT03_100-ZRDATE, "####

  END OF GS_ORDER.

DATA : GT_ORDER LIKE TABLE OF GS_ORDER.



"#### ###

DATA : BEGIN OF GS_DELIVER,

  ZCOLOR TYPE C LENGTH 4, "### ## ##

  ZORDNO LIKE ZEDT03_101-ZORDNO, "####

  ZIDCODE LIKE ZEDT03_101-ZIDCODE, "##ID

  ZMATNR LIKE ZEDT03_101-ZMATNR , "####

  ZMTART LIKE ZEDT03_101-ZMTART, "####

  ZMTART_KR TYPE C LENGTH 20, "#####

  ZMATNAME LIKE ZEDT03_101-ZMATNAME, "###

  ZVOLUM LIKE ZEDT03_101-ZVOLUM, "##

  VOLUM LIKE ZEDT03_101-VOLUM, "VOLUM

  VRKME LIKE ZEDT03_101-VRKME, "Sales Unit

  ZSLAMT LIKE ZEDT03_101-ZSLAMT, "####

  ZWAERS LIKE ZEDT03_101-ZWAERS, "##

  ZDFLAG LIKE ZEDT03_101-ZDFLAG, "####

  ZDFLAG_KR TYPE C LENGTH 20, "#####

  ZDGUBUN LIKE ZEDT03_101-ZDGUBUN, "####

  ZDGUBUN_KR TYPE C LENGTH 20, "#####

  ZDDATE LIKE ZEDT03_101-ZDDATE, "####

  ZRDATE LIKE ZEDT03_101-ZRDATE, "####

  ZFLAG LIKE ZEDT03_101-ZFLAG, "####

  END OF GS_DELIVER.

DATA : GT_DELIVER LIKE TABLE OF GS_DELIVER.



"## ##

RANGES GR_ZDATE FOR ZEDT03_100-ZJDATE.



DATA : OK_CODE TYPE SY-UCOMM. "###### ### ## ##



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER. "## #### ##

DATA : GC_DOCKING2 TYPE REF TO CL_GUI_DOCKING_CONTAINER. "## #### ##

DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID. " ### ## ## ##

DATA : GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID. " ### ## ## ##



DATA : GS_VARIANT TYPE DISVARIANT.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT. "## #### (## ALV# ###!)

DATA : GT_FIELDCAT TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT2 TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO. "#### (## ALV# ###!)



DATA : GS_SORT TYPE LVC_S_SORT. "SORT (## ALV# ###!)

DATA : GT_SORT TYPE LVC_T_SORT.



DATA : GV_CHECK TYPE C LENGTH 1.