
*&---------------------------------------------------------------------*

*&  Include           ZPROJECT19_001_TOP

*&---------------------------------------------------------------------*






TABLES: ZPDT19_001, ZPDT19_002, ZPDT19_003.



CONSTANTS : C_X TYPE CHAR1 VALUE 'X'.

CONSTANTS : C_A TYPE CHAR1 VALUE 'A'.



DATA : GS_001 TYPE ZPDT19_001.

DATA : GT_001 TYPE TABLE OF ZPDT19_001.



DATA : GS_002 TYPE ZPDT19_002.

DATA : GT_002 TYPE TABLE OF ZPDT19_002.



DATA : GS_003 TYPE ZPDT19_003.

DATA : GT_003 TYPE TABLE OF ZPDT19_003.



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.



DATA : GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA : GC_SPLITTER2 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



DATA : GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER3 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER4 TYPE REF TO CL_GUI_CONTAINER.



DATA : GC_CONTAINER5 TYPE REF TO CL_GUI_CONTAINER.



DATA : GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID4 TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT,

       GT_FIELDCAT1 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT2 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT3 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT4 TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GS_SORT TYPE LVC_S_SORT .

DATA : GT_SORT1 TYPE LVC_T_SORT.

DATA : GT_SORT2 TYPE LVC_T_SORT.

DATA : GT_SORT3 TYPE LVC_T_SORT.



DATA : GS_VARIANT TYPE DISVARIANT.



TYPES : BEGIN OF TY_004,

  LIFNR LIKE ZPDT19_001-LIFNR, "#####

  BUKRS LIKE ZPDT19_002-BUKRS, "####

  ZKTOKK LIKE ZPDT19_001-ZKTOKK, "#####

  NAME1 LIKE ZPDT19_001-NAME1, "####

  LAND1 LIKE ZPDT19_001-LAND1, "###

  STCD1 LIKE ZPDT19_001-STCD1, "####

  STCD2 LIKE ZPDT19_001-STCD2, "#####

  STRAS LIKE ZPDT19_001-STRAS, "##

  EKORG LIKE ZPDT19_003-EKORG, "####

  EKGRP LIKE ZPDT19_003-EKGRP, "####

  WAERS LIKE ZPDT19_003-WAERS, "##

  ZMWSKZ LIKE ZPDT19_003-ZMWSKZ, "####

  ZAKONT LIKE ZPDT19_002-ZAKONT,

  ZTERM LIKE ZPDT19_002-ZTERM,

  END OF TY_004.

DATA : gs_004 TYPE ty_004.



" F4 ### ##

DATA: gt_f4 TYPE lvc_t_f4,

      ls_f4 TYPE lvc_s_f4.



DATA: lt_values TYPE TABLE OF ty_f4,  " ### # ###

      ls_value  TYPE ty_f4.



DATA gv_f4_field TYPE fieldname.   " F4 ### ### ##



DATA gv_f4_rowid TYPE i.         " F4# ## ALV row ##

DATA : GT_004 TYPE TABLE OF ty_004.



DATA gr_handler TYPE REF TO lcl_event_handler.



DATA gv_num TYPE LIFNR.