
*&---------------------------------------------------------------------*

*&  Include           ZEDR15_PRACTICE009_TOP

*&---------------------------------------------------------------------*






TABLES : ZEDT15_102."#### ###

TABLES : ZEDT15_103."####-##

TABLES : ZEDT15_104."####

TABLES : ZEDT15_106."####






*RANGE## ##




RANGES : GR_ZFG FOR ZEDT15_102-ZQFLAG. "### ##






*## ##




CONSTANTS : C_X VALUE 'X'.






*ITAB ##




DATA : BEGIN OF GS_EMP,"####

  ZPERNR TYPE ZEDT15_102-ZPERNR, "####

  ZPNAME TYPE ZEDT15_103-ZPNAME, "##

  ZDEPCODE TYPE ZEDT15_102-ZDEPCODE, "## (MODIF)

  DATBI TYPE ZEDT15_102-DATBI, "####

  DATAB TYPE ZEDT15_102-DATAB, "####

  ZDEPRANK TYPE ZEDT15_102-ZDEPRANK, "## (MODIF)

  ZGENDER TYPE ZEDT15_103-ZGENDER,"## (MODIF)

  ZEDATE TYPE ZEDT15_102-ZEDATE, "####

  ZADDRESS TYPE ZEDT15_103-ZADDRESS, "##

  ZQDATE TYPE ZEDT15_102-ZQDATE, "####

  ZQFLAG TYPE ZEDT15_102-ZQFLAG, "####

  END OF GS_EMP.



DATA : BEGIN OF GS_EMP_OUT,"#### ###

  ICON TYPE C LENGTH 4, "## (### ##, ## ##, ### ##)

  ZPERNR TYPE ZEDT15_102-ZPERNR, "####

  ZPNAME TYPE ZEDT15_103-ZPNAME, "##

  ZDEPCODE_T TYPE C LENGTH 20, "## (MODIF)

  DATBI TYPE ZEDT15_102-DATBI, "####

  DATAB TYPE ZEDT15_102-DATAB, "####

  ZDEPRANK_T TYPE C LENGTH 20, "## (MODIF)

  ZGENDER_T TYPE C LENGTH 2,"## (MODIF)

  ZEDATE TYPE ZEDT15_102-ZEDATE, "####

  ZADDRESS TYPE ZEDT15_103-ZADDRESS, "##

  ZQDATE TYPE ZEDT15_102-ZQDATE, "####

  ZQFLAG TYPE ZEDT15_102-ZQFLAG, "####

  END OF GS_EMP_OUT.



DATA : GT_EMP LIKE TABLE OF GS_EMP.

DATA : GT_EMP_OUT LIKE TABLE OF GS_EMP_OUT.



DATA : BEGIN OF GS_TEST,"####

  ZPERNR TYPE ZEDT15_104-ZPERNR, "####

  ZDEPCODE TYPE ZEDT15_104-ZDEPCODE,"##(MODIF)

  ZYEAR TYPE ZEDT15_104-ZYEAR,"##

  DATBI TYPE ZEDT15_104-DATBI,"####

  DATAB TYPE ZEDT15_104-DATAB,"####

  ZRANK TYPE ZEDT15_104-ZRANK,"##

  ZQFLAG TYPE ZEDT15_102-ZQFLAG, "#### (##### ###)

  END OF GS_TEST.



DATA : BEGIN OF GS_TEST_OUT,"#### ###

  ZPERNR TYPE ZEDT15_104-ZPERNR, "####

  ZDEPCODE_T TYPE C LENGTH 20,"##(MODIF)

  ZYEAR TYPE ZEDT15_104-ZYEAR,"##

  DATBI TYPE ZEDT15_104-DATBI,"####

  DATAB TYPE ZEDT15_104-DATAB,"####

  ZRANK TYPE ZEDT15_104-ZRANK,"##

  END OF GS_TEST_OUT.



DATA : GT_TEST LIKE TABLE OF GS_TEST.

DATA : GT_TEST_OUT LIKE TABLE OF GS_TEST_OUT.



DATA : BEGIN OF GS_SAL,"####

  ZPERNR TYPE ZEDT15_106-ZPERNR, "####

  ZYEAR TYPE ZEDT15_106-ZYEAR,  "##

  DATBI TYPE ZEDT15_106-DATBI,"####

  DATAB TYPE ZEDT15_106-DATAB,"####

  ZSALARY TYPE ZEDT15_106-ZSALARY,"####

  ZBANKCODE TYPE ZEDT15_106-ZBANKCODE,"### (MODIF)

  ZACCOUNT TYPE ZEDT15_106-ZACCOUNT,"####

  ZQFLAG TYPE ZEDT15_102-ZQFLAG, "#### (##### ###)

  END OF GS_SAL.



DATA : BEGIN OF GS_SAL_OUT,"####

  ZPERNR TYPE ZEDT15_106-ZPERNR, "####

  ZYEAR TYPE ZEDT15_106-ZYEAR,  "##

  DATBI TYPE ZEDT15_106-DATBI,"####

  DATAB TYPE ZEDT15_106-DATAB,"####

  ZSALARY TYPE ZEDT15_106-ZSALARY,"####

  ZWAERS TYPE WAERS, "### ## ##(##X)

  ZBANKCODE_T TYPE C LENGTH 4,"### (MODIF)

  ZACCOUNT TYPE ZEDT15_106-ZACCOUNT,"####

  END OF GS_SAL_OUT.



DATA : GT_SAL LIKE TABLE OF GS_SAL.

DATA : GT_SAL_OUT LIKE TABLE OF GS_SAL_OUT.






*ALV## ##




DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.



DATA : GC_SPLITTER1 TYPE REF TO CL_GUI_SPLITTER_CONTAINER. "#### ###

DATA : GC_SPLITTER2 TYPE REF TO CL_GUI_SPLITTER_CONTAINER. "CONTAINER1# ### ###



DATA : GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER. "SPLITTER1

DATA : GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER. "SPLITTER1

DATA : GC_CONTAINER3 TYPE REF TO CL_GUI_CONTAINER. "SPLITTER2

DATA : GC_CONTAINER4 TYPE REF TO CL_GUI_CONTAINER. "SPLITTER2



DATA : GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID. "CONTAINER2# ##

DATA : GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID. "CONTAINER3# ##

DATA : GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID. "CONTAINER4# ##



DATA : GS_FIELDCAT TYPE LVC_S_FCAT.

DATA : GT_FIELDCAT1 TYPE LVC_T_FCAT. "GRID1

DATA : GT_FIELDCAT2 TYPE LVC_T_FCAT. "GRID2

DATA : GT_FIELDCAT3 TYPE LVC_T_FCAT. "GRID3



DATA : GS_VARIANT TYPE DISVARIANT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT1 TYPE LVC_T_SORT. "GRID1 (col-pos2# zpernr)

DATA : GT_SORT2 TYPE LVC_T_SORT. "GRID2, GRID3 (col-pos1# zpernr)