
*&---------------------------------------------------------------------*

*&  Include           ZMM06_004_SCR

*&---------------------------------------------------------------------*






SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  PARAMETERS P_EBELN   TYPE ZEDT06_EKKO-EBELN MODIF ID COM.           " ####

  PARAMETERS P_WERKS   TYPE ZEDT06_EKPO-WERKS  MODIF ID COM.          " ###

  PARAMETERS P_BUDAT   TYPE MKPF-BUDAT MODIF ID M1 DEFAULT SY-DATUM . " #####.

SELECTION-SCREEN END OF BLOCK B1.





SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.



  SELECTION-SCREEN BEGIN OF LINE.

    PARAMETERS P_GR RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

    SELECTION-SCREEN COMMENT 4(10) TEXT-B01 FOR FIELD P_GR.



    SELECTION-SCREEN POSITION 25.

    PARAMETERS P_FIND RADIOBUTTON GROUP R1.

    SELECTION-SCREEN COMMENT 32(10) TEXT-B02 FOR FIELD P_FIND.

  SELECTION-SCREEN END OF LINE.



SELECTION-SCREEN END OF BLOCK B2.