
*&---------------------------------------------------------------------*

*&  Include           ZEDR20_PROJECT003_TOP

*&---------------------------------------------------------------------*




TABLES: ZEDT20_MKPF, ZEDT20_MSEG, ZEDT20_EKPO, ZEDT20_EKKO, ZEDT20_MARA.



" ALV ## ##

DATA: GC_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER,    " ALV### DOCKING CONTAINER #### ##

    GC_GRID TYPE REF TO CL_GUI_ALV_GRID,    " ALV ### ALV GRID #### ##

    OK_CODE TYPE SY-UCOMM,    " TOOLBAR ## ##

    GS_FIELDCAT TYPE LVC_S_FCAT,    " ###### ###

    GT_FIELDCAT TYPE LVC_T_FCAT,    " ###### ###

    GT_SORT TYPE LVC_T_SORT,    " SORT ###

    GS_SORT TYPE LVC_S_SORT,    " SORT ###

    GS_LAYOUT TYPE LVC_S_LAYO,    " LAYOUT ###

    GS_VARIANT TYPE DISVARIANT.   " LAYOUT #### ###



DATA: BEGIN OF GS_MIGO,

  ZCHECK TYPE C,    " ##

  EBELN TYPE ZEDT20_MSEG-EBELN,    " ######

  EBELP TYPE ZEDT20_EKPO-EBELP,    " ##

  LIFNR TYPE ZEDT20_MSEG-LIFNR,    " ###

  BEDAT TYPE ZEDT20_EKKO-BEDAT,    " ###

  MATNR TYPE ZEDT20_MSEG-MATNR,    " ####

  MAKTX TYPE ZEDT20_MARA-MAKTX,    " ###

  POMENGE TYPE ZEDT20_MSEG-MENGE,

  MENGE TYPE ZEDT20_MSEG-MENGE,    " ##

  REMENGE TYPE ZEDT20_MSEG-MENGE,

  MEINS TYPE ZEDT20_MSEG-MEINS,    " ##

  BPRME TYPE ZEDT20_EKPO-BPRME,    " ##

  WAERS TYPE ZEDT20_MSEG-WAERS,    " ##

  PRDAT TYPE ZEDT20_EKPO-PRDAT,    " ###

  WERKS TYPE ZEDT20_MSEG-WERKS,    " ###

  LGORT TYPE ZEDT20_MSEG-LGORT,    " ####

  BUKRS TYPE ZEDT20_MSEG-BUKRS,    " ####

  END OF GS_MIGO.

DATA: GT_MIGO LIKE TABLE OF GS_MIGO.



DATA: BEGIN OF GS_WAREHOUSED_HEADER,

  EBELN TYPE ZEDT20_EKKO-EBELN,    "####

  WERKS TYPE ZEDT20_MSEG-WERKS,    " ###

  BEDAT TYPE ZEDT20_EKKO-BEDAT,    " PO## ###

  BUKRS TYPE ZEDT20_EKKO-BUKRS,    " ####

  EKGRP TYPE ZEDT20_EKKO-EKGRP,    " ####

  LIFNR TYPE ZEDT20_EKKO-LIFNR,    " #####

  NAME1 TYPE ZEDT20_LFA1-NAME1,    " ### ##

  END OF GS_WAREHOUSED_HEADER.

DATA: GT_WAREHOUSED_HEADER LIKE TABLE OF GS_WAREHOUSED_HEADER.



DATA: BEGIN OF GS_WAREHOUSED_ALV,

  ZCHECK TYPE C,    " ##

  ZLSTATUS TYPE C LENGTH 2,    " ####

  EBELN TYPE ZEDT20_MSEG-EBELN,    "####

  LOEVM TYPE ZEDT20_MSEG-LOEVM,    " ##

  EBELP TYPE ZEDT20_EKPO-EBELP,    " ##

  MBLNR TYPE ZEDT20_MSEG-MBLNR,    " ######

  ZEILE TYPE ZEDT20_MSEG-ZEILE,    " #####

  MAKTX TYPE ZEDT20_MARA-MAKTX,    " ###

  POMENGE TYPE ZEDT20_MSEG-MENGE,    " PO ##

  MENGE TYPE ZEDT20_MSEG-MENGE,    " ## ## ##

  MEINS TYPE ZEDT20_MSEG-MEINS,    " ##

  BLDAT TYPE ZEDT20_MKPF-BLDAT,    " ###

  LGORT TYPE ZEDT20_MSEG-LGORT,    " ####

  END OF GS_WAREHOUSED_ALV.

DATA: GT_WAREHOUSED_ALV LIKE TABLE OF GS_WAREHOUSED_ALV.



DATA: BEGIN OF GS_EKKO.

  include structure
ZEDT20_EKKO
.

  DATA: END OF GS_EKKO.

DATA: GT_EKKO LIKE TABLE OF GS_EKKO.



DATA: BEGIN OF GS_EBELN,

  EBELN TYPE ZEDT20_MSEG-EBELN,

  END OF GS_EBELN.

DATA: GT_EBELN LIKE TABLE OF GS_EBELN.



DATA: BEGIN OF GS_MARA,

  MATNR TYPE ZEDT20_MARA-MATNR,

  MAKTX TYPE ZEDT20_MARA-MAKTX,

  END OF GS_MARA.

DATA: GT_MARA LIKE TABLE OF GS_MARA.



DATA: BEGIN OF GS_MSEG.

  include structure
ZEDT20_MSEG
.

  DATA: END OF GS_MSEG.

DATA: GT_MSEG LIKE TABLE OF GS_MSEG.



DATA: BEGIN OF GS_MKPF.

  include structure
ZEDT20_MKPF
.

  DATA: END OF GS_MKPF.

DATA: GT_MKPF LIKE TABLE OF GS_MKPF.



DATA: GO_EVENT TYPE REF TO EVENT.