
*&---------------------------------------------------------------------*

*&  Include           ZEDR20_PROJECT003_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  PARAMETERS: P_EBELN TYPE ZEDT20_MSEG-EBELN.   " ####

  PARAMETERS: P_WERKS TYPE ZEDT20_MSEG-WERKS.   " ###

  SELECT-OPTIONS: S_BLDAT FOR ZEDT20_MKPF-BLDAT MODIF ID M1 NO INTERVALS NO-EXTENSION.   " #####

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  SELECTION-SCREEN BEGIN OF LINE.

    SELECTION-SCREEN COMMENT (5) TEXT-001 FOR FIELD P_R1.

    PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

    SELECTION-SCREEN COMMENT 20(5) TEXT-002 FOR FIELD P_R2.

    PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B2.