
*&---------------------------------------------------------------------*

*&  Include           ZEDR15_PRACTICE008_TOP

*&---------------------------------------------------------------------*

*####, #### ### ####




TABLES : ZEDT15_100.

TABLES : ZEDT15_101.






*## ### ##(X)# ## ## ##




CONSTANTS : C_X VALUE 'X'.

CONSTANTS : C_A VALUE ''.






*## ## ##




RANGES : R_ZFG FOR ZEDT15_101-ZFLAG.








*### # ### ###### ##




DATA : BEGIN OF GS_ORDER, "####

  ZORDNO LIKE ZEDT15_100-ZORDNO, "####

  ZIDCODE LIKE ZEDT15_100-ZIDCODE, "##ID

  ZMATNR LIKE ZEDT15_100-ZMATNR, "####

  ZMATNAME LIKE ZEDT15_100-ZMATNAME, "###

  ZMTART LIKE ZEDT15_100-ZMTART, "#### (MODIFY)

  ZVOLUM LIKE ZEDT15_100-ZVOLUM, "##

  VRKME LIKE ZEDT15_100-VRKME, "##

  ZNSAMT LIKE ZEDT15_100-ZNSAMT, "####

  ZSLAMT LIKE ZEDT15_100-ZSLAMT, "####

  ZDCAMT LIKE ZEDT15_100-ZDCAMT, "####

  ZWAERS LIKE ZEDT15_100-ZWAERS, "##

  ZSALE_FG LIKE ZEDT15_100-ZSALE_FG, " #### (MODIFY)

  ZJDATE LIKE ZEDT15_100-ZJDATE, "####

  ZRET_FG LIKE ZEDT15_100-ZRET_FG, "#### (MODIFY)

  ZRDATE LIKE ZEDT15_100-ZRDATE, "####

  ZFLAG LIKE ZEDT15_101-ZFLAG, "####### ## ##(##X)

  END OF GS_ORDER.



DATA : BEGIN OF GS_ORDER_OUT, "#### ###

  ICON TYPE C LENGTH 4, "##(### ### #### ## ##)

  ZORDNO LIKE ZEDT15_100-ZORDNO, "####

  ZIDCODE LIKE ZEDT15_100-ZIDCODE, "##ID

  ZMATNR LIKE ZEDT15_100-ZMATNR, "####

  ZMATNAME LIKE ZEDT15_100-ZMATNAME, "###

  ZMTART_T TYPE C LENGTH 8, "#### (ZMTART# #### MODIFY)

  ZVOLUM LIKE ZEDT15_100-ZVOLUM, "##

  VRKME LIKE ZEDT15_100-VRKME, "##

  ZNSAMT LIKE ZEDT15_100-ZNSAMT, "####

  ZSLAMT LIKE ZEDT15_100-ZSLAMT, "####

  ZDCAMT LIKE ZEDT15_100-ZDCAMT, "####

  ZWAERS LIKE ZEDT15_100-ZWAERS, "##

  ZSALE_FG_T TYPE C LENGTH 4, " #### (ZSALE_FG# #### MODIFY)

  ZJDATE LIKE ZEDT15_100-ZJDATE, "####

  ZRET_FG_T TYPE C LENGTH 10, "#### (ZRET_FG# #### MODIFY)

  ZRDATE LIKE ZEDT15_100-ZRDATE, "####

  END OF GS_ORDER_OUT.



DATA : GT_ORDER LIKE TABLE OF GS_ORDER.

DATA : GT_ORDER_OUT LIKE TABLE OF GS_ORDER_OUT.



DATA : BEGIN OF GS_DELIVER, "####

  ZORDNO LIKE ZEDT15_101-ZORDNO, "####

  ZIDCODE LIKE ZEDT15_101-ZIDCODE, "##ID

  ZMATNR LIKE ZEDT15_101-ZMATNR, "####

  ZMATNAME LIKE ZEDT15_101-ZMATNAME, "###

  ZMTART LIKE ZEDT15_101-ZMTART, "#### (MODIFY)

  ZVOLUM LIKE ZEDT15_101-ZVOLUM, "##

  VRKME LIKE ZEDT15_101-VRKME, "##

  ZSLAMT LIKE ZEDT15_100-ZSLAMT, "####

  ZWAERS LIKE ZEDT15_100-ZWAERS, "##

  ZDFLAG LIKE ZEDT15_101-ZDFLAG, "#### (MODIFY)

  ZDGUBUN LIKE ZEDT15_101-ZDGUBUN, "#### (MODIFY)

  ZDDATE LIKE ZEDT15_101-ZDDATE, "####

  ZRDATE LIKE ZEDT15_101-ZRDATE, "####

  ZFLAG LIKE ZEDT15_101-ZFLAG, "####

  END OF GS_DELIVER.



DATA : BEGIN OF GS_DELIVER_OUT, "#### ###

  ICON TYPE C LENGTH 4, "##(### ### #### ## ##)

  ZORDNO LIKE ZEDT15_101-ZORDNO, "####

  ZIDCODE LIKE ZEDT15_101-ZIDCODE, "##ID

  ZMATNR LIKE ZEDT15_101-ZMATNR, "####

  ZMATNAME LIKE ZEDT15_101-ZMATNAME, "###

  ZMTART_T TYPE C LENGTH 8, "#### (ZMTART# #### MODIFY)

  ZVOLUM LIKE ZEDT15_101-ZVOLUM, "##

  VRKME LIKE ZEDT15_101-VRKME, "##

  ZSLAMT LIKE ZEDT15_100-ZSLAMT, "####

  ZWAERS LIKE ZEDT15_100-ZWAERS, "##

  ZDFLAG_T TYPE C LENGTH 8, "#### (ZDFLAG# #### MODIFY)

  ZDGUBUN_T TYPE C LENGTH 6, "#### (ZDGUBUN# #### MODIFY)

  ZDDATE LIKE ZEDT15_101-ZDDATE, "####

  ZRDATE LIKE ZEDT15_101-ZRDATE, "####

  ZFLAG LIKE ZEDT15_101-ZFLAG, "####

  END OF GS_DELIVER_OUT.





DATA : GT_DELIVER LIKE TABLE OF GS_DELIVER.

DATA : GT_DELIVER_OUT LIKE TABLE OF GS_DELIVER_OUT.



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.



DATA : GC_GRID100 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID200 TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_VARIANT TYPE DISVARIANT.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT.

DATA : GT_FIELDCAT TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT TYPE LVC_T_SORT.