
*&---------------------------------------------------------------------*

*& Report ZEDR24_012_PARAMETER

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR24_012_PARAMETER.



"-------------------------------------------------------------------------

"1. ## ##






*"## ##

*PARAMETERS : P_ZCODE LIKE ZEDT24_001-ZCODE OBLIGATORY.    "### ##

*PARAMETERS : P_ZPERNR TYPE C LENGTH 10 VISIBLE LENGTH 5.  "5## ###

*PARAMETERS : P_ZGEN LIKE ZEDT24_001-ZGENDER DEFAULT 'M'.  "### ##

*PARAMETERS : P_ZNUM TYPE P DECIMALS 2 NO-DISPLAY.         "### ### ##

*

*"## ##

*PARAMETERS : Z_CHECK AS CHECKBOX DEFAULT 'X'.            "#### #### ##

*

*"### ##

*PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'.

*PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

*

*IF Z_CHECK = 'X'.

*  WRITE :/ '##'.

*ELSE.

*  WRITE :/ '## X'.

*ENDIF.

*

*

*IF P_R1 = 'X'.

*  WRITE :/ 'R1'.

*ELSEIF P_R2 = 'X'.

*  WRITE :/ 'R2'.

*ENDIF.






"-------------------------------------------------------------------------

"2. #### ## #### # ## ## ##






*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  PARAMETERS : P_ZCODE LIKE ZEDT24_001-ZCODE OBLIGATORY.    "### ##

*  PARAMETERS : P_ZPERNR TYPE C LENGTH 10 VISIBLE LENGTH 5.  "5## ###

*  PARAMETERS : P_ZGEN LIKE ZEDT24_001-ZGENDER DEFAULT 'M'.  "### ##

*  PARAMETERS : P_ZNUM TYPE P DECIMALS 2 NO-DISPLAY.         "### ### ##

*SELECTION-SCREEN END OF BLOCK B1.

*

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

*  PARAMETERS : Z_CHECK AS CHECKBOX DEFAULT 'X'.            "#### #### ##

*  SELECTION-SCREEN BEGIN OF LINE.

*    PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X'.

*      SELECTION-SCREEN POSITION 3.

*      SELECTION-SCREEN COMMENT (10) FOR FIELD P_R1.

*    PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

*      SELECTION-SCREEN POSITION 20.

*      SELECTION-SCREEN COMMENT (10) FOR FIELD P_R2.

*  SELECTION-SCREEN END OF LINE.

*SELECTION-SCREEN END OF BLOCK B2.

*

*IF Z_CHECK = 'X'.

*  WRITE :/ '##'.

*ELSE.

*  WRITE :/ '## X'.

*ENDIF.

*

*

*IF P_R1 = 'X'.

*  WRITE :/ 'R1'.

*ELSEIF P_R2 = 'X'.

*  WRITE :/ 'R2'.

*ENDIF.






"-------------------------------------------------------------------------

"3. PARAMETER# DB ## # ####




*DATA : BEGIN OF GS_STUDENT.

*  INCLUDE TYPE ZEDT24_001.

*DATA : END OF GS_STUDENT.

*DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

*

*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

*  PARAMETERS : P_ZCODE LIKE ZEDT24_001-ZCODE.

*  PARAMETERS : P_ZPERNR TYPE C LENGTH 10 NO-DISPLAY.

*  PARAMETERS : P_ZGEN LIKE ZEDT24_001-ZGENDER DEFAULT 'M'.

*SELECTION-SCREEN END OF BLOCK B1.

*

*SELECT * FROM ZEDT00_001

*  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

*  WHERE ZCODE = P_ZCODE

*    AND ZGENDER = P_ZGEN.

*

*IF GT_STUDENT[] IS NOT INITIAL.

*  CLEAR : GS_STUDENT.

*  LOOP AT GT_STUDENT INTO GS_STUDENT.

*    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_STUDENT-ZENAME, GS_STUDENT-ZPERNR.

*  ENDLOOP.

*ELSE.

*  WRITE :/ '### ##'.

*ENDIF.






DATA : BEGIN OF GS_STUDENT,

  ZMNAME LIKE ZEDT24_002-ZMNAME,

  ZKNAME LIKE ZEDT24_001-ZKNAME,

  ZCODE LIKE ZEDT24_001-ZCODE,

END OF GS_STUDENT.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.



SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  PARAMETERS : P_ZCODE LIKE ZEDT24_001-ZCODE.

  PARAMETERS : P_ZPERNR TYPE C LENGTH 10 NO-DISPLAY.

  PARAMETERS : P_ZGEN LIKE ZEDT24_001-ZGENDER DEFAULT 'M'.

SELECTION-SCREEN END OF BLOCK B1.



CLEAR P_ZCODE.

CLEAR P_ZGEN.



SELECT * FROM ZEDT00_001

  INTO CORRESPONDING FIELDS OF TABLE GT_STUDENT

  WHERE ZCODE = P_ZCODE "SELECTION-OPTIONS ### IN ##

    AND ZGENDER = P_ZGEN.



IF GT_STUDENT[] IS NOT INITIAL.

  CLEAR : GS_STUDENT.

  LOOP AT GT_STUDENT INTO GS_STUDENT.

    WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZMNAME.

  ENDLOOP.

ELSE.

  WRITE :/ '### ##'.

ENDIF.