
*&---------------------------------------------------------------------*

*&  Include           ZEDR14_PRACTICE008_TOP

*&---------------------------------------------------------------------*






TABLES : ZEDT14_100, ZEDT14_101.



CONSTANTS : BEGIN OF BOOL,    "CONSTANTS ##

  TRUE(1) VALUE '1',

  FALSE(1) VALUE '0',

  END OF BOOL.

CONSTANTS FIRST_DATE(2) VALUE '01'.



"### ITAB

DATA : BEGIN OF GS_PRINT100.

  include structure
ZEDT14_100
.

DATA : END OF GS_PRINT100.

DATA : GT_PRINT100 LIKE TABLE OF GS_PRINT100.



DATA : BEGIN OF GS_PRINT101.

  include structure
ZEDT14_101
.

DATA : END OF GS_PRINT101.

DATA : GT_PRINT101 LIKE TABLE OF GS_PRINT101.



"### ITAB

DATA : BEGIN OF GS_FINAL100, "###### ## ###

    ZCOLOR TYPE C LENGTH 4,   "###

    ZORDNO LIKE ZEDT14_100-ZORDNO,  "####

    ZIDCODE LIKE ZEDT14_100-ZIDCODE,  "##ID

    ZMATNR LIKE ZEDT14_100-ZMATNR,  "####

    ZMATNAME LIKE ZEDT14_100-ZMATNAME,  "###

    ZMTART LIKE ZEDT14_100-ZMTART,  "####

    ZVOLUM LIKE ZEDT14_100-ZVOLUM,  "##

    VRKME LIKE ZEDT14_100-VRKME,  "##

    ZNSAMT LIKE ZEDT14_100-ZNSAMT,  "####

    ZSLAMT LIKE ZEDT14_100-ZSLAMT,  "####

    ZDCAMT LIKE ZEDT14_100-ZDCAMT,  "####

    ZWAERS LIKE ZEDT14_100-ZWAERS,  "##

    ZSALE_FG LIKE ZEDT14_100-ZSALE_FG,  "####

    ZJDATE LIKE ZEDT14_100-ZJDATE,  "####

    ZRET_FG LIKE ZEDT14_100-ZRET_FG,  "####

    ZRDATE LIKE ZEDT14_100-ZRDATE,  "####

    ZMTART_TEXT TYPE C LENGTH 10,   "#### ##

    ZSALE_TEXT TYPE C LENGTH 10,    "## ##

    ZRET_TEXT TYPE C LENGTH 10,   "#### ##

  END OF GS_FINAL100.

DATA : GT_FINAL100 LIKE TABLE OF GS_FINAL100.



DATA : BEGIN OF GS_FINAL101, "###### ## ###

    ZCOLOR TYPE C LENGTH 4,   "###

    ZORDNO LIKE ZEDT14_101-ZORDNO,  "####

    ZIDCODE LIKE ZEDT14_101-ZIDCODE,  "##ID

    ZMATNR LIKE ZEDT14_101-ZMATNR,  "####

    ZMATNAME LIKE ZEDT14_101-ZMATNAME,  "###

    ZMTART LIKE ZEDT14_101-ZMTART,  "####

    ZVOLUM LIKE ZEDT14_101-ZVOLUM,  "##

    VRKME LIKE ZEDT14_101-VRKME,  "##

    ZSLAMT LIKE ZEDT14_101-ZSLAMT,  "####

    ZWAERS LIKE ZEDT14_100-ZWAERS,  "##

    ZDFLAG LIKE ZEDT14_101-ZDFLAG,  "####

    ZDGUBUN LIKE ZEDT14_101-ZDGUBUN,  "####

    ZDDATE LIKE ZEDT14_101-ZDDATE,  "####

    ZRDATE LIKE ZEDT14_101-ZRDATE,  "####

    ZFLAG LIKE ZEDT14_101-ZFLAG,   "####

    ZMTART_TEXT TYPE C LENGTH 10,  "#### ##

    ZDFLAG_TEXT TYPE C LENGTH 10,  "#### ##

    ZDGUBUN_TEXT TYPE C LENGTH 10,  "## ##

  END OF GS_FINAL101.

DATA : GT_FINAL101 LIKE TABLE OF GS_FINAL101.



DATA : OK_CODE TYPE SY-UCOMM.



DATA: GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA: GC_GRID TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_VARIANT TYPE DISVARIANT.



DATA: GT_FIELDCAT TYPE LVC_T_FCAT,

      GS_FIELDCAT TYPE LVC_S_FCAT.



DATA: GS_LAYOUT TYPE LVC_S_LAYO.



DATA: GT_SORT TYPE LVC_T_SORT,

      GS_SORT TYPE LVC_S_SORT.