
*&---------------------------------------------------------------------*

*&  Include           ZEDR14_PRACTICE008_SCR

*&---------------------------------------------------------------------*






"### ## ##

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS : S_ZORDNO FOR ZEDT14_100-ZORDNO.

  PARAMETERS : P_ZID LIKE ZEDT14_100-ZIDCODE.

  SELECT-OPTIONS : S_ZMATNR FOR ZEDT14_100-ZMATNR.

  SELECT-OPTIONS : S_ZJDATE FOR ZEDT14_100-ZJDATE MODIF ID M1.

  SELECT-OPTIONS : S_ZDDATE FOR ZEDT14_101-ZDDATE MODIF ID M2.

SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

  PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

SELECTION-SCREEN END OF BLOCK B2.

SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME.

  PARAMETERS : P_CH1 AS CHECKBOX DEFAULT 'X' MODIF ID M3.

SELECTION-SCREEN END OF BLOCK B3.



AT SELECTION-SCREEN OUTPUT.

  LOOP AT SCREEN.

    IF SCREEN-GROUP1 = 'M1'.

      IF P_R1 = 'X'.

        SCREEN-ACTIVE = BOOL-TRUE.

      ELSEIF P_R2 = 'X'.

        SCREEN-ACTIVE = BOOL-FALSE.

      ENDIF.

    ENDIF.

    MODIFY SCREEN.

    IF SCREEN-GROUP1 = 'M2'.

      IF P_R1 = 'X'.

        SCREEN-ACTIVE = BOOL-FALSE.

      ELSEIF P_R2 = 'X'.

        SCREEN-ACTIVE = BOOL-TRUE.

      ENDIF.

    ENDIF.

    MODIFY SCREEN.

  ENDLOOP.