
*&---------------------------------------------------------------------*

*&  Include           ZSPLITTER_CONTAINER022_TOP

*&---------------------------------------------------------------------*






TABLES : ZEDT022_001.



DATA : BEGIN OF GS_STUDENT,

  ZCOLOR TYPE C LENGTH 4,

  ZCODE LIKE ZEDT022_001-ZCODE,

  ZPERNR LIKE ZEDT022_001-ZPERNR,

  ZKNAME LIKE ZEDT022_001-ZKNAME,

  ZENAME LIKE ZEDT022_001-ZENAME,

  ZGENDER LIKE ZEDT022_001-ZGENDER,

  ZSUM LIKE ZEDT022_002-ZSUM,

  ZMAJOR LIKE ZEDT022_002-ZMAJOR,

  ZMNAME LIKE ZEDT022_002-ZMNAME,

  END OF GS_STUDENT.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA : GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



"CONTAINER ## ##

DATA : GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.



DATA : GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_VARIANT TYPE DISVARIANT.



DATA : GS_FIELDCAT1 TYPE LVC_S_FCAT.

DATA : GS_FIELDCAT2 TYPE LVC_S_FCAT.



DATA : GT_FIELDCAT1 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT2 TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GS_SORT1 TYPE LVC_S_SORT.

DATA : GS_SORT2 TYPE LVC_S_SORT.



DATA : GT_SORT1 TYPE LVC_T_SORT.

DATA : GT_SORT2 TYPE LVC_T_SORT.