
*&---------------------------------------------------------------------*

*&  Include           ZDOCKING_CONTAINER08_02_TOP

*&---------------------------------------------------------------------*






TABLES :ZEDT08_001.



DATA: BEGIN OF GS_STUDENT,

  ZCOLOR TYPE C LENGTH 4,

  ZCODE LIKE ZEDT08_001-ZCODE,

  ZPERNR LIKE ZEDT08_001-ZPERNR,

  ZKNAME LIKE ZEDT08_001-ZKNAME,

  ZENAME LIKE ZEDT08_001-ZENAME,

  ZGENDER LIKE ZEDT08_001-ZGENDER,

  ZSUM LIKE ZEDT08_002-ZSUMM,

  ZMAJOR LIKE ZEDT08_002-ZMAJOR,

  ZMNAME LIKE ZEDT08_002-ZMNAME,

  END OF GS_STUDENT.



DATA: GT_STUDENT LIKE TABLE OF GS_STUDENT.

DATA: GT_STUDENT2 LIKE TABLE OF ZEDT08_001.



DATA: OK_CODE TYPE SY-UCOMM.



DATA: GS_FIELDCAT TYPE LVC_S_FCAT.

DATA: GT_FIELDCAT TYPE LVC_T_FCAT.

DATA: GT_FIELDCAT1 TYPE LVC_T_FCAT.

DATA: GT_FIELDCAT2 TYPE LVC_T_FCAT.

DATA: GS_LAYOUT TYPE LVC_S_LAYO.

DATA: GS_SORT TYPE LVC_S_SORT.

DATA: GT_SORT TYPE LVC_T_SORT.



DATA: GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA: GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA: GC_GRID TYPE REF TO CL_GUI_ALV_GRID.



DATA: GO_EVENT TYPE REF TO EVENT.



DATA: GS_VARIANT TYPE DISVARIANT.



DATA: GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.

DATA: GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.



DATA: GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA: GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.



DATA: GT_SORT1 TYPE LVC_T_SORT.

DATA: GT_SORT2 TYPE LVC_T_SORT.



DATA: E_ROW_ID TYPE LVC_S_ROW.

DATA: E_COLUMN_ID TYPE LVC_S_COL.

DATA: ES_ROW_NO TYPE LVC_S_ROID.



DATA: GS_SAVE TYPE ZEDT08_001.

DATA: GT_SAVE TYPE TABLE OF ZEDT08_001.