
*&---------------------------------------------------------------------*

*&  Include           ZMM02_002_SCR

*&---------------------------------------------------------------------*




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  PARAMETERS : P_LIFNRV TYPE LIFNR MODIF ID M2. "#####

  PARAMETERS : P_BUKRS TYPE BUKRS. "####

  PARAMETERS : P_LIFNRC TYPE LIFNR MODIF ID M1. "###

  PARAMETERS : P_BEDAT TYPE BEDAT MODIF ID M1. "###

  PARAMETERS : P_EBELN TYPE EBELN MODIF ID M2. "PO##

SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  SELECTION-SCREEN BEGIN OF LINE.

  SELECTION-SCREEN COMMENT (5) TEXT-001 FOR FIELD P_CRE.

  PARAMETERS: P_CRE RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1. "##

  SELECTION-SCREEN COMMENT 35(5) TEXT-002 FOR FIELD P_VIEW.

  PARAMETERS: P_VIEW RADIOBUTTON GROUP R1. "##

  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B2.