
*&---------------------------------------------------------------------*

*&  Include           ZMM09_004_SCR

*&---------------------------------------------------------------------*






SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  "####

  PARAMETERS : P_EBELNC LIKE ZEKKO_09-EBELN MODIF ID C. "####

  PARAMETERS : P_WERKSC LIKE ZMSEG09-WERKS MODIF ID C. "###

  PARAMETERS : P_BLDAT LIKE ZRBKP09-BLDAT MODIF ID C.  "#####



  "####

  PARAMETERS : P_EBELNS LIKE ZEKKO_09-EBELN MODIF ID S. "####

  PARAMETERS : P_WERKSS LIKE ZMSEG09-WERKS MODIF ID S. "###



  SELECTION-SCREEN SKIP.



  "####/## ##

  PARAMETERS : P_R1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

  PARAMETERS : P_R2 RADIOBUTTON GROUP R1.

SELECTION-SCREEN END OF BLOCK B1.



"######




*SELECTION-SCREEN BEGIN OF SCREEN 101 AS SUBSCREEN. "#####

*  PARAMETERS : P_BLDATH LIKE ZRBKP09-BLDAT. "###

*  PARAMETERS : P_BUDATH LIKE ZRBKP09-BUDAT. "###

*  PARAMETERS : P_RMWWR LIKE ZRBKP09-RMWWR.  "##

*  PARAMETERS : P_WAERS LIKE ZRBKP09-WAERS. "###

*  PARAMETERS : P_MWSKZ LIKE ZRBKP09-MWSKZ. "####

*  PARAMETERS : P_WMWST1 LIKE ZRBKP09-WMWST1. "## (###### +/-)

*  PARAMETERS : P_BKTXT LIKE ZRBKP09-BKTXT.  "###

*  PARAMETERS : P_ZTERM LIKE ZRBKP09-ZTERM.  "####

*  PARAMETERS : P_ZFBDT LIKE ZRBKP09-ZFBDT.  "###

*

*SELECTION-SCREEN END OF SCREEN 101.




SELECTION-SCREEN BEGIN OF SCREEN 102 AS SUBSCREEN. "##



SELECTION-SCREEN END OF SCREEN 102.