
*&---------------------------------------------------------------------*

*&  Include           ZMM09_004_TOP

*&---------------------------------------------------------------------*






DATA : OK_CODE TYPE SY-UCOMM.



CONSTANTS : C_V1 TYPE STRING VALUE 'V1 (####10%)'.

CONSTANTS : C_V2 TYPE STRING VALUE 'V2 (####0%)'.

CONSTANTS : C_V3 TYPE STRING VALUE 'V3 (####0%)'.

CONSTANTS : C_V4 TYPE STRING VALUE 'V4 (#####10%)'.

CONSTANTS : C_V5 TYPE STRING VALUE 'V5 (######10%)'.



CONSTANTS : C_TAX_V1 TYPE P DECIMALS 2 VALUE '0.10',

           C_TAX_V2 TYPE P DECIMALS 2 VALUE '0.00',

           C_TAX_V3 TYPE P DECIMALS 2 VALUE '0.00',

           C_TAX_V4 TYPE P DECIMALS 2 VALUE '0.10',

           C_TAX_V5 TYPE P DECIMALS 2 VALUE '0.10'.





"tabstip ##

CONTROLS TABSTRIP TYPE TABSTRIP.

DATA : DYNNR TYPE SY-DYNNR.



"101 #####

DATA : GF_BLDAT LIKE ZRBKP09-BLDAT, "### (#####)

       GF_BUDAT LIKE ZRBKP09-BUDAT, "###

       GF_RMWWR LIKE ZRBKP09-RMWWR, "##

       GF_WAERS LIKE ZRBKP09-WAERS, "###

       GF_MWSKZ LIKE ZRBKP09-MWSKZ, "####

       GF_WMWST1 LIKE ZRBKP09-WMWST1, "##

       GF_BKTXT LIKE ZRBKP09-BKTXT, "###

       GF_ZTERM LIKE ZRBKP09-ZTERM, "####

       GF_ZFBDT LIKE ZRBKP09-ZFBDT. "###





DATA : GF_BALANCE TYPE WRBTR. "##

DATA : GF_WAERS2 TYPE WAERS.



"alw, ## ##

DATA : GC_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER,

       GC_GRID   TYPE REF TO CL_GUI_ALV_GRID.



DATA : GC_ITEM_200 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,

       GC_GRID_200 TYPE REF TO CL_GUI_ALV_GRID.





DATA : GS_FIELDCAT TYPE LVC_S_FCAT,

       GT_FIELDCAT TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GT_TOOLBAR TYPE UI_FUNCTIONS.



"### (alv ###)

DATA : BEGIN OF GS_ITEM_ALV,

  LV_CHECK TYPE C LENGTH 1, "#### (##### ##)

  BUZEI LIKE ZRSEG09-BUZEI,  "## ## (######)

  NETPR LIKE ZEKPO_09-STPRS, "##

  MENGE TYPE ZRSEG09-MENGE, "## (####)

  MEINS LIKE ZRSEG09-MEINS, "##

  WAERS LIKE ZEKKO_09-WAERS,  "##

  WRBTR LIKE ZRSEG09-WRBTR, "#### (## * ##)

  EBELN LIKE ZRSEG09-EBELN,  "PO##

  EBELP LIKE ZRSEG09-EBELP,  "PO# ## ##

  MWSKZ_S TYPE STRING,       "####

  WMWST  LIKE ZRSEG24-WMWST, "##

  MATNR LIKE ZMSEG09-MATNR, "####

  ZMATNAME LIKE ZMARA09-ZMATNAME, "#### (###)

  WERKS LIKE ZMSEG09-WERKS, "###

  DBMTR LIKE BSIK-DMBTR,     "## (### + ##)

  SGTXT LIKE ZRSEG09-SGTXT, "###

END OF GS_ITEM_ALV.

DATA : GT_ITEM_ALV LIKE TABLE OF GS_ITEM_ALV.



DATA : GO_EVENT TYPE REF TO EVENT.

DATA : GO_EVENT_200 TYPE REF TO EVENT.



"##### ## ##

DATA : GV_FLAG_EVENT TYPE ABAP_BOOL VALUE ABAP_FALSE.



"###

DATA : ICON_ST1 TYPE ICONS-TEXT.



"## #### ###

DATA : GV_BELNR LIKE ZRBKP09-BELNR.



DATA : GS_RBKP LIKE ZRBKP09. "####



DATA : GS_RSEG LIKE ZRSEG09. "## ###

DATA : GT_RSEG LIKE TABLE OF GS_RSEG.



DATA : BEGIN OF GS_ITEM_ALV_200,

  LV_CHECK TYPE C LENGTH 1, "##

  BELNR TYPE ZRBKP09-BELNR, "######

  GJAHR TYPE ZRBKP09-GJAHR, "####

  BUZEI TYPE ZRSEG09-BUZEI, "#### ## ##

  EBELN TYPE ZRSEG09-EBELN, "######

  EBELP LIKE ZRSEG09-EBELN, "## (######### #)

  MATNR TYPE ZRSEG09-MATNR, "####

  ZMATNAME TYPE ZMARA09-ZMATNAME, "###

  MENGE TYPE ZRSEG09-MENGE, "####

  MEINS TYPE ZRSEG09-MEINS, "##

  NETPR TYPE ZRSEG09-NETPR, "##

  WRBTR TYPE ZRSEG09-WRBTR, "####

  WMWST TYPE ZRSEG09-WMWST, "##

  DBMTR TYPE ZRSEG09-DBMTR, "##

  SGTXT TYPE ZRSEG09-SGTXT, "###

  WAERS TYPE ZRSEG09-WAERS, "## #

  SHKZG TYPE ZRSEG09-SHKZG,

END OF GS_ITEM_ALV_200.

DATA : GT_ITEM_ALV_200 LIKE TABLE OF GS_ITEM_ALV_200.



"##/## ## ##

DATA : BEGIN OF GS_CANCEL_DEC,

  BELNR TYPE ZRSEG09-BELNR,

  GJAHR TYPE ZRSEG09-GJAHR,

  IS_FULL TYPE ABAP_BOOL, "####='X'

END OF GS_CANCEL_DEC.

DATA : GT_CANCEL_DEC LIKE TABLE OF GS_CANCEL_DEC.



DATA: gv_need_balance_calc TYPE abap_bool VALUE abap_true.





"#### ###

DATA : BEGIN OF GS_MIRO_LIST,

  BELNR LIKE ZRBKP09-BELNR, "######

  BUDAT LIKE ZBKPF09-BUDAT, "###

END OF GS_MIRO_LIST.

DATA : GT_MIRO_LIST LIKE TABLE OF GS_MIRO_LIST.



DATA : BEGIN OF GS_MIRO_ALV,

  DISP_TEXT TYPE CHAR200,

END OF GS_MIRO_ALV.

DATA : GT_MIRO_ALV LIKE TABLE OF GS_MIRO_ALV.



"alv ##

DATA : GC_CUSTOM_MIRO_LIST TYPE REF TO CL_GUI_CUSTOM_CONTAINER.

DATA : GC_GRID_MIRO_LIST TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_FIELDCAT_200 TYPE LVC_S_FCAT,

       GT_FIELDCAT_200 TYPE LVC_T_FCAT.



DATA : GS_LAYOUT_200 TYPE LVC_S_LAYO.



DATA : GO_EVENT_MIRO TYPE REF TO EVENT.



"### ###

DATA : BEGIN OF GS_HEADER_ALV,

  BELNR LIKE ZRBKP09-BELNR, "######

  BLART LIKE ZRBKP09-BLART, "####

  BLDAT LIKE ZRBKP09-BLDAT, "###

  BUDAT LIKE ZRBKP09-BUDAT, "###

END OF GS_HEADER_ALV.

DATA : GT_HEADER_ALV LIKE TABLE OF GS_HEADER_ALV.



"## #####

DATA : BELNR_200 LIKE ZRBKP09-BELNR,

       BLART_200 LIKE ZRBKP09-BLART,

       BLDAT_200 LIKE ZRBKP09-BLDAT,

       BUDAT_200 LIKE ZRBKP09-BUDAT.