
*&---------------------------------------------------------------------*

*&  Include           ZEDR02_PRACTICE008_SCR

*&---------------------------------------------------------------------*






SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS : S_ZORDNO FOR ZEDT02_100-ZORDNO. "####

  SELECT-OPTIONS : S_ZCODE FOR ZEDT02_100-ZIDCODE NO-EXTENSION NO INTERVALS. "##ID

  SELECT-OPTIONS : S_ZMATNR FOR ZEDT02_100-ZMATNR. "####

  SELECT-OPTIONS : S_ZJDATE FOR ZEDT02_100-ZJDATE MODIF ID M1. "####

  SELECT-OPTIONS : S_ZDDATE FOR ZEDT02_101-ZDDATE MODIF ID M2. "####

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  PARAMETERS : P_ORDER RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1. "####

  PARAMETERS : P_SHIP RADIOBUTTON GROUP R1. "####

SELECTION-SCREEN END OF BLOCK B2.



SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME.

  PARAMETERS : P_RE AS CHECKBOX DEFAULT 'X'. "#### ##

SELECTION-SCREEN END OF BLOCK B3.