
*&---------------------------------------------------------------------*

*&  Include           ZMMR04_001_TOP

*&---------------------------------------------------------------------*




DATA : OK_CODE TYPE SY-UCOMM.



DATA GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA GC_GRID TYPE REF TO CL_GUI_ALV_GRID.



DATA GS_FIELDCAT TYPE LVC_S_FCAT.

DATA GT_FIELDCAT TYPE LVC_T_FCAT.



DATA GS_LAYOUT TYPE LVC_S_LAYO.

DATA GS_VARIANT TYPE DISVARIANT.



DATA GO_EVENT TYPE REF TO EVENT.  " ZMMR04_001_CLS## ##



DATA : BEGIN OF GS_VENDOR,

  LIFNR TYPE ZLFA1_04-LIFNR,   " #####

  NAME1 TYPE ZLFA1_04-NAME1,   " ####

  LAND1 TYPE ZLFA1_04-LAND1,   " ###

  STCD1 TYPE ZLFA1_04-STCD1,   " #### (##### 3000###)

  STCD2 TYPE ZLFA1_04-STCD2,   " ##### (2000### ###)

  STRAS TYPE ZLFA1_04-STRAS,   " ##



  ZAKONT TYPE ZLFB1_04-ZAKONT,  " ##

  ZTERM TYPE ZLFB1_04-ZTERM,  " ####



  EKORG TYPE ZLFM1_04-EKORG,  " ####

  EKGRP TYPE ZLFM1_04-EKGRP,  " ####

  WAERS TYPE ZLFM1_04-WAERS,  " ######

  ZMWSKZ TYPE ZLFM1_04-ZMWSKZ,  " ####

  END OF GS_VENDOR.

DATA GT_VENDOR LIKE TABLE OF GS_VENDOR.



DATA : BEGIN OF GS_VENDOR_ALV,

  NAME1 TYPE ZLFA1_04-NAME1,   " ####

  LAND1 TYPE ZLFA1_04-LAND1,   " ###

  ZKTOKK TYPE ZLFA1_04-ZKTOKK, " #####

  STCD1 TYPE ZLFA1_04-STCD1,   " ####

  STCD2 TYPE ZLFA1_04-STCD2,   " #####

  STRAS TYPE ZLFA1_04-STRAS,   " ##



  LOEVM TYPE ZLFB1_04-LOEVM,  " #####

  ZAKONT TYPE ZLFB1_04-ZAKONT,  " ##

  ZTERM TYPE ZLFB1_04-ZTERM,  " ####



  EKORG TYPE ZLFM1_04-EKORG,  " ####

  EKGRP TYPE ZLFM1_04-EKGRP,  " ####

  WAERS TYPE ZLFM1_04-WAERS,  " ######

  ZMWSKZ TYPE ZLFM1_04-ZMWSKZ,  " ####

  END OF GS_VENDOR_ALV.

DATA GT_VENDOR_ALV LIKE TABLE OF GS_VENDOR_ALV.