
*&---------------------------------------------------------------------*

*&  Include           ZEDR00_PRACTICE009_TOP

*&---------------------------------------------------------------------*




TABLES : ZEDT00_102, ZEDT00_103. "####

TABLES : ZEDT00_106. "####

TABLES : ZEDT00_104. "####



CONSTANTS : C_X TYPE CHAR1 VALUE 'X'.

CONSTANTS : C_A TYPE CHAR1 VALUE 'A'.



RANGES : R_FG FOR ZEDT00_102-ZQFLAG.



DATA : BEGIN OF GS_EMP, "####

  ZPERNR LIKE ZEDT00_102-ZPERNR, "####

  ZPNAME LIKE ZEDT00_103-ZPNAME, "##

  ZDEPCODE LIKE ZEDT00_102-ZDEPCODE, "####

  DATBI LIKE ZEDT00_102-DATBI, "####

  DATAB LIKE ZEDT00_102-DATAB, "####

  ZDEPRANK LIKE ZEDT00_104-ZRANK, "##

  ZGENDER LIKE ZEDT00_103-ZGENDER, "##

  ZEDATE LIKE ZEDT00_102-ZEDATE, "####

  ZQDATE LIKE ZEDT00_102-ZQDATE, "####

  ZQFLAG LIKE ZEDT00_102-ZQFLAG, "####

  ZADDRESS LIKE ZEDT00_103-ZADDRESS, "##

  END OF GS_EMP.

DATA : GT_EMP LIKE TABLE OF GS_EMP.



DATA : BEGIN OF GS_EMP_ALV, "#### ##

  ICON TYPE C LENGTH 4, "###

  ZPERNR LIKE ZEDT00_102-ZPERNR, "####

  ZPNAME LIKE ZEDT00_103-ZPNAME, "##

  ZDEPCODE_NAME TYPE C LENGTH 10, "##

  DATBI LIKE ZEDT00_102-DATBI, "####

  DATAB LIKE ZEDT00_102-DATAB, "####

  ZRANK_NAME(8), "##

  ZGENDER_NAME(4), "##

  ZEDATE LIKE ZEDT00_102-ZEDATE, "####

  ZQDATE LIKE ZEDT00_102-ZQDATE, "####

  ZQFLAG LIKE ZEDT00_102-ZQFLAG, "####

  ZADDRESS LIKE ZEDT00_103-ZADDRESS, "##

  END OF GS_EMP_ALV.

DATA : GT_EMP_ALV LIKE TABLE OF GS_EMP_ALV.



DATA : BEGIN OF GS_CONTACT, "## ####

  ZPERNR LIKE ZEDT00_106-ZPERNR, "####

  ZYEAR LIKE ZEDT00_106-ZYEAR, "####

  DATBI LIKE ZEDT00_106-DATBI, "####

  DATAB LIKE ZEDT00_106-DATAB, "####

  ZSALARY LIKE ZEDT00_106-ZSALARY, "####

  ZBANKCODE LIKE ZEDT00_106-ZBANKCODE, "####

  ZACCOUNT LIKE ZEDT00_106-ZACCOUNT, "####

  END OF GS_CONTACT.

DATA : GT_CONTACT LIKE TABLE OF GS_CONTACT.



DATA : BEGIN OF GS_CONTACT_ALV, "## #### ##

  ZPERNR LIKE ZEDT00_106-ZPERNR, "####

  ZYEAR LIKE ZEDT00_106-ZYEAR, "####

  DATBI LIKE ZEDT00_106-DATBI, "####

  DATAB LIKE ZEDT00_106-DATAB, "####

  ZSALARY LIKE ZEDT00_106-ZSALARY, "####

  ZWAERS TYPE WAERS, "##

  ZBANK_NAME TYPE C LENGTH 10, "##

  ZACCOUNT LIKE ZEDT00_106-ZACCOUNT, "ZBANKL

  END OF GS_CONTACT_ALV.

DATA : GT_CONTACT_ALV LIKE TABLE OF GS_CONTACT_ALV.



DATA : BEGIN OF GS_ASSESS, "####

  ZPERNR LIKE ZEDT00_104-ZPERNR, "####

  ZDEPCODE LIKE ZEDT00_104-ZDEPCODE, "####

  ZYEAR LIKE ZEDT00_104-ZYEAR, "####

  DATBI LIKE ZEDT00_104-DATBI, "####

  DATAB LIKE ZEDT00_104-DATAB, "####

  ZRANK LIKE ZEDT00_104-ZRANK, "##

  END OF GS_ASSESS.

DATA : GT_ASSESS LIKE TABLE OF GS_ASSESS.



DATA : BEGIN OF GS_ASSESS_ALV, "#### ##

  ZPERNR LIKE ZEDT00_104-ZPERNR, "####

  ZDEPCODE_NAME TYPE C LENGTH 10, "##

  ZYEAR LIKE ZEDT00_104-ZYEAR, "####

  DATBI LIKE ZEDT00_104-DATBI, "####

  DATAB LIKE ZEDT00_104-DATAB, "####

  ZRANK LIKE ZEDT00_104-ZRANK, "##

  END OF GS_ASSESS_ALV.

DATA : GT_ASSESS_ALV LIKE TABLE OF GS_ASSESS_ALV.



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.



DATA : GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA : GC_SPLITTER2 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.



DATA : GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER3 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_CONTAINER4 TYPE REF TO CL_GUI_CONTAINER.



DATA : GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT,

       GT_FIELDCAT1 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT2 TYPE LVC_T_FCAT.

DATA : GT_FIELDCAT3 TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GS_SORT TYPE LVC_S_SORT .

DATA : GT_SORT1 TYPE LVC_T_SORT.

DATA : GT_SORT2 TYPE LVC_T_SORT.

DATA : GT_SORT3 TYPE LVC_T_SORT.



DATA : GS_VARIANT TYPE DISVARIANT.