
*&---------------------------------------------------------------------*

*& Report ZEDR20_012

*&---------------------------------------------------------------------*

*&

*&---------------------------------------------------------------------*




REPORT ZEDR20_012.






*DATA: GS_STUDENT TYPE ZEDT20_001.

*DATA: GT_STUDENT LIKE TABLE OF GS_STUDENT.

*

*DATA: BEGIN OF GS_MAJOR,

*  ZCODE LIKE ZEDT20_001-ZCODE,

*  ZPERNR LIKE ZEDT20_001-ZPERNR,

*  ZMNAME LIKE ZEDT20_001-ZMNAME,

*END OF GS_MAJOR.

*DATA: GT_MAJOR LIKE TABLE OF GS_MAJOR WITH NON-UNIQUE KEY ZCODE.

*

*CLEAR: GT_STUDENT, GS_STUDENT, GT_MAJOR, GS_MAJOR.

*GS_STUDENT-ZPERNR = '0000000001'.

*GS_STUDENT-ZCODE = 'SSU-01'.

*GS_STUDENT-ZKNAME = '###'.

*GS_STUDENT-ZENAME = 'DONG'.

*GS_STUDENT-ZGENDER = 'M'.

*GS_STUDENT-ZTEL = '01011112222'.

*APPEND GS_STUDENT TO GT_STUDENT.

*

*"GS_MAJOR-ZPERNR = '0000000001'.

*GS_MAJOR-ZCODE = 'SSU-01'.

*GS_MAJOR-ZMNAME = '####'.

*APPEND GS_MAJOR TO GT_MAJOR.

*

*LOOP AT GT_STUDENT INTO GS_STUDENT.

*  CLEAR: GS_MAJOR.

*  MOVE-CORRESPONDING GS_STUDENT TO GS_MAJOR.

*  "READ TABLE GT_MAJOR FROM GS_MAJOR INTO GS_MAJOR.    " ## READ ##

*

*  "READ TABLE GT_MAJOR WITH TABLE KEY ZCODE = GS_STUDENT-ZCODE   " TABLE KEY# ### READ

*  "INTO GS_MAJOR.

*

**  READ TABLE GT_MAJOR WITH KEY ZPERNR = GS_STUDENT-ZPERNR

**                               ZCODE = GS_STUDENT-ZCODE

**  INTO GS_MAJOR.   " ## WORK AREA ##

*

**  READ TABLE GT_MAJOR WITH KEY ZPERNR = GS_STUDENT-ZCODE INTO GS_MAJOR

**  COMPARING ZCODE.   " GS_MAJOR# GS_MAJOR# ZCODE# ### ## # ##

*

*  READ TABLE GT_MAJOR WITH KEY ZCODE = GS_STUDENT-ZCODE INTO GS_MAJOR

*  TRANSPORTING ZMNAME.

*

**  READ TABLE GT_MAJOR INTO GS_MAJOR INDEX SY-TABIX.

*  IF SY-SUBRC = 0.

*    WRITE:/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_MAJOR-ZMNAME.

*  ELSE.

*    WRITE:/ '#### #### #####.'.

*  ENDIF.

*ENDLOOP.