
*&---------------------------------------------------------------------*

*&  Include           ZWORK15_001_TOP

*&---------------------------------------------------------------------*






"#### ### ## ## ##

TABLES : SSCRFIELDS.

SELECTION-SCREEN FUNCTION KEY 1.



"#### ### ### ######

DATA : GS_RAW TYPE ALSMEX_TABLINE.

DATA : GT_RAW LIKE TABLE OF GS_RAW.



DATA : BEGIN OF GS_ZTCURR, "EXCEL# #### ITAB

       KURST TYPE ZTCURR015-KURST, "####

       FCURR TYPE ZTCURR015-FCURR, "####

       TCURR TYPE ZTCURR015-TCURR, "####

       GDATU TYPE ZTCURR015-GDATU, "####

       UKURS TYPE ZTCURR015-UKURS, "##

       FFACT TYPE ZTCURR015-FFACT, "########

       TFACT TYPE ZTCURR015-TFACT, "########

  END OF GS_ZTCURR.

DATA : GT_ZTCURR LIKE TABLE OF GS_ZTCURR.





DATA : BEGIN OF GS_ZTCURR_OUT, "ALV# #### ITAB

       KURST TYPE ZTCURR015-KURST, "####

       FCURR TYPE ZTCURR015-FCURR, "####

       TCURR TYPE ZTCURR015-TCURR, "####

       GDATU TYPE ZTCURR015-GDATU, "####

       UKURS TYPE ZTCURR015-UKURS, "##

       FFACT TYPE ZTCURR015-FFACT, "########

       TFACT TYPE ZTCURR015-TFACT, "########

       CRNAME TYPE ZTCURR015-CRNAME, "###

       CRDATE TYPE ZTCURR015-CRDATE, "###

  END OF GS_ZTCURR_OUT.

DATA : GT_ZTCURR_OUT LIKE TABLE OF GS_ZTCURR_OUT.



DATA : GS_SAVE TYPE ZTCURR015,

      GT_SAVE TYPE TABLE OF ZTCURR015.



DATA : OK_CODE TYPE SY-UCOMM.



DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.



DATA : GO_EVENT TYPE REF TO EVENT.



DATA : GS_VARIANT TYPE DISVARIANT.



DATA : GS_FIELDCAT TYPE LVC_S_FCAT.

DATA : GT_FIELDCAT TYPE LVC_T_FCAT.



DATA : GS_LAYOUT TYPE LVC_S_LAYO.



DATA : GS_SORT TYPE LVC_S_SORT.

DATA : GT_SORT TYPE LVC_T_SORT.