
*&---------------------------------------------------------------------*

*& Include ZMMR25_004_SCR

*&---------------------------------------------------------------------*






SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-T01.



PARAMETERS: P_EBELN TYPE ZEDT25_ZEKKO-EBELN OBLIGATORY,

            P_WERKS TYPE ZEDT25_ZEKPO-WERKS OBLIGATORY,

            P_BUDAT TYPE ZEDT25_ZRBKP-BUDAT MODIF ID M1.



SELECTION-SCREEN BEGIN OF LINE.

  SELECTION-SCREEN COMMENT 2(10) TEXT-001 FOR FIELD P_R1.

  PARAMETERS: P_R1 RADIOBUTTON GROUP RB1 DEFAULT 'X' USER-COMMAND UC1.

  SELECTION-SCREEN COMMENT 20(10) TEXT-002 FOR FIELD P_R2.

  PARAMETERS: P_R2 RADIOBUTTON GROUP RB1.

SELECTION-SCREEN END OF LINE.



SELECTION-SCREEN END OF BLOCK B1.