
*&---------------------------------------------------------------------*

*&  Include           ZEDR15_028_TOP

*&---------------------------------------------------------------------*






TABLES : ZEDT15_001.



DATA : BEGIN OF GS_STUDENT,




*    ZCOLOR  TYPE C LENGTH 4,




    ZCODE   LIKE ZEDT15_001-ZCODE, "####

    ZPERNR  LIKE ZEDT15_001-ZPERNR, "####

    ZKNAME  LIKE ZEDT15_001-ZKNAME, "##

    ZENAME  LIKE ZEDT15_001-ZENAME, "###

    ZGENDER LIKE ZEDT15_001-ZGENDER, "##

    ZSUM    LIKE ZEDT15_002-ZSUM, "##

    ZMAJOR  LIKE ZEDT15_002-ZMAJOR, "##

    ZMNAME  LIKE ZEDT15_002-ZMNAME, "###

    END OF GS_STUDENT.

DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.



DATA : OK_CODE TYPE SY-UCOMM. "### ## ### ####### ##



DATA : GS_FIELDCAT TYPE SLIS_FIELDCAT_ALV.

DATA : GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV.



DATA : GS_LAYOUT TYPE SLIS_LAYOUT_ALV.



DATA : GS_SORT TYPE SLIS_SORTINFO_ALV.

DATA : GT_SORT TYPE SLIS_T_SORTINFO_ALV.