
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  PARAMETERS : P_LIFNR LIKE ZLFA1_05-LIFNR MODIF ID M2.

  PARAMETERS : P_BUKRS TYPE ZLFB1_05-BUKRS.

  PARAMETERS : P_KTOKK LIKE ZLFA1_05-KTOKK MODIF ID M1.

SELECTION-SCREEN END OF BLOCK B1.



SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

  SELECTION-SCREEN BEGIN OF LINE.

  SELECTION-SCREEN COMMENT (5) TEXT-001 FOR FIELD P_CRE.

  PARAMETERS : P_CRE RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1.

  SELECTION-SCREEN COMMENT 20(5) TEXT-002 FOR FIELD P_VIEW.

  PARAMETERS : P_VIEW RADIOBUTTON GROUP R1.

  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B2.